### ISSUE TITLE
Support separating prql dialect and version header using | instead of \n

### ISSUE THREAD

**Issue by snth** [PRQL/prql#1006]
In most places `\n` and `|` can be used interchangeably for separating pipeline steps. Is it possible to also enable this for the `prql` dialect and version header?

So while the following works:
```elm
prql version:1 dialect:ansi
from a | select b
```

The following produces an error:
```elm
prql version:1 dialect:ansi | from a | select b

Error: during parsing
   ╭─[:1:29]
   │
 1 │ prql version:1 dialect:ansi | from a | select b
   ·                             ┬  
   ·                             ╰── expected ident_part_first, operator_mul, operator_add, operator_compare, operator_logical, or operator_coalesce
───╯
```

In a CLI context it is not always easy to produce `\n` characters, so being able to use `|` would be useful.

**Comment by max-sixty** [comment]
One issue is that the `prql` header isn't part of the pipeline currently. Similar to the `table` statement.

To what extent do we think people using the CLI won't require the header? Potentially the tool could add it in based on a config / some read of the underlying source. How will the DB connection be configured — could it read it from that?

**Comment by snth** [comment]
Yeah, all good ideas. I'm currently (ab)using this to separate PRQL from SQL queries without having another flag. I can put the required `\n` in without any problems.

The main use I saw was for passing the SQL dialect but I agree with you that that can probably be set through another CLI argument which can ensure that the proper formatting is passed.

This is definitely a low priority item. Do you have a `Someday/Maybe` tag we can apply to this issue? I was just curious why there was a difference in behaviour here.

**Comment by max-sixty** [comment]
> This is definitely a low priority item. Do you have a `Someday/Maybe` tag we can apply to this issue? I was just curious why there was a difference in behaviour here.

Great, good idea!

**Comment by max-sixty** [comment]
From discussion on Discord https://discord.com/channels/936728116712316989/957732687995621426/1047601796367011860 — let's close things like this that we're not really planning to do. It doesn't mean we won't ever do them; we can reopen if needed
