### ISSUE TITLE
Filtering for empty strings

### ISSUE THREAD

**Issue by mklopets** [PRQL/prql#1023]
There's currently no way to filter based on empty strings (other than S-strings). This should work, but doesn't:

```
from employee
filter name != ""
```

instead, it fails with:
```
Error: during parsing
   ╭─[:2:17]
   │
 2 │ filter name != ""
   ·                 ┬  
   ·                 ╰── expected string_inner
───╯
```

**Comment by aljazerzen** [comment]
Yeah, that's a bug with string parsing.
