### ISSUE TITLE
Reject queries that have newer version than the compiler itself

### ISSUE THREAD

**Issue by aljazerzen** [PRQL/prql#1037]
When the query specifies a version, but the compiler version is lower, reject the query with message:
```
This query uses version of PRQL that is not supported by your prql-compiler. You may want to upgrade it.
```

**Comment by MarinPostma** [comment]
I can take a stab at that

**Comment by max-sixty** [comment]
Great @MarinPostma 

FYI you can get the current version using https://stackoverflow.com/a/27841363

**Comment by MarinPostma** [comment]
@max-sixty It seems that the version is stored as an integer within the query. What exactly is this version number correspond to? The major version of the crate? or is language already V1 as the [documentation would suggest](https://prql-lang.org/book/queries/dialect_and_version.html?highlight=version#version)?

**Comment by max-sixty** [comment]
> @max-sixty It seems that the version is stored as an integer within the query. What exactly is this version number correspond to? The major version of the crate? or is language already V1 as the [documentation would suggest](https://prql-lang.org/book/queries/dialect_and_version.html?highlight=version#version)?

Ah, that's a great point.

I could imagine a couple of things we can do:

- Take the first number from the version, and use that. So the current version would be `0`. The linked example would change to `version:0`
- (would need discussion; I wouldn't implement yet) Allow for more defined versions; like `0.2.9`, and store something other than an int there (e.g. https://docs.rs/semver/latest/semver/struct.Version.html)

**Comment by aljazerzen** [comment]
I'd rather use semver. If we keep it just a number we close the door on having semver. 

Also, we can directly compare with cargo version, which is the only versioning chain we currently have.

**Comment by MarinPostma** [comment]
If we chose semver, we would still support `version:0`, but accept more precise version numbers as well, like `version:0.2` or `version:0.2.3`. This is backward compatible as well

**Comment by snth** [comment]
I also vote for semver so `prql-compiler` 0.2.9 would accept `version:0.2` and `version:0.2.3` but fail on `version:0.2.10` or `version:0.3`.

**Comment by max-sixty** [comment]
OK great, sounds like the vote is carried for:

> Allow for more defined versions; like 0.2.9, and store something other than an int there (e.g. https://docs.rs/semver/latest/semver/struct.Version.html)

FWIW eventually I can see us also being able to compile queries for older versions, in the same way that rust editions work. For that purpose, we'd only care about the first one.

But I agree there's another case where we care about minor versions which add features, very reasonable to do it this way, in the same way that rust compiler versions work.

---

@MarinPostma would you still be up for implementing this? It's a bit more complicated than initially proposed. I (& others) would be very happy to help you. It would also be OK to implement the first bullet first, and then implement the second later — small PR are good!

**Comment by MarinPostma** [comment]
No problem with implementing that

**Comment by max-sixty** [comment]
Thanks @MarinPostma !
