### ISSUE TITLE
Refactor ir::ir_fold to borrow IR AST instead of taking by value

### ISSUE THREAD

**Issue by aljazerzen** [PRQL/prql#1042]
To walk over all nodes in the AST, we use [fold pattern](https://rust-unofficial.github.io/patterns/patterns/creational/fold.html). Currently it is used in `ast::ast_fold` and `ir::ir_fold`.

The downside of this pattern is that it can either take the AST by value, as a reference or as a mutable reference. We pass AST by value in both cases, but actually, for `ir::ir_fold` it would be more convenient if it were passed as reference.

In practice this means that we want to change:
```rust
pub trait IrFold {
    fn fold_transform(&mut self, transform: Transform) -> Result<Transform> {
        fold_transform(self, transform)
    }
```
... into ...
```rust
pub trait IrFold {
    fn fold_transform(&mut self, transform: &Transform) -> Result<()> {
        fold_transform(self, transform)
    }
```

`IrFold` is used at two locations, each of which needs to be refactored to take `Query` by reference. This can be done because both cases only extract information from the query and do not mutate it.

**Comment by max-sixty** [comment]
In an effort to ruthlessly prioritize, can we do this after the semantic merge? Lots of clones are very OK in the short term (maybe even the long term!)

**Comment by aljazerzen** [comment]
Yeah we could do it after, but it's also a good task to get familiar with our AST folding pattern.

**Comment by max-sixty** [comment]
I was trying to do this given I wanted to do something on Onboarding — but am confused again...

Is the return type of this literal — `Result()`?
```
    fn fold_transform(&mut self, transform: &Transform) -> Result<()> {
```

Or do you mean that as shorthand, and in the code it would `Result<&Transform>`? Because at the moment, it's doing work to make a new `Transform`, not just returning whether it was successful or not.

**Comment by MarinPostma** [comment]
I can do that :)

**Comment by MarinPostma** [comment]
I propose that the trait is renamed to `FoldIrRef` where only a ref is required, wdyt?

**Comment by MarinPostma** [comment]
I gave this a quick look, and it appears that the two instances where AstFold are used return a mutated version of the AST, do you want to mutate the last in place? in which case, fold method would take a exclusive reference to the AST node?

**Comment by MarinPostma** [comment]
@max-sixty I just saw that you were taking a stab at this 🤦, my bad

**Comment by aljazerzen** [comment]
Oh sorry, in the meantime I've found another use of IrFold that does need passing by value.

Which means that this issue is obsolete.

**Comment by max-sixty** [comment]
> @max-sixty I just saw that you were taking a stab at this 🤦, my bad

No prob, thanks for starting.

Possibly @aljazerzen has some more suggestions for us :)
