### ISSUE TITLE
Comment out failing tests on semantic branch?

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1048]
At the moment it's difficult to merge things into semantic because tests fail

Should we comment out the failing tests and then uncomment them when we get them to pass? In pytest this would be `xfail`, but I'm not sure whether cargo has the same concept, hence the suggestion to comment out...

**Comment by aljazerzen** [comment]
There is [#[ignore]](https://github.com/rust-lang/rust/blob/054b7b7/src/libcoretest/num/flt2dec/strategy/grisu.rs#L56). 

I would refrain from commenting out, because the rust-analyzer cannot find references and will not refactor when renaming and such.

**Comment by max-sixty** [comment]
> There is [#[ignore]](https://github.com/rust-lang/rust/blob/054b7b7/src/libcoretest/num/flt2dec/strategy/grisu.rs#L56).

Much better!
