### ISSUE TITLE
Omit table names in idents when there is only one table in SELECT

### ISSUE THREAD

**Issue by aljazerzen** [PRQL/prql#1081]
> this issue is part of onboarding, see more info [here](https://github.com/prql/prql/pull/593#issuecomment-1282120001)

----

When we compile to very basic `SELECT` statements, table name prefixes in indents are not needed:
```sql
SELECT title FROM movies;
```
As soon as there are multiple tables, prefixes are needed:

```sql
SELECT movies.title FROM movies JOIN genres USING(genre_id);
```

This is because table `genres` could have column with name `title` which would cause conflict.

On branch `semantic`, we always include prefix, just to be sure, but it would be better to omit when possible. To make simple queries simpler.

(this is not critical to get done, but it's easy. @max-sixty I think this is too easy for you, leave it to @MarinPostma or @priithaamer or someone else)

---- 

Best way to achieve this is to add a flag `omit_ident_prefix: bool` on [`translator::Context`](https://github.com/prql/prql/blob/22c79b42155621df84ef5fd0429f594ea103abf8/prql-compiler/src/sql/translator.rs#L23-L26). It should start as `false`.

Then, before starting to build a SELECT query, we must count all tables in `From` and `Join` transforms. This can be done by a new struct that implements an `IrFold`, similar to `CidRedirector` (https://github.com/prql/prql/blob/22c79b42155621df84ef5fd0429f594ea103abf8/prql-compiler/src/sql/anchor.rs#L263-L272.

Something like:
```rust
struct TableCounter {
    count: u16,
}
impl IrFold for TabelCounter {
   fn fold_transform(...) { ... }
}
```

Folding of the SELECT (represented by `Vec<Transform>`) can be invoked here:

https://github.com/prql/prql/blob/22c79b42155621df84ef5fd0429f594ea103abf8/prql-compiler/src/sql/translator.rs#L120-L126

and set the flag:
```rust
context.omit_ident_prefix = tableCounter.count == 1;
```

To actually omit prefixes, `translate_ident` with have to be updated: https://github.com/prql/prql/blob/22c79b42155621df84ef5fd0429f594ea103abf8/prql-compiler/src/sql/codegen.rs#L406-L431

When this is all done, many of currently failing tests should start working. You can check that by running:
```
cargo test --lib -- --ignored
```
You can now remove `#[ignored]` from tests that pass.

**Comment by MarinPostma** [comment]
Looks interesting if @max-sixty lets me have it :)

**Comment by max-sixty** [comment]
> @max-sixty I think this is too easy for you

I doubt this, but yes @MarinPostma please go ahead!
