### ISSUE TITLE
State the benefits of PRQL more clearly

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1087]
In most of the conversations I've been having with folks, the starting questions are almost always "why is this good" and "who is it for". Then when I discuss them, it clicks.

I don't think our copy is sufficient at the moment — on the website we lead with "Principles" rather than "Benefits".

Let's instead have key benefits, and maybe how they map to main users; e.g. (will refine)
- Better developer ergonomics — edit queries as you explore data
- One language for all DBs
- Easier to learn
- Machines and people can generate alike

...it should probably _not_ have words like "orthogonal" :)

Users (will refine)
- SQL pro
- Data analyst
- Newbie
- DB vendor

**Comment by aljazerzen** [comment]
We should have sections:

Compared to SQL:
- Better developer ergonomics — edit queries as you explore data. Composable
- Easier to learn
- Modern

Compared to dataframes libraries:
- One language for all DBs & most in-memory relational engines (TODO)
- Dataframes are first-class citizens (name resolving and type checking of column references)

Take my suggestions with a grain of salt, I don't speak to so many data analysts and may have a narrow scope on compiler internals :D

**Comment by max-sixty** [comment]
Closed by #1098
