### ISSUE TITLE
Pandas integration

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1099]
I think a limited pandas integration would be quite possible. I remember @rbpatt2019 discussing this when he was doing lots [^1] 

It wouldn't do everything that pandas can do, but for most of what PRQL can do, the translation doesn't require context and is fairly simple (I think). 

Two options I could see:
- Compile the PRQL AST into a python string, like we do for SQL, and `eval` it in python. Advantage is that it's easy to see what the pandas code is doing.
- Execute pandas methods from the AST. Advantage is that we're not building a string.

Another direction would be to use DuckDB, which can take a pandas DataFrame — we have a version of this in `pyprql`, though it might need a refresh.

If someone wanted to take this on, I would be quite supportive, and happy to help

[^1]: Hope all's well, if you're still online Ryan!

**Comment by max-sixty** [comment]
As discussed on discord with @mklopets & @aljazerzen , the PyPRQL probably does need a refresh. That said, the functionality is pretty good, and I might downweigh have a specific pandas target rather than using DuckDB like PyPRQL does

> why is the "pandas integration" implemented as a pandas accessor as opposed to just an importable function?
> `df.prql.query('from other_df')`

> I think either it should be `df.prql("derive a = b + c")`, OR just `prql("from df | derive a = b + c")` (or `con.prql` if that can't be implicit)

**Comment by eitsupi** [comment]
> I think either it should be `df.prql("derive a = b + c")`, OR just `prql("from df | derive a = b + c")` (or `con.prql` if that can't be implicit)

Just a note: R's [tidyquery](https://github.com/ianmcook/tidyquery) supports both notations, but I feel that the latter is more straightforward, because eventually one of the tables must be represented in the string when targeting multiple tables like join.

**Comment by mklopets** [comment]
I think I'm missing some context here: @max-sixty could you elaborate a tiny bit on how this is different from what `pyprql` does (other than that one small API change we discussed)?

**Comment by max-sixty** [comment]
My original thinking was that we could make a backend target specifically for pandas. 

`pyprql` has a duckdb backend which can itself target pandas.

On reflection, I think that's very sufficient, and writing our own pandas backend would not be a good idea! 

I can work on some refresh of that at some point (I just added https://github.com/prql/PyPrql/issues/75), though others are more than welcome to have a go, CC @charlie-sanders if you're up for a quick win.
