### ISSUE TITLE
Lezer / CodeMirror grammar

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1102]
As discussed with @antonycourtney, a [Lezer]( https://lezer.codemirror.net/docs/guide/) grammar would be useful, to the extent he explores using PRQL in some of his tools. 

IIUC this will give us a CodeMirror grammar for free. It's a similar design to treesitter.

For context we have a startling array of grammars for syntax highlighting:
- [hljs](https://github.com/prql/prql/blob/8c402e06ef7393211fc947c6f1684f8865c5ab02/book/highlight-prql.js), for the website & book
- [textmate](https://github.com/prql/prql-code/blob/d9946a6897688f5364e3c710e61a8fd77c60c006/syntaxes/prql.tmLanguage.json), for VSCode
- [monaco](https://github.com/prql/prql/blob/8c402e06ef7393211fc947c6f1684f8865c5ab02/playground/src/workbench/prql-syntax.js), for the playground

**Comment by aljazerzen** [comment]
Similar to #285, related to #131

**Comment by max-sixty** [comment]
Closing as completed. I'm yet to work this into the Jupyter extension though.
