### ISSUE TITLE
Passing `printf` through?

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1103]
I have some existing SQL queries that do fancy formatting on numeric values using printf(). Example:

```
printf("$%,d", SD_Assessment2021) as "Ass. 2021" # 1234567 -> $1,234,567
```
I would like to wrap this formatting in a function (because I use it many places), but don't see how to do it yet. 

Is it possible to do this in prql now? Is it on the road map? Many thanks.

**Comment by snth** [comment]
I don't think that's a general SQL expression, is this for sqlite specifically? Have you tried using an [s-string](https://prql-lang.org/book/language-features/s-strings.html)?

**Comment by richb-hanover** [comment]
> is this for sqlite specifically? 

I'm using it with SQLite. I don't know much about the SQL language.

> Have you tried using an [s-string](https://prql-lang.org/book/language-features/s-strings.html)?

I just found s-strings... I'll check them out and re-open if it's warranted.

**Comment by richb-hanover** [comment]
@snth - the playground makes it look as if s-strings might work. Thanks.

```
func dollars d -> s"""printf("$,d",{d})"""

from foo
select (dollars 1234567)
```
