### ISSUE TITLE
prql-js tests in GHA?

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1113]
Do we currently run the [`prql-js` tests](https://github.com/prql/prql/blob/main/prql-js/tests/test_all.js) in GHA?

I see we have a separate [`package.json`](https://github.com/prql/prql/blob/main/prql-js/tests/package.json) for the tests, with a version of `0.2.2`. I don't know JS test conventions at all — are they generally a separate package? I can adjust the release script to bump that `package.json` if so.

CC @charlie-sanders if you're around, I know you've done some work on these, thanks.

**Comment by mklopets** [comment]
@max-sixty I think you reworked how JS tests are run on GH actions in https://github.com/prql/prql/pull/1194 and this can probably be closed?

**Comment by max-sixty** [comment]
Ah thanks, yes this is now done!
