### ISSUE TITLE
Variable replacement doesn't respect precedence

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1116]
In this example, the resulting code for `diff` should be `c - a - b` or `c - (a + b)` 
```
from foo
select [
   sum = (a+b),
   diff = c-sum  # actually outputs "c - a + b AS diff"
]
```
(Tested with current VScode plugin and Playground)

**Comment by max-sixty** [comment]
Great, good catch.

A full repro:

```elm
from foo
select [
   s = (a+b),
   diff = c-s
]
```

```sql
SELECT
  a + b AS s,
  c - a + b AS diff
FROM
  foo
```

**Comment by richb-hanover** [comment]
Another example where the current 0.2.9 compiler gets the wrong output by not parenthesizing its sub-expressions.

To reproduce, this example compares property tax between 2020 & 2021. The tax is computed by multiplying the year's rate (dollars per thousand of value) by the home's assessed value in the year, dividing by 1000 to normalize. (At the $25.00 tax rate, a $100,000 house would pay $2,500 in 2020.)

The function `pct` takes an "old" and "new" value and computes a percentage increase.

```
# Displays problem with computations that aren't parenthesized

# pct computes the amount (percent) the new differs from old
func pct o n -> s"100.0*({n}-{o})/{o}"

derive [
  Rate2020=25.00,
  Rate2021=24.00,
  Value2020=100000,
  Value2021=110000,
  Tax2020=Rate2020*Value2020/1000,
  Tax2021=Rate2021*Value2021/1000,
  Increase=(pct Tax2020 Tax2021),
]
select [
  Tax2020,
  Tax2021,
  Increase,
]
take 1
```
This yields these values:

Tax2020: 2500
Tax2021: 2640 (in reality, a 5.6% increase)
Increase: 56000.0

The problem can be fixed by putting parentheses around the denominator `25 * 100000 / 1000` in the following result. However, this seems to be an unfriendly edge case because arithmetic "doesn't work" as most people expect. 

```
SELECT
  25 * 100000 / 1000 AS "Tax2020",
  24 * 110000 / 1000 AS "Tax2021",
  cast(
    (
      100 *(24 * 110000 / 1000 -25 * 100000 / 1000) / 25 * 100000 / 1000
    ) as real
  ) AS "Increase"
```
**Update:** Edited the `pct` function to remove the cast()

**Comment by richb-hanover** [comment]
Update to my `(pct ...)` function. The version above displays a percent increase of 5.6% as "56000.0". It can be made numerically accurate by:
 
1. Casting the numerator (only) to real,
2. Putting parentheses around the denominator

`func pct o n -> s'cast(({n}-{o}) as real)/({o})*100'`

Observations:

* When writing PRQL I am comfortable taking responsibility for ensuring enough digits of accuracy (using `cast` as needed)
* But I don't want to have to sprinkle `(...)` around the code to ensure that "arithmetic works" 
* NB: The extra paren's still don't solve the problem of the original report.

Thanks for listening!

**Comment by max-sixty** [comment]
Thanks for the extra examples. 

> The problem can be fixed by putting parentheses around the denominator `25 * 100000 / 1000` in the following result. However, this seems to be an unfriendly edge case because arithmetic "doesn't work" as most people expect.

To confirm that I'm understanding the full issue, would parenthesizing the expression be sufficient? I think that's the case but wanted to check.

**Comment by max-sixty** [comment]
I adjusted the title a bit as it's specific to variables / s-strings, and not specific to left-to-right precedence, IIUC

**Comment by richb-hanover** [comment]
I agree the updated title is better.

To address your latest question: For the "percentage calculation", it is possible to work around the problem by inserting paren's around the denominator. But...

In "ordinary arithmetic", the formula for a percentage change is `(new - old) / old`.  As a PRQL function, adding the parens like this:  `(new - old) / (old)` works around the problem.

But people are going to want to write code using "ordinary arithmetic". In my example, the percentage was 1000x too large, an obvious error that caused me to look deeper. 

In the original case, I could not find a way to avoid `diff = c-s` from producing the wrong result.

So I believe it's an important goal for PRQL to allow people to write their code the "obvious way" and have the compiler generate the what they expect. Final thoughts:

* I don't know enough to say whether parenthesizing each "variable replacement" is sufficient
* I am happy to keep testing

Thanks.

**Comment by max-sixty** [comment]
I very much agree with your stated goal! `(new - old) / old` should work.

From what I can see, if the compiler adds parentheses around expressions, then that's sufficient. But if there are any contrary examples then please post...

**Comment by richb-hanover** [comment]
> ... if the compiler adds parentheses around expressions, then that's sufficient. But if there are any contrary examples then please post...

That sounds right. And I don't know of any case where that wouldn't work, but I'll definitely sound off if I find any.

**Comment by max-sixty** [comment]
A draft fix: https://github.com/prql/prql/pull/1136

**Comment by max-sixty** [comment]
Closed by https://github.com/prql/prql/pull/1136

**Comment by richb-hanover** [comment]
Uh oh. I don't think the current code handles the case of [#1116](https://github.com/prql/prql/issues/1116#issuecomment-1312341909) where the divisor has multiple divisions. 

After executing the resulting SQL (from the Playground), the Increase column (the result of the `pct` function) shows 5600.0 instead of 5.6 (%)

**Comment by max-sixty** [comment]
Can we show the PRQL and resulting SQL?

**Comment by richb-hanover** [comment]
Sorry - I should have provided the test case. Here's the PRQL and the result (using today's Playground)
```prql
# Displays problem with computations that aren't parenthesized
# pq20.prql

# pct computes the amount (percent) the new differs from old
func pct o n -> s'100.0*({n}-{o})/{o}'

derive [
  Rate2020=25.00,
  Rate2021=24.00,
  Value2020=100000,
  Value2021=110000,
  Tax2020=Rate2020*Value2020/1000,
  Tax2021=Rate2021*Value2021/1000,
  Increase=(pct Tax2020 Tax2021),
]
select [
  Tax2020,
  Tax2021,
  Increase,
]
sort Increase
```
yields
```
SELECT
  25.0 * 100000 / 1000 AS "Tax2020",
  24.0 * 110000 / 1000 AS "Tax2021",
  100.0 *(24.0 * 110000 / 1000 -25.0 * 100000 / 1000) / 25.0 * 100000 / 1000 AS "Increase"
```

After executing the resulting SQL (from the Playground), the Increase column (the result of the pct function) shows 56000.0 instead of 5.6 (%)

Update: What's peculiar is that the expected answer is 5.6%. But the computed value is 10,000 times that amount, not 1,000 times. So I don't see how SQL computes that value...

**Comment by richb-hanover** [comment]
NB: Placing paren's around the denominator of the pct function gives the correct result, e.g., 

`func pct o n -> s'100.0*({n}-{o})/({o})'` yields 5.6

**Comment by max-sixty** [comment]
Thanks for spotting! V helpful.

To the extent we can produce a minimal example, then that's useful; I'll start with that otherwise when I'm online.

**Comment by richb-hanover** [comment]
Caught you, you weasel! :-) Reproducible case - requires a function call:

```
# Minimal example for tax increase
# pq28.prql

# fun1 & fun2 divide their "n" param by "d"
func fun1 n d -> s' {n} / {d} '
func fun2 n d -> s' {n} / ({d}) '

from albums
select [
  a = 24.0 * 100000 / 1000,
  # correct
  b = 100.0 * (a + 100)/a, 
  # incorrect
  c = (fun1 (100.0 * (a + 100)) a ),
  # correct - fun2 wraps denominator in (...)
  d = (fun2 (100.0 * (a + 100)) a ),
]
take 1
```
Playground yields (21Nov2022)

```
SELECT
  24.0 * 100000 / 1000 AS a,
  100.0 * (24.0 * 100000 / 1000 + 100) / (24.0 * 100000 / 1000) AS b,
  100.0 * (24.0 * 100000 / 1000 + 100) / 24.0 * 100000 / 1000 AS c,
  100.0 * (24.0 * 100000 / 1000 + 100) / (24.0 * 100000 / 1000) AS d
FROM
  albums
LIMIT
  1
```
SQL output shows:

```
a	b	c	d
2400.0	104.166666666667	1041666.66666667	104.166666666667
```

**Comment by richb-hanover** [comment]
**Update:** Even simpler test  case

```
# Minimal example for tax increase
# pq28.prql

# fun1 & fun2 divide their "n" param by "d"
func fun1 n d -> s' {n} / {d} '
func fun2 n d -> s' {n} / ({d}) '

from albums
select [
  a = 1/100.0,
  b = 1/a,          # correct
  c = (fun1 1 a ),  # incorrect
  d = (fun2 1 a ),  # correct - fun2 wraps denominator in (...)
]
take 1
```
Playground yields (21Nov2022)

```
SELECT
  1 / 100.0 AS a,
  1 / (1 / 100.0) AS b,
  1 / 1 / 100.0 AS c,
  1 / (1 / 100.0) AS d
FROM
  albums
LIMIT
  1
```
SQL output shows:

```
a	b	c	d
0.01	100.0	0.01	100.0
```

**Comment by max-sixty** [comment]
Excellent case @richb-hanover ! I'll look at this

**Comment by snth** [comment]
I read the last example (and only skimmed over the rest of the thread so apologies if I'm missing some context).

To me it seems that while functions are defined through s-string substitutions, they are essentially opaque to the compiler so there's not much it can do to ensure semantic correctness.

Only thing I could think of is to wrap each function argument in parenthesis and then run the final SQL through a SQL parser to transform it into some sort of normalised / optimal form which hopefully can eliminate superfluous punctuation, like `(1)/(1)` -> `1/1` while `(1)/(1/100)` -> `1/(1/100)`.

**Comment by max-sixty** [comment]
> To me it seems that while functions are defined through s-string substitutions, they are essentially opaque to the compiler so there's not much it can do to ensure semantic correctness.

Yes I think this is spot-on. We're using literal replacement and expecting semantic correctness. If we use semantic replacement, it works — i.e. `func fun3 n d -> n / d`.

---

I'm not sure of the best solution — the current design is correct is the literal sense, but at least with these examples, it's clearly not doing what the user intends.

Potential reasons to not wrap / nest the variable:
- Are there cases where nesting the variable would be wrong? Seems unlikely at first glance.
- I'm hesitate to have an additional parsing stage to remove superfluous parentheses

Alternatively, is there a simple heuristic we could use to decide whether to nest? e.g. "has non-word characters" (though this makes the special-cases worse, not better)

**Comment by max-sixty** [comment]
Opened a new issue with the most recent comment, since this is now smaller is scope now that the associativity issue is  fixed

**Comment by richb-hanover** [comment]
Link to new issue is #1155
