### ISSUE TITLE
What's a good place to discuss language questions and issues?

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1117]
I have had some fun horsing around with PRQL, building queries that match some SQL queries I built a while back. I also have been taking notes about confusion/hurdles/problems that I've encountered.

I posted them in my [pqtest repo.](https://github.com/richb-hanover/pqtest)

None of my comments (except #1116) are serious, and can be addressed over time. What's the best way to review these? Thanks for a wonderful tool!

**Comment by max-sixty** [comment]
@richb-hanover this is fantastic! Thank you so much. We really need this sort of review.

In terms of how to convert these into improvements in PRQL, a few tracks, depending on how much you'd like to make a mark on the repo itself:

- Many things could go in the book; e.g.

> Am I correct that the opening [ must be on same line as the select or derive for a multi-line list? It would be helpful to examples showing lists in brackets each on separate line.

> Similarly, I was unsure how to set multiple ON... expressions for a join. I ultimately said, "Well, maybe they just go in a list [ ... ]. I tried it and it worked. I don't know how you could make it more obvious - maybe another example in the JOIN documentation?

> How to specify the correct join columns if different tables have different/conflicting names? In SQL, I would use ...from Table1 l join Table2 r on l.foo = r.bar

> Your example celsius_of_fahrenheit of really grinds my gears. Can you use the correct formula?


- There a category of bad error messages. That could either be an issue in this repo, or if you're feeling ambitious, an insta test showing the error message, with a `TODO` to improve it. To set expectations, we can make really good error messages if the query gets past our `pest` parser. If it doesn't, the error messages will be bad until we can use a different parser (ref https://github.com/prql/prql/issues/131)

> The VSCode Extension for PRQL v0.3.2 is a terrific learning environment. I will note that it's easy to generate valid-looking PRQL that isn't valid SQL.

Thanks! This is the excellent work of @jiripospisil!

- Some things are bugs which can be issues, e.g.

> Is it true that filter must precede select? I don't understand the semantics. pq8.prql shows an error if filter is at the end, but works OK if filter comes before the select. Why?

- Some things are good questions which could be issues; e.g.

> In this example, there's an extra space before the "-" in the generated code. Is that expected?

- Some things do need examples; e.g.

> Are variable names case-sensitive? Sometimes it seems they are, although I didn't write down an example.

> Sometimes VSCode extension declared that a variable was not defined when I had clearly used it earlier. How does it know?

> What's the rule for using x in functions vs {x}? (Maybe it has to do with s-strings...)


What does that leave?

**Comment by richb-hanover** [comment]
You have categorized my stream-of-consciousness list well. I am up to my elbows in stuff right now, so I won't be able to work on most of these. (I'm hoping that I left enough suggestions for someone to take on the documentation changes.)

I figure I _do_ owe you reproducible examples for the last set, though: I will add them to my `pqtest` repo, then post a note here. 

PS One more question for documentation... 
* Why do some S-strings use `"` and others use `"""`? I don't find an explanation in the Book.

**Comment by max-sixty** [comment]
> Why do some S-strings use `"` and others use `"""`? I don't find an explanation in the Book.

Either work! https://prql-lang.org/book/language-features/strings.html

**Comment by richb-hanover** [comment]
> Either work!

Ahah! I searched for `"""` and got no results. Now I have more experiments to perform, more variations to play with! :-) Thanks.

**Update:** And seemingly, `'` and `'''` also work as string delimiters

**Comment by richb-hanover** [comment]
Closing this, to move it to a Discussion...
