### ISSUE TITLE
prql and floating point/scientific notation

### ISSUE THREAD

**Issue by cottrell** [PRQL/prql#1118]
This query seems to fail due to the e-5 ... is there some obvious way to work around it?

```python
prql.to_sql("""
from df
derive [
   cc = 1.34e-5 * a
]
""")

SyntaxError:  --> 4:13
  |
4 |    cc = 1.34e-5 * a
  |             ^---
  |
  = expected operator_mul, operator_add, operator_compare, operator_logical, operator_coalesce, or interval_kind

```

**Comment by max-sixty** [comment]
Thanks for the question.

While we don't have scientific notation in PRQL yet, this "should" be solvable with an s-string.

Unfortunately because we format the SQL and our SQL formatter doesn't seem to support them either, it currently doesn't work for a different reason:

```elm
from df
derive [
   cc = s"1.34e-5" * a
]
```

```sql
SELECT
  df.*,
  1.34 e -5 * a AS cc  # shouldn't have spaces here
FROM
  df
```

This is related to https://github.com/prql/prql/issues/965. No word yet on https://github.com/shssoichiro/sqlformat-rs/issues/15.

To the extent this is important, I can add a workaround — let us know.

**Comment by cottrell** [comment]
s-string is a good enough work around for me. It's good to know what does not exist yet (but might eventually).

**Comment by cottrell** [comment]
I just noticed that there is still some whitespace issue as shown below that is probably worth fixing eventually:

```python
In [170]: df = pd.DataFrame(np.random.randn(10, 1), columns=['a']).reset_index()

In [171]: q = prql.to_sql("""
     ...: from df
     ...: derive [
     ...:    cc = s"1.34e-5 * a"
     ...: ]
     ...: """)

In [172]: duckdb.query(q).df()
---------------------------------------------------------------------------
ParserException                           Traceback (most recent call last)
Input In [172], in <cell line: 1>()
----> 1 duckdb.query(q).df()

ParserException: Parser Error: syntax error at or near "-"
LINE 3:   1.34 e -5 * a AS cc
                 ^

In [173]: duckdb.query("select df.*, 1.34e-5 * a as cc from df").df()
Out[173]: 
   index         a            cc
0      0  1.431854  1.918684e-05
1      1  0.771389  1.033661e-05
2      2  0.510250  6.837351e-06
3      3  0.008511  1.140497e-07
4      4 -0.218765 -2.931449e-06
5      5 -0.649255 -8.700023e-06
6      6 -0.668568 -8.958808e-06
7      7 -0.423988 -5.681436e-06
8      8 -0.583732 -7.822005e-0
9      9 -0.622073 -8.335777e-06

In [174]: print(q)
SELECT
  df.*,
  1.34 e -5 * a AS cc
FROM
  df

```


Workaround might be

```python
In [181]: prql.to_sql("""
     ...: from df
     ...: derive [
     ...:    cc = s"cast('1.34e-5' as float) * a"
     ...: ]
     ...: """)
Out[181]: "SELECT\n  df.*,\n  cast('1.34e-5' as float) * a AS cc\nFROM\n  df"
```

or

```python
In [185]: prql.to_sql("""
     ...: from df
     ...: derive [
     ...:    cc = ('1.34e-5' | as float) * a
     ...: ]
     ...: """)
Out[185]: "SELECT\n  df.*,\n  CAST('1.34e-5' AS float) * a AS cc\nFROM\n  df"
```

**Comment by max-sixty** [comment]
Yes re the whitespace — I tried to say that above, likely I wasn't clear.

But your workaround with `CAST` is very clever! Great idea.

> This is related to https://github.com/prql/prql/issues/965. No word yet on https://github.com/shssoichiro/sqlformat-rs/issues/15.

Are you OK bundling this into those issues re the s-string contents being formatted, sometimes incorrectly?

**Comment by cottrell** [comment]
Yeah, sounds good. Will close this to reduce noise
