### ISSUE TITLE
Bad error message: `filter` after `select`

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1124]
PRQL compiles this code just fine to produce the expected SQL:

```
from foo
filter a == "bar"
select [
  b
]
```

Moving the `filter` after the `select` gives an "Unknown variable" error:

```
from foo
select [
  b
]
filter a == "bar"     # Unknown variable `a`
```

Is this expected?

**Comment by max-sixty** [comment]
This is expected — `select [b]` means there's only one column there — `b` — and so it can't filter on `a`. Does that make sense? Maybe we want `derive` instead of `select` for this?

**Comment by richb-hanover** [comment]
Ahah! I'm still learning the semantics of PRQL. Your explanation makes total sense. The trick is to come up with a comprehensible error message.

Perhaps something like, "Unknown variable `a` in result table" or "Variable `a` not present in result[1]" ...

[1] What's the term of art for the data structure that gets passed to the next stage of the pipeline? That's the word to use in place of "result"...

**Comment by max-sixty** [comment]
> [1] What's the term of art for the data structure that gets passed to the next stage of the pipeline? That's the word to use in place of "result"...

Ha, this is a good question actually  — "result at X" might be reasonable? "Intermediate result"?

---

> Perhaps something like, "Unknown variable `a` in result table" or "Variable `a` not present in result[1]" ...

The full error message is (btw it's helpful if we post both the input and output when making issues):

```
Error: 
   ╭─[:5:8]
   │
 5 │ filter a == "bar"     # Unknown variable `a`
   ·        ─┬  
   ·         ╰── Unknown variable `a`
───╯
```

it does point to the location where it can't find `a`. Maybe we could say "found column `a` above, but it excluded at `select [b]`", or try and offer suggestions? That would be quite nice, but also would require more work.

---

I'm not sure the best way of organizing issues for error messages. If we have an issue for every bad error message, then we're going to have hundreds of issues, given the pest errors are quite bad.

Probably the way of making incremental progress is to write some insta snapshot tests for what we _want_ the error messages to be, set the tests to ignore, and then folks can use those as guides when building the error message.

I'll close this for now but feel free to continue the discussion here

**Comment by richb-hanover** [comment]
> ...  Maybe we could say "found column a above, but it excluded at select [b]"...

That's correct, but very long and probably a lot of work. Another tack: Can we make it Google-able? I don't know how malleable _pest_ is, but perhaps we could offer "Column `a` not present in result"

- It's a short string, with only the variable name needing to be substituted
- It's correct (if you think about the "result" properly)
- Googling "PRQL 'Column not present in result' would likely lead the reader to the right documentation

**Comment by max-sixty** [comment]
> "Column `a` not present in result"

I'd be open to that change!

For tweaks like this — where there's no bug or feature request — but the experience of PRQL would be marginally improved — the contribution is welcome. I'm not sure how to manage the GH issues though — it's unlikely a different contributor is going to adjust that error message unless they perceive the issue themselves. So my inclination is to suggest either making that change yourself, or keeping a list of suggestions in your repo if a budding contributor wants to start with some small changes.

Please keep adding issues for bugs or any questions, you've had a good recent run!

**Comment by richb-hanover** [comment]
> ... is to suggest either making that change yourself...

Thanks for your confidence, but I am reluctant to learn yet another code base/language/development environment. (Even if I _did_ set up a Docker environment that might make it "easy"! :-) 

I'm going to leave the change for someone who's more facile in Rust... (I do acknowledge your question: how do we keep track of these "simple changes"? Other projects have a "Good first bug" tag...)

But don't worry - I'm going to keep throwing (friendly) rocks in the pond. Thanks again.
