### ISSUE TITLE
Case-sensitive variable names in Playground

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1125]
The following code gives `Unknown variable 'appraised'` in the Playground
```
derive [
  Appraised=1000
]
select [
  appraised
]
```

Saving this as a file using the VScode extension _sometimes_ causes the latter "appraised" to be converted to "Appraised" (removing the error) before saving the file.

Are all variable names case-sensitive in PRQL?

**Comment by richb-hanover** [comment]
**Update:** I believe the two items mentioned in #1117 are both symptoms of this single test case:

> * Are variable names case-sensitive? Sometimes it seems they are, although I didn't write down an example.
>
> * Sometimes VSCode extension declared that a variable was not defined when I had clearly used it earlier. How does it know?

**Comment by max-sixty** [comment]
> Saving this as a file using the VScode extension _sometimes_ causes the latter "appraised" to be converted to "Appraised" (removing the error) before saving the file.

WDYM that sometimes VSCode converts it? As in, VSCode changes your PRQL text?

I wasn't aware we had an auto-formatter. Are we confident this is the PRQL extension — does it do this without the extension installed?

Re case sensitivity — yes, PRQL is case-sensitive. To the extent that's not in the book, that would be a helpful addition!

**Comment by richb-hanover** [comment]
1) Yes, I seem to remember the VScode extension changing case (like a pretty-printer that patches up the code on Save...) But it doesn't always do it. 

2) And now I cannot create a reproducible case. It sounds as if I should report it if I can find one.

3) I don't know all the things that the VScode extension is doing. It tends to "do the right thing", so it's very comfortable to use. But I don't think it auto-formats.

4) Case-sensitivy - a few random neurons are firing. I'll write them up separately.

**Comment by max-sixty** [comment]
OK thanks — let's reopen when we can repro
