### ISSUE TITLE
Case Sensitivity in PRQL - Pros and Cons

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1128]
I've been woolgathering about the value of case-sensitivity in PRQL. So I thought I would write down my random thoughts, to see what I think, and pass that along to you.

Assumptions:

- PRQL will always require a compiler to generate the SQL. It can enforce any rules
- I _think_ SQL is case-insensitive. I know its keywords are; most of my experience is with SQLite, where I believe table and column names are also case-insensitive.
- I work with lots of languages, and always have trouble remembering where case-sensitivity matters. I always stumble along for the first 15 minutes while I refresh my memory.
- I don't use SQL professionally - I don't know whether its lack of case-sensitivity is a problem that needs to be rectified.

Pros to case-sensitivity:

- It's consistent to require all table names, columns, variables to be the same case
- PRQL requires its keywords (from, select, etc) to be lower case
- The PRQL compiler can enforce all the constraints. That avoids a serious user trap of allowing variables "Abc" and "abc" to represent different values

Cons to case-sensitivity: (Arguments why it's OK not to be case-sensitive)

- I think in terms of hurdles for developers. Learning something new is hard; learning arbitrary rules, especially if they "don't make a difference" is harder.
- Who do we expect to be the "user base" for PRQL? If it's just software developers, then they'll be able to use whatever rules we devise. If they're grizzled SQL pro's who don't care about upper/lower case, not so much
- The underlying SQL "engine" doesn't care - it simply executes what we output.
- PRQL emits uppercase SQL keywords. Reading that out could be confusing.

Conclusion: In my mind, this argues for non-case-sensitivity: let variables "Abc" and "abc" be the same. The compiler can still check that toLower(variable-name) matches. The underlying/back end SQL engine won't care. It avoids "yet another" hassle in producing usable PRQL code. If we like, the PRQL compiler/VScode extension can provide hints that "Abc" and "abc" don't match, but will still produce correct code.

All this said, I am completely prepared to believe that there are compelling reasons for case-sensitivity. Thanks for listening.

**Comment by aljazerzen** [comment]
I think this decision was made before I joined the project, but I also stand behind it. But it's a good thing that we have a discussion about it.

The trend in other programming languages is going toward case sensitive keywords and identifier, with basically all major languages being case sensitive (C, C++, Java, Rust, Go, JavaScript, Python). This is not a real justification, but just an observation.

Primary reason I dislike insensitivity is that it is really hard to implement for all languages. In slovenian, there are a few extra letters (č, š and ž) with their uppercase variants (Č, Š and Ž). I don't think that we should delve into supporting slovenian and every other letter collation, but I also think that if `caj ~ CAJ` then it should also hold that `čaj ~ ČAJ`. That would be much harder to explain to a non technical user than insensitivity.

Also, I like having a "normalized" code style as opposed to different conventions that are used by different companies or communities. Rust does this really well with rustfmt and Python with black formatter. I know that we could still auto format or display lints about non-conventional casing, but I think we can afford to inforce case sensitivity from the start.

And as you pointed out, we can enforce this rule.

**Comment by richb-hanover** [comment]
> I think this decision was made before I joined the project, but I also stand behind it. But it's a good thing that we have a discussion about it.

Good. I'm content with this decision. One of the reasons I write these things out is to document a discussion of the issues, and our conclusions. I will close this. Thanks, all.

**Comment by max-sixty** [comment]
> One of the reasons I write these things out is to document a discussion of the issues, and our conclusions.

Great, thanks @richb-hanover , very much agreed
