### ISSUE TITLE
Need to preserve "zero" decimal places in variables

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1139]
It's a common SQL technique to multiply a value by 1.0 (or by 100.0 if computing percentages) to force a cast to REAL. But it looks as if the 0.2.9 compiler drops zeroes after the decimal point:
```
from foo
derive [
x = 1.0,
y = 1.00000000001,
z = 1.1,
q = 100.0,
]
```
gives

```
SELECT
  foo.*,
  1 AS x,
  1.00000000001 AS y,
  1.1 AS z,
  100 AS q
FROM
  foo
```

**Comment by max-sixty** [comment]
Nice find; marking this as a bug.

**Comment by richb-hanover** [comment]
That was speedy. Thanks!

Side question: What's the policy on incrementing the version number? (I see the Playground is already updated.)

Side question #2: I see the VScode extension has also been updated to handle `i=1.0`. That's very cool! But how did that happen?  Thanks again

**Comment by max-sixty** [comment]
> Side question: What's the policy on incrementing the version number? (I see the Playground is already updated.)

Mostly whenever someone would like a release, I cut one...

> Side question #2: I see the VScode extension has also been updated to handle `i=1.0`. That's very cool! But how did that happen? Thanks again

I don't see this?

**Comment by richb-hanover** [comment]
Hmmm... I need to clean my spectacles. It's available now in the Playground, not in the VScode extension. Sorry for the false alarm
