### ISSUE TITLE
Cleanup after solving precedence problems

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1146]
The solution to #1136 and #1139 make significant improvements to the usefulness of the PRQL anguage. A couple thoughts:

- Does this warrant a change to the version number?
- How can a new version of the VScode extension be generated?
- Does the Changelog need to be updated (since significant bugs have been fixed)?

Thanks as always

**Comment by max-sixty** [comment]
Yes we can release a patch version later

New VSCode extension then needs to be released by updating its `package.json`

Yes we should do the Changelog — I generally do this when releasing; though PR welcome!

**Comment by richb-hanover** [comment]
It would be terrific to release a new version of the VScode extension. Then I could use it to create (and save) queries that rummage through my database of property values. Thanks.

**Comment by richb-hanover** [comment]
**Update:** the VScode extension updated itself to 0.3.3 when I launched VScode. It now matches the Playground behavior that fixes some of the operator precedence problems and the failure to carry floating point digits. Thanks.

Neither the Playground nor the VScode extension address the [#1116bug ](https://github.com/prql/prql/issues/1116#issuecomment-1322230825) that involves a function call.
