### ISSUE TITLE
Public API of prql-compiler and binding libraries

### ISSUE THREAD

**Issue by aljazerzen** [PRQL/prql#1167]
This is structure of our current constructs and all supported conversions at the moment:
```
            PRQL string
                │ ▲
                │ │
          parse │ │ format
                │ │
       ──────►  ▼ │
PL JSON        PL AST
       ◄──────   │
                 │
                 │resolve & lower
                 │
       ──────►   ▼
RQ JSON        RQ AST
       ◄──────   │
                 │
                 │translate
                 │
                 ▼
            SQL string
```

The question is what functions should we provide as public API of prql-compiler and bindings for other languages?

We had:
```rust
fn parse(string: &str) -> Result<Vec<Stmt>>;
fn semantic::resolve(statements: Vec<Stmt>) -> Result<Query>;
fn sql::translate(query: Query) -> Result<String>;

fn compile(prql: &str) -> Result<String> {
    parse(prql).and_then(semantic::resolve).and_then(sql::translate)
}

pub fn format(prql: &str) -> Result<String>;
pub fn to_json(prql: &str) -> Result<String>;
pub fn from_json(json: &str) -> Result<String>;
```

And I replaced the 3 last functions with:
```rust
fn pl_to_prql(pl: Vec<Stmt>) -> Result<String>;
fn pl_to_json(pl: Vec<Stmt>) -> Result<String>;
fn json_to_pl(json: &str) -> Result<Vec<Stmt>>;
fn json_to_rq(json: &str) -> Result<Query>;
```

Bindings current have `compile` function along with `to_json` and `from_json` (and some of them `to_sql`). I think we should unify the API to be the same of all of the bindings.

What should be our naming schema? 

Should we rename `parse`, `resolve` and `translate` to `x_to_y()`?

**Comment by eitsupi** [comment]
+1 for renaming to `x_to_y`.
Considering the possibility of future compilations to other targets such as substrait, etc., I think it makes sense to clearly state what is being converted from what.

**Comment by aljazerzen** [comment]
Yeah, I'll probably change the API to what I proposed. This is updated schema:
```
                   PRQL

                   │ ▲
        prql_to_pl │ │ pl_to_prql
                   │ │
    json_to_pl     ▼ │
        ────────►
PL JSON           PL AST
        ◄────────
    pl_to_json     │
                   │
                   │
          pl_to_rq │
                   │
                   │
    json_to_rq     ▼    rq_to_substrait
        ────────►        ─────────►
RQ JSON           RQ AST            Substrait
        ◄────────        ◄─────────
    rq_to_json     │    substrait_to_rq
                   │
         rq_to_sql │
                   ▼

                   SQL
```
Excluding unimplemented Substrait, there are 8 functions.

All of them will be producing unformatted errors, which can passed to `format_errors`.

For convenience, I'll keep the `compile` function which is basically `prql_to_pl`, `pl_to_rq`, `rq_to_sql` and `format_errors` combined.

So total 10 functions that cover all of functionality one would want (i hope).

**Comment by aljazerzen** [comment]
Another thing I realized today was that dialect does not belong into the language, but should be part of compilation options.

Because declaring `dialect:postgres` at the top of the query gives impression that *the PRQL query* is somehow in postgres dialect, when we mean that the *target* should be postgres dialect.

I got confused about that when looking at [pomsky playground](https://playground.pomsky-lang.org/) and realized that we have it even worse.

So I propose that `rq_to_sql` takes the following argument:
```rust
CompilerOptions { dialect: Dialect, pretty_print: bool }
```
(`pretty_print=false` would disable formatting the query and return it in one line)

**Comment by max-sixty** [comment]
> Because declaring `dialect:postgres` at the top of the query gives impression that _the PRQL query_ is somehow in postgres dialect, when we mean that the _target_ should be postgres dialect.

Yes interesting.

It would mean that we can't offer a very simple `str -> str` API — instead tools need some way to ask the user which dialect they want, and then pass it as a flag to the API. Not a huge downside! But we'd have to think about how to do that in the playground and VSCode extension.

WDYT about structuring the compiler code with `CompilerOptions` but also allowing a query to specify its dialect like we do now?

Would you still have `version` in the header? In some ways it's similar as a global flag, though possibly unlike `dialect`, it is part of the query?

**Comment by snth** [comment]
Hmm, this is a tricky one because I think there are advantages to both approaches here.

It's true that the PRQL query should be independent of the dialect and eventually when we have tight integration with data tools it should just produce a data result set without a SQL intermediate form (in any dialect).

However at the moment we are just targeting SQL so it is convenient to be able to specify the output format/dialect.

How about marking this as a PRAGMA directive which makes it clear that it's a directive for the compiler and not part of the query?

Something like the following (just a lazy first stab so change at will):
```sql
-- PRAGMA: output_dialect:postgres
```

**Comment by max-sixty** [comment]
> ```sql
> -- PRAGMA: output_dialect:postgres
> ```

Isn't this quite similar to the current approach though?

**Comment by aljazerzen** [comment]
The comment is not a part of the language, but just an annotation to this specific compiler. But yes, we could just say that current `prql dialect:postgres` is not part of the language, but a generic tag.

In both cases, one may think that it's implying prql's dialect and not generated sql's dialect. Maybe just change query def to 
```
prql output_dialect:postgres
```

I'm +1 on adding dialect to CompileOptions and 0 on both kinds of `output_dialect` in the lang.
