### ISSUE TITLE
Uppercase table name breaking compiler

### ISSUE THREAD

**Issue by mklopets** [PRQL/prql#1183]
With the recent semantic/0.3.0 changes, this query compiles just fine (using a locally running playground):
```elm
table SomethingSomething = (
  from somesource
)

table othertable = (
  from SomethingSomething
)

from othertable
```

but this, where othertable is PascalCased, doesn't:
```elm
table SomethingSomething = (
  from somesource
)

table OtherTable = (
  from SomethingSomething
)

from OtherTable
```

There's no compilation error returned, but the browser console shows Rust erroring out with `Uncaught Error: unreachable`. If you just copy/paste the broken query into the playground (as opposed to typing it out), the output remains completely unchanged.

**Comment by aljazerzen** [comment]
Yup, this is a problem and it's not casing.

When resolving I put CTEs into a module that has a hashmap, which does keep the order. When I extracted them back out, I sort them by name so the compilation is stable. 

Workaround for you is adding a number before the tables names, but this is priority for me now. A simple toposort should sort it out.

**Comment by aljazerzen** [comment]
https://github.com/prql/prql/blob/076fe3000e81155c629f4f9e87491bea3753ba17/prql-compiler/src/semantic/lowering.rs#L506-L508

edit: wrong TODO comment
