### ISSUE TITLE
Missing select with join

### ISSUE THREAD

**Issue by mklopets** [PRQL/prql#1198]
```elm
from account

filter name == "PRQL" # this creates the intermediary table_1 which triggers the problem

join user_in_account [==account_id]

select name
```
Compiles to
```sql
WITH table_1 AS (
  SELECT <------------ this should also select `name`
    account_id
  FROM
    account
  WHERE
    name = 'PRQL'
)
SELECT
  name <-------------  this does not exist in table_1
FROM
  table_1
  JOIN user_in_account ON table_1.account_id = user_in_account.account_id
```
```
Query 1 ERROR: ERROR:  column "name" does not exist
LINE 10:   name
           ^
```

If the original PRQL is modified:
```diff
-select name
+select account.name
```
then the output SQL is fine.

We could either:
1. require the PRQL `select` at the end to explicitly specify the table
2. automatically select `account.name` as we already know there's a `name` there for a fact – this is clearly somewhat less safe, but also less verbose
3. do a combo of these – compile like option 2, but output a warning (not error) about the table being inferred

**Comment by aljazerzen** [comment]
This currently expected behavior that I petitioned to change with #1193 

In this case, `select name` is ambiguous reference because it could mean both `account.name` or `user_in_account.name`. This means that it resolves to s-string, which anchoring cannot not consider when creating CTEs.

This implicit resolution to s-strings is exactly the reason for #1193

**Comment by mklopets** [comment]
FWIW, I'd argue that while there's indeed a language design question behind how we should solve this, it's also currently a bug as far as users are concerned, as PRQL happily accepts this input query, generating SQL that will never work on any database

If this worked in some cases, depending on what your DB looked like, then that would be different.

**Comment by max-sixty** [comment]
Without wanting to move the discussion from #1193 here — so assuming we allow this — shouldn't the result be:

```diff
WITH table_1 AS (
  SELECT
-    account_id
+    * 
  FROM
    account
  WHERE
    name = 'PRQL'
)
SELECT
  name
FROM
  table_1
  JOIN user_in_account ON table_1.account_id = user_in_account.account_id
```

While it's not always the case that snippets of PRQL will compile into exactly the same SQL when moved, it's worth noting that the result of the first two lines does compile to this when alone:

```elm
from account

filter name == "PRQL"
```

...is indeed:

```sql
SELECT
  *
FROM
  account
WHERE
  name = 'PRQL'
```

**Comment by max-sixty** [comment]
This now raises an error:

```
Error: 
   ╭─[:7:8]
   │
 7 │ select name
   ·        ──┬─  
   ·          ╰─── Ambiguous name. Could be from any of _frame.user_in_account.`*`, _frame.account.`*`
───╯
```

I'll close but feel free to reopen
