### ISSUE TITLE
Resolving table name inside S-string

### ISSUE THREAD

**Issue by mklopets** [PRQL/prql#1199]
```elm
from x

filter field > 0 # this causes an intermediary table_1 to be created

join y [something]

select [
  # this compiles to `x.field` while it should be `table_1.field`
  field = s"{x}.field"
]
```
The resulting query will fail on the DB level:
```sql
WITH table_1 AS (
  SELECT
  FROM
    x
  WHERE
    field > 0
)
SELECT
  x.field AS field <---------- there's no `x` available here – instead, this should reference table_1.field
FROM
  table_1
  JOIN y ON something
```

Curly brackets inside of S-strings nicely resolve fields (`s"{x.field}"`) but resolving only the table part doesn't (`s"{x}.field"`).

**Comment by mklopets** [comment]
Open (language design) Q: is resolving just a table name something we want to support inside S-strings?

If no, we should probably error. If yes, this here is a bug.

**Comment by aljazerzen** [comment]
To prql-compiler, this basically just a reference to a table instance from within a query. It doesn't know that in s-string, you are actually referring to a column.

Such table references would need to have their own implementation for find the correct name in the current CTE, and I'm not sure it reasonable to invest our time in that.

Instead we should probably error out, as you suggest.

**Comment by max-sixty** [comment]
(I'm late to comment here — but def agree re keeping s-strings opaque — we had some tangential issues a couple of weeks ago. One reflection from those is that anything we do to make them less opaque would still be unsatisfying, and add onto any confusion)
