### ISSUE TITLE
Formal grammar spec for prql

### ISSUE THREAD

**Issue by qharlie** [PRQL/prql#12]
A formal grammar specification would allow others to easily create parsers, do you have a preference PEG or BNF ?

**Comment by rchowell** [comment]
Once syntax has an initial decision, I can take up an ANTLR parser

**Comment by max-sixty** [comment]
Thanks for opening the issue @qorrect !

My initial plan was to write a parser in `nom`, which I've heard great things about and had good initial experiences with. As you can see, it's not much at the moment.

I think a formal grammar would be useful, and the language is developed enough to start on that if someone wants to have a go. I would vote to go for a PEG grammar given the language is relatively simple™, and if we pursue the nom route it'll be broadly compatible.

As ever, open to feedback! Thank you!

**Comment by max-sixty** [comment]
Now that we're using pest, we have an analytical grammar to coordinate around.

My sense is that while some details are still evolving, the analytical spec is sufficient, and we can formalize when there's less evolution. But if anyone would benefit from changes (e.g. @qorrect depending on what's helpful for you if you're doing this in python), feel free to comment.

**Comment by vanillajonathan** [comment]
With a formal grammar you could generate a syntax diagram #1810.
