### ISSUE TITLE
Trigger new build of VScode extension?

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1202]
Is the `0.3` version of PRQL good enough to be worth launching a new version of the VScode extension? Thanks.

**Comment by max-sixty** [comment]
Done

**Comment by max-sixty** [comment]
(https://github.com/prql/prql-vscode/releases/tag/0.3.4)

**Comment by richb-hanover** [comment]
**Update:** 

1. The VScode extension automagically updated when I opened VScode (I had quit it) and saw the Extensions item in the sidebar had an update. I clicked "Reload Required" and Presto! I now have  `0.3.0` installed. 
2. This version update is even further impetus to display the version number in a comment
3. I have reached a new stable plateau, so I can go back to my (assigned) work to actually massage the SQL database.

THANKS!
