### ISSUE TITLE
Generated SQL has duplicate column

### ISSUE THREAD

**Issue by neelance** [PRQL/prql#1249]
PRQL input:
```prql
from report
derive r = s"RANK() OVER (PARTITION BY timeperiod, campaignid ORDER BY _sdc_report_datetime DESC)"
filter r == 1
```

Output:
```sql
WITH table_1 AS (
  SELECT
    *,
    RANK() OVER (
      PARTITION BY timeperiod,
      campaignid
      ORDER BY
        _sdc_report_datetime DESC
    ) AS r
  FROM
    report
)
SELECT
  *,
  r
FROM
  table_1
WHERE
  r = 1
```

This output is not good, because the `SELECT *, r` generates two columns with the same name `r`. One gets renamed to `r_1` by BigQuery. In some situation it can even cause an error "duplicate column name".

**Comment by max-sixty** [comment]
Great. And here's a simpler case:

```elm
from report
derive a = b
filter a == 1
```

```sql
WITH table_1 AS (
  SELECT
    *,
    b AS a
  FROM
    report
)
SELECT
  *,
  a
FROM
  table_1
WHERE
  a = 1
```

I also don't think we need the CTE here. Though no great harm in it.

(Separately from this issue — and I'm guessing you know this — but the s-string isn't required; PRQL can do the window function)

**Comment by max-sixty** [comment]
(Labeling as "bug"; as a broad definition of "thing we should change")
