### ISSUE TITLE
Does the Dockerfile work?

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1266]
@richb-hanover thank you for getting the `Dockerfile` running a while ago!

But I've been trying to get it working for a while, and I can't so far run `task test-all`. Is that just me — can you run that successfully?

It's ofc great to have partial work in the repo — the whole project is very partial! But we should be able to say what works vs. doesn't work yet.

The issues I was getting:
- Errors from `cd playground && npm install && npm run build` — from `task build-web` fails: https://github.com/prql/prql/actions/runs/3690957304/jobs/6248506869
- The version of `hugo` from `apt` isn't recent enough to compile the website

I tried moving to `brew` in https://github.com/prql/prql/pull/1262 so we'd have recent versions, but that now generates an error too: https://github.com/prql/prql/actions/runs/3691393939/jobs/6249349276

I also struggled at testing locally, since `brew` doesn't run on arm64 linux, and on amd64 linux `cargo install` runs out of memory at 16GB on fetching its index! So quite the confluence...

If we can narrow the scope of this, then great. If we can't quite manage to get there, it's also OK to remove it from the repo until we can — no shame in pausing.

**Comment by max-sixty** [comment]
And if it only works for a subset of things — maybe just the rust part — then that's completely fine. We can just annotate it, adjust the proposed tests in #1262, and then we're in a good place.

**Comment by richb-hanover** [comment]
I could believe that the Dockerfile only partially works. My testing was primarily for a) Playground, b) Language Book, c) Website, since those are easily tested from observation. (At the time I created the Dockerfile, I didn't really understand the PRQL test regime, and had no idea how to test/use the compiler or other bits outside of the Playground.)

When I try `task test-all` within the Docker container, it fails this step `task: [test-rust] cargo insta test --accept -p mdbook-prql -- run_examples` with the error below.

It might make sense to update the USING_DOCKERFILE.md to indicate what _is_ working

---
```
...
done: no snapshots to review
task: [test-rust] cargo insta test --accept --target=x86_64-unknown-linux-gnu --delete-unreferenced-snapshots
error: Found argument '--target' which wasn't expected, or isn't valid in this context

USAGE:
    cargo insta test --accept

For more information try --help
task: Failed to run task "test-all": task: Failed to run task "test-rust": exit status 1
```

**Comment by aljazerzen** [comment]
The image builds and run fine on my computer. I tried running prql-compiler and `cargo test`.

I'm quite confused by this work flow. Do people run containers for development? It does not contain my shell, aliases or git config, so I cannot see myself using it. I would go for a nix-shell (if someone wrote declarations for it) but docker image is just too bare.

**Comment by richb-hanover** [comment]
> I'm quite confused by this work flow. Do people run containers for development?

Yes, some people do. I wouldn't expect that you would use it - you're deeply invested in all the tooling to make this stuff go. And you have highly-customized your configuration and workflow (over weeks?) to make all this happen.

But I dance along in life playing with a dozen or so different projects, using all kinds of languages, environments, etc. And I regularly crash into version/configuration problems. You can read my semi-rant at https://github.com/prql/prql/pull/1022#issuecomment-1276947514 Or my other [semi-rant.](https://randomneuronsfiring.com/more-fun-with-docker-tooling/)

For me, firing up the Docker container (that never fails) to make sure that my edits to the Language Book are good is _waaaay_ easier than wrestling with even one rust/Python/etc. version incompatibility.

**Comment by aljazerzen** [comment]
Ok, I see your use case.

It's true that setting up dev env for new project is a pain in the ass and for quick "let me check this out" docker is the best option.

Thank you for contributing the dockerfile for any other new-commers.

**Comment by max-sixty** [comment]
Thanks for looking @richb-hanover !

Great, sounds like it works for the rust — let me adjust the tests a bit so it only tests for that, and add a note.

---

> When I try `task test-all` within the Docker container, it fails this step `task: [test-rust] cargo insta test --accept -p mdbook-prql -- run_examples` with the error below.

That sounds like an outdated version of insta; it might require a `task install-cargo-tools`.

**Comment by max-sixty** [comment]
If you get some time soon @richb-hanover , have a look at #1262 and lmk if you have any feedback

**Comment by aljazerzen** [comment]
For anyone who will be doing any tweaks, add this to `.dockerignore`:
```
target/
```

**Comment by richb-hanover** [comment]
Using #1262, I got farther (see below).

NB: I was able to `cd book; mdbook serve -p 3000` and it started right up and I could look at the Book...

Two more items:
* The 'rust caching' article has disappeared. Here's the Wayback Machine link to the original article: https://web.archive.org/web/20221028051630/https://blog.mgattozzi.dev/caching-rust-docker-builds/
* I am going offline for a week or so. Thanks for all this great work!

```
... ran fine up to here...
task: [build-all] mdbook build book/
2022-12-15 12:36:54 [INFO] (mdbook::book): Book building has started
Warning: The mdbook-admonish preprocessor was built against version 0.4.21 of mdbook, but we're being called from version 0.4.23
   Compiling libm v0.2.6
   Compiling num-traits v0.2.15
   Compiling num-integer v0.1.45
   Compiling bstr v0.2.17
   Compiling toml v0.5.9
   Compiling clap v3.2.23
   Compiling opener v0.5.0
   Compiling globset v0.4.9
   Compiling handlebars v4.3.5
   Compiling clap_complete v3.2.5
   Compiling chrono v0.4.23
   Compiling mdbook v0.4.22
   Compiling mdbook-preprocessor-boilerplate v0.1.1
   Compiling mdbook-prql v0.3.1 (/app/book)
    Finished dev [unoptimized + debuginfo] target(s) in 4m 29s
     Running `target/debug/mdbook-prql supports html`
Running comparison preprocessor
    Finished dev [unoptimized + debuginfo] target(s) in 0.79s
     Running `target/debug/mdbook-prql`
Running comparison preprocessor
Running comparison preprocessor
2022-12-15 12:41:25 [INFO] (mdbook::book): Running the html backend
task: [build-all] cd playground && npm install && npm run build
"npm": executable file not found in $PATH
task: Failed to run task "test-all": task: Failed to run task "build-all": exit status 127
```
