### ISSUE TITLE
Is the Playground broken?

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1272]
Just now, I went to try something on the Playground at https://prql-lang.org/playground/

The window briefly flashes up the "sidebar" at the left, then clears to the grey background. A quick peek with the browser Inspect Element shows there isn't much content there...

In fact, it looks as if the `id="root"` element is empty. (Firefox and Safari on macOS 12.6.1)

**Comment by aljazerzen** [comment]
Yes it was, thank you for reporting. It is now fixed.
