### ISSUE TITLE
Playground can't build on npm@9

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1296]
I can't work out why...

```
$ npm install -g npm@9

$ npm run build

> prql-playground@0.1.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'prql-js/dist/bundler' in '/Users/maximilian/workspace/prql/playground/src/workbench'
```

I'll lock the npm version at 8 for the moment in https://github.com/prql/prql/pull/1293, as I'm probably not being that productive attempting to fix it.

**Comment by Shuozeli** [comment]
Seems to be related to https://github.com/npm/cli/issues/5965. The default value of `install-links` is set to true in [npm@9](https://docs.npmjs.com/cli/v9/commands/npm-install?v=true#install-links). 

Install the `../prql-js` with `install-links` as false.
```
npm i ../prql-js --install-links=false
npm run build
```

**Comment by max-sixty** [comment]
Great find @Shuozeli !
