### ISSUE TITLE
Playground "copy to clipboard" no longer works

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1309]
I'm just getting `undefined` hitting the clipboard. I tried on Firefox & Chrome

**Comment by max-sixty** [comment]
We've also lost the error reporting location, which seems to always default to the first word now:

<img width="220" alt="image" src="https://user-images.githubusercontent.com/5635139/208754621-9bf141c1-7f7c-44e0-aa11-4a0f7baeed21.png">

I haven't written much infra for `prql-js` and the playground — I don't think we have tests for this sort of thing. I'm happy to spend some time there if that would make us more productive. I don't have much JS experience but I'm sure it's tractable...

**Comment by aljazerzen** [comment]
These are minor bugs that could be caught by testing, yes.

But UI testing is hard and quite resource intensive, so I don't think it's worth setting up right now.
