### ISSUE TITLE
Main repo shows GHA page instead of README.md

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1352]
When  I go to https://github.com/PRQL/prql, I expect to see the main repo's README.md page.

Recently (today? After the update to the README?) I note that that link takes me to the Github workflows page at https://github.com/PRQL/prql/blob/main/.github/README.md. Thoughts?

**Comment by max-sixty** [comment]
D'oh! I guess GH priorities `.github/README.md` over the root. Thanks for spotting!!
