### ISSUE TITLE
Recursive queries documentation?

### ISSUE THREAD

**Issue by cfv1984** [PRQL/prql#1354]
Hi! Most of the tables I work with on this side project use recursive CTEs to build adjacency lists; things like posts, tags etc have a hierarchy built this way and I would like to preserve that.

Is this possible with `prql`? I can't find any reference to it in the available docs, but maybe I'm just terrible at searching :(

**Comment by max-sixty** [comment]
Check out https://github.com/PRQL/prql/issues/407 — give that a vote & add some examples of the sort of queries you're doing to signal boost it. I think this is a less familiar area for some of us.
