### ISSUE TITLE
Add color option to CLI

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1355]
Currently the CLI can't take options such as `--color` / `--no-color`. Ideally we'd be able pass these, and they would flow through with an `Options` struct to the compiler.

A future version could check whether we're in a TTY and default to `--no-color` if so (it's also possible that clap offers something like this?).

Labeling as Good first issue (which also make good nth issues). As ever, lots of folks will be happy to answer questions!

**Comment by Shuozeli** [comment]
Hi Max, 

I'd like to work on this. My thought of the steps for adding the option are:

1. Add one `enable_color` boolean field in the [Option](https://github.dev/PRQL/prql/blob/467d508a45ea1472f027d1da5ea7700cb0caae4c/prql-compiler/src/sql/mod.rs#L60) struct under the `sql/mod.rs`.

2. Add the cli argument `enable_color`, `color`, or `no-color` to the compile command.

3. Pass the cli argument as an `Option` field to the compile function

Please correct me if my understanding is wrong.

**Comment by max-sixty** [comment]
That would be great @Shuozeli !

I think that sounds very reasonable.

I would pass a full `Options` struct to the `compile` function (I think that's what you were suggesting). And yes re the `--color` / `--no-color` flags.

There's a "smaller" version where we strip out the color at the CLI level, I think that would be easier but less good (but OK!)

@aljazerzen lmk if you have any thoughts!

**Comment by aljazerzen** [comment]
Hmm, sql does not do any highlighting ATM, so it doesn't need color option (at least for now). But the cli argument would be use to control [this param](https://github.com/prql/prql/blob/c7df3d4cc1d9830cd6c96cfd1ddbc843139eff59/prql-compiler/src/error.rs#L186) in error formatting. This function is called 

The best way to do this would be:
- add a new Options struct to `lib.rs`:
  ```rust
  struct Options {
      sql: sql::Options,
      color: bool
  }
  ```
- change `compile(prql: &str, options: Option<sql::Options>)`
  to this `compile(prql: &str, options: Option<Options>)`
- add a `impl Default for Options` and `impl From<sql::Options> for Options` for convenience
- make sure that all crates compile and pass `cargo test`

**Comment by max-sixty** [comment]
OK, so we'd have a nested `Options` struct. That seems very reasonable too. 

@Shuozeli does that make sense to you?

**Comment by Shuozeli** [comment]
Yes, thank you for the clarification. I will be working on this one.

**Comment by vanillajonathan** [comment]
@Shuozeli Any progress on this?
