### ISSUE TITLE
Error: "Cannot lower to IR Expr" when using a function as a group's keys

### ISSUE THREAD

**Issue by thisismiller** [PRQL/prql#1361]
I was trying to see if I could abstract out the group by keys into a function, and broke the compiler instead.

The following query in the playground:

```
func compute_keys row -> [row.x, row.y]

from T 
group [(from | compute_keys)] (
  derive x = y + 1
)
```

Produces the following error:

> "Cannot lower to IR expr: `Expr { id: Some(13), kind: Closure(Closure { name: None, body: Expr { id: None, kind: FuncCall(FuncCall { name: Expr { id: None, kind: Ident(Ident { path: [], name: \"compute_keys\" }), span: Some(span-chars-64-76), target_id: None, ty: None, needs_window: false, alias: None }, args: [Expr { id: Some(10), kind: Closure(Closure { name: Some(Ident { path: [\"std\"], name: \"from\" }), body: Expr { id: None, kind: Literal(Null), span: Some(span-chars-968-972), target_id: None, ty: None, needs_window: false, alias: None }, body_ty: Some(table<[]>), args: [Expr { id: None, kind: Ident(Ident { path: [], name: \"_pip_val\" }), span: None, target_id: None, ty: None, needs_window: false, alias: None }], params: [FuncParam { name: \"default_db.source\", ty: Some(table<[]>), default_value: None }], named_params: [], env: {} }), span: Some(span-chars-57-62), target_id: None, ty: Some(func table<[]> -> table<[]>), needs_window: false, alias: None }], named_args: {} }), span: Some(span-chars-64-76), target_id: None, ty: None, needs_window: false, alias: None }, body_ty: None, args: [], params: [FuncParam { name: \"_pip_val\", ty: None, default_value: None }], named_params: [], env: {} }), span: Some(span-chars-56-77), target_id: None, ty: Some(func infer -> infer), needs_window: false, alias: None }`"

Pretty sure this should just be some sort of parsing error, but if there's an actually supported way to do this, please let me know.

**Comment by aljazerzen** [comment]
This error should say "expected a list of columns, found a closure".

You probably want this:
```elm
func group_xy pipeline rel -> (
    rel
    group [x, y] pipeline
)

from T 
group_xy (
  derive z = rank
)
```

**Comment by aljazerzen** [comment]
With #1397 this is now the output:

```
Error:
    ╭─[:61:8]
    │
 61 │ group [(from | compute_keys)] (
    ·        ──────────┬──────────
    ·                  ╰──────────── unexpected `<closure over `compute_keys <closure over `null` with 1/1 args>` with 0/1 args>`
    ·
    · Help: this is probably a 'bad type' error (we are working on that)
────╯
```

Not the most readable, but this will be improved when we improve typing.
