### ISSUE TITLE
`sql_dialect` / `dialect`/ `target`?

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1388]
Previously our header used `dialect`, like:

```elm
prql dialect:postgres
```

Now we use `sql_dialect`
```elm
prql sql_dialect:postgres
```

I was thinking through the semantics of how something like https://github.com/PRQL/prql/issues/1369 would work. 
It could be `prql python_dialect:xarray`. But then we have two parameters that can't be used together, rather than just one parameter. Should it instead be more general, something like:

```elm
prql target:sql.postgres
```

and then #1369 would use

```elm
prql target:python.xarray
```

While I don't expect we'll have any target apart from SQL soon (#1369 is highly speculative!), 0.4 is a breaking change, so if we want to change it, doing so now would avoid another breaking change later.

**Comment by aljazerzen** [comment]
Good idea, I concur.
