### ISSUE TITLE
Negative Take Value Generates Invalid SQL

### ISSUE THREAD

**Issue by BlurrechDev** [PRQL/prql#1396]
The following is the result of some testing via https://prql-lang.org/playground/

**Minimal example 1:**
```elm
prql sqldialect:mysql
from employees | take (-1)
```

Generates the following invalid SQL:
```sql
SELECT
  *
FROM
  employees
LIMIT
  -1 L
```

**Minimal example 2:**
Any range starting with a number less than 1 has a similar issue.
```elm
prql sqldialect:mysql
from employees | take (0..1)
```

Generates the following SQL with a disallowed negative offset:
```sql
SELECT
  *
FROM
  employees
LIMIT
  2 OFFSET -1
 
  ```

As an aside, I'm big fan of this project and I only wish it had existed years ago. 👍 🥇

**Comment by aljazerzen** [comment]
Closed by #1397 as:

```
Error:
    ╭─[:58:18]
    │
 58 │ from employees | take (0..1)
    ·                  ─────┬─────
    ·                       ╰─────── take expected a positive int range, but found 0..1
────╯
```
