### ISSUE TITLE
`table` `Display` misses parentheses

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1414]
This is the output of a query's `.to_string`, from https://github.com/PRQL/prql/pull/1413/files#diff-238f7d8cbd582e19ac0d1da76d1d7ec3985c0204c0140c571967815ba42abec8R6 . 

The s-string needs surrounding parentheses; this wouldn't be valid.

```elm
table grouping = s"
  SELECT SUM(a)
  FROM tbl
  GROUP BY
    GROUPING SETS
    ((b, c, d), (d), (b, d))
"
```

This would be a good first issue — it should be quite reasonable to add parentheses to `Table`'s `Display` trait output.

**Comment by Rishav1707** [comment]
Shall I work on this issue? @max-sixty

**Comment by aljazerzen** [comment]
@max-sixty a consequence of removing onboarding label in favor of good-first-issue is that all good-first-issues should have a detailed explanation...

But regarding the issue: I think it'd be best to change how parser works, because having parenthesis here is not really necessary.

**Comment by max-sixty** [comment]
OK very much agree on the quality of the issue, sorry @Rishav1707 . We'll write a better issue.

But @aljazerzen re how we do this — check out my comments on https://github.com/PRQL/prql/issues/1394#issuecomment-1369334315 — how are you envisaging parsing it without parentheses? We could have the rvalue in the parser be `(s_string | nested_pipeline)`, though it would be special-casing that.

**Comment by aljazerzen** [comment]
I think we can parse an regular expr_call here, because this would also make sense:

```
table a = take 4 (from employees)
```

So for the normal case of using a pipeline, you'd have to use parenthesis, just like a regular inline pipeline.

**Comment by max-sixty** [comment]
You're absolutely right — #1422
