### ISSUE TITLE
Simplify GHA, move actions into workflows

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1424]
GHA now allows for a depth of four workflows, up from a depth of two: https://docs.github.com/en/actions/using-workflows/reusing-workflows#nesting-reusable-workflows

As described in [this footnote](https://github.com/prql/prql/blob/main/DEVELOPMENT.md#user-content-fnref-6-2023e5f0a169d67b6f944f92bb253e5a), there's currently some complexity in our workflows because of the prior limitation of two — we have steps in Actions such as https://github.com/prql/prql/blob/0.3.1/.github/actions/test-rust/action.yaml, because it was a way around that limitation.

So a welcome change would be to:
- Remove copypasta
  - `test-js.yaml` could be called from `test-all.yaml`, rather than copy&pasting the text
  - same for `test-java`
- Move the actions steps back into workflows
  - We could start with `test-python`; there is no need for that to be an action now, and it has an existing workflows which just call the action. (Done, #1554)
  - `test-rust` could become a workflow which gets called from `pull-request.yaml` & `test-all.yaml`
  - We may want to leave the two `build` actions as actions — they produce artifacts we use later in the workflows that call them — and maybe `time-compilation`. It's probably a bit cleaner to have them as workflows, but much more marginal than the others.

While this is less "critical path" than a rust contribution, it would be a good way of contributing to PRQL without writing rust, or if someone is interested in learning more about GitHub workflows.

**Comment by max-sixty** [comment]
Tangentially related — building the playground when that changes. With the proposed design here, that could be its own workflow which the release steps calls. ref https://github.com/PRQL/prql/pull/1497#issuecomment-1382442379

**Comment by fool1280** [comment]
Hi Max, can I take a look at this?

**Comment by fool1280** [comment]
Hi Max, I would like to work on this :)

**Comment by max-sixty** [comment]
Great @fool1280 ! Feel free to ask questions or PR something. Feel free to start with something small; no need to do it all in one PR.

**Comment by fool1280** [comment]
Hi @max-sixty, please correct me if I'm wrong. I'm still a bit stuck on this part: 

> Move the actions steps back into workflows
We could start with test-rust & test-python; there is no need for these to be actions now, and they each have existing workflows which just call the actions.

For test-python, are we moving some actions to test_all or are we moving all of the test_python action into the test_python workflow, then call it? Sorry, it is the first time I worked with GitHub actions

**Comment by max-sixty** [comment]
> are we moving all of the test_python action into the test_python workflow, then call it

This is exactly correct! So https://github.com/PRQL/prql/blob/ad543b80426981e0d2300d38061633226d3ea9dc/.github/actions/test-python/action.yaml would be deleted and its contents moved to https://github.com/PRQL/prql/blob/ad543b80426981e0d2300d38061633226d3ea9dc/.github/workflows/test-python.yaml 

(it's not quite a copy paste since the names for things can be slightly different, but it's close)

**Comment by max-sixty** [comment]
NB: the current python action calls another action `build-prql-python`. For an initial PR, I'd suggest leaving `build-prql-python` unchanged, and then we can evaluate whether it's needed as a separate thing later.

**Comment by max-sixty** [comment]
`test-python` is done! From #1554. I updated the text at the top of this issue with some clarifications on `test-rust` & the copy-pasting that currently exists

**Comment by fool1280** [comment]
Should I continue the work for `build` actions? Personally, I don't think it can be more efficient as some of the steps in actions depends on the previous ones. Turning `build` into workflow would require defining which output to return and makes the code more complicated. What do you think?

**Comment by max-sixty** [comment]
> Personally, I don't think it can be more efficient as some of the steps in actions depends on the previous ones.

I think that's right. And they never run independently, so even the benefits are limited to the smallest code clean-up...

So I think we might have reader a zenith here! (Of course open to changes if you can think of them.)

I'll close this as completed then. Thank you v much @fool1280 ! 

BTW if you want more like this — check out https://github.com/PRQL/prql/issues/866. Or if you want to do anything else, let us know and folks will continue helping.

**Comment by fool1280** [comment]
Thank you, let me take a look at it :) I would like to eventually try some small Rust issues, but couldn't find one so far. Is there any recommendation?

**Comment by max-sixty** [comment]
Great, yes for sure re rust issues! How much rust experience do you have?

If you're new, I would start with something really small. For example, take an issue like https://github.com/PRQL/prql/issues/1588, and write a test in `test.rs` that shows it fails. So nothing gets fixed, but we can reproduce the error, and you can get the environment set up.

If you have more experienc, we can find a bigger issue (we have actually been meaning to make better issues for new-ish contributors, some of them in https://github.com/PRQL/prql/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 aren't _that_ easy. So this could be a good forcing mechanism for us to do that.

**Comment by fool1280** [comment]
Oh, I'm totally new to Rust, let me look into it :) Thanks @max-sixty :) (idk what to called you lol)

**Comment by max-sixty** [comment]
> Oh, I'm totally new to Rust, let me look into it :) Thanks @max-sixty :) (idk what to called you lol)

Great, feel free to open a partially complete PR if you want help (or even an empty one!). The Discord is also active.

**Comment by fool1280** [comment]
Thanks, I'll let you know!

**Comment by max-sixty** [comment]
Closed by #1560 among others, thanks to @fool1280 !
