### ISSUE TITLE
tracking: compiler panic

### ISSUE THREAD

**Issue by aljazerzen** [PRQL/prql#1431]
This is a tracking issue of all pancics that occur during compilation. 

Most `.unwrap`s and `unimplemented!`s have been introduced with with semantic branch and 0.3 where I was too lazy to gracefully handle many corner cases. Many of these cases are also actual unimplemented features, so the real fix is to do the features.

So let's link any future issues with examples that panic to here, so they can be converted into tests when we come around to fix them all.

**Comment by aljazerzen** [comment]
Ref #1334

**Comment by max-sixty** [comment]
*Edit: this is now fixed*

---

Here's a panic, which should error because of the function call without parentheses:

```elm
from employees
derive foo = round 1+1 bar
```

**Comment by max-sixty** [comment]
@aljazerzen could this be a Good First Issue? I'm thinking that given an example, folks can find the panic fairly easily, and change it from `.unwrap` to an `Error`?

**Comment by aljazerzen** [comment]
Yeah maybe. Sometimes it can be an actual programmer error.

**Comment by max-sixty** [comment]
OK — I've added the label. 

But for anyone seeing this — as @aljazerzen, there's some possibility that the errors are deeper (but that should be fairly clear very early). Feel free to post any questions at all!

**Comment by max-sixty** [comment]
I don't see any outstanding issues — maybe there were fewer than we thought? Or maybe we haven't found them yet...

**Comment by aljazerzen** [comment]
Apparently yes. I expected more of them, but it turns out that my `.unwrap()`s were justified :D
