### ISSUE TITLE
Bad link in DEVELOPMENT.md

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1433]
In the `## Releases` section, it says:

> 3. After merging, go to [Draft a new release](https://github.com/PRQL/prql/releases/new), copy the changelog entry into the release notes, enter the tag to be created, and hit "Publish".

The link - https://github.com/PRQL/prql/releases/new - doesn't go anyplace useful. I didn't fix it because I'm not sure where the link _should_ go.

**Comment by max-sixty** [comment]
I think possibly this only works for maintainers? I see:

<img width="531" alt="image" src="https://user-images.githubusercontent.com/5635139/210634253-a3155b01-91b1-4065-bd92-b5ccdea51f15.png">

Happy to have a footnote to on that link to say this...

**Comment by richb-hanover** [comment]
> Happy to have a footnote to on that link to say this...

That's a good idea.

(When I click that link, I wind up at https://github.com/ ... )

**Comment by aljazerzen** [comment]
Closed by #1523
