### ISSUE TITLE
BigQuery: Window framing clause is not allowed for analytic function rank

### ISSUE THREAD

**Issue by neelance** [PRQL/prql#1434]
This works:
```
from report
derive r = s"RANK() OVER (PARTITION BY timeperiod, campaignid ORDER BY _sdc_report_datetime DESC)"
filter r == 1
```
Generated SQL:
```sql
WITH table_1 AS (
  SELECT
    *,
    RANK() OVER (
      PARTITION BY timeperiod,
      campaignid
      ORDER BY
        _sdc_report_datetime DESC
    ) AS r
  FROM
    report
)
SELECT
  *
FROM
  table_1
WHERE
  r = 1
```

I tried to turn this into pure PRQL:
```
from report = `stitch_bing_ads_2.campaign_performance_report`
group [timeperiod, campaignid] (
  sort [-_sdc_report_datetime]
  derive [r = rank]
)
filter r == 1
```
Generated SQL:
```sql
WITH table_1 AS (
  SELECT
    *,
    RANK() OVER (
      PARTITION BY timeperiod,
      campaignid
      ORDER BY
        _sdc_report_datetime DESC ROWS BETWEEN UNBOUNDED PRECEDING
        AND UNBOUNDED FOLLOWING
    ) AS r
  FROM
    stitch_bing_ads_2.campaign_performance_report AS report
)
SELECT
  *
FROM
  table_1
WHERE
  r = 1
```

BigQuery is not happy about the additional `ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING`:
```        
Window framing clause is not allowed for analytic function rank at [8:35]
```

**Comment by max-sixty** [comment]
Yes, thanks for adding the issue @neelance .

The broader issue is tracked by https://github.com/PRQL/prql/issues/1069. The different dialects behave differently and originally somewhat confusingly, but I think we now have a good mental model of how they work.

I think for the moment we could:
- Add a method here for `is_window_clause_allowed(&self, function_name) -> bool`: https://github.com/PRQL/prql/blob/a9d098284c1bf6549eaaceee645448c8f90fe4eb/prql-compiler/src/sql/target.rs#L103, and hardcode the functions that accept window clauses in BigQuery
- Call that method from https://github.com/PRQL/prql/blob/main/prql-compiler/src/sql/translator.rs when creating the window clause [^1], and then either return the window clause or nothing

@aljazerzen do you agree? Would this make a Good First Issue?

[^1]: @aljazerzen do you know where in the file this is? I couldn't see it at first and wanted to respond quickly. I can look more later if you don't know off-hand.

**Comment by aljazerzen** [comment]
We have a more specific issue about this open: #1247

Yes, I agree it should be done like this, I'll write more about in the issue.

**Comment by max-sixty** [comment]
Great description in #1247! I'll add one note there and close this so we can consolidate there.
