### ISSUE TITLE
Improve developer onboarding docs

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1438]
I've tried to make it easy to get started with PRQL development, but I'm not sure whether that's been successful, so I'd really like feedback on what's currently missing.

- Is [`DEVELOPMENT.md`](https://github.com/PRQL/prql/blob/main/DEVELOPMENT.md) clear?
  - Other contiguous files are [`CONTRIBUTING.md`](https://github.com/PRQL/prql/blob/main/CONTRIBUTING.md) & [`USING_DOCKER.md`](https://github.com/PRQL/prql/blob/main/USING_DOCKER.md), which we could combine / split up more.
- Do people use the `task setup-dev`? Would folks prefer a copy-pasta? 
  - At least a copy-paste to get to being able to run `cargo insta test`? (as discussed with @aljazerzen on Discord)
  - FWIW I use `task setup-dev` a lot to update my dependencies, I do think there are some great advantages to having something encapsulated & tested. But probably it's not for everyone. (@aljazerzen doesn't use it)
- Should we more clearly indicate what is required to get set up in that doc vs. general commentary? We want to have something that someone looks at and thinks "OK that will take 2 min, let's do it"
- Would folks use a [Codespaces](https://docs.github.com/en/codespaces)? We could provide a template.

What are good projects which have done this well? I've been chatting with @charliermarsh — ruff has had huge success at getting new contributors. Their equivalent doc is https://github.com/charliermarsh/ruff/blob/main/CONTRIBUTING.md. Their environment is simpler — just `cargo install cargo-insta`, no other targets / language bindings / website tools. So my guess is that the distinction between the projects is more in how easy it is to do a PR, rather than getting set up, but very open to thoughts / feedback.

Thanks in advance, all comments welcome

**Comment by aljazerzen** [comment]
I prefer:
- my editor of choice over Codespaces,
- basic rust toolchain over helpers that I don't understand fully.

I don't know what other people use, so any feedback from @MarinPostma, @BlurrechDev, @boramalper or @JettChenT would be appreciated.

**Comment by JettChenT** [comment]
Hi! To provide some feedback on my onboarding process for developing:
- I did use `task setup-dev`. The DEVELOPMENT.md is pretty clear on how to set up the development environment.
- Codespaces would be useful, as the target folder for building this project takes up several gigabytes of storage, which could become a burden for developers who have limited storage space available.

**Comment by max-sixty** [comment]
This got lots of changes, so closing
