### ISSUE TITLE
S-string table creation case sensitivity

### ISSUE THREAD

**Issue by mklopets** [PRQL/prql#1439]
This should work, but doesn't:
```elm
from s"select first_name, id, age from employees order by age asc"
```

...while this does:
```elm
from s"SELECT first_name, id, age from employees order by age asc"
```

```
s-strings representing a table must start with `SELECT `
```

SQL keywords are case-insensitive, so to avoid confusing people, it'd make sense for PRQL to match this behaviour.

Related to me finding this but unrelated to the point of this issue: I was today years old when I realised that the web playground shows certain errors only on hover (and not in the red box at the bottom of the editor)

**Comment by max-sixty** [comment]
Yes, agree. 

This should be a fairly easy fix I think — find where the error is raised, and make the comparison case insensitive.
