### ISSUE TITLE
PL an RQ output in the PRQL Playground

### ISSUE THREAD

**Issue by snth** [PRQL/prql#1490]
Since we now have **output.sql** and **output.arrow** tabs in the playground, would it be possible to also produce **output.pl** and **output.rq** tabs?

That might be a really nice way to get to know the structure of the PL and RQ representations.

I wouldn't want to degrade the user experience of people using the playground though so this shouldn't impact things like response times in generating the SQL output since I'm sure that will still be the primary thing people want to see. Therefore ideally the PL and RQ tabs would only be populated when someone actually clicks on that tab to view it.

**Comment by max-sixty** [comment]
Yes this would be useful — basically all the outputs of the CLI in the playground (but someone would have to do the JS...)

**Comment by aljazerzen** [comment]
Good idea and easy to do. On it.

**Comment by snth** [comment]
I wish I had only posted it this morning instead of last night because then @aljazerzen would have closed the issue in under an hour! 😜

As always, incredible speed @aljazerzen ! 🙌🙌🙌

Thank you! 🙏
