### ISSUE TITLE
Resolving ambiguities between table & column name

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1502]
Currently this raises an error:

```elm
from problem
select solution
join solution [solution==solution.id]
```

```
Error: 
   ╭─[:3:16]
   │
 3 │ join solution [solution==solution.id]
   ·                ────┬───  
   ·                    ╰───── Ambiguous name. Could be from any of _frame.solution, _right.solution._self
───╯
```

...but actually we can know that `solution` has to be the column, because the `==` condition can't take tables / namespaces.

From Discord discussion at https://discord.com/channels/936728116712316989/1063592724080640101/1063610423284334653 with Hytak

**Comment by aljazerzen** [comment]
The error could be nicer, but this query should not compile: `solution` could either be existing column or an inferred column `solution.solution`.

I really don't feel that we should change name resolution depending on expected type - imagine this in any other language:
```rust
let a = 3;
let a = "str";
assert_eq!(a + 5, 8);
```

**Comment by max-sixty** [comment]
> The error could be nicer, but this query should not compile: `solution` could either be existing column or an inferred column `solution.solution`.

Yes good point. It's expressable as:

```
from problem
select solution
join s=solution [solution==s.id]
```

So closing!
