### ISSUE TITLE
Strictness over supplying namespaces

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1503]
The compiler is very strict about when it needs namespaces and when it doesn't — i.e. it's not that they're always required, it's very context-sensitive.

I'll start by saying I realize that we've had discussions on this in the past, and that @aljazerzen has done basically all the work around these features, so his view should be weighed particularly highly. And a project we decided on "Namespace required" in https://github.com/PRQL/prql/issues/1193 & https://github.com/PRQL/prql/issues/1168, even though I dissented, and I'm not necessarily trying to rehash that.

But if we're doing that, could we then allow namespaces after a `select` or `join`?

Here are the two cases:

#### Namespace required

```sql
from problem
join sol [problem.solution==sol.id]
select foo
```

...though we do get a decent error message:

```
Error: 
   ╭─[:3:8]
   │
 3 │ select foo
   ·        ─┬─  
   ·         ╰─── Ambiguous name. Could be from any of _frame.problem._infer, _frame.sol._infer
───╯
```

In SQL, we can leave it ambiguous

```sql
SELECT
  foo
FROM
  problem
  JOIN sol ON problem.solution = sol.id
```

#### Original namespace not allowed

OTOH, once a column has been resolved, it's no longer part of a namespace, and supplying the original namespace raises an error: https://prql-lang.org/book/transforms/select.html#admonition-note

```elm
from e=employees
select e.first_name
filter e.first_name == "Fred"
```

```
Error: 
   ╭─[:4:8]
   │
 4 │ filter e.first_name == "Fred"
   ·        ──────┬──────  
   ·              ╰──────── Unknown name e.first_name
───╯
```

I totally get why the resolver does this. But it makes moving lines around in a query difficult, which is a central feature of pipelines. There is no semantic ambiguity there.

I would hold a different view if the line were instead `select first_name=e.first_name` — then we have a new item, with a new namespace. 

But if column hasn't been redefined, what do we think about allowing the original namespace to be optionally included?

**Comment by aljazerzen** [comment]
> Original namespace not allowed

This is result of compiler behavior around name inference we never talked about. It can be best demonstrated with this snippet:

```
# no assign names:
select [title, albums.artist_id]
# are inferred as:
select [title = title, artist_id = albums.artist_id]
```

As I cannot think of a reason why it should work this way (it was probably just convenient to implement this way), I'll change it so work as:

```
# no assign names:
select [title, albums.artist_id]
# are inferred as:
select [albums.title = title, albums.artist_id = albums.artist_id]
```

**Comment by max-sixty** [comment]
Awesome, I think that would be ideal!

(BTW I prefer the music DB to the employees DB! +1 on using that for canonical examples!)

**Comment by aljazerzen** [comment]
(Yeah, I dislike typing "employees". I know it contains a double letter, but 50% of the time "emplooyes" is what I write before seeing it's just ridiculous. Also it's nice having an actual database you can refer to instead of making one for the sake of the queries.)

**Comment by max-sixty** [comment]
> (Yeah, I dislike typing "employees". I know it contains a double letter, but 50% of the time "emplooyes" is what I write before seeing it's just ridiculous. Also it's nice having an actual database you can refer to instead of making one for the sake of the queries.)

Yeah, and it feels less fun and more corporate than `albums`...
