### ISSUE TITLE
Playground: Replace output.{pl,rq}.json with output.{pl,rq}.yaml

### ISSUE THREAD

**Issue by snth** [PRQL/prql#1534]
I tried to inspect the output.pl.json and output.rq.json output for some queries to get know the PL and RQ structures and I found the JSON output very difficult to parse (for at least this)/a human. Once I passed it through https://www.json2yaml.com/ it was much more readable.

I think the playground output is probably for human consumption so there YAML would make more sense. 

For the APIs it makes sense to keep it as JSON since those will probably be consumed by machines.

Not a priority.

**Comment by max-sixty** [comment]
Agree with this & #1533. 

Probably the playground could do with an owner — not sure how your interests are shaking up with `prql-query` vs other things — but if you want to take on a set of quick wins, these would be good ones!

**Comment by snth** [comment]
I don't think I can be the playground owner as my JS experience is pretty much non-existent but, to the extent that this can be handled on the rust side I can take a stab at it.

I'll have a look.

**Comment by max-sixty** [comment]
> I don't think I can be the playground owner as my JS experience is pretty much non-existent

Yeah, great minds think alike, unfortunately... Someone with lots of JS experience would be a valuable addition to the project given your & my skills there!
