### ISSUE TITLE
Link bindings pages in book to `Readme`s

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#1583]
It doesn't seem to reflect the API changes in 0.4.

Perhaps it's better to copy the contents of the README like Elixir's page does?

https://github.com/PRQL/prql/blob/8a85eb12b65a8218a732ea2184cda2b4521acde7/book/src/bindings/elixir.md?plain=1#L1

**Comment by aljazerzen** [comment]
Yup, it'd be better if we were including, otherwise there just too much duplicated text that needs to be maintained.

**Comment by max-sixty** [comment]
The js one is at https://github.com/PRQL/prql/pull/1608

**Comment by eitsupi** [comment]
I think we have done.
