### ISSUE TITLE
Escaping curly braces inside S-strings

### ISSUE THREAD

**Issue by mklopets** [PRQL/prql#1588]
```elm
from x
derive y = = s"asd{blah"
```
for reasons(tm), one might need something like this to work, but I wasn't able to figure out how. Instinctively, I tried a backslash, but that didn't work.

This is related to #1225 but different, as that one technically has a known workaround (a very large number of quotes around S-strings 😄)

**Comment by max-sixty** [comment]
Hmmm, I was excited to finally have an immediate answer for you @mklopets , but yet I disappoint myself — this works with matching braces, but weirdly not with unmatched braces: https://prql-lang.org/book/language-features/s-strings.html#braces

Let me know if you were indeed looking for non-matching braces, I can prioritize if so

**Comment by max-sixty** [comment]
To confirm @mklopets — this works:

```elm
from employees
derive [
  has_valid_title = s"regexp_contains(title, '([a-z0-9]*-){{2,}}')"
]
```

...because it uses double braces in `{{2,}}` — does that suffice?

**Comment by mklopets** [comment]
In our uber-specific case, our S-string replaced things inside of a string. X got replaced with `{` and Y got replaced with `}`. It's technically possible I could have added double curly braces and ordered these two replacements accordingly, but that would have made it extremely confusing, and does in fact only work if you need both of these, not one.

FWIW, the super-duper-specific workaround was to use the curly braces' ASCII codes to creates those strings (`chr(123)`)

I'm a huge proponent for us having a generic `\escape` pattern
