### ISSUE TITLE
Dealing with nested derived columns with s-strings

### ISSUE THREAD

**Issue by cottrell** [PRQL/prql#1594]
I think prql wants to denest derived cols but can not do so for s-strings. Consider the following which generate what I think is invalid SQL

```prql
from employees
derive [
   this = cost,
]
derive [
   more = s"log(this)",
]
```
```sql
SELECT
  *,
  cost AS this,
  log(this) AS more
FROM
  employees

-- Generated by PRQL compiler version 0.4.1 (https://prql-lang.org)
```

A possible workaround is this for now

```prql
from employees
derive [
   this = cost,
]
filter true
derive [
   more = s"log(this)",
]
```

```sql
WITH table_1 AS (
  SELECT
    *,
    cost AS this
  FROM
    employees
)
SELECT
  *,
  log(this) AS more
FROM
  table_1
WHERE
  true

-- Generated by PRQL compiler version 0.4.1 (https://prql-lang.org)
```

**Comment by max-sixty** [comment]
At the moment we've decided to force the explicitness, ref https://github.com/PRQL/prql/issues/1503 & https://github.com/PRQL/prql/issues/1193.

Personally I remain a bit unsatisfied by the current ergonomics. But everything is expressible, and I recognize there are benefits to the explicitness. So I would put this in the category of "OK for the moment, let's see, we'll make it better in the future somehow". 

If anyone has ideas or views that aren't expressed in the linked issues, feel free to add them here.

@cottrell I'll close this but please feel completely free to reopen

**Comment by max-sixty** [comment]
The s-string needs braces, or it's just a string! For example:

```elm
from employees
derive [
   this = cost,
]
derive [
   # more = s"log(this)",
   more = s"log({this})",   # braces
]
```

```sql
SELECT
  *,
  cost AS this,
  log(cost) AS more   # references `cost` correctly
FROM
  employees

-- Generated by PRQL compiler version 0.4.1 (https://prql-lang.org)
```

Does that make sense?

**Comment by max-sixty** [comment]
(closing but please reopen @cottrell , thank you for the issue!)
