### ISSUE TITLE
Language server protocol implementation

### ISSUE THREAD

**Issue by bcho** [PRQL/prql#1622]
Hey I am working on a [side project](https://github.com/b4fun/ku) that prototyping with querying logs with PRQL. It's similar to Azure Data Explorer, which provides a Monaco based editor for writing the query, and send queries to the database backend (sqlite currently). I have made some preliminary implementations for intellisense in my side project (completion, folding etc). But for more complex usage, for example, completion based on the function types, table schemas, we need a proper parser to help us analyze the user input. Therefore, I think LSP is a good approach for this work, which can be used in the vscode plugin and other projects.

I am planning to invest a bit on this area - just raising the issue here first to gather some ideas / suggestions :P

**Comment by max-sixty** [comment]
That looks like a really cool project. I'm a big fan of Kusto!

An LSP implementation is something we'd really like to provide. I don't have strong priors on exactly how we should do this — what should the compiler interface look like / can we implement it in rust / do we need it to be incremental?

I think we can probably continue the discussion at https://github.com/PRQL/prql/issues/330 — which is very old now but had some initial discussion.

Do let us know if we can be helpful with `ku` at all!
