### ISSUE TITLE
Should we switch to the integrated view in book & pg?

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1663]
We now have https://prql-lang.org/book_integrated/ & https://prql-lang.org/playground_integrated/

I like the playground one (another TODO is to improve the formatting here)

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/5635139/216518371-6d56abf9-af03-4e90-bb3d-5a098ea701eb.png">

The book one is decent; maybe too many headings with both "PRQL" and "PRQL Language Book" (but we could change that to just "Book"

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/5635139/216518456-f5dce976-20f3-4adb-8198-37dfefd35248.png">

If people agree, I'm happy to merge these `*_integrated` into the main version

**Comment by richb-hanover** [comment]
I think the `*_integrated` is definitely better than the current state. +1.0 for merging.

I don't mind the mildly redundant "Book" in the heading followed by "PRQL Language Book" directly below. "Book" standing alone is a little cryptic, at least until you get into the PRQL ethos. 

That "PRQL Language Book" row also contains other useful stuff: the Search field, print, link to github, themes, etc.

**Comment by aljazerzen** [comment]
> If people agree, I'm happy to merge these `*_integrated` into the main version

What do you mean with this? Aren't link in the website topbar already pointing to `*_integrated`?

I personally dislike the iframe for the book, because I cannot copy or link to subpages, as all pages have url https://prql-lang.org/book_integrated/

I don't mind it for the playground.

**Comment by max-sixty** [comment]
> What do you mean with this? Aren't link in the website topbar already pointing to `*_integrated`?

Yes but not links from elsewhere; lots still have prql-lang.org/book

> I personally dislike the iframe for the book, because I cannot copy or link to subpages, as all pages have url https://prql-lang.org/book_integrated/

Ah, I hadn't realized this; that is indeed much worse. Maybe we should revert that unless there's a way of getting that to work....

**Comment by richb-hanover** [comment]
> Ah, I hadn't realized this; that is indeed much worse. Maybe we should revert that unless there's a way of getting that to work....

I hadn't realized that either. In my mind, the lack of links into separate pages of the Book outweighs the benefits of having the unified site.
