### ISSUE TITLE
String escaping / a niche case that's unrepresentable

### ISSUE THREAD

**Issue by maarekj** [PRQL/prql#1682]
Hi,

How to represent the following string: `"starts with double quote and closes with simple quote'`

Even using multiquotes it is impossible.

If I do `""""starts with double quote and closes with simple quote'"""` this is a syntax error.
If I do `'''"starts with double quote and closes with simple quote''''`, this is a syntax error.

**Comment by max-sixty** [comment]
This is a good case! Nice job for finding this.

Let me think. Maybe this will be the trigger for string escapes...

**Comment by max-sixty** [comment]
I'm not sure this is possible in the current construction. It likely would be by concat-ing two strings in the generated SQL, but that's not ideal. 

@mklopets your dream of string escapes may be coming true.

That said, it's a very niche case! So I'm not sure it's a high priority.

If someone wants to take a swing at designing how escaping would work, ideally referencing other languages' implementations, that would be welcome. For example:
- what escapes are valid? `\"` & `\n` & `\\` are easy candidates but are there ambiguities?
- should we have a raw string with `r""`? Is that just a literal string or are some escapes valid?

(fyi I changed the title for clarity, hope that's OK)

**Comment by max-sixty** [comment]
Strings now support escaping. `r"foo"` is a raw string that doesn't use escape characters (which needs better docs, #2989)
