### ISSUE TITLE
Argument substitution

### ISSUE THREAD

**Issue by pbsds** [PRQL/prql#17]
Many SQL engines allow you to substitute in variables in a safe and escaped way.

Example taken from [here](https://magicstack.github.io/asyncpg/current/usage.html):
```python
values = await conn.fetch(
    'SELECT * FROM mytable WHERE id = $1',
    10,
)
```
If the end goal is to generate SQL, then these substitution markers should also be supported by PRQL.

- Should these be positional only?
- Should PRQL support `key=value` substitution?

**Comment by max-sixty** [comment]
Given that we're transpiling to SQL, I think PRQL could be:

```sql
SELECT * FROM mytable WHERE id = $1
```

```elm
from mytable
filter id = $1
```

...and the DB will fill in the rest. We'll have to ensure that `$1` is a valid token there, which I don't think will conflict with anything.

Does that make sense?

**Comment by max-sixty** [comment]
I added this to the new examples path here: https://github.com/max-sixty/prql/blob/main/examples/sql-parameters.md
