### ISSUE TITLE
Add target into output comment

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1711]
An idea from @eitsupi in https://github.com/PRQL/prql/issues/1686:

> Perhaps compiler could mention the target in the comments of the output SQL?

...so we could change

```diff
- -- Generated by PRQL compiler version 0.4.2 (https://prql-lang.org)
+ -- Generated by PRQL compiler version 0.4.2 with a Snowflake target (https://prql-lang.org)
```

(or feel free to adjust the wording)

I think this would be good! It'd be a nice first issue; easy to test.

**Comment by aljazerzen** [comment]
+1 from me

To be future-proof for new compile options, I'd suggest this format:

```diff
- -- Generated by PRQL compiler version 0.4.2 (https://prql-lang.org)
+ -- Generated by PRQL compiler version 0.4.2 with target:sql.snowflake (https://prql-lang.org)
```

Edit: chaneg `=` to `:`

**Comment by eitsupi** [comment]
> ```diff
> + -- Generated by PRQL compiler version 0.4.2 with target=sql.snowflake (https://prql-lang.org)
> ```

I too think this is nice, but I am wondering if the slight difference from the header notation (`target:sql.snowflake`) might cause confusion.

Would it be difficult to use `=` instead of `:` in the header?

**Comment by snth** [comment]
Isn't this like an argument passed to the compile function and we generally use `:` for function arguments so wouldn't `:` make more sense?

I agree that whatever we go with should be consistent between the header and footer.

**Comment by aljazerzen** [comment]
Oh, I misread, @eitsupi you wanted to change header, not signature.

In anycase, I do agree with @snth: header syntax mimics function call.
