### ISSUE TITLE
Don't execute division in PRQL (yet)

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1733]
From https://github.com/PRQL/prql/issues/1712

We shouldn't run division yet, since DBs can have different results. We can find more sophisticated approaches in the future, but for the moment, we can disable it.

If possible, we can keep other operations — e.g. `9/5 * 2` can become `18/5`. But if that's not easy, we can go without that.

This could be a good first issue?

**Comment by richb-hanover** [comment]
NB: Perhaps the subject line should be "Don't execute INTEGER division in PRQL" &mdash; `9/5.0` is likely to work everywhere as expected (although I haven't tested)

I had to finesse this in the `percent_diff` function by multiplying by "100.0" in  the [Pretty SQL Reports](https://prql-lang.org/posts/2023-01-28-format-pretty-reports/) blog posting

**Comment by max-sixty** [comment]
If we can only exclude int division, that's marginally better. But a) it might introduce float errors between rust / the DB, and b) if it's at all difficult, we can exclude all division...

**Comment by richb-hanover** [comment]
I get it now - the commit message "Delegate int division..." makes it clear. Thanks.
