### ISSUE TITLE
A bug in the 'group' transform

### ISSUE THREAD

**Issue by YuxiLing** [PRQL/prql#1748]
In the documentation, the syntax of `group` is `group [{key_columns}] {pipeline}`. 

However, I found it only supports the inner pipeline in `aggregate` type. I tried `derive`, `select`, `sort` and `filter`, I found `group` doesn't work. Here is an example:

Given prql query like this:
```
from tb1
group [c2] (derive a1 = c0 + c1)
```
The SQL query I get from both online prql playground and prql-python is shown below:
```
SELECT
  *,
  c0 + c1 AS a1
FROM
  tb1

-- Generated by PRQL compiler version 0.4.2 (https://prql-lang.org)
```

I think the right answer should be like this:
```
SELECT
  *,
  c0 + c1 AS a1
FROM
  tb1
GROUP BY
  c2
```
The same bug exists when I replace `derive` with `select`, `sort`, `filter`, and `take`. 

Given another example:
```
from tb1
group [c2] (select t1 = 3 + c0)
```
The SQL generated is like this:
```
SELECT
  3 + c0 AS t1
FROM
  tb1

-- Generated by PRQL compiler version 0.4.2 (https://prql-lang.org)
```
The right answer should be:
```
SELECT
  c2
  3 + c0 AS t1
FROM
  tb1
GROUP BY
  c2
```
I think it only supports the inner pipeline in the type of `aggregate` currently.

**Comment by YuxiLing** [comment]
The version I tested is 'PRQL compiler version 0.4.2'

**Comment by aljazerzen** [comment]
This is intended behavior.

In SQL, adding a GROUP clause signals **aggregation** for each of the groups.
In PRQL, group does not do aggregation by default.

Your example:
```
group [c2] (derive a1 = c0 + c1)
```
... would mean:
- for each group,
- compute a new column a1 by adding c0 and c1,
- result for each group would be the initial group, but with an extra column,
- in the end, combine all groups back into a single relation.

Now, computing a new column is not affected by group at all, since it operates on each row separately.

Does that make sense?

**Comment by max-sixty** [comment]
Thanks for the issue @YuxiLing 

> SELECT
>   *,
>   c0 + c1 AS a1
> FROM
>   tb1
> GROUP BY
>   c2

What would this SQL be doing? Generally `GROUP BY` would be using some aggregation like `SUM`.

As @aljazerzen 's points out, this is an area where PRQL makes a deliberate change from SQL, in that aggregations are explicit. But possibly we should be raising errors rather than producing SQL that is unlikely to work. I can see why the current behavior is confusing.

**Comment by YuxiLing** [comment]
Thanks for your clarification.

Just one final tip from my side: maybe you could mention this difference between SQL `group by` and PRQL `group` in your PRQL Language Book.

Nevermind. Thank you so much.

**Comment by max-sixty** [comment]
> Just one final tip from my side: maybe you could mention this difference between SQL `group by` and PRQL `group` in your PRQL Language Book.

Yes, strongly agree, we put something in `aggregate` here: https://prql-lang.org/book/transforms/aggregate.html#aggregate-is-required, and have a long section in our [FAQ](https://prql-lang.org/faq/) under "What’s going on with this aggregate function?"

If we had something similar in our `group` docs, would that help @YuxiLing ? Or is it still confusing?

---

Is there ever a case for `GROUP BY` without a function in the `SELECT` statement? If not, possibly we should error? Particularly in these areas where we're a bit different to SQL, raising an error gives us a chance to explain what's going on in an error message.

**Comment by YuxiLing** [comment]
Thanks. FAQ clarifies this problem clearly.

**Comment by max-sixty** [comment]
@YuxiLing if it's OK, I'll reopen this for this question. I still think PRQL could do a better job here.

> Is there ever a case for `GROUP BY` without a function in the `SELECT` statement? If not, possibly we should error? Particularly in these areas where we're a bit different to SQL, raising an error gives us a chance to explain what's going on in an error message.

**Comment by aljazerzen** [comment]
Yes, there is a case:

```
from tracks
group album_id (take 1)
```

There was even discussion in #1457 about how this:
```
func no_op rel -> rel

from tracks
group album_id no_op
```
... should just sort the rows so that all `album_id`s are next to each other. This could be accomplished with sorting by `album_id`.

Also, if you'd have:
```
from tracks
group album_id (sort title)
```
... I believe this should produce `ORDER BY album_id, title`.

**Comment by max-sixty** [comment]
Yes interesting. Arguably `(take 1)` is an aggregation function. But the other cases are at least ambiguous enough that this isn't an easy situation where we can just raise.

So I'll close...
