### ISSUE TITLE
Can't build Dockerfile with `cargo install --locked...`

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1757]
I attempted to recreate the Dockerfile and the build failed. Several cargo packages had been yanked and there were other errors that I don't understand. This happened on both a M2 and Intel Mac. See the full output at:

https://pastebin.com/kgSCetgq

I imagine this is caused by version updates to underlying packages. I changed the `Taskfile.yml` not to use `--locked` and the Dockerfile built fine on both machines.

What advice can you offer about next steps? How can we keep the versions aligned? Thanks.

**Comment by max-sixty** [comment]
Can you confirm on the latest `main`? I broke this for a few hours accidentally yesterday, but then fixed it, and tests passed: https://github.com/PRQL/prql/actions/runs/4141714558/jobs/7161585167

**Comment by richb-hanover** [comment]
Yup - latest `main` works fine. I merged `main` into my branch about four hours before you fixed the _mdbook-footnote_ problem. Thanks.
