### ISSUE TITLE
Test the documented examples

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#176]
We have some [documented examples](https://github.com/max-sixty/prql/tree/main/examples) — some of which currently work and some of which don't.

It would be great to test our documented examples. The current format for docs seems good; I'd also be open to a different format, but there should be no rust in these examples — they're for users rather than developers of prql.

(TBC, we already have an order of magnitude more tests, mostly using `insta` — not tests need to be docs, but all docs should be tested)

Assuming we're happy with the format, a really useful tool would:
- Parse the `.md` files
- Extract the PRQL
- Run the PRQL
- Compare to SQL
- Add something like a `# Not yet implemented` comment if it raises an error
- Allows for copying & pasting the result if it works but the output isn't exactly the same

**Comment by max-sixty** [comment]
https://github.com/max-sixty/prql/pull/249 does much of this! If we could run that script from `test_compile.rs` that would close the whole loop!

**Comment by aljazerzen** [comment]
Currently, there is:

- a `examples/prql/` directory with `.prql` files,
- a script that can compile each of the files,
- original PRQL and results are written into `examples/`,
- if compilation fails, the results are not written, so we can have non-working examples the way we want,
- there can be other files in `examples/`, they don't have to have a `.prql` file in `examples/prql/`

TODO:
- integration tests: run compiled SQL against Postgres

**Comment by max-sixty** [comment]
One other TODO (not urgent but would be nice) is to make the script run from `cargo test`, so we can run them as part of our usual tests workflow. I'm not sure how easy that would be: presumably we'd either have to shell out (and not on Windows?), or have the script in rust.

Another approach is to run them regularly with another approach; e.g. a GitHub Action.

**Comment by max-sixty** [comment]
Much of this is done by https://github.com/max-sixty/prql/pull/259. The remaining TODO is:

> This doesn't actually test that they don't change; it only writes the
output. People running locally will see that. It would be great to
have this as an actual output.
>
> It would be even better to have the script in rust.
>
> The design shares a lot with insta, which we use extensively
already, including wanting to check the output matches, but I'm not
sure we can make it work easily, given we want the output to be
readable. An alternative would be to pull out the output from
generated insta files into a readable format.

**Comment by max-sixty** [comment]
I _think_ the easiest approach to this — as hopefully helpful advice rather than an edict, if someone takes this — is:
- Use insta's `glob`, ref "Globbing" here: https://insta.rs/docs/advanced/
- In the glob function do three things:
  - Check whether it's intended to work (could search for a string like "Doesn't yet work", or rely on a file suffix).
  - `assert_snapshot!`, which will write an insta snapshot
  - Run a rust version of the [`generate-md.sh`](https://github.com/max-sixty/prql/pull/249/files#diff-cbbeff84683785543e6453486e8c43431dc6d8ea3c4df3a877811788d118ee4cR1), which writes the `.md` file

This means that they're tested without us having to write our own snapshot test. The test outputs (i.e. the insta snapshots) aren't the same object as the documented outputs (i.e. the .md files), but they're created by the same process and so functionally equivalent.
