### ISSUE TITLE
[book] `let` is not mentioned

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#1765]
The documentation doesn't mention the `let` statement.

It should, it is a really nice feature of PRQL!

I just found out about it in #1762.

**Comment by max-sixty** [comment]
It's currently at https://prql-lang.org/book/queries/tables.html. 

Possibly we should rename that to "Let"?

**Comment by vanillajonathan** [comment]
I don't know.

But maybe it should also have a simper example, like just assigning a string to a variable. Maybe this should even be featured on the front page?

**Comment by max-sixty** [comment]
> like just assigning a string to a variable

At the moment it only supports "relations" (i.e. tables). But we'd like to generalize it to also allow scalars like numbers or strings.

---

Yes, let me see if I can adjust the docs a bit. They won't be perfect but I'll try and make it clearer. It's good feedback

**Comment by vanillajonathan** [comment]
> At the moment it only supports "relations" (i.e. tables). But we'd like to generalize it to also allow scalars like numbers or strings.

It seems to work with  a single number. This works:
```elm
let num = 5
from employees
take num
```

**Comment by max-sixty** [comment]
> It seems to work with a single number. This works:

OK, you're absolutely right!

**Comment by max-sixty** [comment]
Ah, I remember now; the thing we can't do is an expression:

```elm
let x = 5 + 5
from y
```

```
Error: 
   ╭─[:1:9]
   │
 1 │ let x = 5 + 5
   ·         ──┬──  
   ·           ╰──── expected pipeline that resolves to a table, but found `10`
   · 
   · Help: are you missing `from` statement?
───╯
```

**Comment by max-sixty** [comment]
Discussed in https://github.com/PRQL/prql/issues/1772

**Comment by vanillajonathan** [comment]
I would like to see simpler examples of just just basic variable assignment, such as:
```elm
let name = "Alice"
```
```elm
let includeDrafts = true
```
```elm
let age = 20
```

**Comment by max-sixty** [comment]
At the moment we don't support expressions — e.g. `let x = 5 + 5`, and so advertising the case where scalars happen to work sets an ambitious expectation. Let's wait until that is implemented and then document those.
