### ISSUE TITLE
Error messages around missing parentheses could be much better

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#1771]
Alice have this large and complex filter so instead of writing it in the filter clause she would like to pass in a function to make her query more readable.

Bob have this filter that he uses a lot so instead of repeating it everywhere he would like to refactor it out to a filter function that he can reuse.

```elm
func my_filter_function country -> country == "Canada"

from employees
filter my_filter_function country
```

Error:
```
rror: 
   ╭─[:4:27]
   │
 4 │ filter my_filter_function country
   ·                           ───┬───  
   ·                              ╰───── Unknown name country
───╯
Error: Binder Error: Referenced column "my_filter_functioncountry" not found in FROM clause!
```

**Comment by max-sixty** [comment]
This is actually a parentheses issue: 

```elm
func my_filter_function country -> country == "Canada"

from employees
filter (my_filter_function x)
```

```sql
SELECT
  *
FROM
  employees
WHERE
  x = 'Canada'

-- Generated by PRQL compiler version:0.5.0 (https://prql-lang.org)

```

Here are the docs on this: https://prql-lang.org/book/syntax.html?highlight=paren#precedence-and-parentheses

---

I'm not sure what's going on in that error message @vanillajonathan — maybe that was from a slightly different query? Or does it reproduce?

---

I definitely think the error message is quite bad here without the parentheses:

```
Error: 
   ╭─[:4:27]
   │
 4 │ filter my_filter_function x
   ·                           ┬  
   ·                           ╰── Unknown name x
───╯
```

Would be great to change that to instead suggest parentheses. Not sure how hard that would be; even marginal improvements would be very welcome.

Maybe I'll change this issue over to that.

**Comment by vanillajonathan** [comment]
I use the Integrated Playground on the website, and I think it gets confused sometimes and shows me some error from the last query I tried before?

Today I get:
```
Error: 
   ╭─[:4:27]
   │
 4 │ filter my_filter_function country
   ·                           ───┬───  
   ·                              ╰───── Unknown name country
───╯
```
Without the "binder error" i got yesterday.

I tried to use your query snippet but it gives me an error:
```
Error: Binder Error: Referenced column "x" not found in FROM clause!
Candidate bindings: "employees.fax", "employees.city", "employees.email", "employees.phone", "employees.title"
LINE 6:   x = 'Canada'
          ^
```

Some of this syntax is probably a bit confusing to someone who comes from a background of one of the more mainstream languages.

**Comment by eitsupi** [comment]
> I use the Integrated Playground on the website, and I think it gets confused sometimes and shows me some error from the last query I tried before?

It may be related to #1785.
In other words, compiler is panicking and the error message is not displayed.

**Comment by max-sixty** [comment]
I think the panic is solved now, and I just added the error message to our list of bad error messages.

So I'll close this; please reopen if that's not accurate. Thanks for the issue!
