### ISSUE TITLE
Playground default SQL vs Arrow

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1779]
We discussed whether the default output should be SQL or Arrow, and making the RQ / PL views nicer.

One thing we should change now (happy to work it out how unless anyone knows and is up for making the change) is that currently if you go to the playground on a new browser and enter `from x`, you get an error, and it's quite unclear what's going on.

Clicking `output.sql` makes it work again, but that's over on the right.

I guess none of us realized because the playground retains state, and we had a different default page.

<img width="287" alt="image" src="https://user-images.githubusercontent.com/5635139/218231948-d221d846-9fd9-4bc4-8512-1ffd474cb46e.png">

**Comment by vanillajonathan** [comment]
I think the Arrow view is nice, but I don't know what Arrow, RQ and PL means.
