### ISSUE TITLE
[python] CompileOptions?

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#1792]
There does not seem to be a way to specify options currently?
`CompileOptions` do not seem to be exposed on the Python side?

https://github.com/PRQL/prql/blob/741c2b30c32d77206b2a167f1bcedd23398da365/prql-python/src/lib.rs#L5-L13

It would be useful to be able to set options here so that the target can be fixed on the pyprql side.

**Comment by max-sixty** [comment]
Definitely; this would be v welcome
