### ISSUE TITLE
Implement uppercase and lowercase string transform

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#1793]
Implement a way to transform a string to lowercase and a string to uppercase.

This can be done by calling the `upper()` and `lower()` functions in SQL.

**Comment by max-sixty** [comment]
This would be a welcome addition to the stdlib if anyone would like a short PR. We'd just need to add them to https://github.com/PRQL/prql/blob/741c2b30c32d77206b2a167f1bcedd23398da365/prql-compiler/src/sql/std_impl.prql and https://github.com/PRQL/prql/blob/741c2b30c32d77206b2a167f1bcedd23398da365/prql-compiler/src/semantic/std.prql and add a test.
