### ISSUE TITLE
Don't hang on no CLI input

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#180]
One nit I have with tools which take some stdin input is to wait indefinitely on no input. It's unclear whether something is happening or not.

Unfortunately we do that currently — run `./target/debug/prql`. Ideally we should just return the `--help`.

**Comment by aljazerzen** [comment]
Fixed with #206 (mosty). We still hang if you type `prql compile`...

**Comment by max-sixty** [comment]
Ah yes I was hoping to eliminate that hanging too...

**Comment by max-sixty** [comment]
I had a look into this — it's not trivial. I think we want to check whether stdin is a tty — e.g. `if atty::is(atty::Stream::Stdin)` — and if it is, print the help.

But in the newer `clap` Derive impl, it doesn't look easy to get access to a command to run `command.print_help()`

This is more of a personal nit + best practice than a real blocker. So I'll remove the `0.1` milestone. 
If anyone knows clap better than me / wants to take a look, it would contribute to PRQL friendliness.

**Comment by max-sixty** [comment]
Fixed with a slightly different approach by #215
