### ISSUE TITLE
Allow no main pipeline?

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1803]
Opening the `std.prql` file in VSCode returns an error `missing main pipeline`. It's possible to replicate with:

```elm
func add -> a + b
```

Should we allow files with no queries? This will become more important when we want to allow importing items from other files.

**Comment by vanillajonathan** [comment]
This would be useful for:
- #643
-  #1773

and if the language were to be extended to also be a Data Manipulation Language (DML), Data Definition Language (DDL), and/or Data Control Language (DCL).

**Comment by richb-hanover** [comment]
> Should we allow files with no queries? This will become more important when we want to allow importing items from other files.

I think it's desirable to permit this. Another manifestation is with the first bullet in #1728. It's thinkable that a "no-query" input should generate an empty output from the PRQL compiler  that indicates "no pipeline"

**Comment by max-sixty** [comment]
As discussed in https://github.com/PRQL/prql/issues/1825 — I think we should be able to _parse_ these queries, but not compile them.

`parse` allows this:

```
$ echo "let x = 2" | prqlc parse
- VarDef:
    name: x
    value:
      Literal: !Integer 2
```

...but somewhere the VSCode extension is raising an error. So possibly this is an issue with that? It shouldn't be trying to compile every PRQL file... I'll open an issue there

**Comment by RandomFractals** [comment]
PRQL vscode extension only uses compile and shows any errors that produces. Nothing has changed there since v0.4.2 when I took over.

Also, should not compile parse PRQL first and generate errors for invalid PRQL before even trying to compile it, and not create error messages when PRQ is valid, or prqlCode is an empty string?

More at: https://github.com/PRQL/prql-vscode/issues/128#issuecomment-1446246847

**Comment by RandomFractals** [comment]
> 

This looks like AST now. Do you think PRQL extension should display that separately?

**Comment by RandomFractals** [comment]
> As discussed in #1825 — I think we should be able to _parse_ these queries, but not compile them.
> 
> `parse` allows this:
> 
> ```
> $ echo "let x = 2" | prqlc parse
> - VarDef:
>     name: x
>     value:
>       Literal: !Integer 2
> ```
> 
> ...but somewhere the VSCode extension is raising an error. So possibly this is an issue with that? It shouldn't be trying to compile every PRQL file... I'll open an issue there

That looks like some kind of AST of PRQL code. 

Do you think PRQL extension should display it in Outline instead as other code editors do?

PRQL document outline is empty in vscode ext. v0.6.0. That is where PRQL parse/statements tree display should be added, which would be a new feature request, in addition to prql compiler not produce errors when there are not any.

![image](https://user-images.githubusercontent.com/656833/221612215-8ae91b81-74dd-402b-aa54-6682f48b71ac.png)

**Comment by max-sixty** [comment]
Lots of stuff here & the related issues which I'll aim to go through later. Just to confirm one thing:

> Nothing has changed there since v0.4.2 when I took over.

Totally, this is definitely something that's been there for ages, not on you at all! (and even if it were, these issues are to be expected)

**Comment by RandomFractals** [comment]
yeah, it is an issue we need to resolve, even for empty prql documents. I noticed that error too when I was prepping ext. v0.6 release.

I propose we consider adding info and warning messages to the compiler, not just errors. Then display them in the Problems panel in vscode, and we can display them in Preview if there is no other output generated.

That would make it consistent for all the compiler api clients too, and use the standard nomenclature of error, warn, info messages display most compilers and linters use.

We should consider showing parsed PRQL AST in vscode Outline, but that's a much larger effort we can discuss separately.

**Comment by vanillajonathan** [comment]
> I propose we consider adding info and warning messages to the compiler, not just errors.

I very much like this idea!

**Comment by max-sixty** [comment]
The immediate question is subsumed by https://github.com/PRQL/prql/pull/2129, and I think we have a very viable path forward.

https://github.com/PRQL/prql-vscode/issues/128 remains, but we can continue on that issue
