### ISSUE TITLE
Mention 1_000_000 in the docs and website

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#1812]
Mention using underscores to separate digits in long numbers such as `1_000_000` to make it easier to read in the docs and/or the website.

This is a pretty cool feature that people should know about, don't be shy!

**Comment by max-sixty** [comment]
Yes we could add this to the syntax page?

**Comment by vanillajonathan** [comment]
Oh it seems it is already mentioned in the syntax page.
> Numbers can contain underscores between numbers; which can make reading large numbers easier...

https://prql-lang.org/book/syntax.html

It is quite hidden though. Maybe there should be a page that lists all the cool features so someone can really grasp how cool and amazing PRQL really is.

**Comment by max-sixty** [comment]
We do have it on the Readme, but implicitly:

<img width="430" alt="image" src="https://user-images.githubusercontent.com/5635139/218341341-997283be-3a15-454a-a466-3124438a58d0.png">

Maybe we sync that example with the example on the homepage and add an example there?

<img width="459" alt="image" src="https://user-images.githubusercontent.com/5635139/218341365-2c142196-f3c6-4a05-bb54-dc4102209ada.png">

What about on the "Friendly syntax" showcase:

<img width="684" alt="image" src="https://user-images.githubusercontent.com/5635139/218341391-16e3ecef-4755-4e3d-a49d-9fc12ced5d51.png">

@vanillajonathan if you'd be up for adding it to the "Friendly syntax" showcase, that would be a nice contribution!

**Comment by vanillajonathan** [comment]
Yeah, maybe under "Friendly syntax" would be a good place to showcase it, but I don't have any good example on how to showcase it.

**Comment by max-sixty** [comment]
Closed in https://github.com/PRQL/prql/pull/1819

> This is a pretty cool feature that people should know about, don't be shy!

Thanks for the suggestion. Lmk if there are other things you think we should add to the showcase — it's absent mindedness rather than shyness...
