### ISSUE TITLE
How can `let` be searchable in the Book?

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1813]
Thanks for changing "Tables" to "Variables" [in the Queries summary.](https://prql-lang.org/book/queries/index.html)

How can we ensure the `let` keyword is searchable? (Currently, searching for "let" gives _No search results for 'let'._) Thanks.

~~NB: s/Tables/Variables/ on that page...~~ Fixed it myself

**Comment by max-sixty** [comment]
Ah good point; maybe it's too short for the search?

We could call the page "Variables / let"? Not elegant but informative?

Or very open to other ideas!

**Comment by vanillajonathan** [comment]
It could be titled "[Let expression](https://en.wikipedia.org/wiki/Let_expression)". There is a article on Wikipedia with that name.

**Comment by aljazerzen** [comment]
The title @vanillajonathan proposes is much better.

I looked into this and it seems like the book could be improved by reorganizing and renaming a few articles. For example, syntax could be split into many different files.

(if we do that, let's make sure to add proper [redirects](https://rust-lang.github.io/mdBook/format/configuration/renderers.html#outputhtmlredirect) so old links continue to work)

**Comment by max-sixty** [comment]
Amazingly `let` is specifically not possible to search for! https://github.com/rust-lang/mdBook/issues/1286. Possibly this will be resolved upstream but wouldn't hold our breath.

I'd accept a PR to change the title to "Let expression", I'm probably -0...

> For example, syntax could be split into many different files.

I'm open-minded on this. I tend to prefer fewer longer pages, which I find easier to read and search, but possibly that's just me.

I agree that separate pages are useful when folks know what they're looking for — "I want to know about *Ranges*" — less for subjects that are implicit, such as "Inner Transforms". 

Certainly no strong view, happy if someone wants to take a swing at reorganizing.

---

While I'm here — I notice that https://prql-lang.org/book/language-features/index.html doesn't include the new Standard library page
<img width="623" alt="image" src="https://user-images.githubusercontent.com/5635139/224842234-efc1199a-3476-4645-a52f-ad45da76bd46.png">

**Comment by aljazerzen** [comment]
Stale.

**Comment by richb-hanover** [comment]
@max-sixty @aljazerzen Since `let` is taking on a prominent place in PRQL, I'd like to make this suggestion:

> Amazingly `let` is specifically not possible to search for! https://github.com/rust-lang/mdBook/issues/1286. Possibly this will be resolved upstream but wouldn't hold our breath.

That code has a `make_stop_word_filter` function/array (I don't read Rust...) I wonder whether they would accept a PR for an `anti_stop_word_filter` that _removes_ certain stop words from that library's list. That would allow various projects to allow certain words through and make `let` become searchable in PRQL. Thanks.

**Comment by aljazerzen** [comment]
I feel you, but I don't think it's worth the pain of patching mdBook.

We have a section on keywords that could link to section about variables. That should be discoverable enough.

**Comment by max-sixty** [comment]
I imagine they would take that patch, but it's worth checking with them as it's lightly maintained...
