### ISSUE TITLE
Cannot use parameters after a select

### ISSUE THREAD

**Issue by maarekj** [PRQL/prql#1827]
Cannot use parameters after a select.

**example:**

```prql
from i = invoices
filter $1 <= i.date or i.date <= $2
select [
  i.id,
  i.total,
]
filter i.total > $3
```

**output in playground:**
```
Error: 
   ╭─[:7:18]
   │
 7 │ filter i.total > $3
   ·                  ─┬  
   ·                   ╰── Unknown name $3
───╯
```

**Comment by aljazerzen** [comment]
Uff, yes, we should parse and resolve params separately from normal idents.

**Comment by max-sixty** [comment]
A workaround is to use an s-string:

```
s"$3"
```

**Comment by aljazerzen** [comment]
I was looking who implemented current behavior, so I could ask them what they meant when they wrote a test that included `$2.name`. Is this a relational param?

It turns out it was me. #272 and #229.

**Comment by max-sixty** [comment]
> It turns out it was me.

Brilliant, happens to me all the time!

If you're up for reading philosophy — https://en.wikipedia.org/wiki/Reasons_and_Persons argues this is actually the correct way to think about it. I found it a challenging but enormously rewarding book...
