### ISSUE TITLE
Peculiar characters shown in Playground links

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1829]
In the [Playground](https://prql-lang.org/playground/), the links to the PRQL website and Language Reference both have peculiar characters at the end. Is this intended?

<img width="240" alt="image" src="https://user-images.githubusercontent.com/1094930/218449145-e5633b50-63e6-48cc-9e80-83a5728601ee.png">

**Comment by eitsupi** [comment]
I saw
![image](https://user-images.githubusercontent.com/50911393/218490151-61187f81-7833-4529-be16-4291e27c6764.png)

Looks like a difference in the fonts.
Perhaps the font on your screen does not have this symbol?

**Comment by richb-hanover** [comment]
Ahah! I see the arrow pointing up and to the right in the image above. I would recommend that we use &nearr; (`&nearr;`) as an alternative to that character.

**On my Mac:** Firefox shows that funny symbol above; both Chrome, Edge, and Safari (on a Mac) show a five-line "hamburger", like this: 
<img width="225" alt="image" src="https://user-images.githubusercontent.com/1094930/218553811-81d9ff81-7edc-47b5-95f5-02cfc7621cde.png">

**On Windows:** Chrome, Edge, and Firefox show the arrow

**Comment by max-sixty** [comment]
The playground is now integrated, so we really only need the Book link now. Changes to this are very welcome. 

If anyone out there wants to make a big short-term impact on the project, improving the UI of the playground would fit well — e.g. #1779!

**Comment by vanillajonathan** [comment]
You could use [Bootstrap Icons](https://icons.getbootstrap.com/) so it works regardless of fonts.

Suitable icons:
- https://icons.getbootstrap.com/icons/arrow-up-right/
- https://icons.getbootstrap.com/icons/box-arrow-up-right/

**Comment by richb-hanover** [comment]
I just submitted PR #1843 to substitute `&#8599;` for `&#x1F855;` that seems to work in all browsers
