### ISSUE TITLE
PHP bindings

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#1844]
PRQL should have bindings for [PHP](https://www.php.net/). PHP have a [FFI](https://www.php.net/manual/en/book.ffi.php), which of particular interest is the [`FFI::cdef`](https://www.php.net/manual/en/ffi.cdef.php) function.

**Comment by max-sixty** [comment]
Thanks @vanillajonathan . If you want to take a swing at creating these and adding them to the repo, with tests, that would be very valuable.

The issues are still helpful on the margin though.

**Comment by vanillajonathan** [comment]
I got it to work, it uses the `libprql_lib` library which it loads using the PHP FFI extension. So for this to work the PHP FFI extension needs to be enabled. It searches for a file called `libprql_lib.so` in same directory as the PHP script.

I've seen some bindings offer the `compile` function, but the C library only offers:
```c
int to_sql(char *prql_query, char *sql_query);
int to_json(char *prql_query, char *json_query);
```

By the way, the `prql-lib` contains no C header file.

This PHP script contains a `to_sql` and a `to_json` function which works. It also contains the `compile` function which does not work.

**Comment by max-sixty** [comment]
> I've seen some bindings offer the `compile` function, but the C library only offers:

I think this is because the `prql-lib` was built on an older version of PRQL. It would be quite welcome to update `prql-lib` and add some tests for it, so it stays current. 

It was originally written as a quick piece of code.

**Comment by vanillajonathan** [comment]
I would like to merge this, I created pull request #1860.
