### ISSUE TITLE
[prql-js][prql-python] The default target?

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#1855]
Related to PRQL/prql-vscode#98

Currently the default target is `Generic`, but a default of `None` may be better to make the target in header available.

https://github.com/PRQL/prql/blob/7c42e5c64b92e9e43b0be82000135663552f0972/prql-js/src/lib.rs#L106
https://github.com/PRQL/prql/blob/7c42e5c64b92e9e43b0be82000135663552f0972/prql-python/src/lib.rs#L98

(Only `None` falls back to the header. if there is nothing in the header after falling back from `None` to the header, it falls back to `Gneric`.)

**Comment by max-sixty** [comment]
Good point, sorry I missed this in the previous reviews.

**Comment by max-sixty** [comment]
And ref https://github.com/PRQL/prql/issues/1686

**Comment by eitsupi** [comment]
Closed by #1856 and #1861
