### ISSUE TITLE
Allow `from_text` to produce numbers

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1865]
Currently `from_text` always produces strings:

```elm
from_text """
a,b,c
1,2,3
"""
```

```sql
WITH table_1 AS (
  SELECT
    '1' AS a,
    '2' AS b,
    '3' AS c
)
SELECT
  a,
  b,
  c
FROM
  table_1 AS table_0

-- Generated by PRQL compiler version:0.5.0 (https://prql-lang.org)
```

`'3' AS c` could instead be just `3 AS c`

That's because here, we always cast to a string:

https://github.com/PRQL/prql/blob/3f637524f4658a81c4c6795820f55496fe679515/prql-compiler/src/semantic/transforms.rs#L935

Two options for selecting the correct type:
- Use our existing parser
- Write a couple lines to decide whether it's a number or not

One other consideration — we may also need to demote _all_ values in a column to strings if one value isn't a number. An alternative to this would be forcing the user to use quotes (`'2'`) for numbers in a string column. Assuming the CSV parser handles the latter option correctly, that would be the closest option so we can make progress.

This would make a good early contribution for anyone who is up for a Rust PR.

**Comment by fusillicode** [comment]
Hi 👋😄 

Thanks a lot for all your work 🙇‍♂️ !

I tried to tackle this issue and end up with the following PR: https://github.com/PRQL/prql/pull/1878

I think the code could be improved and refactored but before doing that I would like to get a feedback around the proposed solution based on your 1st suggested option, i.e. "Use our existing parser".

The proposed solution rationale is: try to get the `Literal`s from the parsed statements and fallback to the already in place `Literal::String` in case of any statements not matching a `Literal` value.

JFYI this PR has been worked on in the context of the Milan Open Source Saturday ![https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-open%20source%20saturday-F64060.svg](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-open%20source%20saturday-F64060.svg) 😄

**Comment by aljazerzen** [comment]
I don't like this, because parsing CSV columns as numbers automatically may produce unexpected results:

This is parsed as int column:
```csv
a
"1"
"2"
```

This is parsed as float column:
```csv
a
"1"
"2.2"
```

This is parsed as string column:
```csv
a
"1"
"2,2"
```

It all makes sense, but it stops making sense when you have a bad CSV file with 1000 rows where a single row contains a decimal dot instead of decimal comma.

I think this feature falls into category of "magic things that are great, until they stop working and you have to understand how they work".

Instead, I would propose that we keep parsing CSV fields as strings and start introducing functions for dealing with conversions from strings to numbers. This way the conversion is explicit and any errors can be traced back to the conversion.

(I hope I don't sound too discouraging :D )

**Comment by max-sixty** [comment]
> It all makes sense, but it stops making sense when you have a bad CSV file with 1000 rows where a single row contains a decimal dot instead of decimal comma.

I can empathize but this is somewhere where we want to be easy rather than robust. This isn't going to be used for production; this is going to be used for things like "how does PRQL work when I aggregate a column of numbers?", and being able to execute an encapsulated query on DuckDB without having to prepare input data.

Having to coerce the types gets in the way of that.

An alternative would be to offer a stricter option, like DuckDB does: https://duckdb.org/docs/data/csv.html

WDYT?

**Comment by aljazerzen** [comment]
That's a good point, this function is (currently) for demo queries anyway.

Ok, I'm -0 on implementing this.

**Comment by eitsupi** [comment]
Perhaps it makes sense to adopt the same types as json (string, numeric, boolean)?
I don't think an automatic guess function is needed to distinguish between these in json.
(This will cause the strings to need to be enclosed in quotes...)

**Comment by aljazerzen** [comment]
JSON is different because it does define how to represent numbers, bools and null.

(and CSV already uses quotes for distinguishing between column-separating commas and commas in a field)

**Comment by max-sixty** [comment]
OK, so I'm def +1 on implementing this, so assuming others are OK with it, let's do it. (thanks @aljazerzen for the -0, think these are good ways of aggregating our views, and hopefully also creates the space for others to come and say "I'm -1")

I'll add some salient questions to the PR, appreciate any responses

**Comment by max-sixty** [comment]
Closing because of relation literals
