### ISSUE TITLE
Simple CLI

### ISSUE THREAD

**Issue by matthias-Q** [PRQL/prql#1874]
Hi,
I do not know if it already exists, but is there a simple CLI for prql, where is takes in a prql file and writes a output (sql, etc)?

I could not find hints to that in the Readme.

**Comment by eitsupi** [comment]
Perhaps you are looking for prqlc?
This is a single binary CLI tool, but I think you will have to build it yourself as there is no distribution of pre-built binaries at this time.
https://github.com/PRQL/prql/tree/main/prql-compiler/prqlc

**Comment by matthias-Q** [comment]
Ah, there it is. Maybe it is worthwhile to make is a bit more visible in the readme. I was looking for 'cli' or something like that and was not able to find it.

**Comment by eitsupi** [comment]
Agree. The documentation definitely has a lot of room for improvement....

**Comment by vanillajonathan** [comment]
Maybe a compiled binary for the `prqlc` could be made available on GitHub when a release is tagged?

**Comment by matthias-Q** [comment]
I am fine with that. I just installed it via cargo. It was just hard to find. But having it released as a binary might be beneficial for others.

**Comment by matthias-Q** [comment]
Closing because you want to make it more visible in #1877
