### ISSUE TITLE
Treesitter grammar for PRQL

### ISSUE THREAD

**Issue by matthias-Q** [PRQL/prql#1882]
Hi, 
I have started writing a tree-sitter parser for PRQL.

https://github.com/matthias-Q/tree-sitter-prql

It is in a very early stage. Main reason is, that I want to have syntax highlighting in neovim for prql files. Check it out, contributions are welcome.

**Comment by max-sixty** [comment]
Nice!!

I especially like the [tests](https://github.com/matthias-Q/tree-sitter-prql/blob/main/test/corpus/pipelines.txt). Is that a native to treesitter or did you build them? I'd been thinking of how to test our existing grammars; this is good. It's similar to our compiler snapshots, but more readable by people.

To the extent you'd like to continue the maintenance of this, would you like to add it to our syntax highlighting index? https://prql-lang.org/book/internals/syntax-highlighting.html.

(And if you prefer to put it into the prql repo, that's fine, but we also encourage folks to keep their own repos if they prefer)

**Comment by matthias-Q** [comment]
Thanks. The tests are native to tree-sitter.

For the syntax highlighting to work, I need to write some queries first...and for that, I need to reach a somewhat stable version of the grammar ([see here](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights)). Otherwise I keep rewriting the grammar and the queries. So, we could add it there as planned.

I would like to put it to your repo at one point, but for now I think, that I could develop faster when it stays in my repo. But I am definitely open to that.

**Comment by max-sixty** [comment]
Super! Let us know if there's anything we can help with.

**Comment by RalfNorthman** [comment]
I'm really excited about this!

Since I use the [helix-editor](https://helix-editor.com/) and it also [relies on tree-sitter grammars for its language support](https://docs.helix-editor.com/guides/adding_languages.html) I took the freedom of opening an issue over in the helix repo.

**Comment by matthias-Q** [comment]
In order to get this working I also added filetype support in vim. This is now also already in downstream in neovim.

**Comment by matthias-Q** [comment]
Hey @max-sixty , I am almost finished. Besides some minor things that I would like to refactor, almost everything should be covered.

one thing that is missing are pipes. I don't see a point in them?
If there are two transforms like `take` and `filter` in one line without a line break or a |, does it not compile? The pipe seems redundant.

**Comment by max-sixty** [comment]
Awesome! Is there anything we can do to boost it? How would folks who use Vim install it? We can put something on the website.

Re pipes, WDYM? If we have `from x | select y | take 10`, that's equivalent to:

```
from x
select y
take 10
```

`from x select y take 10` doesn't compile, since we're not sure where to split the transforms. With that example, we could know that `select` starts a new one, but we also allow for custom functions, and the parser would become very context-heavy, and error messages would be quite confusing — `from x sel` would complain about multiple arguments to `from`.

Does that make sense?

Often fundamental language insights which lead to great improvements come from questions like these, so please keep pushing if it doesn't make sense!

**Comment by matthias-Q** [comment]
I will do some more minor changes and then I would hand in over to you in the PRQL github space. I have already added the filetype recognition in vim/neovim. As soon as the repo finds it new home it makes sense to add it to nvim-treesitter (this is the mandatory plugin for neovim that loads the grammars)

For the pipes question:
I was surprised that `from x select y` does not work. I SQL that is perfectly valid. But I guess I understand your point.

In that regard, the treesitter parser would be a bit more permissive, since `select x from y` will not generate a parser error as is does not care about line breaks, spaces or tabs.

Maybe I have to find a way to add this in. Maybe a look in the python grammar might help (because of the indentation logic)

**Comment by max-sixty** [comment]
I think in a way your point is absolutely correct — if we know at parse time what is a function, we can say "every function starts with a pipe". So:

```elm
func add -> a + b

from x
derive y = add a b
# Or with pipe:
derive y = a | add b

# Or, NOT currently valid, but would be in the proposed world
derive y = a add b
```

We know that `derive y = a add b` is `a | add b` and not `a add | b` because we know only `add` is a function.

The challenge here is that the parser needs to know the name of every function, which means the parser needs a lot of context (definitely not a context-free grammar!). 
For example I think it wouldn't be possible to produce a treesitter grammar, because it can't compute that there's a function `add`. Is that correct?

One language which gets close to this is https://github.com/betaveros/noulith

**Comment by matthias-Q** [comment]
Ok, I think I get your point. In the mean time I found a way to include the pipes. Even though it is a bit more permissive. The tree-sitter grammar will not yell if the pipe splits in between any operation. However, since it is only for highlighting, folding and indentation it should be fine.

Maybe I invest some time later to handle this better.


Since I am now more or less happy with the state of the grammar, I would like to transfer the repo into the PRQL organizational space. Would that be fine?

**Comment by max-sixty** [comment]
> Even though it is a bit more permissive. The tree-sitter grammar will not yell if the pipe splits in between any operation. However, since it is only for highlighting, folding and indentation it should be fine.

Yes great, we can definitely be more permissive in these — on looking through your code, it looks already much more complete than our other syntax highlighter grammars, even if not as complete as our actual parser, understandably.

And hopefully folks will report any issues and we can iterate where necessary.

> Since I am now more or less happy with the state of the grammar, I would like to transfer the repo into the PRQL organizational space. Would that be fine?

Absolutely. As the author you can choose — a repo in your org which we link to / a repo in the PRQL org / a library in the `PRQL/prql` repo. Your suggestion of a repo in the PRQL org sounds very reasonable. 

We'd love you to stay involved with the project, and if you'd be happy to be the maintainer in any of those options that would be awesome. If you'd rather not, that's OK ofc, but we should be explicit about the level of maintenance that folks can expect in the README.

Does that sound reasonable?

**Comment by matthias-Q** [comment]
Yes, I would maintain the repo and it would be better to have it under the PRQL org. What do I need to do?

**Comment by max-sixty** [comment]
Great! Transfer it over... https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by matthias-Q** [comment]
> You don’t have the permission to create public repositories on PRQL

**Comment by max-sixty** [comment]
TBC, did you try and transfer it or create a new repo? https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account. IIUC there shouldn't be any permissions to transfer (I need to hit accept when you've done it)

**Comment by matthias-Q** [comment]
I tried to transfer it to PRQL.

**Comment by matthias-Q** [comment]
> To transfer repositories to an organization, you must have repository creation permissions in the receiving organization. If organization owners have disabled repository creation by organization members, only organization owners can transfer repositories out of or into the organization.

**Comment by max-sixty** [comment]
Sorry, you're correct. I'll start a new repo, give you permissions, and we can push your whole git history there...

**Comment by max-sixty** [comment]
Done at https://github.com/PRQL/prql-treesitter. IIUC you just need to accept the invitation @matthias-Q . Ping me back if any issues, thanks for your patience so far.

**Comment by matthias-Q** [comment]
I have pushed it. Can you rename it to `tree-sitter-prql` It seems to be the official naming convention.

**Comment by max-sixty** [comment]
> I have pushed it. Can you rename it to `tree-sitter-prql` It seems to be the official naming convention.

Done! https://github.com/PRQL/tree-sitter-prql

It's looking great (very nice tests!). I'm sure stuff will come up and we can iterate, but looks great so far.

Thanks a lot @matthias-Q !

**Comment by matthias-Q** [comment]
Thanks @max-sixty 

I will close this issue now.
