### ISSUE TITLE
Special string target expression to fall back to the target in query header?

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#1907]
Related to #1855 and PRQL/prql-vscode#98

Wondering if it is worth implementing a special string expression for not specifying a target in the compiler options.
For example, I assume a name like `"sql.none"` or simply `"none"`.

This is converted to `Target::Sql(None)` or `Target::default()` (now `Target::Sql(None)`) at the following location.

https://github.com/PRQL/prql/blob/c6c73ef3631b414730cc14aa1fa4130183f6519f/prql-compiler/src/lib.rs#L153-L172

**Comment by max-sixty** [comment]
What would be the advantage of a string like `"none"` rather than just passing `None`? 

Is it that some languages don't have good support for `None`, and so a string would be better? For example in the issue you reference, maybe in prql-vscode's JSON settings, it's difficult to have an actual value of `None`?

**Comment by eitsupi** [comment]
> Is it that some languages don't have good support for None, and so a string would be better? For example in the issue you reference, maybe in prql-vscode's JSON settings, it's difficult to have an actual value of None?

Yes, I had that use in mind.
Strings are easy to pass outside of Rust, but passing `Sql(None)` is difficult.

**Comment by max-sixty** [comment]
Yes great. Accepting a string of `"none"` seems fine. 

I'm unsure whether we should do it in the bindings or in `prql-compiler`. For example, python has good support for `None`, we should encourage that rather than `"None"`. But no strong views.

**Comment by aljazerzen** [comment]
What about `sql.unknown` or `sql.any`?

We want to signal the fact that it will default to the target in the file header.

**Comment by eitsupi** [comment]
Thanks, I like `sql.any`.

**Comment by eitsupi** [comment]
Given that it looks like non-SQL targets can be specified in the header, would `any` be better than `sql.any`?

**Comment by aljazerzen** [comment]
Let's also add `any` along `sql.any`, if it turns out that is possible to compile to other targets with same API (the `compile` function).
