### ISSUE TITLE
DuckDB extension

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1936]
One potential integration that would be great — a DuckDB extension which can allow DuckDB to accept PRQL as well as SQL.

At initial version could be very thin — accept PRQL, compile to SQL, pass to DuckDB. It would have similar functionality to a simple wrapper.

I haven't yet read up on how to build it. There's a Rust framework: https://github.com/Mause/duckdb-extension-framework, and here's an example for Deltatable: https://github.com/Mause/duckdb-deltatable-extension

**Comment by max-sixty** [comment]
The rust framework is fairly basic at the moment; here's an example of its use: https://github.com/Mause/duckdb-deltatable-extension/blob/main/src/table_function.rs — every function is unsafe...

So this would probably be a fairly technical piece of work for someone who is familiar with C++ andor DuckDB...

**Comment by max-sixty** [comment]
Check out @ywelsch's https://github.com/ywelsch/duckdb-prql!!

**Comment by snth** [comment]
For anyone wanting to use this with Docker, try out `ducker`!

https://github.com/duckerlabs/ducker

**Comment by max-sixty** [comment]
Closing as completed
