### ISSUE TITLE
Use MegaLinter?

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#1944]
Since this repository contains files in quite a few different languages, setting up MegaLinter could provide many suggestions.
https://megalinter.io/latest/

There is some overlap in role with the pre-commit hook, though.

**Comment by max-sixty** [comment]
Would it be better than pre-commit with `rustfmt` + `prettier` (+ `black`)? We do have lots of code from different languages in the repo, so maybe we could also do Java & Elixir etc with one tool?

pre-commit is easy to run locally (doesn't require node...)

(I have some personal loyalty to pre-commit, it has served me well, but very happy to move if this has material advantages)

**Comment by eitsupi** [comment]
> Would it be better than pre-commit with `rustfmt` + `prettier` (+ `black`)?

It would be good to disable these on the MegaLinter side so that the same Linter is not executed many times.
(While it is convenient to be able to run various tools at once, there are many cases where it is more flexible to leave it to specialized Linter workflows, and those types of Linters should be disabled on MegaLinter.)

> We do have lots of code from different languages in the repo, so maybe we could also do Java & Elixir etc with one tool?

Linter for Elixir does not seem to be included, but the following is included.
https://megalinter.io/latest/descriptors/java/
https://megalinter.io/latest/descriptors/c/
https://megalinter.io/latest/descriptors/php/

Also, actionlint (for GitHub Actions) is very useful and inspects GitHub Actions definitions that cannot be executed locally.
https://megalinter.io/latest/supported-linters/#tooling-formats

> pre-commit is easy to run locally

I don't see much value in running these tools locally, as they automatically modify PR when I push to GitHub.
I see the PRs of this repository and probably many people do not use pre-commit locally?

That said, this is entirely a personal preference and I am not looking to replace existing pre-commit settings.

**Comment by max-sixty** [comment]
> I am not looking to replace existing pre-commit settings.

Ah, I see, so we'd only run this for the languages we don't lint in `pre-commit`. That sounds like a good way to start.

> I don't see much value in running these tools locally, as they automatically modify PR when I push to GitHub.

I broadly agree. There are some files which can't run remotely — e.g. GitHub workflow files can't be changed by an action. And I think some folks would like to see the code locally they're going to merge.

But if we're only running this on the non-core languages, then that's completely fine.

---

Shall we see what changes it suggests and then merge if they look reasonable?

**Comment by eitsupi** [comment]
Excessive errors may occur until all unnecessary Linter are disabled, but you can see here that MegaLinter is working anyway.
https://github.com/PRQL/prql/actions/runs/4270484674/jobs/7434309891

**Comment by nvuillam** [comment]
Pre-commit and MegaLinter are not in competition, they can be both used for the greater good :)
Pre-commit for local use, and MegaLinter for CI use, if you have linters present in both, just make sure that they read the same config files :)

**Comment by eitsupi** [comment]
> Pre-commit for local use, and MegaLinter for CI use, if you have linters present in both, just make sure that they read the same config files :)

Thank you for your comment. I apologize for my lack of explanation, but this repository uses pre-commit in CI, so I expect that if I enable MegaLinter auto-fix, the same part will be fixed separately by the two workflows, causing a conflict.
So MegaLinter auto-fix is not available.
