### ISSUE TITLE
Compiler crashes on bad input

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#1961]
```rust
let prql = "from foo bar";
if let Ok(sql) = compile(&prql, Options::default()) {
    println!("SQL: {}", sql)
}
```

    thread 'main' panicked at 'bad transform cast:
```rust
[Expr {
  id: Some(3),
  kind: Ident(Ident { path: ["default_db"], name: "foo" }),
  span: Some(span-chars-5-9),
  target_id: None,
  target_ids: [],
  ty: Some(table<[foo.*]>),
  needs_window:
  false,
  alias: None,
  flatten: false },
Expr {
  id: None,
  kind: Literal(Null),
  span: None,
  target_id: None,
  target_ids: [],
  ty: None,
  needs_window: false,
  alias: None,
  flatten: false }]
```
    prql-compiler-0.5.2/src/semantic/transforms.rs:779:29
    stack backtrace:
       0: rust_begin_unwind
                 at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
       1: core::panicking::panic_fmt
                 at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
       2: core::result::unwrap_failed
                 at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
       3: core::result::Result<T,E>::expect
                 at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1070:23

**Comment by max-sixty** [comment]
Is this on `main`? This was fixed in https://github.com/PRQL/prql/pull/1928

Closing but reopen if still valid

**Comment by vanillajonathan** [comment]
No, this is not on `main`, it is with 0.5.2. Maybe time for 0.5.3 soon?

**Comment by max-sixty** [comment]
> No, this is not on `main`, it is with 0.5.2. Maybe time for 0.5.3 soon?

Yes. If it's blocking your development, I can do one now!

Otherwise we try and do around every two weeks, so we'd do one in a week.

**Comment by vanillajonathan** [comment]
No, it is not blocking, its just a slight nuisance. I can wait, no worries.

**Comment by max-sixty** [comment]
Thanks! Let me know if it becomes blocking.
