### ISSUE TITLE
Expand set of quoted keywords to include sqlite keywords

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1966]
I have a tables named "Assessment" and "Appraisal", so I entered the statement `from as=Assessment`. It generates (obviously) the following SQL:

```
SELECT
  *
FROM
  "Assessment" AS as
```
and SQLite throws an error: `Result: near "as": syntax error`

It's easy enough to work around (`from ass=Assessment`) but could this be solved in PRQL, perhaps by quoting the variable name? (I don't know enough about SQL...)

**Comment by max-sixty** [comment]
Thanks for the issue @richb-hanover !

My guess is that SQLite is stricter than others. 

We currently have some quoting of keywords. For example, if we replace `as` with `from`, PRQL should generate:

```
SELECT
  *
FROM
  assessment AS "from"  # "from" gets quoted
```

I tried expanding the keywords we quote in #1967. But it quotes a _lot_ of words — `temp` / `close` / `month` / etc. We'd want to change our examples before merging that, as it adds lots of noise to the outputs.

Do we know what the SQLite rules are? What needs to be quoted in that position?

**Comment by aljazerzen** [comment]
These are the docs for SQLite: https://www.sqlite.org/lang_keywords.html

**Comment by max-sixty** [comment]
> These are the docs for SQLite: https://www.sqlite.org/lang_keywords.html

Thanks a lot. 

What's a good design here?

I guess we could just copy them in and put them on the `DialectHandler` struct?

**Comment by aljazerzen** [comment]
Nah, we can add them for all dialects. Quoting too much is not that bad, except if it really buffs up our examples.

**Comment by max-sixty** [comment]
The attached closed PR really did mangle a lot of the examples, but that was a much wider set. So agree it's OK to try expanding the set to the SQLite keywords for all dialects if that's easier and the results look fine

**Comment by max-sixty** [comment]
I edited the description and added the Good First Issue label. As ever, if you think you might be interested in contributing and anything is unclear, feel free to ask!
