### ISSUE TITLE
Allow `?`  for parameters

### ISSUE THREAD

**Issue by linux-china** [PRQL/prql#1987]
Just noticed prql-jdbc driver from https://github.com/PRQL/prql/pull/1929  and it's really useful.  Just send PRQL over prql-jdbc  and prql-jdbc will transpile PRQL to SQL transparently  and  fetch data from database. 

A question here,  Java JDBC/R2DBC use `?` as placeholder for parameters,   and now PRQL uses `$1`, `$2` as parameters, and maybe [Allow braces for parameters](https://github.com/PRQL/prql/issues/1479), but `?` as parameter placeholder still very important because it's a standard in JDBC.

An example for prql-jdbc: 

```java
PreparedStatement stmt = conn.prepareStatement("from mytable | filter name == ?");
//  SELECT * FROM mytable WHERE name = ?
stmt.setString(1, "John");
```

With prql-jdbc and `?` as parameter placeholder, and I think most Java JDBC frameworks/libraries can use PRQL directly: 

* Spring JdbcTemplate: 

```java
String query = "from EMPLOYEE | filter ID == ?";
// "SELECT * FROM EMPLOYEE WHERE ID = ?";
Employee employee = jdbcTemplate.queryForObject(
  query, new Object[] { id }, new EmployeeRowMapper());
```

* MyBatis

```xml
<select id="selectPerson" parameterType="int" resultType="hashmap">
  from PERSON | filter ID == #{id}
</select>
<!--  BoundSql:  select * from PERSON where id = ? --> 
```

**Comment by max-sixty** [comment]
Thanks for the issue @linux-china .

Are there any docs on the use of `?`? For example, I'm curious how it deals with multiple parameters.

My initial hypothesis is that we should use one thing in PRQL and then the integrations can do the translation — for example if we decide to use `${foo}`, then the JDBC driver can translate that to `?` if needed. But let's have a look at some cases and see what would work best.

(And if you have any feedback on #1929, I'm sure it will be well-received. I notice you already made an addition to the existing code to throw an error in Java rather than panic; that sort of thing might be useful advice in #1929 too)

**Comment by linux-china** [comment]
Javadoc for PreparedStatement:  https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html 

JDBC spec only supports positional parameter with placeholder `?`.  But positional parameter is some risky, and some Java frameworks/libraries use named parameters.

```java
        String sqlQuery = "INSERT INTO student VALUES(:id, :name, :department)";
```

```java
Mono.from(connectionFactory.create())
  .flatMapMany(connection -> connection
    .createStatement("SELECT firstname FROM PERSON WHERE age > $age")
    .bind("$age", 42)
    .execute())
```

```java
    @PRQL("from user|filter id == ${id}")
    User findUserById(Integer id);
```

or you can wrapper JdbcTemplate to PrqlTemplate: 

```
prqlTemplate.query("from employee | filter name == ${name}", ... )
```

>> we decide to use ${foo}, then the JDBC driver can translate that to ?

My option: `?` is for JDBC level and it's fundamental, Named parameter `${name}`  or `:name` is for frameworks and libraries.  Sometime we should use both.   For example, if you use Spring Framework, almost you will choose named parameter because less risky and easy to write.

**Comment by aljazerzen** [comment]
But if some Java frameworks/libraries use named parameters, they must be translated to positional parameters before they hit the database. Because I know for a fact, that Postgres does not support named parameters.

Could these frameworks/libraries translate named to positional before we compile PRQL to SQL? 

This way PRQL as a language does not need to support many ways to do the same thing.

**Comment by linux-china** [comment]
> Could these frameworks/libraries translate named to positional before we compile PRQL to SQL?

I'm not sure. A easy solution now is to wrap up these frameworks/libraries to accept PRQL,  then compile PRQL to SQL, and finally call delegated APIs that accept SQL. With this way, you just need to replace named PRQL parameter from `${name}` to `:name` framework style, and then  the frameworks will handle all others things.  

The following API is to wrap up Spring NamedParameterJdbcTemplate with PRQL support. 

```java
    @Test
    public void testParameters() throws Exception {
        prqlTemplate.query("from test2 | filter id == ${id}", Collections.singletonMap("id", 1), rs -> {
            System.out.println(rs.getString("name"));
        });
    }
```

To wrap up Spring JdbcTemplate, and it's easy, and now I can use PRQL directly to query database by wrapping up Spring JdbcTemplate. 

![image](https://user-images.githubusercontent.com/46711/221836733-1a45fad3-c4a4-4722-a64d-5c3590627792.png)

**Comment by zhicwu** [comment]
Good point @linux-china. I was thinking to add a Java parser which can address issue like this.

Anyway, I think it's probably better to add an compile option in PRQL lib to recognize parameters based on given pattern.

**Comment by aljazerzen** [comment]
Wow @linux-china this is great! Are you using just the plain library from main branch or the PR for JDBC?

But regarding using `?` or `:some_name` for params - I don't think this is possible to parse consistently.

Take this example:
```
from a
select [x ? 5]
select :param
```
In the first `select`, `?` will be parsed as [coalesce](https://prql-lang.org/book/language-features/coalesce.html), even though you may want it to be a param (and x is a function that takes `?` and `5`).

In the second select, `:param` will ne parsed as a named param to `select` function, even though it you want to be a query parameter.

---

Sidenote: #1957 adds support for params of form `$some_name`.

---

It seems that the only way to make JDBC and other frameworks / libraries work correctly, would be to compile PRQL to SQL **after** `?` and `:name` have been processed into `$1`.

**Comment by linux-china** [comment]
MyBatis with PRQL:

![image](https://user-images.githubusercontent.com/46711/223919802-0f0a4fb8-64bb-43ce-88d3-a7fc34ee4393.png)

`?` parameter is required.

**Comment by snth** [comment]
See #1479 for how to work around this with s-strings.
