### ISSUE TITLE
Compiler does not do Unicode

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#2003]
The compiler does not work with Unicode so it is not possible to use Unicode characters in the variable name for let expressions, or in the table names or in column names.

**Comment by max-sixty** [comment]
Please could we have an example or two?

**Comment by max-sixty** [comment]
Here's an example:

```elm
from tète
```

```
Error:
   ╭─[-:1:7]
   │
 1 │ from tète
   ·       ┬
   ·       ╰── unexpected è
───╯

```

I'm guessing the lexer is splitting too aggressively; I do think we should support this

**Comment by alex-knyaz** [comment]
I have cursed sqlite database with table names like this: "📦 Заказы", "⚪ Пункты", "🔴 Отгружаемый товар". 

it just does not work...

help
