### ISSUE TITLE
Creative Commons license

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#2009]
May I suggest the [Creative Commons Zero v1.0 Universal](https://spdx.org/licenses/CC0-1.0.html) (CC0-1.0) or the [Creative Commons Attribution 4.0 International](https://spdx.org/licenses/CC-BY-4.0.html) (CC-BY-4.0)?

**Comment by max-sixty** [comment]
I've been told that we should not release logos and brand stuff openly, because it can make it confusing for users as to whether a product is endorsed by the PRQL team & community, particularly if commercial entities start using it. We are very happy for commercial entities to use PRQL, but we want to make that distinction clear.

I haven't spent much time thinking or researching this. Is there anything that anyone wants to do that this would allow? I can spend some time thinking about it or researching it. (otherwise I won't)

Longer term, I'd be happy to give these to some non-profit entity that acts in the benefit of the open-source project — we've made a commitment to (edit: not!) use them for commercial purposes.

**Comment by vanillajonathan** [comment]
Good point!

Creative Common have a couple of variants of their license.
- BY is By Attribution, it means PRQL needs to be mentioned.
- NC is Non Commercial.
- ND is No Derivatives.
- SA is Share-Alike.

Some links of interest:
- [Android](https://developer.android.com/distribute/marketing-tools/brand-guidelines#android_robot) robot (CC BY 3.0)
- [GNOME](https://foundation.gnome.org/logo-and-trademarks/) needs written permission.
- [KDE](https://kde.org/stuff/clipart/)
- [Firefox](https://www.mozilla.org/en-US/foundation/trademarks/list/) - you must mention that Firefox is a trademark of Mozilla Foundation.
- [Lua](https://www.lua.org/images/) under their terms.
- [PHP](https://www.php.net/download-logos.php) (CC BY-SA 4.0)
- [PostgreSQL logo](https://www.postgresql.org/about/policies/trademarks/) is covered by their trademark policy.
- [Python logo guidelines](https://www.python.org/community/logos/)
- [Rust Logo Policy and Media Guide](https://foundation.rust-lang.org/policies/logo-policy-and-media-guide/) (CC BY 4.0)
- [MariaDB](https://mariadb.com/about-us/logos/) under their trademark policy
- [MongoDB](https://www.mongodb.com/brand-resources) under their trademark
- [MySQL logo guidelines](https://www.mysql.com/about/legal/trademark.html)
- [.NET](https://github.com/dotnet/brand) under CC0 1.0 Universal.
- Tux penguin - https://web.archive.org/web/20191001080512/https://isc.tamu.edu/~lewing/linux/
- [Wilber](https://www.gimp.org/about/selling.html), the logo of GIMP. (CC BY-SA 3.0)

**Comment by max-sixty** [comment]
Great links!

I'd be happy to copy the Rust one, that looks very liberal while protecting against any confusion.

We can discuss on an upcoming dev call if we get time...

**Comment by max-sixty** [comment]
I moved this from `prql-brand`.

@vanillajonathan opened it at the right place, but here we can track it & plan to discuss

**Comment by vanillajonathan** [comment]
If you need legal advice you can consult the [Software Freedom Law Center](https://softwarefreedom.org/about/contact/) (SFLC).

**Comment by aljazerzen** [comment]
I don't have a reliable advice to give here.

But you do have my approval to apply any commonly used license.

**Comment by vanillajonathan** [comment]
I also think the "book" should be licensed under the Creative Commons as that would make it easier to incorporate materials from the "book" into blogs, wikis, white papers, tutorials and books.

**Comment by max-sixty** [comment]
I guess I had thought that an open-source license is more permissive than Creative Commons. Is that not the case? I'd be happy to dual-license it if so (but we should only add that complication if there is actually a case for it)

**Comment by vanillajonathan** [comment]
They are for different things; open source license cover computer software and things such as binaries and source code availability which does not apply to content while open content licenses are for works of art and documentation.

**Comment by max-sixty** [comment]
Do you have any sources for requiring a different license for docs? The first source I found was https://opensource.stackexchange.com/questions/6110/is-there-any-particular-reason-to-license-docs-with-cc-by-4-0-rather-than-mit, which suggests there's no need to have different licenses

**Comment by vanillajonathan** [comment]
No, I don't.

But I guess Creative Commons is easier to understand for the layman, while the Apache License which is quite lengthy can be difficult to understand as it deals with binaries, source code, trademarks and patents.

Wikipedia and Wikibooks require content to licensed under CC or GFDL.
> By publishing changes, you agree to the [Terms of Use](https://foundation.wikimedia.org/wiki/Terms_of_Use), and you irrevocably agree to release your contribution under the [CC BY-SA 3.0 License](https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License) and the [GFDL](https://en.wikipedia.org/wiki/Wikipedia:Text_of_the_GNU_Free_Documentation_License).

**Comment by max-sixty** [comment]
OK, if we can get a reliable source that answers "why do you have two licenses?" we can reopen for the docs. Otherwise I'd vote to keep this simple and avoid multiple licenses.

(edit: mistakenly closed, so reopened — we still need to add a CC license for the brand repo — open to contributions there)

**Comment by vanillajonathan** [comment]
https://github.com/dotnet/brand/blob/main/LICENSE

**Comment by max-sixty** [comment]
Yes, we should do it for the brand, that's a good idea — contribution to that repo welcome!

Without a good reason, I don't think we should do it for the docs, which are already open source

**Comment by max-sixty** [comment]
@vanillajonathan do you want to PR the CC license into the prql-brand repo?

**Comment by vanillajonathan** [comment]
Alright, I'll copy the LICENSE file from the /dotnet/brand/ project which is Creative Commons Zero v1.0 Universal which means no rights reserved and basically is public domain.

**Comment by max-sixty** [comment]
I think we want something as close as possible to https://foundation.rust-lang.org/policies/logo-policy-and-media-guide/, rather than CC-Zero
