### ISSUE TITLE
An examples/ directory with lots of PRQL examples 

### ISSUE THREAD

**Issue by qharlie** [PRQL/prql#201]
We could use these for ensuring our SQL generated is in sync between different impls also.

**Comment by max-sixty** [comment]
For sure! We have a start with https://github.com/max-sixty/prql/tree/main/examples, but lots more to do

**Comment by danjones1618** [comment]
These examples would be good integration tests. I discussed a system in #27. It's probably worth having such a system now that transpiration is happening.

**Comment by qharlie** [comment]
Closing due to added examples and other tickets that will further refine this
