### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2010]
It's time to do a new release — I can do this

Are we OK with 0.5.3 or do we do 0.6.0? Ref https://github.com/PRQL/prql/issues/1997

Should I re-revert the switch syntax change now or wait for https://github.com/PRQL/prql/issues/1795? I don't really see much reason to wait, it's experimental and so we should feel free to change it lots

**Comment by snth** [comment]
I've commented on #1795 regarding the control value (tl;dr in favour of renaming to `case`, against control value). What would re-reverting the syntax change mean? Where did we end up on `->` vs `=>`?

**Comment by snth** [comment]
How much documentation do we have on `loop`? I wanted to try this out and maybe write up a blog post about it. Perhaps in combination with `ducker`?

Given that `loop` is quite a large feature addition, I think a 0.6,0 release would be appropriate.

**Comment by aljazerzen** [comment]
Update from dev call: let's release 0.6.0 since we do have breaking changes.

TODO:
- [ ] re-revert switch arrows syntax change,
- [ ] rename switch to case,
- [x] documentation for loop

**Comment by max-sixty** [comment]
(FYI I may not get to this today, but will do early this week if I don't)

**Comment by max-sixty** [comment]
I think everything is done now, we just have to hit the button. I may do it in the morning
