### ISSUE TITLE
Unnecessary "OVER ()" for aggregate functions

### ISSUE THREAD

**Issue by Jelenkee** [PRQL/prql#2018]
Hello,
```
from invoices
select [avg_price = avg total]
```
generates
```
SELECT
  AVG(total) OVER () AS avg_price
FROM
  invoices
```

This query returns the average price. But not once, but n times, where n is the number of rows in the table.
I would expect instead:
```
SELECT
  AVG(total) AS avg_price
FROM
  invoices
```

**Comment by eitsupi** [comment]
You should use `aggregate` instead of `select`.

```elm
from invoices
aggregate [avg_price = avg total]
```

```sql
SELECT
  AVG(total) AS avg_price
FROM
  invoices
```

Aggregation is described in the FAQ, so please check it.
https://prql-lang.org/faq/

**Comment by Jelenkee** [comment]
I see. Thanks
