### ISSUE TITLE
Rationalizing the repo

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2029]
The repo is getting very busy in its root. If someone arrived and thought "Where can I find the core code", they might have no idea. (this happens to me occasionally in other repos)

Could we:
- Move al the bindings into a `bindings` path?
- Move `playground` & `website` & `book` into `web` path?
- I tried to see whether some of our config files could go into `.config`. But only `insta` seems to support that at the moment; we have a lot of them. I don't think there are any we don't use at all. 
- Any others? `snap` could maybe go somewhere? Maybe into a `build` path? Docker might be subsumed by the devcontainer work.

<img width="983" alt="image" src="https://user-images.githubusercontent.com/5635139/223037983-7e7b4960-53ae-4fc4-bb74-35f1586f5df5.png">

**Comment by aljazerzen** [comment]
> Move al the bindings into a bindings path?

Yes, +1

> Move playground & website & book into web path?

Yes, +1

> Any others? snap could maybe go somewhere? 

Into `packages/`?

**Comment by vanillajonathan** [comment]
Maybe move the playground out to its own repository, `/PRQL/playground`?
Maybe move the playground to its own subdomain, `play.prql-lang.org`?

**Comment by eitsupi** [comment]
I don't think prql-js and playground should be moved from this repository given the current deployment process.

**Comment by max-sixty** [comment]
> Maybe move the playground out to its own repository, `/PRQL/playground`?
> Maybe move the playground to its own subdomain, `play.prql-lang.org`?

We actually wanted the playground to be _more_ integrated with the website — e.g. we added a banner at the top of the playground to mirror the website, so it feels like the same property.

Possibly we'd get more contributions from folks who are comfortable with JS if it were a separate repo; there's some tradeoff there. But yes, the current deployment would be much more difficult, I wouldn't think it were worth the extra work there without more confidence it would lead to more contributions.

**Comment by max-sixty** [comment]
Mostly done — just need to do a `packages` and `grammars` one, each with exactly one item...

**Comment by max-sixty** [comment]
Closed by #2135, #2117, #2121
