### ISSUE TITLE
TLDR page for prqlc

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#2030]
Add a TLDR page for `prqlc`.
See https://tldr.sh/

**Comment by vanillajonathan** [comment]
I created a PR at tldr-pages/tldr/pull/9921

**Comment by max-sixty** [comment]
I agree this would be cool!

I think we could add some examples to the docs (re https://github.com/PRQL/prql/issues/177), and then reference those in TLDR. We wouldn't need to do that automatically, it would be fine to have a note to say to update TLDR.

**Comment by max-sixty** [comment]
I see the PR — that looks excellent. It's simple enough that I don't think those things will change, it's fine without tests.

**Comment by kbdharun** [comment]
Thanks, I have merged the PR, and I think the issue can be closed.

**Comment by max-sixty** [comment]
Thanks @kbdharun !

@vanillajonathan if you want to make an index of these, that would be useful (and serve as a good demonstration of all your work!)

**Comment by vanillajonathan** [comment]
Sure. What should I call it?
It sounds like it should be on the website, not the book.
So far only TLDR have been merged.

You can see it live at https://tldr.inbrowser.app/pages/common/prqlc

**Comment by max-sixty** [comment]
I would basically just replicate https://prql-lang.org/book/internals/syntax-highlighting.html for "Helpers" (or feel free to rename); then there's a good index of where these live; WDYT?

**Comment by vanillajonathan** [comment]
Yeah, I can do that, but I am not sure it belongs to the "language book". Maybe it belongs more to the website, I don't know. But yeah, I can put in the book.

**Comment by max-sixty** [comment]
> I am not sure it belongs to the "language book". Maybe it belongs more to the website, I don't know. But yeah, I can put in the book.

I see it as more of an index for developers to know where things are, less of something users would refer to unless they're using the tool already. (I agree the "Internals" section in the book doesn't fit that well with the main part of the book; alternatively we could use markdown files on GitHub — the book has the advantage it's a nice presentation and easy to find...)

**Comment by eitsupi** [comment]
It seems completed.

**Comment by max-sixty** [comment]
Nice! Looks good @vanillajonathan !
