### ISSUE TITLE
Add prqlc to eg

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#2035]
`eg` provides examples of common uses of command-line tools.

I created a PR at srsudar/eg/pull/99

**Comment by max-sixty** [comment]
@vanillajonathan if you want to add a page like https://prql-lang.org/book/internals/syntax-highlighting.html to the book, that would help track where these are.

**Comment by vanillajonathan** [comment]
Good idea!
I am waiting for things to get merged upstream, then I can do that.

**Comment by vanillajonathan** [comment]
This has now been merged, but I now see that `eg` isn't very maintained, so I am not sure if I should add it to the `helpers.md` file.

**Comment by max-sixty** [comment]
May as well! But low priority if you don't get time...
