### ISSUE TITLE
Remove redundant code snippets in book

### ISSUE THREAD

**Issue by Jelenkee** [PRQL/prql#2060]
Currently the PRQL-snippets exist in the markdown files and in  `book/tests/prql`.  That is not good for maintenance of these snippets.

A solution could be to use a "macro" in the markdown files to import them at build time.
Or you parse the markdown files and extract the snippets when running the tests.

I would prefer the first solution

**Comment by max-sixty** [comment]
Hi @Jelenkee — these are auto-generated by https://github.com/PRQL/prql/blob/60b7b0750c1c7095c2c21cdb55cdc8e23724526a/book/tests/snapshot.rs#L44, and get run with `cargo test`

Does that make sense? It sounds a bit like your suggested solution.

Possibly we should document this better? There's a bullet "Examples" at https://github.com/PRQL/prql/blob/60b7b0750c1c7095c2c21cdb55cdc8e23724526a/book/src/contributing/development.md#how-we-test, but it's kinda far from the code.

**Comment by Jelenkee** [comment]
I see. And you didn't add those files to gitignore because the tests run faster, did you?

**Comment by max-sixty** [comment]
Good question...

We currently split up the extractions from the testing (which is at https://github.com/PRQL/prql/blob/9d0e6fdc37c3075c6623f0b21d8f1e4ce79ae15e/book/tests/snapshot.rs#L188), and the testing reads the files.

Though this isn't strictly necessary, we could avoid writing the PRQL files and just extract them each time we wanted them. There's no performance benefit.

Two points:
- We want to test our autoformatting when that's further along, and writing the autoformatted examples is a good way. We could try and write these _into_ the markdown, but that's more complicated.
- One caveat is that the extraction has slightly different behavior on Windows, and we rely on the files for running the Windows tests, https://github.com/PRQL/prql/issues/356. So we'd need to write a function to do that, which requires someone with a Windows machine and an hour.

**Comment by Jelenkee** [comment]
* Autoformatting sounds good. But is it really that complicated to inject it into markdown? You already add the transpiled SQL to the markdown. Seems not had to me, provided that a function to format prql already exists.
* I will look into that Windows problem later

**Comment by max-sixty** [comment]
> Autoformatting sounds good. But is it really that complicated to inject it into markdown? You already add the transpiled SQL to the markdown. Seems not had to me, provided that a function to format prql already exists.

I was unclear — you're absolutely right. I had meant that mutating the `.md` file would be a bit more complicated. But mutating the markdown AST before producing the HTML is indeed already done. I suspect we'd do that, and have the markdown files have imperfectly formatted PRQL. Does that make sense?

**Comment by max-sixty** [comment]
Closed by #2105
