### ISSUE TITLE
Escaping in F-Strings and S-Strings does not work

### ISSUE THREAD

**Issue by Jelenkee** [PRQL/prql#2082]
Currently `{`, `}` and `"` cannot be escaped.

Example:
  how to compile an F-String to `CONCAT('{"}{')`

**Comment by max-sixty** [comment]
Do the multiple quotations & double-braces in  https://prql-lang.org/book/language-features/s-strings.html#braces & https://prql-lang.org/book/language-features/strings.html help?

V open to doc improvements if those aren't clear / could be linked better.

**Comment by max-sixty** [comment]
That said, does the escaping we have in normal strings not work in s & f-strings? (@Jelenkee if you have a full example, great)

**Comment by Jelenkee** [comment]
You are right. Escaping quotation marks with these triple-quotes is possible. But curly braces are still buggy.

**Comment by max-sixty** [comment]
OK cool. If you have a full example that's easiest to engage, but otherwise I can make one

**Comment by max-sixty** [comment]
Here's an example of the escaping working:

```elm
from my_table
derive x = foo
select db_version = s"{{ x }}version\t()"
```

```sql
SELECT
  { x } version () AS db_version
FROM
  my_table

-- Generated by PRQL compiler version:0.6.1 (https://prql-lang.org)

```

That said, I think it's fairly likely there are gaps here. @Jelenkee if you want to open a bug report with an example, that's very welcome, thank you as ever
