### ISSUE TITLE
PRQL Playground behaviour appears broken

### ISSUE THREAD

**Issue by snth** [PRQL/prql#2102]
### What happened?

The following input failed to produced neither output nor error message.

### PRQL input

```elm
from_text format:json '{"a":1}'
```

### SQL output

```SQL
<NOTHING>
```

### Expected SQL output

```SQL
WITH table_0 AS (
  SELECT
    1 AS a
)
SELECT
  a
FROM
  table_0 AS table_1

-- Generated by PRQL compiler version:0.6.0 (https://prql-lang.org)
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

### Anything else?

The following works but I think ndjson should also be accepted or should at least produce an error informing the user that the input was not understood:

```elm
from_text format:json '[{"a":1}]'
```

**Comment by snth** [comment]
This is probably just a playground issue actually because I'm seeing similar behaviour with other queries in the playground and running the query above with the latest prqlc does produce the following error:

    Error: "While parsing rows: invalid type: map, expected a sequence at line 1 column 0\nWhile parsing object: missing field `columns` at line 1 column 7"

**Comment by max-sixty** [comment]
Do the examples in the book work? If so, what's the salient diff between those and this?

**Comment by aljazerzen** [comment]
No, this is an issue with your JSON format.

It can be either `[{"a": 1}]` or `{"rows": ["a"], "data": [[1]]}`.

Error message could be better, definitely it should have a span.

Maybe we should add parsing for your schema too.

**Comment by max-sixty** [comment]
OK, closing, but feel free to open a new one for the underlying issues
