### ISSUE TITLE
Multiple error messages do not work in prqlr (R)

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#2103]
### What's up?

I know this is not strictly a prql-compiler issue, but any help in developing prqlr would be appreciated.

After adopting prql-compiler 0.6.0, I noticed that the R session running prqlr in the following examples froze. (eitsupi/prqlr#100)

```r
"from a | select {b}" |> prqlr:::compile(target = NULL, format = FALSE, signature_comment = FALSE)
```

```r
"from a | select {b}" |> prqlr:::prql_to_pl()
```

It works fine with other clients. For example, prqlc.

```sh
$ echo 'from a | select {b}' | prqlc compile
Error:
   ╭─[-:1:17]
   │
 1 │ from a | select {b}
   ·                 ┬
   ·                 ╰── unexpected {
───╯
Error:
   ╭─[-:1:19]
   │
 1 │ from a | select {b}
   ·                   ┬
   ·                   ╰── unexpected }
───╯
```

After some testing, I found that `prql_compiler::prql_to_pl` was the cause.

https://github.com/PRQL/prql/blob/ed1e896ecbb1c5e18f0f1286639118e3a77b0100/prql-compiler/src/lib.rs#L229-L233

I suspect that this is probably because the following part does not work in R (the process does not end).
Could you please give me some tips for debugging?

https://github.com/PRQL/prql/blob/ed1e896ecbb1c5e18f0f1286639118e3a77b0100/prql-compiler/src/error.rs#L229-L276

**Comment by eitsupi** [comment]
After examining the dependent prql-compiler commits while switching between them, we confirmed that this symptom first occurs in commit 0a1e6944cf7a9d458e8bb7670898acfff0bb02ff.

The comments on the line deleted by 0a1e6944cf7a9d458e8bb7670898acfff0bb02ff indicate that an infinite loop occurred previously (zesterer/chumsky#301).
Perhaps an infinite loop is still occurring in prqlr, but I don't know what is triggering it......

**Comment by max-sixty** [comment]
Sorry for the trouble...

Is `prqlr` on the same version of dependencies as `main`? I know we had to maintain a different fork because of the rust version, and the `chumsky` version really mattered here.

**Comment by eitsupi** [comment]
https://github.com/eitsupi/prqlr/blob/8c6fb5de7c85648acb16ab6eb6fae518456df3b7/src/rust/Cargo.toml#L14

Installs prql-compiler 0.6.0 from crates.io now.

This is really strange because it only happens with prqlr.
Is it because it is staticlib?
I thought about looking into other staticlibs but couldn't figure out how.

**Comment by eitsupi** [comment]
Oh...it using chumsky 0.9.0!
https://github.com/eitsupi/prqlr/blob/8c6fb5de7c85648acb16ab6eb6fae518456df3b7/src/rust/Cargo.lock#L87

I should update that...sorry bothering you.

**Comment by max-sixty** [comment]
> I should update that...sorry bothering you.

Not at all, I didn't think about it at first either
