### ISSUE TITLE
dbt (jinja) integration been removed from prql-compiler?

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#2104]
### What happened?

The functionality that was in prql-compiler for dbt integration seems to have been removed in #1722 (moved to prqlc).

https://github.com/PRQL/prql/blob/ed1e896ecbb1c5e18f0f1286639118e3a77b0100/book/src/integrations/dbt.md?plain=1#L156-L158

Perhaps the documentation needs updating?
And it might be better to put it on Changelog as a breaking change.

### PRQL input

```elm
from {{ ref('foo') }}
```

### SQL output

```SQL
None
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
Yes; we never actually ended up using this — I couldn't get dbt to run things in the order that I wanted. (And now there are discussions about a deeper integration with dbt).

So yes we should remove these docs. I can do that unless anyone gets there first...

Yes we can add to the changelog too, no harm in doing that.

**Comment by eitsupi** [comment]
Closes because the document has been updated.
