### ISSUE TITLE
Add index of "helpers"

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2133]
### What's up?

@vanillajonathan has kindly added `prqlc` to lots of helper libraries such as https://github.com/tldr-pages/tldr/pull/9921.

Would it be possible to make an index of them, like we have at https://prql-lang.org/book/internals/syntax-highlighting.html, so we know where they are and can update them when needed? It would also serve as a nice way of showing the work that's been done there.

I think it can be very simple — just be a short bulleted list of links to each file.

@vanillajonathan would you be up for doing this? Thank you in advance if so

**Comment by vanillajonathan** [comment]
Yeah, I can do so.

**Comment by aljazerzen** [comment]
I believe this is done: https://prql-lang.org/book/internals/helpers.html
