### ISSUE TITLE
Warnings from `prql-dotnet`

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2141]
### What's up?

From https://github.com/PRQL/prql/pull/2140/files

<img width="972" alt="image" src="https://user-images.githubusercontent.com/5635139/224622547-ddda7b93-78db-4a00-853d-11b35d11c139.png">

Please could we either fix the issue, ignore the warnings, or disable the lint?

Not to blast @s — but @vanillajonathan & @eitsupi if you are up for taking a look...

**Comment by vanillajonathan** [comment]
Those warnings are because they get assigned from libprql so .NET isn't aware of it. I'll silence them.
