### ISSUE TITLE
Code blocks in the Book seems broken

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#2157]
### What's up?

It does not seem to be rendering correctly after the code block.
Could there be a problem with the preprocessing process to update md files?

![image](https://user-images.githubusercontent.com/50911393/224683633-2b888a8e-525e-4914-ae4e-3dcf7757fa88.png)

https://github.com/PRQL/prql/blob/4be8d8c0ece56bfa87e0b8803c608ea1cd9dbab9/prql-compiler/README.md?plain=1#L1-L34

**Comment by max-sixty** [comment]
Oh no! Good spot, thanks @eitsupi .

It looks like this is happening for the files that are `#include`-d...

**Comment by max-sixty** [comment]
Fixed & test added in #2160
