### ISSUE TITLE
Un-optimized DuckDB SQL with multiple `group` transforms

### ISSUE THREAD

**Issue by cboettig** [PRQL/prql#2169]
### What happened?

The PRQL query given below generates unexpected SQL which results in a far slower and less memory-efficient query in duckdb (i.e. crashes my system after consuming over 60 GB ram).  I think the translation is the result of the lacking DISTINCT for a multi-group expression.  

### PRQL input

```elm
from s'SELECT * from read_parquet("s3://gbif-open-data-us-east-1/occurrence/2023-02-01/occurrence.parquet/*")'
filter phylum == 'Chordata'
derive [longitude = (decimallongitude | round 0),
        latitude = (decimallatitude | round 0)
        ]
group ["class", genus, longitude, latitude] (take 1) # aka select distinct
group ["class", longitude, latitude] (
  aggregate n = count
)
```

### SQL output

```SQL
WITH table_0 AS (
  SELECT
    *
  from
    read_parquet(
      "s3://gbif-open-data-us-east-1/occurrence/2023-02-01/occurrence.parquet/*"
    )
),
table_3 AS (
  SELECT
    ROUND(decimallongitude, 0) AS longitude,
    ROUND(decimallatitude, 0) AS latitude,
    ROW_NUMBER() OVER (
      PARTITION BY 'class',
      genus,
      ROUND(decimallongitude, 0),
      ROUND(decimallatitude, 0)
    ) AS _expr_0
  FROM
    table_0 AS table_1
  WHERE
    phylum = 'Chordata'
)
SELECT
  'class',
  longitude,
  latitude,
  COUNT(*) AS n
FROM
  table_3 AS table_2
WHERE
  _expr_0 <= 1
GROUP BY
  'class',
  longitude,
  latitude
```

### Expected SQL output

```SQL
SELECT "class", longitude, latitude, COALESCE(n, 0.0) AS n
FROM (
  SELECT "class", longitude, latitude, COUNT(*) AS n
  FROM (
    SELECT DISTINCT
      "class",
      genus,
      ROUND(decimallongitude, 0) AS longitude,
      ROUND(decimallatitude, 0) AS latitude
    FROM read_parquet("s3://gbif-open-data-us-east-1/occurrence/2023-02-01/occurrence.parquet/*")
    WHERE (phylum = 'Chordata')
  )
  GROUP BY "class", longitude, latitude
)
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

### Anything else?

I have also tried re-writing this with the `s'` 'escape hatch', e.g. `select s'DISTINCT ...`, but this doesn't seem to work so I'm probably not doing it right.  

For comparison, the following R code generates the desired SQL (shown below), which executes quite efficiently:

```r
library(duckdb)
library(tidyverse)

con <- dbConnect(duckdb())
dbSendQuery(con, "INSTALL httpfs;")
dbSendQuery(con, "LOAD httpfs;")


dbSendQuery(con, 'CREATE VIEW gbif AS SELECT * FROM read_parquet("s3://gbif-open-data-us-east-1/occurrence/2023-02-01/occurrence.parquet/*")')
gbif <- tbl(con, "gbif")

ds <- gbif |> 
  filter(phylum == "Chordata") |>
  mutate(latitude = round(decimallatitude,0L),
         longitude = round(decimallongitude,0L)) |> 
  select(class, genus, longitude, latitude) |>
  distinct() |>
  count(class, longitude, latitude) |> 
  show_query()
 ``` 
 
 Thanks for the help, and very excited about PRQL!

**Comment by max-sixty** [comment]
Thanks for the issue!

This gets most of the way there:

```prql
from s'SELECT * from read_parquet("s3://gbif-open-data-us-east-1/occurrence/2023-02-01/occurrence.parquet/*")'
filter phylum == 'Chordata'
derive [
  longitude = (decimallongitude | round 0),
  latitude = (decimallatitude | round 0)
]
select [class, genus, longitude, latitude]
group [class, genus, longitude, latitude] (take 1) # aka select distinct
```

```sql
WITH table_0 AS (
  SELECT
    *
  from
    read_parquet(
      "s3://gbif-open-data-us-east-1/occurrence/2023-02-01/occurrence.parquet/*"
    )
)
SELECT
  DISTINCT class,
  genus,
  ROUND(decimallongitude, 0) AS longitude,
  ROUND(decimallatitude, 0) AS latitude
FROM
  table_0 AS table_1
WHERE
  phylum = 'Chordata'

-- Generated by PRQL compiler version:0.6.1 (https://prql-lang.org)

```

The difference here is that we have to tell PRQL that the only columns going into the `group` are `select [class, genus, longitude, latitude]` — `DISTINCT *` would be wrong if there were other columns.

---

But then adding the final `group` confuses the compiler:

```
from s'SELECT * from read_parquet("s3://gbif-open-data-us-east-1/occurrence/2023-02-01/occurrence.parquet/*")'
filter phylum == 'Chordata'
derive [
  longitude = (decimallongitude | round 0),
  latitude = (decimallatitude | round 0)
]
select [class, genus, longitude, latitude]
group [class, genus, longitude, latitude] (take 1) # aka select distinct
group [class, longitude, latitude] (aggregate n = count)
```

FYI `"class"` in quotes is selecting the string, not a column named `class`.

**Comment by max-sixty** [comment]
Thanks for the issue!

This gets most of the way there:

```elm
from s'SELECT * from read_parquet("s3://gbif-open-data-us-east-1/occurrence/2023-02-01/occurrence.parquet/*")'
filter phylum == 'Chordata'
derive [
  longitude = (decimallongitude | round 0),
  latitude = (decimallatitude | round 0)
]
select [class, genus, longitude, latitude]  # added by me
group [class, genus, longitude, latitude] (take 1) # aka select distinct

# I removed the final group transform
```

```sql
WITH table_0 AS (
  SELECT
    *
  from
    read_parquet(
      "s3://gbif-open-data-us-east-1/occurrence/2023-02-01/occurrence.parquet/*"
    )
)
SELECT
  DISTINCT class,
  genus,
  ROUND(decimallongitude, 0) AS longitude,
  ROUND(decimallatitude, 0) AS latitude
FROM
  table_0 AS table_1
WHERE
  phylum = 'Chordata'

-- Generated by PRQL compiler version:0.6.1 (https://prql-lang.org)

```

The difference here is that we have to tell PRQL that the only columns going into the `group` are those that are being grouped-by, with `select [class, genus, longitude, latitude]`. If there were other columns, then `DISTINCT *` would give the wrong result.

---

But, unfortunately, then adding the final `group` confuses the compiler:

```elm
from s'SELECT * from read_parquet("s3://gbif-open-data-us-east-1/occurrence/2023-02-01/occurrence.parquet/*")'
filter phylum == 'Chordata'
derive [
  longitude = (decimallongitude | round 0),
  latitude = (decimallatitude | round 0)
]
select [class, genus, longitude, latitude]
group [class, genus, longitude, latitude] (take 1) # aka select distinct
group [class, longitude, latitude] (aggregate n = count)   # added back
```

```sql
WITH table_0 AS (
  SELECT
    *
  from
    read_parquet(
      "s3://gbif-open-data-us-east-1/occurrence/2023-02-01/occurrence.parquet/*"
    )
),
table_3 AS (
  SELECT
    class,
    ROUND(decimallongitude, 0) AS longitude,
    ROUND(decimallatitude, 0) AS latitude,
    ROW_NUMBER() OVER (
      PARTITION BY class,
      genus,
      ROUND(decimallongitude, 0),
      ROUND(decimallatitude, 0)
    ) AS _expr_0
  FROM
    table_0 AS table_1
  WHERE
    phylum = 'Chordata'
)
SELECT
  class,
  longitude,
  latitude,
  COUNT(*) AS n
FROM
  table_3 AS table_2
WHERE
  _expr_0 <= 1
GROUP BY
  class,
  longitude,
  latitude

-- Generated by PRQL compiler version:0.6.1 (https://prql-lang.org)
```

---

Here's a minimal example:

```elm
from x
select [class, begins]
group [class, begins] (take 1)
group [class] (aggregate n = count)
```

```sql
WITH table_1 AS (
  SELECT
    class,
    ROW_NUMBER() OVER (PARTITION BY class, begins) AS _expr_0
  FROM
    x
)
SELECT
  class,
  COUNT(*) AS n
FROM
  table_1 AS table_0
WHERE
  _expr_0 <= 1
GROUP BY
  class

-- Generated by PRQL compiler version:0.6.1 (https://prql-lang.org)
```

I'm guessing the evaluation for whether the columns match isn't specific enough. This would be a continuation of https://github.com/PRQL/prql/pull/2109.

---

It's interesting that DuckDB doesn't like the `ROW_NUMBER` construction. If there's a way of specifying this logic which it prefers, we could change to that for that dialect. Different DBs seem to have different & strong preferences on how to do this "take 1 the top 1 item from each group", and we had thought this was a good general option. We can change for each DB if needed.

---

FYI `"class"` in quotes is selecting the string, not a column named `class`.

**Comment by cboettig** [comment]
Thanks for this!  I saw the excellent discussion regarding `distinct` in #292, I may also ping the duckdb folks about why things go so extremely haywire in the `group_by` construction.

Thanks for raising the question with `class` vs `"class"` -- note that the quoted version of the column name is produced by `dplyr`/ `dbplyr`'s sql translation.  I believe dbplyr's introduction of double quotes here is done very intentionally, to avoid the potential collision with a possible keyword (it also does this if column names include protected characters I think).  I may be out of my depth here, but I believe the 'escape' conventions differ (https://stackoverflow.com/questions/2901453/sql-standard-to-escape-column-names), duckdb I believe follows the conventions of SQLite (for which it wants drop-in replacement compatibility) and Postgres in using double quotes.  It looks like the PRQL parser is translating these to single quotes.  I'm not sure that's the ideal behavior here, or what the intended mechanism for escaping column names which happen to be keywords is.  (let me know if this should be a different issue thread? or maybe just my poor understanding of escaped names!)

**Comment by max-sixty** [comment]
Great re the upstream issue!

For quotes, check out https://prql-lang.org/book/syntax.html — PRQL uses single & double quotes both for strings, and then backticks for identifiers. (I'm not a great fan of using backticks in this way, but also not a fan of the existing SQL semantics, and the differences between DBs...) Does that make sense?

**Comment by cboettig** [comment]
ah, back ticks like MySQL, yup that makes sense! (and probably better than treating `'` and `"` differently)

**Comment by cboettig** [comment]
@max-sixty just wanted to share the very nice reply from https://github.com/duckdb/duckdb/issues/6709#issuecomment-1468376709, seems reasonable.

**Comment by max-sixty** [comment]
> @max-sixty just wanted to share the very nice reply from [duckdb/duckdb#6709 (comment)](https://github.com/duckdb/duckdb/issues/6709#issuecomment-1468376709), seems reasonable.

Excellent, thanks! I opened https://github.com/PRQL/prql/issues/2182

So let's do that, and postpone this issue — that will give us 90% of what we want, and is far easier. I'll close this and mark as postponed, so we don't lose it — even after we do that, we'll still be generating `DISTINCT ON` in the case there's an additional `group`.

Thanks for the issue, this was really helpful.

**Comment by cboettig** [comment]
Thanks @max-sixty , wonderful!

Maybe a side-question, but is it possible meanwhile to force the use of `DISTINCT`  in this context by using the S-string "escape hatch"?  I've tried hacking that but it seems to break the compile (no sure if that's related to the issue you mention in adding the last aggregation after using the `select` trick?)

**Comment by max-sixty** [comment]
> Maybe a side-question, but is it possible meanwhile to force the use of `DISTINCT` in this context by using the S-string "escape hatch"? I've tried hacking that but it seems to break the compile (no sure if that's related to the issue you mention in adding the last aggregation after using the `select` trick?)

I think unfortunately not. We would be able to by having the initial query in a `let x = ...` and then an s-string but currently we can't have a table/relation in an s-string https://github.com/PRQL/prql/issues/1762

How blocking is this for you? I could prioritize #2182 if it is blocking

**Comment by cboettig** [comment]
re s-strings, thanks, that's good to know!  

> How blocking is this for you?

thanks for asking, that's very nice of you! I can work around this for now by sticking with pure SQL calls in the edge cases like this, so no worries.  but I'll keep an eye on that issue and would definitely enjoy moving my other code over once that's available!
