### ISSUE TITLE
Implement `DISTINCT ON` for DuckDB

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2182]
### What's up?

We should translate to `DISTINCT ON` for DuckDB & Postgres where we want to `take 1` within a group, but can't use `DISTINCT`. It's much higher perf in DuckDB, and slightly higher in Postgres:

https://github.com/duckdb/duckdb/issues/6709

**Comment by max-sixty** [comment]
I have a partial branch, but I think it's waiting on https://github.com/sqlparser-rs/sqlparser-rs/issues/806. 

It's possible we could fool the parser (which, tbc, we use as a serializer, it's great!) into thinking `ON` were a function, but to the extent that's forthcoming, using a native version would be ideal...

**Comment by eitsupi** [comment]
sqlparser is now updated...

**Comment by max-sixty** [comment]
Would be closed by https://github.com/PRQL/prql/pull/2244

**Comment by eitsupi** [comment]
Closed by #2244

**Comment by eitsupi** [comment]
Reopened by #3788
Blocker: #3111
