### ISSUE TITLE
Website: bootstrap script is broken

### ISSUE THREAD

**Issue by dlazerka** [PRQL/prql#2204]
### What happened?

I think the `bootstrap.min.js` is broken for some reason on prql-lang.org homepage. As a result, links to e.g. "Friendly syntax" is not clickable.
Browsers: Firefox, Chrome, latest versions.

The following is in browser console:
 ```
Uncaught SyntaxError: expected expression, got keyword 'case'     [bootstrap.bundle.min.js:6:29460](https://prql-lang.org/plugins/bootstrap/bootstrap.bundle.min.js)
```

### PRQL input

```elm
N/A
```

### SQL output

```SQL
N/A
```

### Expected SQL output

```SQL
N/A
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
Thank you v much for raising @dlazerka . I just submitted a fix.
