### ISSUE TITLE
[Book] `prql_no_test` code blocks are ignored?

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#2212]
### What's up?

In reading the book I found several places where code blocks were missing.
Maybe related to `prql_no_test`?

![image](https://user-images.githubusercontent.com/50911393/225936284-51cb304a-893f-40ac-b5f4-d096075e49c8.png)

https://github.com/PRQL/prql/blob/9ba64df09442681f53b17a8b3306ed4b9a006d7a/web/book/src/language-features/standard-library/README.md?plain=1#L16-L23

![image](https://user-images.githubusercontent.com/50911393/225936710-bdfdc85e-27cc-48de-a511-36be9fed192a.png)

https://github.com/PRQL/prql/blob/9ba64df09442681f53b17a8b3306ed4b9a006d7a/web/book/src/language-features/standard-library/loop.md?plain=1#L1-L11

**Comment by max-sixty** [comment]
Sorry, this is me again! I'm fixing now

**Comment by max-sixty** [comment]
Thanks a lot for spotting! That should be fixed now

**Comment by eitsupi** [comment]
Wow, very quick fix! Thanks.

**Comment by eitsupi** [comment]
Hmmm......
Code blocks are showing, but perhaps the layout is not as expected?

https://prql-lang.org/book/language-features/standard-library/loop.html
![image](https://user-images.githubusercontent.com/50911393/225951388-416d192a-45fd-4e73-b177-810b7b6276f2.png)

**Comment by max-sixty** [comment]
Oh no! OK that fix was a bit too fast. Checking again!

**Comment by max-sixty** [comment]
(now fixed, thanks a lot @eitsupi )
