### ISSUE TITLE
Function vs. identifier namespaces

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#222]
Something PRQL does that's distinct from general purpose languages — and common with SQL — is allow identifiers to refer to data; e.g. PRQL's `from a | select [b, c]` would generally be something like `load("a")["b", "c"]`, with quotes around the data references.

One disadvantage of PRQL's approach is it's difficult to mix identifiers and function names. SQL does this quite well, at the cost of no abstractions; for example:

```sql
select
  limit_date as date,             # Create a column named `data`
  date('2021-01-01') as start,    # Use `date` as a function
  count(*) as count               # Create a column name `count` without interfering with the function
from data
group by 1
having count > 0
```

But PRQL gets confused by:

```elm
from data
aggregate [count: count foo] by:limit_date
filter count > 0                 # What does `count` refer to here?
```

`count` refers to the function, rather than the column, so this raises an error.

I think that's fairly reasonable, but it leads to a few priorities:
- Good error messages — if someone uses `count` like this, we should say "you have an assignment above named `count`, but it refers to a function here", and not "wrong number of arguments for `count`".
- Additions to the stdlib become backward-incompatible, since they might conflict with existing column names
- We should add documentation for avoiding this. One workaround is using an s-string; i.e. `s'count'` always compiles into `count` in SQL. Possibly there's a language addition that allows a more specific way of being explicit, without giving up our treasured approach of allowing identifier for data references.

**Comment by aljazerzen** [comment]
I think we should formally define namespace for each point in the pipeline. That is, a list of all known functions, variables and tables.

With that we could provide autocomplete, nice error messages and explicitly decide whether functions and variables should have be in the same namespace (what about functions without args?) and how can different names override each other.

To me, it would be reasonable to be able to override a function from stdlib. Like in the example above, after aggregate, name `count` should reference the column, right?

**Comment by max-sixty** [comment]
> With that we could provide autocomplete, nice error messages and explicitly decide whether functions and variables should have be in the same namespace (what about functions without args?) and how can different names override each other.

I definitely agree with the vision, that's compelling.

A couple of questions:
- How would it work with your latest parser changes? Now that we parse functions in the parse tree, how would we discriminate between the `count` as a function and `count` as a ident?
  - One approach is to mandate that functions always have >0 params, like in your latest PR
  - We do want to keep the parser context-free; i.e. we should be able to parse a line of PRQL without knowing what's above it.
- Definitely agree on overriding functions with functions or variables with variables. I wonder whether it might get confusing if functions override variables or variables override functions (particularly if we eventually allow importing other files, which could change). But we can see.
  - Again, this is solved by mandate that functions always have >0 params. There was an elegance at allowing 0-param functions, but practicality > elegance...
- I think implicitly defined items would always be of lower precedence; e.g. columns from `foo_table.*`. That works at both the language design and implementation level, since we don't know about them.

**Comment by aljazerzen** [comment]
Functions with zero params can be treated separately: as variables. They dont have to be not parsed as function calls but normal idents

Its imperative that we have two modes: 
   1. starting with `scope: *`, which allows referencing any table or column so there is no errors.
   1. using a predefined scope (maybe from database, from previous pipeline), which checks if variables you are using are defined

This way we can run compiler in "just get me the SQL" mode and also "interactive, correct me" mode.

**Comment by max-sixty** [comment]
Yes great, the distinction is useful; I agree the "predefined" scope would allow much more than we can currently do. It's consistent with the [Database cohesion](https://github.com/max-sixty/prql#database-cohesion) category.

**Comment by aljazerzen** [comment]
From my latest PR:

```elm
from data
aggregate [count: count foo] by:limit_date
filter count > 0                 # What does `count` refer to here?

Error:
   ╭─[-:3:8]
   │
 3 │ filter count > 0                 # What does `count` refer to here?
   ·        ──┬──
   ·          ╰──── Ambiguous variable. Could be from either of {"%", "$"}
───╯
```

`%` means namespace of all functions and `$` is current pipeline result (I call that frame).

Names are not user-friendly yet, but I believe this issue can be closed :D
