### ISSUE TITLE
Odd characters in playground book tree

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2223]
### What's up?

Not sure whether this is just me, but I see on https://prql-lang.org/playground:

Chrome:

<img width="93" alt="image" src="https://user-images.githubusercontent.com/5635139/225984726-98df4ace-b502-498b-b7f9-582bfa9a6d94.png">

Firefox:

<img width="80" alt="image" src="https://user-images.githubusercontent.com/5635139/225984830-bd1b6522-118d-48fc-82a2-98b2872438f5.png">

CC @Jelenkee if you know off-hand...

**Comment by Jelenkee** [comment]
All I can say is: It works on my machine :wink: 
I will look into this and perhaps replace these unicode characters with SVGs

**Comment by max-sixty** [comment]
Interesting — maybe it's my machine then!

If anyone else can break the tie...

**Comment by richb-hanover** [comment]
I see them too. I think there should be non-breaking spaces in `::before` content of sidebar.css instead of the `\1F892` that was there...

```
.folderRow::before,
.fileRow::before {
  content: "\00a0"; /* non-breaking space */
...
```
I just created a PR to fix this. https://github.com/PRQL/prql/pull/2225

**Comment by richb-hanover** [comment]
PS I'm not sure what else is happening in the `::before` CSS. When I was testing locally, I initially set `.fileRow::before` to the non-breaking space (without the other CSS). It appeared that the indentation was a bit less than it was for the `.folderRow` for the BOOK's entries. It's attractive now, so I'm guessin' that much of this scales the &nbsp; to be slightly wider... If the original author wanted to explain, it would be helpful. Thanks.
 
```
.folderRow::before,
.fileRow::before {
  content: "\00a0"; /* non-breaking space */
  margin-right: 5px;
  display: inline-block;
  transition: transform 0.3s ease;
  transform-origin: center;
  transform: scale(1.25, 1.25);
}
```

**Comment by richb-hanover** [comment]
Oh dear. I hadn't realized that the character was supposed to be a twisty triangle (err... a "disclosure triangle") Clicking the entry expands the hierarchy. It's late here - I will ponder on how to fix this (part of it may be substituting a white right-triangle  `\25b7`) and come back in the weekend...

**Comment by richb-hanover** [comment]
@max-sixty This time for sure. PR https://github.com/PRQL/prql/pull/2235 should address this.

**Comment by max-sixty** [comment]
It's looking great! We even get a nice little animation on click? We don't deserve...

<img width="349" alt="image" src="https://user-images.githubusercontent.com/5635139/226140504-d43e0feb-c137-410a-a8cc-3f31c70998cb.png">

**Comment by richb-hanover** [comment]
The animation was there all along. I noticed it when the odd character rotated when I clicked. (That was my realization last night.) Swapping in the different white right-pointing triangle Unicode value plus a little tidying seems to have done the trick. Glad it's looking good now.
