### ISSUE TITLE
`columns` representation

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2229]
### What's up?

Not the _top_ priority of the project, but would it make sense represent columns here:

https://github.com/PRQL/prql/blob/79e5529413fecc66b824d1936e89ac3889f248fb/prql-compiler/src/ast/rq/mod.rs#L77

...with an [`IndexMap`](https://github.com/bluss/indexmap)`<Cid, RelationColumn>`, rather than a Vec of a 2-tuple? That would make the RQ representation more concise.

(It can't be a `HashMap` because it needs to be ordered)

**Comment by aljazerzen** [comment]
Yea, I wanted to change that to

```
    ... 
    pub columns: Vec<ColumnDef>
}

struct ColumnDef {
    column: RelationColumn,
    cid: CId,
}
```
... which is not really more concise.

I treat RQ as a public interface, where third-party library constructs are discouraged.

**Comment by max-sixty** [comment]
> I treat RQ as a public interface, where third-party library constructs are discouraged.

Yes, good point.

I was predominantly thinking that for the _serialization_ of RQ, it's more concise to have a map — basically half the number of lines — and maps are ordered in JSON / YAML

But I agree for the rust representation it's worse to require a 3rd part library.

Would you support having it as a map the `Serde` implementation? (super low priority, maybe not worth the discussion)

**Comment by aljazerzen** [comment]
> and maps are ordered in JSON / YAML

Not really. Many implementations may treat them that way, but [the standard](https://www.json.org/json-en.html) says:

> An object is an unordered set of name/value pairs.

**Comment by max-sixty** [comment]
> Not really. Many implementations may treat them that way, but [the standard](https://www.json.org/json-en.html) says:
> 
> > An object is an unordered set of name/value pairs.

Ah, good find.

OK then, I guess this isn't going to work. Thanks for engaging...
