### ISSUE TITLE
pre-commit CI's formatting is wrong about multi-line footnotes in mdBook's Markdown

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#2248]
### What's up?

https://github.com/PRQL/prql/pull/2237#issuecomment-1474876022

The changes 1aead27d6f5f81b1677527d330051a4a4b670747 made by pre-commit CI is clearly wrong changes.
But I don't know how to stop this...

Before

![image](https://user-images.githubusercontent.com/50911393/226114530-342cd829-44ee-4d9f-a451-713094d567b9.png)

After

![image](https://user-images.githubusercontent.com/50911393/226114539-a20ee5e5-75b5-49c5-97cd-bd5d574bee60.png)

**Comment by max-sixty** [comment]
Re-indenting the code block works: https://github.com/PRQL/prql/pull/2237/commits/a6cb5e90b71dff313d03d3348a4e3464b1e6f808

...but doesn't solve this indentation problem here: https://github.com/PRQL/prql/commit/1aead27d6f5f81b1677527d330051a4a4b670747#diff-30aeff354da8b464a99b788a30f3a81597cf6aacae8c3486ad25abf1b4f0fc0bL184-R188

I had put in https://github.com/rust-lang/mdBook/issues/2003, which led to https://github.com/raphlinus/pulldown-cmark/issues/623, which is the underlying issue, I think.

---

For the book, we can use the `{{footnote}}` style — this is only a problem when we want to share content between the book & GitHub. But that should be quite rare...

**Comment by eitsupi** [comment]
Thanks for digging into this.
I think this may a common Markdown extension issue that is out of specs (CommonMark, gfm).......

**Comment by max-sixty** [comment]
Yes agree. Lmk if you think there's much to do here, otherwise I guess we close without resolving...
