### ISSUE TITLE
`filter id = $1` cannot be parse

### ISSUE THREAD

**Issue by shota-kizawa** [PRQL/prql#226]
A query like the following cannot be parse. Is this correct behavior?
```
from mytable
filter id = $1
```

ref: https://github.com/max-sixty/prql/blob/main/examples/sql-parameters.md

## Error log
```
$ cargo run compile
from mytable
filter id = $1
 --> 2:13
  |
2 | filter id = $1␊
  |             ^---
  |
  = expected EOI, terms, or operator
```

**Comment by max-sixty** [comment]
At the moment we don't have the parameters feature. I'd be very up for adding it though.

I couldn't find a great "help" on SQL parameters, but here's Postgres': https://www.postgresql.org/docs/current/xfunc-sql.html#XFUNC-SQL-FUNCTION-ARGUMENTS

Feel free to reply with questions.

**Comment by shota-kizawa** [comment]
Thank you!

I'll create a separate issue!

**Comment by max-sixty** [comment]
Perfect, thanks! Feel free to close this.

Any other things you see and we don't have issues for — please feel free to open them1
