### ISSUE TITLE
Columns of certain names like "date" can not be directly referred to?

### ISSUE THREAD

**Issue by cottrell** [PRQL/prql#2273]
### What happened?

You can't directly work with a column named "date" for example.

### PRQL input

```elm
from invoices
derive [
  # t = invoices.date,  # works
  # t = date,  # error
  t = f"{date}"  # error
]
```

### SQL output

```SQL
Error: 
   ╭─[:4:7]
   │
 4 │   t = date,  # error
   ·       ──┬─  
   ·         ╰─── function std.derive, param `columns` expected type `column`, but found type `set`
───╯
```

### Expected SQL output

```SQL
SELECT
  *,
  date AS t
FROM
  invoices

-- Generated by PRQL compiler version:0.6.1 (https://prql-lang.org)
```

### MVCE confirmation

- [x] Minimal example
- [ ] New issue

### Anything else?

If this is known and in the docs, I searched for "escape" and "columns" and similar things but did not come across a work around other than using the table name.

**Comment by max-sixty** [comment]
Yup, we're working through this in https://github.com/PRQL/prql/issues/2155. It's not a great situation at the moment, but we will fix it. The temporary workaround is `s"date"` or `invoices.date`, as in your example above...

(I'll close as dupe but please reopen if I'm mistaken, thanks as ever for the issue @cottrell ...)
