### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2280]
### What's up?

https://github.com/PRQL/prql/blob/3a50d91d764440a98c73605a702259c5331ac2a3/web/website/content/faq.md#L9 is quite old, we should update.

I'll do it unless anyone is up particularly up for it

**Comment by richb-hanover** [comment]
I have started to update this. Give me a day or two to push what I have

**Comment by richb-hanover** [comment]
Comments welcome on PR #2309. Thanks.

**Comment by ArslanYM** [comment]
@richb-hanover have you fixed this issue?

**Comment by richb-hanover** [comment]
PR #2309 has been merged. There's another PR #2336 that has not yet been merged, and is open for comments.

**Comment by richb-hanover** [comment]
@max-sixty Should we close this issue in favor of #2336?

**Comment by max-sixty** [comment]
Yes! 

Let me do a final pass of #2336 tomorrow!
