### ISSUE TITLE
Add SQL parameter features

### ISSUE THREAD

**Issue by shota-kizawa** [PRQL/prql#229]
ref: #226

**Comment by aljazerzen** [comment]
SQL parameters are just identifiers. Their detection and substitution should be left to the database.

Is there a reason we couldn't just allow idents from starting with `$`?

**Comment by max-sixty** [comment]
Good point @aljazerzen; we can definitely do that

**Comment by max-sixty** [comment]
Good point @aljazerzen; we can definitely do that
