### ISSUE TITLE
Equi-joins

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#231]
Currently:

```elm
from newest_employees
join average_salaries [country]
```

...compiles to:

```sql
SELECT
  *
FROM
  newest_employees
  JOIN average_salaries ON country
```

I think that should be `USING(country)` — any thoughts?

**Comment by aljazerzen** [comment]
What about 

```
from newest_employees
join average_salaries using:country
```

There can only be one column to be using, to syntax `[]` does not make much sense.

**Comment by max-sixty** [comment]
We can have lots of columns in `USING`!

```
SELECT
  *
FROM
  newest_employees
JOIN average_salaries USING (country, employee_id)
```

...would be a valid query.

WDYT @aljazerzen ?

**Comment by aljazerzen** [comment]
Oh, my bad. Of course it can take multiple arguments.

**Comment by max-sixty** [comment]
Are you OK with #245? 

Someone could still do `join [x=x]` if they really wanted an inner join rather than a `using` join, even though I think that might be unlikely in practice.

**Comment by aljazerzen** [comment]
What do you mean? You should be able to use `join employees side:inner [emp_no]` as well as `join employees side:left [emp_no]`?

I did some reading and as far as I understand `SELECT FROM A JOIN B USING(x)` is (almost) the same as `SELECT FROM A JOIN B ON A.x = B.x`.

**Comment by max-sixty** [comment]
> What do you mean? You should be able to use `join employees side:inner [emp_no]` as well as `join employees side:left [emp_no]`?

My message was confusing. I was saying that the proposed syntax for `using` join doesn't preclude someone from specifying another type of join. If they want `x JOIN y ON a = b`, they can still write `... join y [a=b]` — there's nothing magic such that they get a `USING` join without expecting one.



> I did some reading and as far as I understand `SELECT FROM A JOIN B USING(x)` is (almost) the same as `SELECT FROM A JOIN B ON A.x = B.x`.

Tell me if I'm wrong — my understanding is that it's an "equi" join rather than an "inner" join. The same rows are joined, but the two columns are merged into one. A benefit is that it's easier to write queries on top of equi joins than inner joins, since there aren't duplicate columns.

**Comment by aljazerzen** [comment]
Ahhhh, that makes sense yeah. If someone wants to `join y [a=b]` they still can :+1: 

But regarding, equi-joins: [postgres says](https://www.postgresql.org/docs/8.3/queries-table-expressions.html) exactly what you said: if you use `USING`, the result has only one column, while `ON` has one for each table.

But that does not prevent you from using `LEFT` or `RIGHT OUTER JOIN`. These two only refer to what rows should be included in the result.
