### ISSUE TITLE
Optimize CI testing

### ISSUE THREAD

**Issue by Jelenkee** [PRQL/prql#2310]
### What's up?

I noticed on a pull request more test run than necessary.
For example `test-rust (ubuntu-latest)` is started [here](https://github.com/PRQL/prql/blob/378bd0bed0e87f7f271f8397fd4ce79fa7aa6d63/.github/workflows/test-all.yaml#L28) and [here](https://github.com/PRQL/prql/blob/378bd0bed0e87f7f271f8397fd4ce79fa7aa6d63/.github/workflows/pull-request.yaml#L28) when a pull request is opened for the main branch.
Additionally the tests for the all bindings run even when only changes on the compiler were made. I don't see a reason for that.

(Actually it is not my concern since you pay the github bills :wink: )

**Comment by max-sixty** [comment]
I added a brief mention here, probably not clear enough: https://github.com/PRQL/prql/blob/0ae2a44ce31c59a2b38c16fdba78fa1838c1a3b2/.github/workflows/pull-request.yaml#L31

We could remove this, and I think I've worked out the cache thing separately. But this test is very cheap — just a few minutes — so not really worth the maintenance burden of ensuring the caches are named the same.

> (Actually it is not my concern since you pay the github bills 😉 )

Actually GitHub pay! So we should be good citizens. But I think this is reasonable.

---



> Additionally the tests for the all bindings run even when only changes on the compiler were made. I don't see a reason for that.

Only in specific circumstances: https://github.com/PRQL/prql/blob/0ae2a44ce31c59a2b38c16fdba78fa1838c1a3b2/.github/workflows/pull-request.yaml#L39-L43 & https://github.com/PRQL/prql/blob/8bac2d1fabf81686a6722cd38829a29493674234/.github/workflows/test-all.yaml#L3-L15

---

Feel free to ask any more questions here, or we can close if there's no big issues to follow-up on
