### ISSUE TITLE
Problem with parsing s-string in `from`?

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#2430]
### What happened?

```elm
let _tab0 = s"""
  SELECT foo
  FROM bar
"""

from _tab0
```

The above PRQL is processed successfully, but the following PRQL with added newlines seems to cause an error.

### PRQL input

```elm
let _tab0 = s"""
  SELECT
    foo
  FROM bar
"""

from _tab0
```

### SQL output

```SQL
None
```

### Expected SQL output

```SQL
WITH table_0 AS (
  SELECT
    foo
  FROM
    bar
),
_tab0 AS (
  SELECT
    *
  FROM
    table_0 AS table_1
)
SELECT
  *
FROM
  _tab0
```

### MVCE confirmation

- [x] Minimal example
- [x] New issue

**Comment by max-sixty** [comment]
A short-term fix would be to just remove newlines when checking the s-string for `SELECT foo`. (Longer term it would be great to remove this restriction)
