### ISSUE TITLE
Problem with `take` with MsSQL

### ISSUE THREAD

**Issue by Jelenkee** [PRQL/prql#2448]
### What happened?

The generated SQL does not work for 3 reasons
* The keyword `ROWS` is missing after `OFFSET n`
* `OFFSET` and `TOP` cannot be used together
* `OFFSET` only works with `ORDER BY`
    - probably in the responsibility of the developer since offset does not make much sense without sorting

A way to fix this may be to replace `TOP` with `FETCH` ([link](https://www.sqlservertutorial.net/sql-server-basics/sql-server-offset-fetch/))

related to #1854

### PRQL input

```elm
prql target:sql.mssql

from tracks
take 3..5
```

### SQL output

```SQL
SELECT
  TOP (3) *
FROM
  tracks OFFSET 2
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
Also related to https://github.com/PRQL/prql/issues/2506

**Comment by max-sixty** [comment]
I think `FETCH` does seem like a better fit than `TOP`...
