### ISSUE TITLE
prql-python arm64 linux wheel

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#2457]
### What's up?

Currently prql-python is not available via PyPI for arm64 Linux.

It would be great if we could also do binary releases for arm64 by setting up a workflow like python-polars.
https://github.com/pola-rs/polars/blob/main/.github/workflows/create-python-release.yml

**Comment by max-sixty** [comment]
Interesting — thanks @eitsupi . 

So at the moment, does installing pyprql for `aarch64` / `arm64` (I get confused by the differences...) just fail?

What's the best version to copy? I also notice https://github.com/messense/crfs-rs/blob/main/.github/workflows/Python.yml is linked from the [maturin-action](https://github.com/PyO3/maturin-action/tree/v1) page, and looks simpler than the polars one (maybe polars has lots of features given its complexity?). WDYT?

**Comment by eitsupi** [comment]
> So at the moment, does installing pyprql for `aarch64` / `arm64` (I get confused by the differences...) just fail?

The last source release seems to be version 0.2.9.

```sh
$ pip install prql-python
Collecting prql-python
  Downloading prql_python-0.2.9.tar.gz (574 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 574.8/574.8 kB 5.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

> What's the best version to copy? I also notice [messense/crfs-rs@`main`/.github/workflows/Python.yml](https://github.com/messense/crfs-rs/blob/main/.github/workflows/Python.yml?rgh-link-date=2023-04-17T20%3A45%3A37Z) is linked from the [maturin-action](https://github.com/PyO3/maturin-action/tree/v1?rgh-link-date=2023-04-17T20%3A45%3A37Z) page, and looks simpler than the polars one (maybe polars has lots of features given its complexity?). WDYT?

Sorry, but I don't understand what you mean by "the best version".

I haven't looked at it in detail as I don't have the bandwidth to work on this right now anyway, but it looked like basically just switching the target.

**Comment by max-sixty** [comment]
> The last source release seems to be version 0.2.9.

Interesting — thanks
 
> Sorry, but I don't understand what you mean by "the best version".
> 
> I haven't looked at it in detail as I don't have the bandwidth to work on this right now anyway, but it looked like basically just switching the target.

Sorry, I was asking whether we should take the workflow that you'd posted and copy that. 

Ofc no problem if you don't know, we should just be clear on what we do know for these Good First Issues, so someone without context doesn't go and do the wrong thing. In the polars workflows there's lots of extra things like the "Set swap space" task, etc. In some of the others, it's simpler.

Is it right to say "this would be a useful goal but we're not sure exactly how to best complete it at the moment"?

**Comment by eitsupi** [comment]
In short, I don't know.

I really don't know as I have no experience working on python package.
Please look into it and give it some trial and error.

**Comment by eitsupi** [comment]
I definitely misunderstood the criteria for good first issue.

I don't think this is a problem that can be solved by a complete newbie who has never used GitHub. So I removed the label. My apologies.

**Comment by max-sixty** [comment]
No problem! It doesn't have to be for a complete newbie — I do them occasionally! — the important criteria is that the context is explicit and self-contained.

So this could be a good one, I just wanted to ensure we were clear on what we knew atm...
