### ISSUE TITLE
Reference to the current pipeline

### ISSUE THREAD

**Issue by aljazerzen** [PRQL/prql#247]
## Problem 

So when writing PRQL, at each line you have access to scope of columns, some of which belong to actual tables, some are aliases and some are columns of CTEs. The problem is that you cannot reference the latter!

See the example:

```
from salaries
aggregate by:[emp_no] [
  emp_salary: average salary
]
join dept_emp [dept_emp.emp_no = emp_no]
```

produces:
```
WITH table_0 AS (
  SELECT
    emp_no,
    AVG(salary) AS emp_salary
  FROM
    salaries
  GROUP BY
    emp_no
),
table_1 AS (
  SELECT
    *
  FROM
    table_0
    JOIN dept_emp ON dept_emp.emp_no = emp_no
)
SELECT
  *
FROM
  table_1
```

Executing this query in PG returns:
```
ERROR:  column reference "emp_no" is ambiguous
LINE 15:     JOIN dept_emp ON dept_emp.emp_no = emp_no
                                                ^
```

`emp_no` could reference `table_0.emp_no` or `dept_emp.emp_no`. We want to reference `table_0`, which we currently can, if we use:

    join dept_emp [dept_emp.emp_no = table_0.emp_no]

but this is an inconsistent hack, that will not work once we prefix the query with some other pipelines or aggregation.

## Proposal

Instead I propose that we introduce `$`, a table reference that points to the *last CTE*. In the query would be:

```
join dept_emp [dept_emp.emp_no = $.emp_no]
```

Alternatively, we could just use `.emp_no`, but I am against that, because it is not explicit enough.

**Comment by max-sixty** [comment]
Yes, I agree the current state isn't good.

I think we should try and do as much as possible here ourselves without asking the user to think about it. 

In this specific example adding `table_0` to the side that isn't specified would work. (We could also encourage using `USING`, but that wouldn't work for non-inner joins).

Are there cases which that approach wouldn't cover?

**Comment by aljazerzen** [comment]
@max-sixty  `USING` does not work for inner joins? Are you sure? #231

**Comment by max-sixty** [comment]
> @max-sixty `USING` does not work for inner joins? Are you sure? #231

"non-inner joins" :)

**Comment by aljazerzen** [comment]
But yes, there are still cases not covered. 

```
 table: company         
---------------------
 id            
 name


 table: user         
---------------------
 username            
 company_id           


select * from user join company using(id); 
-- ERROR: column "id" specified in USING clause does not exist in left table

select * from user join company using(company_id); 
-- ERROR: column "company_id" specified in USING clause does not exist in left table
```

**Comment by max-sixty** [comment]
Right right — my question is whether this approach would cover these problems, without the user having to specify `$`. i.e. could we fix these ourselves. WDYT?

> In this specific example adding `table_0` to the side that _isn't_ specified would work.

**Comment by aljazerzen** [comment]
@max-sixty Can you tell me, how hard would it be to do 2.? You don't have to read all this, but it should be here for any future recourse.

Ok, deal with the worst case scenario:

We want to produce this sql:
```
WITH table_0 (...) 
SELECT * 
FROM table_0 
JOIN user ON user.company = table_0.id
```

When user is writing this query:
```
from company | take 10 | join user [?]
```
and comes to the `?`, what they want is to write "*the foreign key that connects the new table and the table from before*". This would be `user.company_id` that references `company.id`, but `company` is out of scope and only `id` may be ambiguous because it may exist on `user` table.

As I see it, we have following options to fix this:


### 1. Identifiers without table names default to last CTE (we prepend them appropriate `table_x.`)
 
```
> from company | take 10 | join user [user.company_id = id]
< 
```

This would be the simplest option, but it breaks the case of: `join user [company_id = id]` where only `user` has `company_id` and only `company` has `id`. Here, both `company_id` and `id` would be compiled to `table_0.company_id` and `table_0.id`.

I would avoid this, because it works very differently than SQL and can be confusing.


### 2. Table names follow trough pipelines

```
> from company | take 10 | join user [user.company_id = company.id]
< WITH table_0 (...) SELECT FROM table_0 JOIN user ON user.company = table_0.id
```

So here, you can reference original table name later in the pipeline, even though it is actually not in scope anymore. For this to be possible, we would have to take care when breaking pipeline into atomic pipelines and substitute table references with their new CTE names.

This one would be the most intuitive, but may not be easy to implement.


### 3. We introduce identifier that references last CTO

```
> from company | take 10 | join user [user.company_id = $.id]
< WITH table_0 (...) SELECT FROM table_0 JOIN user ON user.company = table_0.id
```

This one is different from current SQL conventions, but is used in [some other libraries](https://rdatatable.gitlab.io/data.table/articles/datatable-sd-usage.html). If we want to keep PRQL simple, this may not be the solution.
Also I am not sure hard would it be to implement this.

---

All in all, I really don't like 1) and would go with 2) if possible. Otherwise 3).

**Comment by max-sixty** [comment]
I completely agree. I _think_ (2) should be possible. I would be up for trying!

I will think more about how to do this without rewriting everything :). 

As a worst case, there's an alternative approach I considered when writing `translator.rs`, which is more imperative, but I think would cover this case:

- Currently: we do a scan over the whole AST and decide where to break into atomic pipelines. Then we take those atomic pipelines and build them, independently of each other.
- A different approach: we go transformation-by-transformation (more like an interpreted language) and a) decide whether to break a new pipeline and b) do the SQL translation, before moving to the next transformation. If we did this, we could keep a mapping of "PRQL table name" -> "SQL CTE name"
- Then when we get to `join user [user.company=company.id]`, we can look at the mapping, and see that `company` was in `table_0`, and update the AST.
- NB: if someone writes `from company | take 10 | join user [company=id]` and there's only one `id` field, this is fine already (assuming there's only one `id` column, but otherwise it's an always an error) — we only have to track the original table if the table is explicitly specified.

There may be closer approaches, and I may be missing something, let me know if you have thoughts. Thank you.

**Comment by aljazerzen** [comment]
About the last point: yes, I they don't specify the table this would my 1st case, where adding table names can break queries. In such case, user is responsible for specifying enough to avoid ambiguity. 

I like the current approach because it separates difficult problems of splitting the pipelines and translating an atomic pipeline. So even if we keep current implementation, we could build a map of "how the tables have been renamed" which would in this case contain "{ company: table_0 }". This would be built during pipelines splitting and used in translating, where one would have to parse all identifiers and do a lookup in the map.

**Comment by max-sixty** [comment]
Yes, I think that would be possible. I can take a go at it later.

**Comment by aljazerzen** [comment]
Just posting a test that also has to be working for when we start working on this:

```prql
from employees
aggregate by:[emp_no] [
    average salary,
    sum     salary,
    average gross_salary,
    sum     gross_salary,
    average gross_cost,
    sum_gross_cost: sum gross_cost,
    ct: count *, 
    # basically a lot of columns
]
join side:left titles [emp_no]
select [
   employees.*,     # take all of the previous columns
   titles.title     # and add this one column from the new table
]
```
