### ISSUE TITLE
FYI re default commit message

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2470]
### What's up?

FYI I've updated the default commit message to _only_ include the PR title. We had previously changed from "pull request title and commit details" to "pull request title and description", as discussed with @eitsupi .

But often the description is just the initial message — folks don't seem to be updating it after making changes to a PR. It often includes @-s, and I know @aljazerzen is less keen on being pinged every time that commit happens to be included somewhere :). For bot updates like dependabot, it contains a whole HTML page.

So this defaults to just one line, with a link to the full PR. Folks can add in more details if they like

<img width="281" alt="image" src="https://user-images.githubusercontent.com/5635139/232603503-492accbc-1c0c-4ddb-9939-d9907facc264.png">

**Comment by aljazerzen** [comment]
Yet I was pinged here! How inconsiderate! ;)
