### ISSUE TITLE
Docs: How to understand/describe the stdlib notation?

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#2477]
### What's up?

 In #2057, @max-sixty used some lingo about function signatures (which makes sense). I see the same kind of notation on the [stdlib](https://prql-lang.org/book/language-features/standard-library/index.html) page, but I don't really understand what the descriptions mean.

I kinda can read them: `func min <scalar || column> column -> null` means that the `min` function takes either a scalar or a column name. But then... what? It returns a column? And what's the skinny-arrow to "null"?

My request: to include a secret keyring decoder that describes this notation the PRQL std functions page. Thanks.

**Comment by aljazerzen** [comment]
Ughh, this a good indication that our syntax for function definition is not obvious.

`<scalar || column> column` is saying "parameter column of type `scalar || column`"
`->` means "maps to"
`null` is the function body, because we don't have a syntax that would say "internal compiler code"

**Comment by richb-hanover** [comment]
This is not a serious problem, just a documentation issue... (I am delighted that the Book includes all the `std` functions, straight from the source code. When a new std function arrives, it automatically gets documented.) We just need to include a description of how to read this notation. 

I'm happy to write something up, but need a Cliff Notes to get me started. NB: I wouldn't be this verbose for each function definition - just selected examples to explain each different bit of syntax.

* From what you wrote above, I think I would write this explanation. 
   > `func min <scalar || column> column -> null`
   > The `min` function takes a parameter that can be either a `scalar` or `column name` and returns a value of another `column name` (the second instance of the word `column`). The `-> null` means that `min` calls internal compiler code to perform this.

   Is this correct?

There are other bits of syntax that I don't understand:

* In `func first<column> offset column -> null`,
   * Why are `first` and `<column>` not separated by a space? What does that signify?
   *  I think I'd write:
      > The `first` function takes a parameter of a column and an (integer) offset and calls internal compiler code to return a column 

   Is this correct?
* In `func round<scalar> n_digits column -> null`
   * Same question about space between `round` and `<scalar>`
   * I think I'd write:
      > The `round` function takes a scalar parameter and calls an internal function to return a column.

   Is this correct?
* In ``func from<table> `default_db.source`<table> -> null`` 
   * Same question about space between `from` and `<table>`
   * I'm not sure about the rest of the syntax
* In this definition:
   ```
   func intersect<table> `default_db.bottom`<table> top<table> -> (
    from t = _param.top
    join b = _param.bottom (all (map _eq (zip t.* b.*)))
    select t.*
   )
   ```
   * Same question about space between `intersect` and `<table>`
   * I'm also not sure about the parameters
   * I think this calls the (Rust?) code between the ` -> ( ... )`
   * Is this correct?

Thanks.

**Comment by aljazerzen** [comment]
I see that the syntax is really non-obvious, based on the fact that I got confused and what I told you is wrong. :D

First of all, this part of the grammar is whitespace insensitive, which means that `from<table>` and `from <table>` are equivalent.

This is an example of the func definition. I'm using excessive whitespace to make it more clearer.
```
func my_func <return_type>   param1 <type_of_param1>   param2 <type_of_param2>  -> body_expr  
```

To make it more obvious, maybe we should declare the ideomatic way not to contain spaces ni `my_func <return_type>` and `param1 <type_of_param1>`. Also, it may be much more clearer if allowed params to be on their own lines.

I hope this answers most of your questions about the examples.

About the last one: it does not call Rust, this is all plain PRQL.

**Comment by richb-hanover** [comment]
Ahah! Thanks for the clarifications. 

1. Let's **not** make any changes to the `std.prql` file for the time being. (The current definitions a) _work_ and b) are compact.)
2. Let me take a stab at descriptions (later this weekend) to see if I can get it right

Thanks.

**Comment by richb-hanover** [comment]
Here's my updated suggestion (incorporating @aljazerzen comments)
Place this commentary at the top of _std.prql_:

```
# The PRQL standard library defines the following functions and transforms. 
# The definitions are whitespace insensitive, and have this form:
# 
# func my_func <return_type> param1 param2 ...  -> body_expr  
# where:
#   * my_func is the name of the function
#   * <return_type> is the type of result wrapped in "< ... >"
#   * param1 is the first parameter optionally followed by a type in "< ... >"   
#   * param2 etc. follow the same pattern as param1
#   * -> body_expr defines the function body that creates the result.
#     It can be PRQL code or "null" to indicate internal compiler code 
#
# Aggregate functions
# These return either a scalar when used within `aggregate`, or a column when used anywhere else. 
func min <scalar || column> column -> null
func max <scalar || column> column -> null
...
```
~~Is this correct? (Especially that last bit about aggregate function return types?) Thanks.~~ (see comments below)

**Comment by aljazerzen** [comment]
Yes, this is correct. I'd add that optional `< ... >` come after `param1`, and change up the aggregation functions the be more general:
```
# Aggregate functions
# These return either a scalar when used within `aggregate`, or a column when used anywhere else. 
```

**Comment by richb-hanover** [comment]
I'll make a PR of this
