### ISSUE TITLE
Right shift operator '>>' in s-string is broken by PRQL by white space insertion.

### ISSUE THREAD

**Issue by cottrell** [PRQL/prql#2487]
### What happened?

Minor but critical problem. Maybe there is some clever escape/workaround?

### PRQL input

```elm
from invoices
derive [
  A = s"invoice_id >> 1"
]
```

### SQL output

```SQL
SELECT
  *,
  invoice_id > > 1 AS "A"
FROM
  invoices

-- Generated by PRQL compiler version:0.8.0 (https://prql-lang.org)
```

### Expected SQL output

```SQL
SELECT
  *,
  invoice_id >> 1 AS "A"
FROM
  invoices

-- Generated by PRQL compiler version:0.8.0 (https://prql-lang.org)
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by cottrell** [comment]
Workaround is to use basic math expressions and '%' (which works in prql s-strings).

**Comment by eitsupi** [comment]
Thanks, but I think it is duplicate of #1284
