### ISSUE TITLE
Can't reference `date` within a function on a relation

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2503]
### What happened?

(Not 100% sure this is a bug, it might be user error!)

I'm not sure there's a way of selecting `date` within a function over a relation, because of a combination of https://github.com/PRQL/prql/issues/2155 and how we resolve idents.

Here's a function which takes a relation, and selects the date column:

### PRQL input

```elm
func f tbl -> (
  tbl
  select tbl.date
  # alternatively `select dt` works, but `select date` gets #2155-ed
  # `select _frame.date` does work!
)

from foo
f
```

### SQL output

```SQL
Error: 
   ╭─[:3:10]
   │
 3 │   select tbl.date
   │          ────┬───  
   │              ╰───── Unknown name tbl.date
───╯
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

### Anything else?

I think the underlying issue is that:
- We don't have a namespace for `tbl`
- So we can only get it from `_frame`. Which works for `dt`, but not `date`
- But if we just have `date`, then it defers to the type name ahead of `_frame`

Obv having `_frame.date` is not viable as anything more than a workaround. So I'm not sure how to solve this — should `tbl` have a namespace?

**Comment by aljazerzen** [comment]
There is a workaround here:

```
func noop a -> a

func f tbl -> (
  noop my_name = tbl
  select my_name.date
)

from foo
f
```

To assign `tbl` to a namespace, you need a function call. This function call can be anything. So let's use `noop` function.

(`from` would work if it didn't automatically resolve from `default_db` module).

We could improve this by allowing assigns in a pipeline? Like so:
```elm
func f tbl -> (
  my_name = tbl
  select my_name.date
)
```
... but I'm not sure if I like this.

**Comment by aljazerzen** [comment]
Because of how I changed parsing for unrelated reasons, this now works:

```
func f tbl -> (
  t = tbl
  select t.date
)

from foo
f
```
