### ISSUE TITLE
Reduce MSSQL support?

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2506]
### What's up?

(This will probably fall into the broader discussions we're having re finding PRQL's short-term focus. This provides a case of where giving up some guarantees would allow us to move faster on the margin)

MSSQL is the most difficult to support dialect:
- Doesn't support `USING`, which would give us natural joins #723 (I'm a big supporter of these, but actually I'm not sure everyone is?)
- Doesn't have any regex operator, re https://github.com/PRQL/prql/pull/2458
- Has issues such as https://github.com/PRQL/prql/issues/2448

Now we have the integration tests — which are really excellent — we either need to make lots of small examples so we can test "around" MSSQL, or just exclude it from any example with the regex operator.

I'm also not sure how popular it is? (Though FWIW have had positive experiences with it!)

Re the wider discussions — one option between "only support DuckDB" and "support everything" is we have tiers [like we do for Bindings](https://prql-lang.org/book/bindings/index.html). We'd run integration tests on only the Supported ones, and the others would be best-effort, and MSSQL would drop down.

**Comment by eitsupi** [comment]
I think it makes sense to exclude MSSQL support for now, as there is a possibility that the conversion to the MSSQL dialect could be left to other software.

**Comment by aljazerzen** [comment]
Yup, I agree. If we don't test it, we cannot support it to the same level we support other dialects.
