### ISSUE TITLE
Remove `web` branch

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2527]
### What's up?

I think having a `web` branch that tracks "latest release + web changes" was a potentially worthwhile — but ultimately unsuccessful experiment.

I hadn't wanted to remove it, because we did come to a decision in https://github.com/PRQL/prql/issues/1507 to try this out, and lots of folks did a decent amount of work to implement it. And most of the downside was having to do that work, rather than the future maintenance burden.

But today I spent a couple of hours trying to figure out https://github.com/PRQL/prql/issues/2518, which would have been more attributable if we deployed from `main`. Ironically, the reason I'd released was to silence the "backport to `web` failed" errors, which required manual merging. 

So on net, I don't think it's worth keeping any longer, and we should instead just publish from `main`.

We can get many of the benefits from releasing more frequently — it's now fairly easy to release, and we've had a consistent schedule of every couple of weeks.

To keep it, I think we'd need one of:
- @aljazerzen having a strong view that I should continue allocating time to this
- Someone offering to own it, and doing things like fixing the issues above

**Comment by aljazerzen** [comment]
I don't have a strong view that you should continue spending time on this.

But there is a third option: we can decrease amount of PRs that we backport and backport only serious bugs on the website. That would decrease potential "failed to backport to web" errors and also decrease surface for things breaking.

**Comment by max-sixty** [comment]
> But there is a third option: we can decrease amount of PRs that we backport and backport only serious bugs on the website. That would decrease potential "failed to backport to web" errors and also decrease surface for things breaking.

I agree this would reduce the time we spend fixing merge failures. Though OTOH we're more likely to get merge failures when we do want to backport (I'm actually surprised how often we get merge failures already), and we're _less_ likely to spot mistakes early — the case yesterday was when we didn't backport a dependency update. 

I continue reflecting and won't do the work to dismantle this quite yet

**Comment by richb-hanover** [comment]
+1

> So on net, I don't think it's worth keeping any longer, and we should instead just publish from main.

IIRC, we were concerned that the web documentation didn't match the code deployed to the playground. So we introduced the `web` branch to have a "stable" branch, while letting `main` run with whatever seemed like a good idea. This led to the need to backport certain fixes, and the problems that @max-sixty describes.

Personally, I think that strategy is overly conservative. As long as we keep the CHANGELOG up to date, people who are using PRQL can "keep up". Longer term, as the project matures, we can pick a time to present separate "stable" and "development" versions to the world. But until we stop writing for "the intrepid", we can simply document what what we have in-flight. It'll be good enough. (And we will have freed the core maintainers from a lot of overhead work that doesn't drive the project forward.)

**Comment by max-sixty** [comment]
FWIW this has actually been pretty useful in the run-up to `0.9.0` — otherwise the book would be radically different given all the syntax changes!

I think ideally we would be able to select versions — probably there's no single approach which works for everyone short of that. And I'm not sure there's a cookiecutter way of doing it, without something like ReadTheDocs (which probably doesn't support mdbook) — suggestions very welcome.

**Comment by eitsupi** [comment]
One of my questions is whether I need to continue using mdBook.
For example, I think some of the Hugo themes implement version switching. (I'm not familiar with them)

(My preference is Docusaurus, but I don't know if there is a way to apply PRQL syntax highlighting, and if it is possible to display PRQL and SQL side by side as we currently do.)

**Comment by max-sixty** [comment]
Briefly on mdbook (we can open a new issue if we continue discussing)

We don't have to stay on mdbook, and it does look like it's lost some development energy unfortunately.

But I think it would be quite a project to shift to something else — we have some code which is somewhat coupled. It's actually much less than it used to be — we've been moving tests from the book to the documentation tests, but it's still there. It's also convenient to have it in rust; though python etc would be OK too.

**Comment by eitsupi** [comment]
If we move to another generator, I think we need to write a preprocessor in Rust that will generate the md files for the generator from the source md files (almost the same md files that currently exist).
I don't think the document tests will be affected.

This means that the documentation for the development version will be generated from the same tested md files as now.

```mermaid
stateDiagram-v2
  md_source --> md_generated(git_ignored): preprocessor
  md_generated(git_ignored) --> html(git_ignored): site generator
```

Documentation for past versions is generated from previously generated md files (committed as part of the release process).

```mermaid
stateDiagram-v2
  md_generated --> html(git_ignored): site generator
```

**Comment by max-sixty** [comment]
Ah yes that could work very well, I agree. That would be good.

ReadTheDocs (which we use with xarray) actually checks out an old version of your code and runs that. Though only on request — otherwise it saves files, like the proposed design (though not in the repo)

(also those diagrams are so cool!)

**Comment by aljazerzen** [comment]
Does md_generated contain the generated SQL?

---

I've looked into having multiple versions of the docs (and maybe Playground). It is possible and actually quite simple, but a bit brittle: when we build a new version of the book or playground, we don't overwrite the whole pg-pages-branch, but just add the built sites into another subfolder:

```
- index.html (this is the website)
- book/
  - 0.8/
    - index.html (this is 0.8 version of the book)
    - ...
  - 0.9/
    - index.html (this is 0.9 version of the book)
    - ...
```

Then we'd only need a selector for the versions on the website somewhere.

**Comment by max-sixty** [comment]
Yeah — I do worry about adding A Small Thing™ that we maintain ourselves, rather than using a pre-existing library which does what @eitsupi describes, if it exists (or something like RTD).

If there's no external solution then we can consider doing it ourselves. But I think our track-record is very impressive for efficiently getting the thing started — and then not so great for cheaply maintaining it — the `web` branch is one example of that...

**Comment by eitsupi** [comment]
> Does md_generated contain the generated SQL?

Yes. For example, in Docusaurus, I think the article and sidebar source is saved with each version, and the HTML is generated by the latest generator.
https://docusaurus.io/docs/versioning

**Comment by richb-hanover** [comment]
I'm going to express a contrarian viewpoint. (Especially since advocated the opposite view a few weeks ago.)

It feels to me that the `web` branch has served us well in the run-up to 0.9.0. We have been able to make significant changes to the `main` branch (while striving to get the docs to match), all while preserving the correctness / accuracy of the published Book, Playground, site.

From this, I draw two impressions:

- I think `web` branch has value since it insulates newcomers from the churn of the day-to-day development.
- I would not advocate seeking another documentation tool. I don't entirely understand the benefit that might come from it. That said, the effort to make the conversion, and to create that "Small Thing™" (and likely, the other "small thing", and its companion...) to address our specific desires (side-by-side code examples, etc.) will come out of the hide of the core development team, slowing the overall progress of the project.

Put more broadly, I don't think our documentation is holding up progress on PRQL. If I understood earlier conversations, our desire for broader awareness and acceptance hinge on finding a "killer integration" between PRQL and some other tool. 

Thanks for listening.

**Comment by eitsupi** [comment]
> (My preference is Docusaurus, but I don't know if there is a way to apply PRQL syntax highlighting, and if it is possible to display PRQL and SQL side by side as we currently do.)

After a little research and testing, these seem feasible. I will try to create a preprocessor for Docusaurus in another repository.

**Comment by max-sixty** [comment]
Of course fine to test, and also would be fine if you wanted this as a big project — but I would caution us against taking on a project to change our docs infrastructure as a team — the current docs infrastructure is OK, and changing it would be a lot of work. 

To the extent there's a tradeoff with things like [finishing off 0.9](https://github.com/PRQL/prql/milestone/5), fixing bugs in the compiler[^1], or improving error messages, they would be much higher prioritization from my POV. 

(There's also thinking about what we can do to make it easy to use PRQL — but that is also a big project!)

There isn't always a tradeoff — folks want to work on what they want to work on! So I'd still welcome this if it's something that folks really want to do. I hope that's reasonable.

[^1]: this is difficult technically, and we've struggled to expand who can do this work, but possibly now it's more modular, folks could become more familiar with a single area.

**Comment by eitsupi** [comment]
> Of course fine to test, and also would be fine if you wanted this as a big project — but I would caution us against taking on a project to change our docs infrastructure as a team — the current docs infrastructure is OK, and changing it would be a lot of work.
> 
> To the extent there's a tradeoff with things like [finishing off 0.9](https://github.com/PRQL/prql/milestone/5), fixing bugs in the compiler[1](#user-content-fn-1-735f549598e8e2e23fd317d346d221cb), or improving error messages, they would be much higher prioritization from my POV.

That makes sense.
I am only interested in this approach and do not expect to replace the document anytime soon.

I have searched and found several Rust programs for evaluating code blocks embedded in documents, so I will just try Markdown replacements with them for study purposes.
https://github.com/facebook/hhvm/blob/9f46b4dee8d5eddfd732f0e44b6d97559889dc8b/hphp/hack/src/hh_manual/src/main.rs
https://github.com/influxdata/flux/blob/d8995bbfb3ad23bbd166a4daaea7a5d9e967dce6/libflux/flux-core/src/doc/example.rs
https://github.com/casey/just/blob/bba673fd791fa08aac95cf263141a4c69162681b/bin/generate-book/src/main.rs

**Comment by max-sixty** [comment]
On reflection, this was quite helpful in the run-up to 0.9, given how different 0.9 was. And it's now a single label to both backport & merge, so the overhead is even lower than it was.

So I'll close this (though maybe not permanently...)
