### ISSUE TITLE
Query starts with "from `starwars.csv`" is not working

### ISSUE THREAD

**Issue by alexhallam** [PRQL/prql#2554]
### What happened?

I was expecting to pass the output of `prsqlc` to duckdb. 

```sh
prqlc compile prql_query.sql | duckdb
```

I can for example have the following sql file

```sql
SELECT
  *
FROM
  read_csv_auto('starwars.csv', header = True)
WHERE
  name = 'Luke Skywalker'
```

and get a `duckdb` output with

```sh
cat prql_query_correct.sql | duckdb 
```

### PRQL input

```elm
from `starwars.csv`
filter name == 'Luke Skywalker'
```

### SQL output

```SQL
SELECT
  *
FROM
  starwars.csv
WHERE
  name = 'Luke Skywalker'

-- Generated by PRQL compiler version:0.8.0 (https://prql-lang.org)
```

### Expected SQL output

```SQL
SELECT
  *
FROM
  read_csv_auto('starwars.csv', header = True)
WHERE
  name = 'Luke Skywalker'

-- Generated by PRQL compiler version:0.8.0 (https://prql-lang.org)
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by alexhallam** [comment]
Found the solution with

```
from (read_csv 'starwars.csv')
filter name == 'Luke Skywalker'
```

**Comment by max-sixty** [comment]
Yes cheers @alexhallam !

#1535 / #2431 I think might make it possible for us to compile to `FROM 'starwars.csv'`, with the quotes, which IIUC is required. Until then, the `read_csv` & `read_parquet` functions compile to the full form

**Comment by eitsupi** [comment]
The issue title did not seem to match the content, so I changed that.

BTW, compile target can be specified with the recently added `--target` option of `prqlc compile` or `PRQLC_TARGET` env var.
https://github.com/PRQL/prql/blob/667f29e4dbb4f728321507c344171f6a6efc626d/prql-compiler/prqlc/src/cli.rs#L90-L91
