### ISSUE TITLE
On Windows, I can't get out with `ctrl-d` from the input screen opened via `prqlc compile` 

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#2569]
I tried prqlc on PowerShell 7 on Windows Terminal, and I realized that I can't quit from the `prqlc compile` screen.

**Comment by max-sixty** [comment]
Thanks!

Is this just the command that Windows sends with that keybinding? Or is something that `prqlc` can change?

https://stackoverflow.com/questions/976796/can-i-make-python-2-5-exit-on-ctrl-d-in-windows-instead-of-ctrl-z

(maybe either way we should change the docs...)

**Comment by eitsupi** [comment]
Oh, I didn't know ctrl-z would work instead. It certainly seems to work.
I think the documentation needs to be updated.
