### ISSUE TITLE
Playground example on website broken

### ISSUE THREAD

**Issue by MCMaurer** [PRQL/prql#2571]
### What happened?

<img width="593" alt="Screen Shot 2023-05-15 at 12 57 57 PM" src="https://github.com/PRQL/prql/assets/15881370/d79effef-d16b-471b-bd53-2dc72425450a">

Just stumbled upon PRQL (very cool so far), but I noticed the `let-table-0.prql` example in the website's Playground appears to have an error.

### PRQL input

```elm
N/A
```

### SQL output

```SQL
N/A
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by richb-hanover** [comment]
Yup. The filter line should be ` filter name == 'Rock And Roll' || name == 'Hip Hop/Rap'` - the "or" operator was replaced with "||"

It's fixed in  https://github.com/PRQL/prql/pull/2533 but not yet backported to the live website

**Comment by eitsupi** [comment]
Thanks both, I merged a PR to fix this #2576.

**Comment by max-sixty** [comment]
Thanks everyone!
