### ISSUE TITLE
Update CHANGELOG?

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#2595]
### What's up?

In the last few weeks there have been some interesting commits (`let f = x -> ...`, work on modules, others?) that have not yet been backported.

If they're "on the glide path" for a new version, could they be described in the CHANGELOG? That makes it easier for readers to know how to try them out, and for anyone with a bent for documentation to add them to the Book. Thanks.

**Comment by max-sixty** [comment]
Yes, I update the changelog with best-efforts before releasing for important items that didn't have entries. Contributions are very welcome though!

**Comment by richb-hanover** [comment]
To give a reader a leg up on trying out these features, it would help to have the **Unreleased** section mention  any documentation that exists for new features, even before they have been backported. For example, a one-line "hint" like these would help:

* `let f = x -> ...` could link to https://github.com/PRQL/prql/blob/main/web/book/src/queries/functions.md
* `modules` could link to https://github.com/PRQL/prql/blob/main/web/book/src/internals/modules.md (if it has been implemented - I can't tell...)

It would be appropriate for the CHANGELOG to warn that they are only available in development versions / the main branch. Thanks.

**Comment by eitsupi** [comment]
I agree that there is currently a lack of documentation on the new features.

However, note that we can always view the Git commit history.
https://github.com/PRQL/prql/compare/0.8.1...main

**Comment by max-sixty** [comment]
I very much agree @richb-hanover. And we indeed have the Unreleased section. 

But I'm not sure how to manage the process such that it's more up-to-date — if we have a policy of "we won't merge your code without a Changelog" and that causes folks to write less code, that's bad. 

So I will carry this burden unless others are up for doing so. That does mean it'll happen at release time, though...

**Comment by richb-hanover** [comment]
I've been ruminating on this, and decided to make a PR (https://github.com/PRQL/prql/pull/2613) for entries in the CHANGELOG that I think would be helpful for interim (unreleased) features.

I'm certainly in favor of a detailed description of a new feature (like `~=`), but the other one-line descriptions of updated features help newcomers understand the considerable work that's going on behind the scenes. 

It also gives intrepid users a reason to take a chance on the development version over the released version.

I am completely content to be overridden on this (or for my PR to be corrected), but I think this improves the outward appearance of PRQL without too much burden for developers. Thanks for listening.
