### ISSUE TITLE
Release to Windows Package Manager Community Repository (and set CI to release automatically)

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#2599]
Previous Discussions #2043

Thanks to #2578, after the next release, we will be able to register a manifest to https://github.com/microsoft/winget-pkgs and install prqlc.exe via `winget install` command.

Once the initial release on the repo is complete, I believe the followings could be used to send the manifests at release time automatically.
https://github.com/vedantmgoyal2009/winget-releaser
https://github.com/microsoft/winget-create

**Comment by eitsupi** [comment]
(I recently noticed that Task, which are also used in this repository, can be installed via winget.)

```sh
❯ winget search task.task
名前 ID        バージョン ソース
---------------------------------
Task Task.Task 3.24.0     winget
```

https://github.com/microsoft/winget-pkgs/blob/6f8ab54231b14bd1528957bba14e29814c0818fb/manifests/t/Task/Task/3.24.0/Task.Task.installer.yaml

**Comment by eitsupi** [comment]
microsoft/winget-pkgs#113133

**Comment by eitsupi** [comment]
After ~~microsoft/winget-pkgs#113133~~ microsoft/winget-pkgs#114768 is merged, we can use https://github.com/vedantmgoyal2009/winget-releaser to release automatically.

**Comment by vanillajonathan** [comment]
Chocolatey might also be of interest.
https://docs.chocolatey.org/en-us/create/create-packages

**Comment by eitsupi** [comment]
Blocked by #3080

**Comment by eitsupi** [comment]
To automate the release of winget using Komac/winget-releaser, a Personal Access Token must be created and a PR must be created by a GitHub account. (like microsoft/winget-pkgs#112690)
https://github.com/vedantmgoyal2009/winget-releaser#token-token

@max-sixty Do you think it is possible to create a PAT of @prql-bot and store it in the secret of this repository?

**Comment by max-sixty** [comment]
> @max-sixty Do you think it is possible to create a PAT of @prql-bot and store it in the secret of this repository?

Definitely! Lmk if you want me to do anything...
