### ISSUE TITLE
Starting on the parser

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#26]
A couple of people reached out asking whether they could help writing the parser, and potentially there are others who would be interested in contributing.

My plan was to use [nom](https://github.com/Geal/nom), because I'd heard good things, had a good first experience, and it's easy to adapt it if we decide to make it more hand-written or use a PEG grammar.

My initial plan was to try and get some of the initial simple examples parsing. This will be mostly activation energy — it's not the most difficult language to parse. So if we can parse this into an AST, that would be a great success:

```elm
from employees
filter country = "USA"                           # Each line transforms the previous result.
derive [                                         # This adds columns / variables.
  gross_salary: salary + payroll_tax,
  gross_cost:   gross_salary + benefits_cost     # Variables can use other variables.
]           
filter gross_cost > 0
aggregate by:[title, country] [                  # `by` are the columns to group by.
    average salary,                              # These are aggregation calcs run on each group.
    sum     salary,
    average gross_salary,
    sum     gross_salary,
    average gross_cost,
    sum_gross_cost: sum gross_cost,
    count,
]
sort sum_gross_cost
filter count > 200
take 20
```

If anyone wants to have a go, I would suggest:
- Take one function (e.g. `derive`)
- Put a PR in after you have a few lines of code — then people won't do the same thing (though I'm not sure if that will actually be a problem!)
- Don't worry about making it complete (e.g. it'd be fine to start on `derive` only for anonymous columns), add comments where stuff is missing
- Do add a few tests. You can see the very early functions I added have tests

If parts are unclear, please feel free to reply here.

**Comment by iafisher** [comment]
I'm going to take a stab at parsing `aggregate` clauses if that's okay.

**Comment by mormahr** [comment]
I've just written a high level language parser (for FormCalc, including later proprietary extensions) with nom and had performance issues. If my understanding is right, nom is focused on parsing flat formats like network protocols. Implementing deeply recursive grammars with operator precedence doesn't seem to be nom's speciality. I think it's because if a parse is attempted and then discarded because it didn't match, all the work is lost and individual sub parts aren't memoized. Maybe some of this can be worked around, but I decided to switch to an LR(1) parser (I used [LALRPOP](https://github.com/lalrpop/lalrpop)) and optimized lexer ([Logos](https://github.com/maciejhirsz/logos)). The learning curve was a little higher, but the code actually got cleaner and more maintainable. Performance is very good.

Just wanted to share my experience, because it was a bit annoying to rewrite the parser from scratch.

**Comment by max-sixty** [comment]
This is an important decision and is somewhat irreversible in the short term, so thanks for raising it @mormahr . People should feel very comfortable raising concerns now, given it's difficult to do so later. I'm very keen that folks' contributions get the permanence they deserve and we're not thrashing from framework to framework once we're moving.

Re LR(1) vs Parser combinators: I had a couple of conversations with people who have more experience with compilers than me — some thoughts from those:
- Either LR(1) or Parser combinators would _work_, and have sufficient performance, it's mostly a decision based on preference and community interest
- Parser combinators are arguably more flexible, given they're inherently compatible with hand-written recursive descent parsers, and have a higher cap on error message quality.
- Operator precedence can be an performance issue in RD parsers without packrat or pratt parsing. But this isn't a big issue at small scale. And PRQL doesn't expect to have long strings requiring precedence rules. (@mormahr to what extent was this a real issue for you vs a potential future concern?).
- LR(1) parsers are arguably more widespread, and so it might be more popular from a community perspective.
- There's potentially a [People's Front of Judea](https://www.youtube.com/watch?v=WboggjN_G-4&ab_channel=layniann) slant to some of the debates :)

The main libraries seem to be:
- [nom](https://github.com/Geal/nom)
- [pest](https://github.com/pest-parser/pest) ([relevant perf clarification](https://unhandledexpression.com/general/2018/10/04/no-pest-is-not-faster-than-nom.html))
- [lalrpop](https://github.com/lalrpop/lalrpop)

...all of which have significant community following and track record with programming languages.

**Comment by max-sixty** [comment]
As explained in #40, I'm up for switching to a pest-parser, even though it's probably less perfect in the final stage, because of how much easier it seems to be to get going:

> I'm trying out pest given it seems easier to get started with than nom.

> While parser combinators, splitting lexing & parsing, and nom all seem to be a favorite in recent conversations I had, I've got stuck on it a few times. It might be we do the easy thing now, keep things modular, and then in the future we can replace parts if needed.

> Backing up, if the project fails in the next couple of months, it'll be because we didn't get off the ground, or didn't make it easy for the community to contribute — not because the error messages from the parser weren't good enough.

I merged the initial effort in, and I'll try and do some more tomorrow. Others are very welcome to build it out — I think we're fairly close to having the first example parsed, and it's easy to make marginal contributions.

**Comment by DrSensor** [comment]
I highly suggest you use the master branch since the crates.io version got stalled (last update 2020)

Also see https://github.com/pest-parser/pest/issues/491#issuecomment-788182509

**Comment by max-sixty** [comment]
> I highly suggest you use the master branch since the crates.io version got stalled (last update 2020)
> 
> Also see [pest-parser/pest#491 (comment)](https://github.com/pest-parser/pest/issues/491#issuecomment-788182509)

Yes, that's a bit concerning. I checked the library isn't vulnerable to that security vuln with `cargo audit` at least. A downside of being on a git dependency is that we can't publish to cargo...

**Comment by max-sixty** [comment]
FYI I found an extremely nicely designed separate [lexer](https://github.com/Rydgel/monkey-rust/blob/master/lib/lexer/mod.rs) & [parser](https://github.com/Rydgel/monkey-rust/blob/master/lib/parser/mod.rs) in monkey-rust, implemented in nom, by @rydgel.

The parser processes tokens (rather than text) from the lexer, also with nom's combinator approach, which is cool.

But the pest approach is going much faster atm so I don't see a compelling reason to switch away from it atm.

**Comment by DrSensor** [comment]
Any reason why not choose [rust-peg](https://github.com/kevinmehall/rust-peg)?

**Comment by max-sixty** [comment]
> Any reason why not choose [rust-peg](https://github.com/kevinmehall/rust-peg)?

I'm open to it. Does anyone have any experience with it? While pest being quasi-maintained isn't great, there are lots of examples & libraries which use it — which makes fast to get something going

**Comment by max-sixty** [comment]
We're now pretty far on the parser! We can parse all of the first example query, and simple functions (thanks @iafisher !). The material things that remain are:
- [x] Joins
- [ ] More complex functions; e.g. named args
- [ ] Single quotes (small one, fairly easy)
- [ ] Window pipelines, e.g. the one in the second example (edit: I don't think the design here is completely set, but we could add a `window` keyword which operates like `table` and parses the subsequent pipeline)
- [x] Tables / CTEs

And ofc will be a bunch of clean-ups / refinements / corner cases too.

**Comment by max-sixty** [comment]
If anyone wants to take a crack at either of these, that would be great, and are fairly self-contained. The latter would be a nice small first PR:
- More complex functions; e.g. named args
- Single quotes (small one, fairly easy)

**Comment by max-sixty** [comment]
This can be safely closed now! Thanks to everyone's contributions, particularly @aljazerzen
