### ISSUE TITLE
Non-inner joins with idents

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#260]
From https://github.com/max-sixty/prql/pull/259, currently `from employees | join salaries side:left [id]` compiles to `... left join on id`.

It's quite unlikely anyone actually wants to do `on id` — while it's valid SQL, is it ever useful? `full join on true` seems like an awkward way to express a `cross join`.

A couple of options:
- Compile to `select * from employees left join salaries on employees.id = salaries.id`. But we don't always know where the column comes from. We could have a heuristic that it's always from the `from` table? Seems like it would get confusing if someone switches those and things break.
- Raise an error

**Comment by aljazerzen** [comment]
`from employees | join salaries side:left [id]` should compile to `... left join using(id)`

Which is valid and common thing to do.

Example:

table `user` has `user_id`
table `billing_account` has `user_id`
They have one-to-one relation.

Some users don't have billing account, so we want left outer join, to also retrieve users with null billing accounts.

```sql
SELECT * FROM user JOIN billing_account side:left [user_id]
```

**Comment by max-sixty** [comment]
Sorry, I don't know why I made this mistake — I've done `left join using` hundreds if not thousands of times myself. You're correct that it should compile to `left join using(id)`.
