### ISSUE TITLE
Could we reduce the cost of the `prqlc` build?

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2639]
### What's up?

I do think building prqlc artifacts is a good idea — and it's already found one bug. 

But it is more than half the CI capacity of each PR. It also causes the cache to churn a bit more (but I don't think a single run's cache is bigger than our capacity yet, which would cause pathological behavior, so not urgent like that would be). I've noticed PRs take much longer to test when it's busy — e.g. this afternoon — since the queue builds up.

A couple of ideas to reduce the cost:
- Compile in debug rather than release mode for PRs?
- If we do that, share the standard rust cache for that platform, which should mean compiling is almost free, which is almost all the runtime.
- If we don't compile in debug mode, switch to running on `test-all` only, and then we can use the `pr-test-all` label to generate the binaries?

CC @eitsupi (but not super important or urgent, or necessarily your responsibility to solve!)

**Comment by eitsupi** [comment]
Sorry for bothering you.

Currently this job is running for all PRs.
This is the same of the `test-rust` job.

https://github.com/PRQL/prql/blob/d786a8b4969a2f7423cbffe4bffef2bc84b982fa/.github/workflows/pull-request.yaml#L4-L37

In my opinion, there is no need to run these jobs if the prql-compiler source code has not been modified.
How about separating `test-rust` and `build-prqlc` from this workflow and changing condition to run only if the prql-compiler code is changed in the PR?
This would reduce the number of workflows and execution time for small changes such as pre-release chores.

**Comment by max-sixty** [comment]
> How about separating `test-rust` and `build-prqlc` from this workflow and changing condition to run only if the prql-compiler code is changed in the PR?
> This would reduce the number of workflows and execution time for small changes such as pre-release chores.

This would be helpful on the margin, yes. 

Though the majority of PRs do change some rust code, so I don't think it solves everything.

What do you think about the other ideas — e.g. compiling in debug mode & sharing a cache?

**Comment by eitsupi** [comment]
> What do you think about the other ideas — e.g. compiling in debug mode & sharing a cache?

Do you think that means that the build is done by different commands in the releases and PRs?

Perhaps PR should build in debug mode and build-all and release should build in release mode?

**Comment by max-sixty** [comment]
On running only the rust test workflows on rust changes — unfortunately I don't think this is possible:
- If a job is marked as "Required", it's always required, and nothing can merge without it passing.
- We want to have that job be required, so we can click "Enable auto-merge"
- We do some custom work at https://github.com/prql/prql/blob/d0149f720560b4045c270c7240634fe8e9ea612e/.github/workflows/pull-request.yaml#L75 to have some more jobs be Required, but that can only work with labels, not with path changes

I hope that GitHub allows specifying "All _included_ tests are required, but not excluded tests" in the future — that would be much simpler

**Comment by max-sixty** [comment]
> Do you think that means that the build is done by different commands in the releases and PRs?

We can use an input to define whether or not to include `--release` at https://github.com/prql/prql/blob/cbcac20055ffb5d9db046ea797f963572d789cb8/.github/actions/build-prqlc/action.yaml#L42

Here's an example of an `if`-like expression: https://github.com/prql/prql/blob/5db61f45ad31ff5673fdfb7890cc3699d47940f9/.github/workflows/test-rust.yaml#L75

> Perhaps PR should build in debug mode and build-all and release should build in release mode?

Yes, agree on PR & release. 

We can always share the cache, which means we'll only benefit from it without `--release`. So probably `test-all` makes sense without `--release` — we really don't care much about the runtime performance or binary size...

**Comment by max-sixty** [comment]
Closed by #2778
