### ISSUE TITLE
Rename filter to where

### ISSUE THREAD

**Issue by aljazerzen** [PRQL/prql#2642]
### What's up?

Originally posted by @snth in https://github.com/PRQL/prql/issues/2124#issuecomment-1563476607

---

While we're making sweeping changes, what about using `where` instead of `filter`? I know `filter` is the traditional term in the FP world but realistically our target audience are data scientists and analytics engineers who are more likely to be familiar with SQL, pandas and polars and `filter` seems like an unnecessary departure from SQL. pandas and dplyr do use `filter` as well though and while pandas does have `where` it actually does something different. polars and kusto allow both `filter` and `where`. So I'd say it's probably balanced based on familiarity.

Another line of argument is that I've sometimes been a bit confused for a few seconds as to whether `filter` "filters out" rows where the condition is true or filters the dataset to keep only those where the predicate is true. Of course it's the latter but I think `where` makes that inherently clearer.

Also, the `join` example would read better with `where`, i.e. `join a where ==id_1 && ==id_2`.

**Comment by aljazerzen** [comment]
I see your point and I've seen criticism (that I cannot find) of PRQL saying "why change keywords if you don't have to?".

There is also the fact that grammatically, where fits nicely into the pipeline.

But I like filter, because it's a hint to all FP people that this is not a clause, it's a function.

So I'm -1 on this change.

**Comment by max-sixty** [comment]
I agree `where` is much more familiar in SQL. But `filter` is more common outside SQL, so it's not like we're choosing something completely random to be different (`winnow`!)...

One objective point for `filter` — it's a verb, like (I think?) every other transform, whereas `where` is a conjunction.

(But anyone for `winnow`? There may be a PR on April 1...)

**Comment by snth** [comment]
I actually agree. Overnight I also thought of the point about the `filter` being a verb which I think is quite a key one.

I'm of the school of thought that says functions and method names should always start with a verb so it makes sense that transforms should be verbs too.

I'm happy to put this to bed and close this issue.

**Comment by max-sixty** [comment]
OK, closing. T'was a reasonable suggestion!
