### ISSUE TITLE
Release prqlc to Scoop main (or extras) bucket

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#2647]
Same as #2599

prqlc may meet the criteria for registration in the Scoop main bucket (https://github.com/ScoopInstaller/Main).

> - a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
> - the latest stable version of the program
> - the full version i.e. not a trial version
> - a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)
> - a non-GUI tool

https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket

**Comment by sitiom** [comment]
Opened a PR for it:
- https://github.com/ScoopInstaller/Main/pull/5029

**Comment by eitsupi** [comment]
Thanks @sitiom!

![image](https://github.com/PRQL/prql/assets/50911393/9a9e462f-97e1-420b-acb0-7d6e53364723)
