### ISSUE TITLE
ambiguous column references after `join` clause

### ISSUE THREAD

**Issue by YuxiLing** [PRQL/prql#2656]
### What happened?

Dear developers,

Hope this information would be helpful. Here are the details.

prql version: 0.8.1

comments: In some complicated scenarios, with a `filter` caluse after the `join` clause in a prql query, prql compiler uses some ambiguous column references.

In the following example, I inner join `tb1` with `tb2`, and do `sort`, `filter`, and `derive` operations with correct column references. But in the sql query from the compiler, it seems that column references in the outermost `SELECT` and `WHERE` clauses (line 14 and 18) are ambiguous, and columns are selected multiple times (two `*`).

### PRQL input

```elm
from tb1
join side:inner tb2 [tb1.c1 == tb2.c2]
sort [tb1.c3]
filter (tb2.c3 < 100)
derive [new_col = tb1.c0+tb1.c2]
```

### SQL output

```SQL
WITH table_1 AS (
  SELECT
    tb1.*,
    tb2.*
  FROM
    tb1
    JOIN tb2 ON tb1.c1 = tb2.c2
  ORDER BY
    tb1.c3
)
SELECT
  *,
  *,
  c0 + c2 AS new_col
FROM
  table_1 AS table_0
WHERE
  c3 < 100
```

### Expected SQL output

```SQL
WITH table_1 AS (
  SELECT
    tb1.*,
    tb2.*
  FROM
    tb1
    JOIN tb2 ON tb1.c1 = tb2.c2
  ORDER BY
    tb1.c3
)
SELECT
  *,
  tb1.c0 + tb1.c2 AS new_col
FROM
  table_1 AS table_0
WHERE
  tb2.c3 < 100
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
Thanks for the report @YuxiLing , agree this is a bug.

Here's a (very slightly) simpler example:

```elm
from tb1
join tb2 (==c2)
take 5
filter (tb2.c3 < 100)
```

```sql
WITH table_1 AS (
  SELECT
    tb1.*,
    tb2.*
  FROM
    tb1
    JOIN tb2 ON tb1.c2 = tb2.c2
  LIMIT
    5
)
SELECT
  *,
  *
FROM
  table_1 AS table_0
WHERE
  c3 < 100

-- Generated by PRQL compiler version:0.8.1 (https://prql-lang.org)
```

I think the issue is that we can combine the `*` after a CTE.
