### ISSUE TITLE
Release plan for 0.9.0

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2689]
### What's up?

0.9.0 is probably going to be our biggest ever release. It'll include:
- Module system
- Syntax changes — functions, tuples
- `fmt`
- Relation literals
- Regex search
- Integer division
...and so many more items (that would at the top of the release notes of any other release)!

Given @aljazerzen is responsible for the vast majority of these, I'll handle the release.

Questions:
- Are there any code changes that we should add before releasing? Are we at peace over not including `NULLS LAST`?
- Do we want to document the module system? Or we want to let it bake before officially releasing?
- What other docs are missing? I am happy to do these. Are there any features that are under-documented?

**Comment by aljazerzen** [comment]
> Are there any code changes that we should add before releasing? Are we at peace over not including NULLS LAST?

I don't feel strongly about including it or not, I still think this is not a breaking change.

> Do we want to document the module system? 

We can document it, with "Experimental" banner.

> What other docs are missing?

Probably the syntax changes have not been updated in the book. Also regex and integer division.

**Comment by eitsupi** [comment]
I think we should document that "The int div operator and mod operator use _truncated division_".

I'm in favor of introducing `NULLS LAST` now to update the DuckDB version.

**Comment by max-sixty** [comment]
Another thing we should do — update the language grammars for the new syntax

**Comment by max-sixty** [comment]
> I'm in favor of introducing `NULLS LAST` now to update the DuckDB version.

TBC on my perspective:
- I was +0.2 on adopting `NULLS LAST`
- I was -1.5 on adopting `NULLS LAST` _with the expectation to later revert it_

We can continue discussing on https://github.com/PRQL/prql/issues/2622...

**Comment by aljazerzen** [comment]
Well then let's not adapt `NULLS LAST`, because we don't know yet what we'll do with #2622.

**Comment by max-sixty** [comment]
As discussed on the dev call — we'll change the float division in generic to just `/`, and the generic dialect will just be "simple SQL". I'll make the change and add some docs.

**Comment by max-sixty** [comment]
Indentation — I'll put a PR in with 2 and we can decide on what looks best!

**Comment by max-sixty** [comment]
Should this block on https://github.com/PRQL/prql/issues/2717 ?

**Comment by aljazerzen** [comment]
I think so.

**Comment by max-sixty** [comment]
Another blocker: https://github.com/PRQL/prql/issues/2781

**Comment by vanillajonathan** [comment]
> Indentation — I'll put a PR in with 2 and we can decide on what looks best!

I propose 4 spaces!

**Comment by aljazerzen** [comment]
> > Indentation — I'll put a PR in with 2 and we can decide on what looks best!
> 
> I propose 4 spaces!

On the last dev call we talked about this and currently most of us prefer 2 spaces, since it produces much more condensed code. Initially, I also voted for 4 spaces, but was convinced on a [few examples](https://github.com/PRQL/prql/blob/main/prql-compiler/tests/integration/snapshots/integration__fmt%40arithmetic.prql.snap).

**Comment by vanillajonathan** [comment]
> > > Indentation — I'll put a PR in with 2 and we can decide on what looks best!
> > 
> > 
> > I propose 4 spaces!
> 
> On the last dev call we talked about this and currently most of us prefer 2 spaces, since it produces much more condensed code. Initially, I also voted for 4 spaces, but was convinced on a [few examples](https://github.com/PRQL/prql/blob/main/prql-compiler/tests/integration/snapshots/integration__fmt%40arithmetic.prql.snap).

My reason for proposing 4 spaces is that 4 spaces seems to more common than 2 spaces.
https://en.wikipedia.org/wiki/Indentation_(typesetting)#Indentation_in_programming

And I find that it is easier to see at what indention level something is at when there are four spaces, because with only two spaces they can get too close to each other, especially in code with multiple levels of indention and long methods.

**Comment by max-sixty** [comment]
If we want to propose 4 spaces, let's open an issue with examples which show 4 spaces being clearer than 2 — otherwise the discussion is too abstract to make progress.

Let's keep this issue focused on 0.9.0 — I'll minimize these comments if that's OK.

**Comment by eitsupi** [comment]
As I wrote here https://github.com/PRQL/prql/issues/2717#issuecomment-1595937205, how about releasing without waiting for the issue to be resolved?

**Comment by max-sixty** [comment]
> As I wrote here [#2717 (comment)](https://github.com/PRQL/prql/issues/2717#issuecomment-1595937205), how about releasing without waiting for the issue to be resolved?

Sorry for not having addressing this directly

I agree we should try and release 0.9.0 as soon as possible. But I think it would be a bad experience if it's not ready: 
- For me `count s"*"` is quite alien for such a fundamental feature
- The grammars — vscode & the playground especially — are especially important. (Possibly we should add tests to them so we can't change the grammar in future without updating these...)

I do think it's a better project if we "can release at any time", so we should try and make changes somewhat atomically; so, for example, the grammars don't fall out of date with the language. 
But I also think there are some big changes in 0.9.0, so it's more understandable in this instance...

**Comment by eitsupi** [comment]
@max-sixty Thanks for your reply.

Given that `count` is only one of many functions and that there are many queries that do not use `count`, I feel that a release should be made even if only `count` does not work ideally.

As for the grammar, I don't think it is actually part of the PRQL release.
That is, the documentation can be modified later by updating the web branch. prql-vscode can only be released after the release of prql-js.
(That said, I think it's important to update the grammar, so I did as much of that work as I could.)

**Comment by max-sixty** [comment]
> That is, the documentation can be modified later by updating the web branch. prql-vscode can only be released after the release of prql-js.

This is true, yes.

But you don't think it would be confusing for the docs to be different from the version in VS Code? It's not so bad when it's a small change, but this will be _very_ different, and so copying code between the two would be impossible.

> Given that `count` is only one of many functions and that there are many queries that do not use `count`, I feel that a release should be made even if only `count` does not work ideally.

I'm open-minded if others agree — what do folks think?

(I also don't know how much work this would be to fix)

Thanks for pushing on this @eitsupi !

**Comment by eitsupi** [comment]
> But you don't think it would be confusing for the docs to be different from the version in VS Code? It's not so bad when it's a small change, but this will be _very_ different, and so copying code between the two would be impossible.

1. We can work on modifying prql-vscode after prql-js is released. It does not take weeks to complete that work. (By the way I already finished it. PRQL/prql-vscode#244)
2. I don't think broken syntax highlighting would prevent the release of the vscode extension. It is common for syntax highlighting to be broken, and a bug fix can be made later.

**Comment by max-sixty** [comment]
Yes, on reflection, I agree. I was associating the errors in VS Code with the syntax highlighter, but they actually come from the parser...

**Comment by max-sixty** [comment]
Thanks to @eitsupi for all the grammars!

Aside from the `count s"*"`, is there anything else remaining?

Does https://github.com/PRQL/prql/issues/2857 need more work? I see we reopened it? Possibly because of the additional examples in the linked PR??

I can do a pass of the changelog.

**Comment by eitsupi** [comment]
@aljazerzen Any thoughts on this?

**Comment by aljazerzen** [comment]
> Aside from the count s"*", is there anything else remaining?

For the count s"*" we have a plan, it just needs to be implemented.

Apart from that it would be nice to fix the windows overflow, but I don't hold that as a hard requirement.

**Comment by max-sixty** [comment]
@aljazerzen would you want us to release before the `s"*"`? I was thinking we would wait, but not sure how big the work is (and don't want you to feel like there's something hanging on you)

I agree the Windows issue doesn't need to block. I'm still confused by it FWIW!

**Comment by aljazerzen** [comment]
I'd rather wait for s"*", since that is a change to the std module and will be changed again soon. The change should not take too much effort, at most a week.

**Comment by aljazerzen** [comment]
I think we can release. Docs can be updated later on.

**Comment by max-sixty** [comment]
#3051 for post-mortem...
