### ISSUE TITLE
Division operators / s-strings

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2694]
### What's up?

We've recently added an int division operator, and moved some logic from the compiler to s-strings.

Moving logic to s-strings is great – it means when we get an issue "this dialect doesn't work with X", it's really easy for someone to make a contribution.

But it does have a couple downsides — in particular because they're only strings, they don't know about precedence. That means that need to add defensive parentheses per https://github.com/PRQL/prql/pull/2693, meaning we end up with quite an expression (both because of the float coercion and the parentheses, let's just focus on the parentheses here though):

```diff
-  ((temp_c - 32) / 1.8 - 0) / 100 AS boiling_proportion
+  ((temp_c - 32 * 1.0 / (1.8)) - 0 * 1.0 / (100 - 0)) AS boiling_proportion
```

I'm particularly concerned about this with the generic SQL translation that folks first encounter when they're approaching the language — I think it's quite important to signal that PRQL is easy to engage with, inspectable, etc.

One option — **parse the s-string into a SQL AST** with `sqlparser-rs`, replacing the variables with `$`. So

```sql
ROUND(ABS(($l) / ($r)) - 0.5) * SIGN(($l) / $r)
```
...gets parsed into[^1]:

<details>

```json
{
  "BinaryOp": {
    "left": {
      "Function": {
        "name": [
          {
            "value": "ROUND",
            "quote_style": null
          }
        ],
        "args": [
          {
            "Unnamed": {
              "Expr": {
                "BinaryOp": {
                  "left": {
                    "Function": {
                      "name": [
                        {
                          "value": "ABS",
                          "quote_style": null
                        }
                      ],
                      "args": [
                        {
                          "Unnamed": {
                            "Expr": {
                              "BinaryOp": {
                                "left": {
                                  "Nested": {
                                    "Value": {
                                      "Placeholder": "$l"
                                    }
                                  }
                                },
                                "op": "Divide",
                                "right": {
                                  "Nested": {
                                    "Value": {
                                      "Placeholder": "$r"
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      ],
                      "over": null,
                      "distinct": false,
                      "special": false,
                      "order_by": []
                    }
                  },
                  "op": "Minus",
                  "right": {
                    "Value": {
                      "Number": [
                        "0.5",
                        false
                      ]
                    }
                  }
                }
              }
            }
          }
        ],
        "over": null,
        "distinct": false,
        "special": false,
        "order_by": []
      }
    },
    "op": "Multiply",
    "right": {
      "Function": {
        "name": [
          {
            "value": "SIGN",
            "quote_style": null
          }
        ],
        "args": [
          {
            "Unnamed": {
              "Expr": {
                "BinaryOp": {
                  "left": {
                    "Nested": {
                      "Value": {
                        "Placeholder": "$l"
                      }
                    }
                  },
                  "op": "Divide",
                  "right": {
                    "Value": {
                      "Placeholder": "$r"
                    }
                  }
                }
              }
            }
          }
        ],
        "over": null,
        "distinct": false,
        "special": false,
        "order_by": []
      }
    }
  }
}
```

</details>

...and then we can replace the `$l` & `$r` with the arguments. On constructing the SQL, the precedence is handled without parentheses.

The downside of this is that an s-string like `s"{x}_column"` no longer works — `x` needs to be a self-contained expression. (We could have two types of s-string, or two types of variables (e.g. `$` vs `{}`, but then that's more complicated.)

What do folks think?

[^1]: 
    That comes from this rust:
    ```rust
    fn main() {
        use sqlparser::dialect::GenericDialect;
        use sqlparser::parser::Parser;
        let sql = "ROUND(ABS(($l) / ($r)) - 0.5) * SIGN(($l) / $r)";

        let parser = Parser::new(&GenericDialect);
        let mut ast = parser.try_with_sql(sql).unwrap();
        println!(
            "{}",
            serde_json::to_string_pretty(&ast.parse_expr().unwrap()).unwrap()
        );
    }
    ```

**Comment by max-sixty** [comment]
I guess we could retain the old behavior with another variant — say a `j` string (like Jinja) — either with exactly the current s-string semantics, or an actual jinja string.

**Comment by aljazerzen** [comment]
If I understand correctly, what you describe would have following steps:
- compile to SQL, will way too much parenthesis,
- parse with sqlparser-rs,
- traverse AST and remove unneeded parenthesis,
- serialize AST back to SQL. 

I was thinking about another approach. We add support for "format" in s-strings: `s"{l:3} DIV {r:12}"`. In this s-string, param l has "format" 3 and r had format 12. We can discuss what format would be for PRQL (date formatting, wink, wink), but for SQL backend, we can change the behavior to always require a number which represents binding strength.

With this, we can move the whole "optional parenthesis depending on required binding strength" mechanism that we currently have in `gen_expr.rs` into the `std.sql.prql`.

I hope I explained that well enough.

**Comment by max-sixty** [comment]
> If I understand correctly, what you describe would have following steps:

Yes!

> We add support for "format" in s-strings: `s"{l:3} DIV {r:12}"`. In this s-string, param l has "format" 3 and r had format 12. We can discuss what format would be for PRQL (date formatting, wink, wink), but for SQL backend, we can change the behavior to always require a number which represents binding strength.

Format strings would be good, for sure.

What would we use for precedence there? Presumably we don't know the binding strength of the operators used in `r`? What would the upside be over the parsing proposal above — presumably we'd have to parse the expressions anyway to evaluate the precedence?

**Comment by aljazerzen** [comment]
You would have something like this:

```
#[binding_strength(4)]
let add = l r -> s"{l:4} + {r:4}"

#[binding_strength(4)]
let mul = l r -> s"{l:5} * {r:5}"

#[binding_strength(11)]
let mod = l r -> s"FLOOR(MOD({l:0}, {r:0}))"
```

So when we need to translate `(mul (add 1 2) 3)`, `mul` would require `left` to be of binding strength of at least 5, but `add` would be only 4. This would cause parenthesis to be inserted.

But when you have `(mul (mod 1 2) 3)`, `mod` would have binding strength of 11, which is greater than what mul requires, so no parenthesis would be needed.

It is essentially the same algorithm we use now, but using rq-operators (that use syntax of s-strings) instaed of using AST of the sqlparser-rs. 

And this would all be implementation detail of SQL backend, I'm not talking about PRQL language.

**Comment by max-sixty** [comment]
One minor comment — I think we should try and find a different syntax — it means that `#` isn't always a comment, it introduces context to the parser. It's fine in Rust because the comment syntax is different. We could use something like `@` like python, but that also conflicts with date literals. `@[foo]` could work?

**Comment by max-sixty** [comment]
I'm sure I'm being slow, but I'm struggling to understand parts of this.

> So when we need to translate `(mul (add 1 2) 3)`, `mul` would require `left` to be of binding strength of at least 5, but `add` would be only 4. This would cause parenthesis to be inserted.

What's the advantage of having `#[binding_strength(4)]` on `add` over just reading the binding strength of `*` ~from `sqlparser-rs` or~ our code in https://github.com/PRQL/prql/blob/5886a758b66422a1a398dcbad7c7deaa43022b90/prql-compiler/src/sql/gen_expr.rs#L786-L817? That was my proposal above. (Does that code do anything now?)

Maybe we decide to move everything over to PRQL and remove that code — I don't have any strong objection to that...

One advantage of parsing into a `sqlparser-rs` AST was that we could maintain the s-string variables, and then potentially replace the values _after_ formatting, enabling https://github.com/PRQL/prql/issues/1284. (but there are other approaches)

> ```diff
> #[binding_strength(4)]
> let add = l r -> s"{l:4} + {r:4}"
> 
> - #[binding_strength(4)]
> + #[binding_strength(5)]
> let mul = l r -> s"{l:5} * {r:5}"
> 
> #[binding_strength(11)]
> let mod = l r -> s"FLOOR(MOD({l:0}, {r:0}))"
> ```

Super minor clarification — is that change correct? I think so based on https://github.com/PRQL/prql/pull/2709/files#diff-f6d964f7215b03bfdb696d81cf4258db7cf5686558bf44fa627d031f2f474c2eR57 (just trying to understand, not point out typos!)

**Comment by eitsupi** [comment]
> it means that `#` isn't always a comment, it introduces context to the parser.

Ideally this file would be a valid PRQL file so the `#` would actually work as a comment?
https://github.com/PRQL/prql/blob/e4d63da092099ef3dc3816a2ff3cd663b5bf7f83/prql-compiler/src/sql/std.sql.prql#L1-L3

**Comment by max-sixty** [comment]
> Ideally this file would be a valid PRQL file so the `#` would actually work as a comment?

Yes, the new code adds new syntax to prql files — including that one — so...

```
# hello
```

...is a comment but...

```
#[ hello
```

...isn't

**Comment by aljazerzen** [comment]
I had `@(binding_strength)` before, but it was conflicting with date literals.

Yes, the syntax has actually been added to the language. We can change it easily, we just need to find something that looks reasonable and does not have conflicts.

**Comment by aljazerzen** [comment]
> What's the advantage of having `#[binding_strength 4]` on `add` over just reading the binding strength of * from our code in ...

We don't have to parse the s-strings. This way they can contain anything they want and we are not constrained to what sqlparser-rs supports (i.e. integer division operator).

We could, as you point out, remove the binding_strength stuff from gen_expr and use solely what's in `std.sql.prql`. But you know, why fix if it ain't broke :D To be serious, it would clean up the code a little, but we could not remove it completely, since `gen_expr` constains special cases for `NOT NULL` and `CONCAT`.

----

> Super minor clarification — is that change correct? 

I don't know what you mean. `mul` having binding strength of 5?

**Comment by max-sixty** [comment]
> I had `@(binding_strength)` before, but it was conflicting with date literals.
> 
> Yes, the syntax has actually been added to the language. We can change it easily, we just need to find something that looks reasonable and does not have conflicts.

Wouldn't parsing `@(` or `@[` be comparable to parsing `#[`? But with less conflict with comments which often appear as the first character on a line, and have higher "conceptual precedence" in my mind.

(I don't have some strong view on the `@`, but it seems reasonable? I am more against adding a non-comment `#`...)

> We don't have to parse the s-strings. This way they can contain anything they want and we are not constrained to what sqlparser-rs supports (i.e. integer division operator).

Yes, fair point.

I don't have an immediate outcome that gets worse with this approach. I worry we have multiple places where we handle precedence — even _within_ the `std.prql` we have multiple places for precedence, given the attribute and the format syntax; and that we're trending back to string futzing (which you've done so much work to take us away from!).

I also though that parsing it would offer an elegant way to avoid formatting the variables, though it's not the only way.

Overall I don't feel strongly.

> I don't know what you mean. `mul` having binding strength of 5?

Right — am I thinking about it correctly — the precedence in the attribute should match the precedence in on each term, for an infix operator?

**Comment by aljazerzen** [comment]
Syntactically, @ can also appear first in line. A date literal is a valid expression on its own and could be stored into a variable using `into`.

But maybe I can pull off the same trick I did with `#`, looking at the following char. Let mi try.

----

> we're trending back to string futzing

That's true, I was also concerned about that. But at the end, sqlparser is just composing strings together, same as we are here. If sqlparser was being a burder in these cases in the compilation process, skipping it won't bring too much harm. I hope.

----

> > I don't know what you mean. `mul` having binding strength of 5?
> 
> Right — am I thinking about it correctly — the precedence in the attribute should match the precedence in on each term, for an infix operator?

The infix operator. This is the strength provided by that whole s-string, which is determined by the "top level" operator in the s-string. In your case that's infix operator `*`, which has bs of 11.

**Comment by max-sixty** [comment]
> Syntactically, @ can also appear first in line. A date literal is a valid expression on its own and could be stored into a variable using `into`.

Totally, I just think it's less likely

(FWIW I'm happy to have a go at this, I'm strongly not saying that it rests on you to change things just because others have some view)



> The infix operator. This is the strength provided by that whole s-string, which is determined by the "top level" operator in the s-string. In your case that's infix operator `*`, which has bs of 11.

OK, I think we might have lost the connection to the original example (my diff was based on https://github.com/PRQL/prql/issues/2694#issuecomment-1574909876) — but I'm pretty confident I understand

---

> I also though that parsing it would offer an elegant way to avoid formatting the variables, though it's not the only way.

I guess if we're using s-strings for more things such that "don't format s-strings" is no longer viable, we could consider using annotations to specify not formatting them. It adds another "mode" though.

**Comment by aljazerzen** [comment]
> > I also though that parsing it would offer an elegant way to avoid formatting the variables, though it's not the only way.
> 
> I guess if we're using s-strings for more things such that "don't format s-strings" is no longer viable, we could consider using annotations to specify not formatting them. It adds another "mode" though.

Technically, we are not using s-strings - they still have a separate code path in the SQL backend. We are just using something that reuses our prql parser to have compilation rules defined in PRQL syntax :D

So it is still possible to implment don't-format-s-strings, just as much as it was before.

**Comment by max-sixty** [comment]
Ah great, that makes sense. Thanks!
