### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#27]
We should add CI to run the tests on cargo. This can start out very simple.

**Comment by danjones1618** [comment]
I was thinking the other day about making an integration testing framework which tests the built binary compiles PRQL into an SQL query which retrieves the same table from various DBs in different DBMSs.

Essentially there would be a folder for each database which contains:
- A database dump called `db.sql`
- Some number of test files `<test_name>.test` describing a test

The test files would be in the following format:
```
author: Test Author    # The author's name
requires:                    # A list of DBMSs to run against
  - mariadb
  - postgres
---
from employees
filter country = "USA"                           # Each line transforms the previous result.
derive [                                         # This adds columns / variables.
  gross_salary: salary + payroll_tax,
  gross_cost:   gross_salary + benefits_cost     # Variables can use other variables.
]           
filter gross_cost > 0
aggregate by:[title, country] [                  # `by` are the columns to group by.
    average salary,                              # These are aggregation calcs run on each group.
    sum     salary,
    average gross_salary,
    sum     gross_salary,
    average gross_cost,
    sum_gross_cost: sum gross_cost,
    count,
]
sort sum_gross_cost
filter count > 200
take 20
---
SELECT TOP 20
    title,
    country,
    AVG(salary) AS average_salary,
    SUM(salary) AS sum_salary,
    AVG(salary + payroll_tax) AS average_gross_salary,
    SUM(salary + payroll_tax) AS sum_gross_salary,
    AVG(salary + payroll_tax + benefits_cost) AS average_gross_cost,
    SUM(salary + payroll_tax + benefits_cost) AS sum_gross_cost,
    COUNT(*) as count
FROM employees
WHERE salary + payroll_tax + benefits_cost > 0 AND country = 'USA'
GROUP BY title, country
ORDER BY sum_gross_cost
HAVING count > 200
---
```

This has sections delimited by "---\n" with the first section being a YAML frontmatter with various meta data and subsequent regions being the PRQL code and SQL code.

The `requires` field would specify which DBMSs it needs to be tested against as if it's plain SQL this would only need to be tested against one management engine. However, if PSQL is extended to express json querying then there's the need to have different SQL code for different DBMSs. (See #14)

The integration framework would then be able to read the tests, populate the various databases, and verify the output from the PRQL query is the same as the SQL.

Let me know what you think and any suggestions


Side note: it's possible the YAML frontmatter isn't needed and this could be encapsulated within the file name.

**Comment by max-sixty** [comment]
I think that would be great as an integration test! To the extent we use the [`db:{db}` feature](https://github.com/max-sixty/prql/blob/60ffd06c1a848697c6c651960f58fc1ecb87a1ac/README.md?plain=1#L112), it could add that in for each DB, since we may need to produce slightly different output for each DB.

To set the context — the central part of the transpiler tests will be generating the SQL text from the PRQL test, without needing a DB. So this would extend those tests to confirm that the generated SQL is compatible with DBs. While it'll be most helpful once we have those transpiler tests working, it'll be helpful even before then to confirm our examples are correct SQL.

Could we integrate this with the [examples path](https://github.com/max-sixty/prql/tree/main/examples)? That is currently in markdown, which has the advantage that it's readable in GitHub. Maybe we add a YAML block in the markdown there with the details of the test? Feel free to take it in the direction you see as best @danjones1618 . (fyi I don't think I put dividers in all the tests yet, but my intention was that be https://github.com/max-sixty/prql/blob/main/examples/list-equivalence.md is the canonical form of prql / sql / divider)
