### ISSUE TITLE
The `count` function needs `s"*"` for the argument in current dev version

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#2717]
### What happened?

From https://github.com/PRQL/prql/pull/2710#issuecomment-1575011845, related to #2713

We are currently using workarounds in the following following locations:

https://github.com/PRQL/prql/blob/69571f1bd44e90e77e5a514a72d218ba9947caeb/README.md?plain=1#L34
https://github.com/PRQL/prql/blob/69571f1bd44e90e77e5a514a72d218ba9947caeb/web/website/content/_index.md?plain=1#L26
https://github.com/PRQL/prql/blob/69571f1bd44e90e77e5a514a72d218ba9947caeb/prql-compiler/examples/compile-files/queries/variables.prql#L16

### PRQL input

```elm
from a
derive {cnt = count}
```

### SQL output

```SQL
NA
```

### Expected SQL output

```SQL
SELECT
  *,
  COUNT(*) AS cnt
FROM
  a
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by aljazerzen** [comment]
While working on the compiler, I had to change the rule which triggers the `OVER` clause for window functions to not look at the result type of the function, but instead look at the parameter type. This works well, but it has a problem: some window functions don't have any parameters:
- `count` (there was `non_null:`, but that's a named param)
- `rank`,
- `row_number`,

For the sake of language design this should not matter, but it lead me to the following question:

How does the `count` function work, if it receives no parameters? What's the input of its computation? Does it just "pull from the relation"? How do `rank` and `row_number` know how many resulting rows should they output?

This was my justification for making them have a parameter. `count` now has a positional `non_null`, and `rank` and `row_number` have a `column` param that is not used in compilation.

This is obviously a bit inconvenient, so how could we design the language to work around this? To have the arguments as they were before, but don't use the "pull from the relation" bullshit justification?

I've hoped to find a quick fix, but then I found the similar issue of #2723 and wanted to clear that first, so the two do not get mixed up.

**Comment by max-sixty** [comment]
> How does the `count` function work, if it receives no parameters? What's the input of its computation? Does it just "pull from the relation"? How do `rank` and `row_number` know how many resulting rows should they output?

Yes, I think we can think about it as one of:
- it looks at the whole relation, rather than just one column.
- it looks _any_ column (and at least in the case of count, also counts nulls, unlike when a column is selected, as you describe)

Is this a big problem, though? Is your point that it introduces a completely new type for just a couple of functions? For the types, I was thinking the type is `int` rather than `T`?

**Comment by aljazerzen** [comment]
> it looks at the whole relation, rather than just one column.

You mean like this?

```elm
from a = albums
aggregate {count a}
```

----

The problem is that this does not make any sense:

```elm
let x = row_number
```
... while this is completely fine:
```elm
let x = sum [1, 2, -6, 45]
```

So my question is: how do we want to describe the difference between these two functions?

----

My solution was to say "there is no difference, rank requires a column too".

```elm
let x = row_number [1, -2, 5]

assert x == [1, 2, 3]
```

**Comment by max-sixty** [comment]
> You mean like this?
> 
> ```elm
> from a = albums
> aggregate {count a}
> ```

Yes!

> The problem is that this does not make any sense:
> 
> ```elm
> let x = row_number
> ```
> 
> ... while this is completely fine:
> 
> ```elm
> let x = sum [1, 2, -6, 45]
> ```
> 
> So my question is: how do we want to describe the difference between these two functions?

My mental model is that they have the relation as a parameter:

```
let x = row_number [{a=1, b='a'}, {a=2, b='a'}]
```

...so indeed `let x = row_number` isn't correct.

Does that make sense?

**Comment by aljazerzen** [comment]
Makes sense, I fully agree.

Now, we just need a way to reference current relation in all contexts (without using `_frame`) and a solution for #2723.

**Comment by eitsupi** [comment]
Since this is seemingly related to the larger issue #2723, can we mark it as a known issue to Changelog, etc. and remove it from the 0.9 milestone and do a 0.9 release?

I believe that the syntax changes between the last release and the development version are currently causing confusion for new users, so I wonder if it might be worthwhile to expedite the 0.9 release, even if there are some flaws. (Of course, if we could solve these issues right away, that would be great.)

**Comment by max-sixty** [comment]
I think this breaks some Windows builds though? At least, we needed to disable the example crate [here](https://github.com/PRQL/prql/blob/ba98b65d2b13a93400d9ce8a4e87ac1654a3f284/Cargo.toml#L19)

And https://github.com/PRQL/prql/issues/2781#issuecomment-1595361616 suggests it's not just CI.

**Comment by eitsupi** [comment]
> I think this breaks some Windows builds though? At least, we needed to disable the example crate [here](https://github.com/PRQL/prql/blob/ba98b65d2b13a93400d9ce8a4e87ac1654a3f284/Cargo.toml#L19)
> 
> And [#2781 (comment)](https://github.com/PRQL/prql/issues/2781#issuecomment-1595361616) suggests it's not just CI.

Interesting. I can reproduce that.

But it does not seem related to `s"*"`. The following one is also overflowed.

```elm
from employees
filter country == "USA"                      # Each line transforms the previous result.
derive {                                     # This adds columns / variables.
  gross_salary = salary + payroll_tax,
  gross_cost = gross_salary + benefits_cost  # Variables can use other variables.
}
filter gross_cost > 0
group {title, country} (                     # For each group use a nested pipeline
  aggregate {                                # Aggregate each group to a single row
    average salary,
    average gross_salary,
    sum salary,
    sum gross_salary,
    average gross_cost,
    sum_gross_cost = sum gross_cost,
    ct = count salary,
  }
)
sort sum_gross_cost
filter ct > 200
take 20
```

Look for a minimal reproducible example.

**Comment by eitsupi** [comment]
@max-sixty I tried a few simple examples with the latest prqlc.exe built from main, and I suspect that this has nothing to do with `count` and everything to do with the number of `filter` and `take` and `sort`.

## Working

```elm
from employees
filter gross_cost > 0
group {title} (
  aggregate {
    ct = count s"*",
  }
)
sort ct
filter ct > 200
```

```elm
from employees
filter gross_cost > 0
take 20
sort ct
filter ct > 200
sort ct
take 20
```

```elm
from employees
filter gross_cost > 0
take 20
sort ct
filter ct > 200
sort ct
take 20
filter ct > 200
sort ct
filter ct > 200
sort ct
```

## Not working

```elm
from employees
filter gross_cost > 0
group {title} (
  aggregate {
    ct = count s"*",
  }
)
sort ct
filter ct > 200
take 20
sort ct
filter ct > 200
take 20
sort ct
filter ct > 200
take 20
sort ct
filter ct > 200
take 20
```

```elm
from employees
filter gross_cost > 0
sort ct
filter ct > 200
take 20
sort ct
filter ct > 200
take 20
sort ct
filter ct > 200
take 20
sort ct
filter ct > 200
take 20
```

```elm
from employees
filter gross_cost > 0
take 20
sort ct
filter ct > 200
sort ct
take 20
filter ct > 200
sort ct
filter ct > 200
sort ct
filter ct > 200
```

**Comment by eitsupi** [comment]
@max-sixty I created a new issue about that (#2857).
