### ISSUE TITLE
prqlc.exe on Windows seems broken by the latest Rust's bug

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#2721]
It appears that `ctrl+z` does not work due to this bug. rust-lang/rust#112154

It may be better to change the version of Rust that does the release build.

**Comment by max-sixty** [comment]
Yeah, let's revert the whole rust version to whatever is working, and then we can jump to 1.71 when that's out?

**Comment by ShaneEverittM** [comment]
> Yeah, let's revert the whole rust version to whatever is working, and then we can jump to 1.71 when that's out?

Actually, I believe the fix will be in 1.72.

**Comment by eitsupi** [comment]
Yeah, I saw your PR is labeled as 1.72 milestone...
Thanks for working on that!
