### ISSUE TITLE
Partial results on invalid queries, for web

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#276]
A problem with the current interactive approach in https://github.com/max-sixty/prql/pull/270 is that after displaying the successfully compiled query for `n` lines, when someone starts the `n+1` line, the existing successful result is replaced by an error, since the next line is only partially formed. Only when the `n+1` line is valid is the result displayed again.

This makes working interactively difficult, since it's not possible to reference the existing result when composing a new line.

So practically:

```
from employees    # works
```
but
```
from employees    # works
deri              # half typed, whole query fails
```

This is more annoying with larger queries. If we were getting actual results from a DB (rather than just compiling SQL) this would be annoying too.

---

I'm no UI designer — no one should hold my ideas in high regard — but one idea to make the experience better:
- Compile the query until the final valid line, and display valid PRQL input in black.
- Any currently invalid PRQL input would be displayed in red (or some other visual indicator, like a vertical line in the left margin), to indicate that it's not included in the current result.
- We'd display both the compiled SQL — which would come from the valid PRQL — and the error that results from attempting to compile the whole query — which would come from the full query including the invalid PRQL.

Re implementation; currently there's no incremental compilation such that we can "pause" on the previous line when encountering an invalid line. But it's fast enough that we could attempt to compile every query `k` for `k=1..=n` (or optimize with caching / binary search if required). 
The feature would be a function that returned a Struct (not an Enum like a `Result`), of `<Option<String>, Option<Error>>` (and possibly another item depending on whether `Error` contains enough detail to know which is the valid vs invalid text).

**Comment by max-sixty** [comment]
Now we have https://github.com/max-sixty/prql/pull/308, it's worth considering what we can do here that doesn't involve defining a new interactive computing approach :)

Probably the close thing is to display the most recently successful query (in some different color? Or a different color box?) and a separate area for the current error message.

Then things like [showing the exact location and message](https://stackoverflow.com/questions/51540252/monaco-editor-linting-errors-customization-with-warning-error-icons) are probably within our grasp, given we know where the error happens (thanks to Ariadne, CC @aljazerzen ) — but not essential at the moment.

And the above idea re finding the "most number of valid lines" can be pushed out more.

**Comment by aljazerzen** [comment]
I agree that "show last successful compilation" is currently the best approach. 

It would be possible to do "find most number of valid lines" (could be helped with span in returned errors), but I don't think that's much better than "show last successful compilation".

**Comment by max-sixty** [comment]
Just for 0.2, having this would be great:
- show the previously successful compilation
- show the errors in the PRQL pane, with something like [`IMarker`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IMarker.html), as described [here](https://github.com/microsoft/monaco-editor/issues/1477)

The current website version gets some of the way there — we get an error bar, but no text on the error.

https://prql.github.io/prql-website/

<img width="996" alt="image" src="https://user-images.githubusercontent.com/5635139/165157049-62aadea5-d688-4944-af68-67d6e92f3780.png">

**Comment by aljazerzen** [comment]
There is error description when you hover on the error, but it have pretty adriane formatting.

I suggest we replace this hover-able text with concise error descriptions, but also add a "problems" panel at the bottom with pretty adriane error message.

**Comment by aljazerzen** [comment]
Closed with https://github.com/prql/prql-webapp
