### ISSUE TITLE
An incorrect SELECT query with an empty SELECT list

### ISSUE THREAD

**Issue by YuxiLing** [PRQL/prql#2762]
### What happened?

prql version: 0.8.1

comments: the syntax error occurs in generated SQL, as shown in the following example.

error message from the database: SELECT clause without selection list.

### PRQL input

```elm
from tb1
sort [c0]
select [new_col1 = c1]
select [new_col2 = 10]
```

### SQL output

```SQL
WITH table_3 AS (
  SELECT
    c0
  FROM
    tb1
  ORDER BY
    c0
),
table_1 AS (
  SELECT
  FROM
    table_3 AS table_2
)
SELECT
  10 AS new_col2
FROM
  table_1 AS table_0
```

### Expected SQL output

```SQL
WITH table_3 AS (
  SELECT
    c0
  FROM
    tb1
  ORDER BY
    c0
),
table_1 AS (
  SELECT
    *
  FROM
    table_3 AS table_2
)
SELECT
  10 AS new_col2
FROM
  table_1 AS table_0
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
Thanks for the issue @YuxiLing — I confirmed it reproduces on `main` too. We'll take a look at fixing...

**Comment by aljazerzen** [comment]
Great bug report. Minimal and to the point.
