### ISSUE TITLE
Potential deprecation of `concolor`

### ISSUE THREAD

**Issue by epage** [PRQL/prql#2765]
I'm posting this as this project is reported as [a dependent of `concolor`](https://crates.io/crates/concolor/reverse_dependencies) and wanted to both give you a heads up to prepare and an opportunity to discuss in case we should re-evaluate this.

We are proposing deprecating `concolor` in favor of either
- [`anstream`](https://docs.rs/anstream/latest/anstream/) 
- application-specific solutions built on [`colorchoice`](https://docs.rs/colorchoice/latest/colorchoice/), [`colorchoice-clap`](https://docs.rs/colorchoice-clap/latest/colorchoice_clap/), and your choice of environment detection crates including [`anstyle-query`](https://docs.rs/anstyle-query/latest/anstyle_query/) and [`supports-color`](https://docs.rs/supports-color/2.0.0/supports_color/).

We welcome feedback on this topic at rust-cli/concolor#47

**Comment by max-sixty** [comment]
Thank you! I commented on the linked issue.
