### ISSUE TITLE
LAST_VALUE() and FIRST_VALUES() doesn't take "offset" argument

### ISSUE THREAD

**Issue by philpep** [PRQL/prql#2775]
### What happened?

Hi,

I appear, at least on postgresql, LAST_VALUE() AND FIRST_VALUE() window functions doesn't accept an offset argument like https://github.com/PRQL/prql/blob/main/prql-compiler/src/sql/std.sql.prql#L31 suggest.

### PRQL input

```elm
from t
derive diff = (last index) - index
```

### SQL output

```SQL
Error:
    ╭─[Root.prql:11:16]
    │
 11 │ derive diff = (last index) - index
    │                ─────┬────
    │                     ╰────── function std.sub, param `left` expected type `int || float || timestamp || date`, but found type `array -> infer`
    │
    │ Help: Have you forgotten an argument to function std.last?
────╯
```

### Expected SQL output

```SQL
SELECT
  *,
  LAST_VALUE(index) OVER (ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) - index AS diff
FROM
  t
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

### Anything else?

Also wonder if it's possible to workaround by defining custom window function as prql functions using s-strings, but  I didn't manage to get it working.

**Comment by max-sixty** [comment]
Thanks. I think those functions are just wrong. I'll fix it now. We should add integration tests for them.
