### ISSUE TITLE
Book examples are especially old

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2781]
### What's up?

These really need a refresh — https://github.com/PRQL/prql/blob/eb506693f55826f348244c004a6d6b47107c49e1/web/book/src/examples/list-equivalence.md

I'll try and have a look this weekend

**Comment by snth** [comment]
Yeah, the term list should also be avoided probably.

Did we settle on tuple?

**Comment by richb-hanover** [comment]
And I don't wish to pile on, but... 

The example queries in the current Playground don't compile - they still use `[ ... ]` for ~~lists~~ tuples.

**Comment by max-sixty** [comment]
> Did we settle on tuple?

I think so! By default I guess...

**Comment by max-sixty** [comment]
> The example queries in the current Playground don't compile - they still use `[ ... ]` for ~lists~ tuples.

Ah, very good point. We can probably completely replace them with some of the test queries in https://github.com/prql/prql/blob/80a792c6e8dac70c811b1c0f2755e5b606eaa2b3/prql-compiler/tests/integration/queries/invoice_totals.prql#L32-L33 (I'm actually not sure how they're there without being tested)

If anyone wants to do that as part of the playground build, that would be quite welcome. I guess it's a blocker for 0.9.0.

**Comment by whoarusty** [comment]
I'm attempting to go through some of the examples to try to help with updating them, but I'm running into an error with the [Variables](https://github.com/PRQL/prql/blob/main/web/book/src/examples/variables.md) example.

When I try to run the entire query, I get:

`thread 'main' has overflowed its stack`

I can compile the entire query successfully up to the last line, but when I add the `take 20` line I then get the error.

I tried searching for this error in the Issues (both open and closed), but I can't find anything to help me.

**Comment by max-sixty** [comment]
Thanks for testing @whoarusty !

I think I remember us occasionally getting this on Windows — can you try removing `ct = count s"*"`? That was causing issues IIRC, and we're going to change how that works that before we release 0.9.0 (both the syntax and the compiler)

I think the main things we want from the examples:
- Queries that run on data that we have access to, like the Chinook dataset around artists (which we have in the playground)
  - We're open to other Chinook data if it's easy to load; IIRC you have a slightly different dataset
- Queries which highlight a breadth of the language, both initial really simple ones and then more complex ones

We can also start from some of our integration test queries; e.g. https://github.com/PRQL/prql/blob/cf4d247cde00a81356267b837f508e380970bea6/prql-compiler/tests/integration/queries/pipelines.prql. Some of those are pretty good (but some are overly "test-like", such as https://github.com/PRQL/prql/blob/cf4d247cde00a81356267b837f508e380970bea6/prql-compiler/tests/integration/queries/arithmetic.prql).

Feel free to post incremental changes and we can iterate on them. Thank you!

**Comment by whoarusty** [comment]
Thanks for this information and suggestions on the examples you're looking for.

When I remove the `ct = count s"*"` and `filter ct > 200` the query compiles fine.

Regarding the dataset -- is there one available in the repo that everyone tests on? I'm still navigating around and probably missing it.

**Comment by max-sixty** [comment]
Yes! Here's an example: https://github.com/PRQL/prql/blob/3c2860b7756f030841ce74c9960820b61920b919/prql-compiler/prqlc/README.md — so linking to https://raw.githubusercontent.com/PRQL/prql/0.8.1/prql-compiler/tests/integration/data/chinook/albums.csv, and there are some other CSVs in that path...

**Comment by whoarusty** [comment]
Thanks for the links.

I found a way to get to the csv files and schema.sql.

~~I get a `400: Invalid request` if I go to the path to see what other files are there: [https://raw.githubusercontent.com/PRQL/prql/0.8.1/prql-compiler/tests/integration/data/chinook](https://raw.githubusercontent.com/PRQL/prql/0.8.1/prql-compiler/tests/integration/data/chinook/)~~

I appreciate all your help with my questions.

**Comment by max-sixty** [comment]
No problem @whoarusty

(someone hid our comments but please keep asking questions if I can be helpful!)

**Comment by eitsupi** [comment]
> (someone hid our comments but please keep asking questions if I can be helpful!)

Oh, sorry. I misread the intent of the question and marked it as Resolved.

**Comment by max-sixty** [comment]
(No prob @eitsupi — you're right! Just wanted to ensure that @whoarusty felt it was OK to ask more... I'll hide these too :) )

**Comment by eitsupi** [comment]
Is there anything else that should be done about this issue?

**Comment by eitsupi** [comment]
This can be closed?

**Comment by richb-hanover** [comment]
Yes - fine by me. I'm sure there are other things to fix, but we can take a fresh look at things now that 0.9.0 is out

**Comment by max-sixty** [comment]
Yes! I think these were deleted. May they RIP...
