### ISSUE TITLE
A single example containing most features, at the top of the readme

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#279]
We've amassed more text on the Readme. Now important facts like "PRQL has functions" may not be obvious to someone who is scanning quickly. (I have an example of this just happening).

So I should make a single representative example and put it at the top. Hopefully without overwhelming with unrecognizable syntax.

**Comment by aljazerzen** [comment]
What we currently have:

```elm
from employees
filter country = "USA"                           # Each line transforms the previous result.
derive [                                         # This adds columns / variables.
  gross_salary: salary + payroll_tax,
  gross_cost:   gross_salary + benefits_cost     # Variables can use other variables.
]
filter gross_cost > 0
aggregate by:[title, country] [                  # `by` are the columns to group by.
    average salary,                              # These are aggregation calcs run on each group.
    sum     salary,
    average gross_salary,
    sum     gross_salary,
    average gross_cost,
    sum_gross_cost: sum gross_cost,
    ct: count,
]
sort sum_gross_cost
filter ct > 200
take 20
```

Missing:
- [ ] functions
- [ ] tables
- [ ] joins
- [ ] aliases

**Comment by qharlie** [comment]
Do we want to use one database for all the examples ?  That way they can run them against an actual DB.  https://github.com/vrajmohan/pgsql-sample-data/tree/master/employee is one , Chinook is also popular https://github.com/lerocha/chinook-database

**Comment by max-sixty** [comment]
Great idea @qorrect ! Any thoughts on which of those we should go with? Chinook seems to have many more stars...

**Comment by max-sixty** [comment]
I've tempered my view a little bit on the "single query" point. One issue with putting a single example is that the more recognizable stuff — `from X | filter Y` — would need to come _after_ the less recognizable stuff — `func` / `table`. I've frequently bounced from a Readme because it's too difficult to start to understand the first example in 30 seconds.

Possible syntheses of the tradeoff:
- A couple of examples — one simple one like we have now, and one more complex one (a bit like we have now)
- A curriculum approach — start with something simple and gradually add complexity, each new example adding something new but relatively contained
- Some clever way of showing what's connected to what — e.g. having the PRQL & SQL next to each other, and showing which parts of the PRQL drive the SQL, e.g. with arrows / color-coding / etc.

**Comment by qharlie** [comment]
I like Chinook , lots of opportunities for joins, its explorable without being boring.

I think the current example is a little too complicated for someone that is seeing the language for the first time.  
Having a couple examples, the first one being easy to understand for a newbie, then maybe 2 more each getting more and more complex.


Let me post a few queries here for Chinook and we can review them ?  Here is an SQLIte version of Chinook https://github.com/qorrect/PyPrql/blob/main/resources/chinook.db?raw=true

**Comment by max-sixty** [comment]
> I think the current example is a little too complicated for someone that is seeing the language for the first time.

Great, this is good feedback. Let's simplify it for sure.

**Comment by qharlie** [comment]
Here are some chinook queries https://github.com/qorrect/PyPrql/tree/main/examples ( just a temp place for them )

**Comment by max-sixty** [comment]
That looks great @qorrect !

**Comment by max-sixty** [comment]
Done a while back!
