### ISSUE TITLE
Type inference for arrays

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#2822]
Seems like we can't define a table that contains null?

```elm
from [
    {x = null},
    {x = '1'},
]
```

```
Error:
   ╭─[Root.prql:3:10]
   │
 3 │     {x = '1'},
   │          ─┬─
   │           ╰─── array expected type `null`, but found type `text`
───╯
```

**Comment by aljazerzen** [comment]
`'1'` and `null` have types `text` and `null`, respectively. These two are two distinct types with no overlap, similarly to how `bool` and `text` are different types.

Do we want our type inference to work like this:
```
['hello', null] -> array of text || null
[false, 'hello'] -> array of bool || text
```
... or like this:
```
['hello', null] -> array of text, type error at second element
[false, 'hello'] -> array of bool, type error at second element
```

Probably the first, I shouldn't even be asking. Right now, the second is implemented, just because it's easier.

**Comment by aljazerzen** [comment]
In any case, we should be able to cast types to super types:

```elm
from [
    {x = <text || null> null},
    {x = '1'},
]
```
... but this is something still left to do.

**Comment by eitsupi** [comment]
Thanks for your answer.
I simply wanted to insert NULL into the table when doing debugging work in https://github.com/PRQL/prql/pull/2815#issuecomment-1588432031.

It would be great if explicit type definitions (super type?) were possible here.

**Comment by aljazerzen** [comment]
:+1:

What do you think about the type inference? Should the compiler automatically infer that this column may also be null?

PS: with super type I meant casting from a type (`int` in this case) into its super type (`int || null` in this case).

**Comment by eitsupi** [comment]
> What do you think about the type inference? Should the compiler automatically infer that this column may also be null?

Of course, there are many situations where it would be useful to have it, but considering that there are backends like ClickHouse that do not allow nulls by default, I think there is merit in requiring for users to mark "nullable" to the column.
Therefore, I think it is a good idea to postpone the implementation of the automatic guess function until there are more requests for it.

**Comment by max-sixty** [comment]
> What do you think about the type inference? Should the compiler automatically infer that this column may also be null?

I think this would be good to have if possible, but by no means top priority.

My guess is that it's easier _within a relation literal_ than a full type system — that would be a nicer experience for relation literals.

**Comment by aljazerzen** [comment]
Again, let's not think about how SQL does things and how we'd implement that, but what do we want our language to be.

---

> My guess is that it's easier within a relation literal than a full type system — that would be a nicer experience for relation literals.

It would be harder to do just for relation literals as opposed to all arrays. And it is not that hard.

**Comment by max-sixty** [comment]
> It would be harder to do just for relation literals as opposed to all arrays. And it is not that hard.

Yes great. (I was thinking relative to working out the types through a whole query!)

**Comment by snth** [comment]
> What do you think about the type inference? Should the compiler automatically infer that this column may also be null?

Yes.

---
I like the approach from the [Query Combinators](https://browse.arxiv.org/pdf/1702.08409.pdf) paper that `int || null` should be represented/thought of as `Optional[int]` and like in Rust, the `Optional` part should be tracked by the type system and when you want to cast to `int` you have to "unwrap" it with the `??` (coalesce) operator. 

Since we're big on ergonomics and in SQL (or data in general) there are a lot of `A || null` types, maybe we could have the syntax `A?` (or `int?` in the example above), to mean `Optional[A]` (and `Optional[int]` respectively)?

**Comment by jangorecki** [comment]
+1 for re-using rust styles.

On the other hand why I think having nullablle data types by default make sense:

- It is the default in RDBMSes (except for clickhouse)
- Column data types will be changed frequently, after each outer join where there is at least one not matching row, like below, `customers.first_name` will change from not nullable string to nullable string. IMO schema/data type change should always be very explicit, like `cast as`, and making it depend on the data is asking for troubles. Imagine a first batch of data load matching all rows, so field generated is not nullable, and next day another batch has some unmatched rows and suddenly this batch tries to load data into table/object having differently defined schema.
```prql
from invoices
filter invoice_id <= 2
join side:left (
  from customers
  filter customer_id==2
) (==customer_id)
select customers.first_name
```

There are probably more arguments for that, but those two are likely to be the strongest ones.

**Comment by aljazerzen** [comment]
Let's move discussion about nullable types into its own issue.

**Comment by aljazerzen** [comment]
Related: https://github.com/PRQL/prql/issues/3925

**Comment by snth** [comment]
I encountered this again today while trying to prepare an example for #905.

> Do we want our type inference to work like this:
> ```
> ['hello', null] -> array of text || null
> [false, 'hello'] -> array of bool || text
> ```
> ... or like this:
> 
> ```
> ['hello', null] -> array of text, type error at second element
> [false, 'hello'] -> array of bool, type error at second element
> ```
> Probably the first, I shouldn't even be asking. Right now, the second is implemented, just because it's easier.

I agree that we would want the first.

**Comment by snth** [comment]
@eitsupi here's a workaound I'm using for now:

```elm
let to_int = func x -> case [x=='null' => null, true => (x | as int)]

from_text format:csv """i,a_i,b_i
0,0,0
1,1,10
2,2,null
3,null,30
4,null,null
"""
sort i

select {a=a_i|to_int, b=b_i|to_int}
```

Which yields:

|a|b|
|-|-|
|0|0|
|1|10|
|2|null|
|null|30|
|null|null|
