### ISSUE TITLE
Update grammars for 0.9

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2840]
### What's up?

We should update the grammars for 0.9. This might just be fixing the tuple / list syntax. They're listed at https://prql-lang.org/book/internals/syntax-highlighting.html

(FWIW some of them could do with a refresh on keywords, or how they handle strings etc, but that's by no means necessary for 0.9)

- [x] Lezer (#2868)
- [x] Handlebars (#2871)
- [x] Monarch (#2874)
- [x] VS Code / Textmate (PRQL/prql-vscode#244)
- [ ] Tree-SItter (PRQL/tree-sitter-prql#13)

**Comment by eitsupi** [comment]
The remaining task is tracked in another repo PRQL/tree-sitter-prql#13, so I close this for now.
