### ISSUE TITLE
Scientific/exponential format silently behaves unexpectedly

### ISSUE THREAD

**Issue by dan-robertson** [PRQL/prql#2860]
### What happened?

Possibly a duplicate of #1118 (though this issue seems different in that these inputs were rejected before).

Entering numbers with scientific notation silently produces the wrong number.

I think instead such inputs should either be rejected or passed through to sql.

### PRQL input

```elm
from numbers
select [ exponential = 1e9 ]
```

### SQL output

```SQL
SELECT
  19 AS exponential
FROM
  numbers
```

### Expected SQL output

```SQL
SELECT
  1E9 AS exponential
FROM
  numbers
-- Or the prql compiler rejects the input
```

### MVCE confirmation

- [X] Minimal example
- [x] New issue

### Anything else?

This was on the playground. Perhaps it is different in other versions.

**Comment by eitsupi** [comment]
Hi, thank you for reporting this!
I can reproduce with the latest dev version.

**Comment by max-sixty** [comment]
Some options for the implementation:
- Convert to float in rust, then convert to scientific when writing. But [not trivial](https://stackoverflow.com/questions/65264069/alignment-of-floating-point-numbers-printed-in-scientific-notation), likely requires heuristics on when to use scientific notation, and some float approximation.
  - We could also store smaller numbers as integers, up to 2^32 for `i32`...
- Store as string
- Raise an error

Probably string is easiest, float is best. Any thoughts from others?

**Comment by max-sixty** [comment]
Actually converting to a float was easiest, in #2865 

It currently will write the whole number out, which isn't ideal with huge numbers, but fixing that is a bit more work, as it requires writing a heuristic for when to express fully vs in scientific notation. (Contributions welcome if anyone wants to take a swing)
