### ISSUE TITLE
setup-dev issues

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2886]
Opening a new issue based on https://github.com/PRQL/prql/issues/2282#issuecomment-1599423029

@khoa165 do you want to try running `brew install npm`? I saw the same logs that you pointed out. It's possible that very old versions of `npm` handled paths differently.

We do test the `Taskfile`, and it runs fine on my system — so it likely a versioning issue rather than a problem with the Taskfile itself.

**Comment by eitsupi** [comment]
It may be necessary to mention in the documentation the required version of rustc, Node.js, etc.

**Comment by max-sixty** [comment]
We do try and install `npm` with `brew` but only if it can't be found at all (https://github.com/PRQL/prql/blob/baf3ba7dc21005c56c0cbe625d9f3ad2d270c77d/Taskfile.yml#L145). 

Possibly we need to check the version too — I can add that check if it indeed is the cause of @khoa165's issue. 

An automated check is more reliable and less overhead for the user, relative to adding docs — so let's default to that if we can...

**Comment by eitsupi** [comment]
That said, I am concerned that implicitly using the brew command may not be good manners (at least for me it is quite surprising that something will be installed implicitly via the brew command).
And of course, the brew command can only be executed on macOS and amd64 Linux.

I think it would make sense to add a version check to the task of running npm.

**Comment by max-sixty** [comment]
> That said, I am concerned that implicitly using the brew command may not be good manners (at least for me it is quite surprising that something will be installed implicitly via the brew command).

Yeah, I think this is relevant. It's a difficult balance to strike — for example it only suggests vscode extensions at https://github.com/PRQL/prql/blob/baf3ba7dc21005c56c0cbe625d9f3ad2d270c77d/Taskfile.yml#L53.

We could do the same with `brew` dependencies, only suggesting — I would be open to that. 

I had thought of brew dependencies similar to the cargo tools — that generally it's fine to add things, and brew doesn't support old versions, so it's fine to upgrade things. But maybe this is too aggressive...

**Comment by khoa165** [comment]
Hi @max-sixty, afer I did `npm install -g npm@latest` and then re-run `task setup-dev` and then run `task run-playground`, it works, I could see the playground on localhost!!!! It must have been b/c of npm version then. My NPM was previously 6.14.14 and it's now 9.7.1

**Comment by khoa165** [comment]
Also I have another question, are we only able to run either playground or book at once and not both? I opened 2 tabs of terminal and ran `task run-playground` first (which works) and then `task run-book` (which works but now playground does not work). Is it b/c they use the same port?

**Comment by max-sixty** [comment]
OK great! The new Taskfile will not proceed on an old version of npm; hopefully that should mean we don't hit this again...

**Comment by max-sixty** [comment]
> Is it b/c they use the same port?

Possibly. It's worth trying to change the ports in the taskfile, re-running, and seeing whether that helps...

**Comment by max-sixty** [comment]
(closing but feel free to ask any more questions here)
