### ISSUE TITLE
lint: Add lint for when `sort` is missing

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#2921]
### What's up?

Problem: There is no guarantee that the rows of a result set returned by a `SELECT` query are in any particular order unless the `ORDER BY` clause is used in the query.

Idea: PRQL should include a lint which suggests to add a `sort`.

# Example
Bad query
```elm
from employees
select [id, first_name, age]
take 10
```

Good query
```elm
from employees
select [id, first_name, age]
sort age
take 10
```

**Comment by max-sixty** [comment]
I think the main issue here is that `sort` can be extremely expensive for large tables. For example, on a 100PB BigQuery table:

```
from foo
take 10
```

...would take less than a second. But

```
from foo
sort bar
take 10
```

...would take hours. So there are lots of times someone wouldn't want `sort`.

I agree that lots of the time, having `sort` *is* helpful. But I think lints probably need to be 95% and allow exclusions.

WDYT?

**Comment by vanillajonathan** [comment]
Good point, I didn't consider that.

The lint wouldn't be of the type Error or Warning, it would be of type Lint — the lightest of them. It would offer some helpful advice but the user would be free to disregard that advice.

Additionally maybe there could be a comment to silence the lint on the next line.

**Comment by max-sixty** [comment]
Yes, I hear you re it being possible to disregard the advice. I still think that it should be no worse to follow the advice something like 95% of the time — exclusions are noisy in the code, and noisy when developing...

**Comment by vanillajonathan** [comment]
Maybe it could only trigger with a `--strict` flag?

I don't know, I think it seems like it could sometimes be some helpful advice for some people maybe.

**Comment by max-sixty** [comment]
Yes.  see your perspective on it often being useful. Let's mark it as postponed — given we don't have any mechanism for producing lints yet, it's some way off, even if we do think it's a good idea. Hope that sounds reasonable to you.
