### ISSUE TITLE
Add a `delete` transform

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#2922]
### What's up?

Add a `delete` transform to delete data.

# Example
```elm
from employees
filter end_date < @2021-01-01
delete
```

**Comment by max-sixty** [comment]
PRQL doesn't change any data in the database — it's just a querying language. Is that what `delete` would be?

**Comment by vanillajonathan** [comment]
I think PRQL would be more useful if it could do more than just query.

I imagine it would translate into:
```sql
DELETE FROM employees WHERE end_date < '2021-01-01';
```

**Comment by max-sixty** [comment]
OK, let's roll this into https://github.com/PRQL/prql/issues/1092. I agree it would be useful — it's a big extension, though. The semantics are more different across dialects, and we would need to be much more risk averse given the bad outcomes from making a mistake.

**Comment by vanillajonathan** [comment]
There could be a lint for this too:

# Bad query
Delete without filter!
```elm
from employees
delete
```

# Good query
Delete with filter of course!
```elm
from employees
filter end_date < @2021-01-01
delete
```
