### ISSUE TITLE
aggregation functions in s-strings in `window`

### ISSUE THREAD

**Issue by cottrell** [PRQL/prql#2928]
### What happened?

This should produce two identical columns I think.

```
from invoices
window rows:-3..3 (
  derive [
  t = average total,
  tt = s"avg({total})",  # fails
  ]
)
```

Instead we get

```
Error: Binder Error: column "invoice_id" must appear in the GROUP BY clause or must be part of an aggregate function.
Either add it to the GROUP BY list, or use "ANY_VALUE(invoice_id)" if the exact value of "invoice_id" is not important.
```

### PRQL input

```elm
from invoices
window rows:-3..3 (
  derive [
  t = average total,
  tt = s"avg({total})",  # fails
  ]
)
```

### SQL output

```SQL
SELECT
  *,
  AVG(total) OVER (ROWS BETWEEN 3 PRECEDING AND 3 FOLLOWING) AS t,
  avg(total) AS tt
FROM
  invoices
```

### Expected SQL output

```SQL
SELECT
  *,
  AVG(total) OVER (ROWS BETWEEN 3 PRECEDING AND 3 FOLLOWING) AS t,
  avg(total) OVER (ROWS BETWEEN 3 PRECEDING AND 3 FOLLOWING) AS tt
FROM
  invoices
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

### Anything else?

I think on 0.8.1. Trying it in the playground.

**Comment by max-sixty** [comment]
Thanks for the report @cottrell ! I reproduced. (To confirm for others — the error message is from the DB, not PRQL)

I'm thinking whether it always works to treat the s-string as opaque and adding the window clause to it. i.e. we do:

```
 $sstring_contents OVER (ROWS BETWEEN 3 PRECEDING AND 3 FOLLOWING) AS $alias,
```

Can you / anyone think of a reason that wouldn't work?

**Comment by aljazerzen** [comment]
So we want to detect usage of aggregation functions in s-strings and add OVER clauses to them? I don't think this is possible with reasonable accuracy.

I think I have to say PRQL does not support s-strings in windows.

Instead, one could define their own aggregation function that would get treated as a proper window function.

**Comment by aljazerzen** [comment]
Sidenote: this issue would be revisited when #2723 is done, to see how it interacts with the new behavior.

**Comment by cottrell** [comment]
> 

Sorry, can you clarify here? Do you mean PRQL can never support s-strings in windows or are you just describing the current state?

Also, would like to understand "define their own aggregation function" ... you mean in the prql compiler itself or is there a way of defining an agg function in prql itself on the fly? I am not aware of that if so.

**Comment by aljazerzen** [comment]
Right, that was unclear.

PRQL will probably never support window functions in s-strings. That's because if we were to support this, we would have to support it in all cases, even this one:

```elm
from invoices
window rows:-3..3 (
  derive [
      tt = s"avg({total}) - lag({total})"
  ]
)
```
... which would be expected to compile to:

```sql
SELECT
  avg(total) OVER (...) - lag(total) OVER (...) as tt
)
FROM invoices
```

We treat s-strings as opaque - we don't parse or transform them in anyway. They are just an escape hatch with eventual goal of removing them completely.

----

> you mean in the prql compiler itself or is there a way of defining an agg function in prql itself on the fly?

On this fly, like this:

```elm
func my_avg <column> col -> s"my_aggregation_func({col})"
# because we define my_avg to return a column,
# the compiler will realize it is a window function

from invoices
window rows:-3..3 (
  derive [
    t = average total,
    tt = my_avg total
  ]
)
```

Note that the syntax (and some of compiler behavior) is about to change with 0.9.

**Comment by cottrell** [comment]
Interesting. I guess there is some "stuff" going on in there that is not merely rendering strings in the place where they should go in SQL.

~~And they take away seems to be that one must then not view s-strings as a backend-get-out-of-jai- free-card because they are limited ... and we must basically be prepared to fork and compile a pure-PRQL function in these cases (or support dropping to SQL for the cases that PRQL does not support).~~

I missed the bit about the "on the fly". Ok so maybe the take away is that best practice is put all s-strings in these on the fly functions. I was not even aware of them until now!

**Comment by max-sixty** [comment]
> So we want to detect usage of aggregation functions in s-strings and add OVER clauses to them? I don't think this is possible with reasonable accuracy.

Definitely not and definitely agree!

I was instead thinking that we'd treat it as opaque, but still allow it in a window func. That would mean that a single function would work, but not a complex expression.

i.e. 

> ` $sstring_contents OVER (ROWS BETWEEN 3 PRECEDING AND 3 FOLLOWING) AS $alias,`

So here:

```elm
from invoices
window rows:-3..3 (
  derive [
    t1 = s"avg({total})",  # works
    t2 = s"avg({total}) - lag({total})"  # doesn't work
  ]
)
```

We'd get

```sql
SELECT
  avg(total) OVER (...) OVER (...) as t1,  # works
  avg(total) - lag(total) OVER (...) as t2  # doesn't work, not allowed (I think)
)
FROM invoices
```

This would give us something similar to the `func` example above. It does seem fairly simple and transparent. Just from the standpoint of language design (ignoring compiler complexity), I'm not sure there's much downside?

**Comment by aljazerzen** [comment]
I don't think this would work. The problem is the way we are detecting window functions is by looking at PRQL functions. If we extend this to s-strings, it might get very wrong in some cases.

For example, if we say "add the OVER clause to every s-string within window", the counter example would be:

```
derive [s"avg({total})" + s"3"]
```
... because that would compile to:
```sql
SELECT avg(total) OVER (...) + 3 OVER (...)
```

**Comment by aljazerzen** [comment]
The solution really is "develop an easy way of declaring own functions" so people can extend our std lib with what they need.

**Comment by max-sixty** [comment]
> ... because that would compile to:
> 
> ```sql
> SELECT avg(total) OVER (...) + 3 OVER (...)
> ```

Yes, good point.

I still think it would be pretty easy to see what's going on, and then move the `+ 3` into another derive outside the window scope, though...

**Comment by brunorpinho** [comment]
Hi all, 

Just ran into this. Has this ever been revisited? Is it still the same position that PRQL will never support this?

```
from table

window rows:.. (
  derive {median_value = (s"median(v)")}
  derive {avg_value = (average v)}
)
```
