### ISSUE TITLE
adding function call to `derive` removes SQL results

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#2939]
### What happened?

Using the main Playground (0.8.1), I enter the following PRQL code that calls my "dollars" function.

If the `nice = (dollars customer_id ),` line is commented out, the _output.arrow_ displays the expected column of `customer_id`s.

If the comment is removed, both the `customer_id` and `nice` columns become empty.

I'm feeling dopey, but I don't see what's wrong...

NB: The "dollars" function comes from the blog post at: https://prql-lang.org/posts/2023-01-28-format-pretty-reports/ with a fix to the `"` surrounding the printf format string...

### PRQL input

```elm
func dollars d -> s"printf('$%,d',{d})"

from invoices
select [
customer_id,
# nice = (dollars customer_id ),
]
```

### SQL output

```SQL
-- This is what the Playground generates when the comment is removed...

SELECT
  customer_id,
  printf('$%,d', customer_id) AS nice
FROM
  invoices

-- Generated by PRQL compiler version:0.8.1 (https://prql-lang.org)
```

### Expected SQL output

```SQL
N/A
```

### MVCE confirmation

- [X] Minimal example
- [ ] New issue

**Comment by aljazerzen** [comment]
I'm guessing that DuckDB has a slightly different implementation of printf and the thousand separator is messing something up.

I'd advise against using printf altogether.

**Comment by max-sixty** [comment]
Very old issue, but am clearing up notifications from vacation.

This is weird. It seems like it's likely an issue with duckdb & the playground, not in the prql-compiler specifically — so I'm less alarmed. Understanding if this happens in `duckdb` cli could isolate it to an issue with the duckdb JS implementation...

**Comment by richb-hanover** [comment]
@max-sixty I believe @aljazerzen is correct - the duckdb implementation of printf is the problem. Removing the `,` from the printf specifier `'$%,d'` causes the SQL output to display (but without comma-separated values, if there were any) 

We can leave this closed. Thanks.
