### ISSUE TITLE
Dead code

### ISSUE THREAD

**Issue by not-my-profile** [PRQL/prql#2979]
To me it seems like the following two functions don't have any effect whatsoever since they are never called:

https://github.com/PRQL/prql/blob/fa3cc740ffbd84a7b5f0bba8565b83ac4f2fe7a4/bindings/prql-js/src/utils.rs#L1-L11

https://github.com/PRQL/prql/blob/fa3cc740ffbd84a7b5f0bba8565b83ac4f2fe7a4/prql-compiler/src/semantic/type_resolver.rs#L326-L341

What's up with that?

**Comment by aljazerzen** [comment]
They are leftover functions that we used in the past and may also use in the future. They could probably be removed.

The second one could be [used here](https://github.com/PRQL/prql/blob/main/prql-compiler/src/semantic/resolver.rs#L550-L557), as it also provides a hint.

Edit: missing link

**Comment by not-my-profile** [comment]
According to `git log -S` both functions were never used. If they are intended to be used I think we should add some `// TODO` comments accordingly.

**Comment by aljazerzen** [comment]
They were probably moved from some other place.

I'm not sure what to do with the first one, but the second one should be hooked into the site that I linked to (and only now noticed that I actually forgot to paste the link :D ).

**Comment by max-sixty** [comment]
Both those blocks are now removed
