### ISSUE TITLE
Playground should display a message for compiler panics

### ISSUE THREAD

**Issue by not-my-profile** [PRQL/prql#2986]
While testing  #2985 in the playground I was confused because it didn't display any error message ... only red squiggles under the last character that when hovered show "Missing query".

I think we should instead display a big error message like:

> Uh, oh this crashed the compiler. This shouldn't be happening please **report an issue**.

**Comment by aljazerzen** [comment]
I agree.

Not sure how to implement this, but it might be connected to the `set_panic_hook` you've found in #2979.

**Comment by max-sixty** [comment]
> Not sure how to implement this, but it might be connected to the `set_panic_hook` you've found in #2979.

Exactly correct! We would need to add a feature so that the panic hook is set...

**Comment by max-sixty** [comment]
This is done!
