### ISSUE TITLE
docs: Updating the "Variables & let" page

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#2991]
### What's up?

I made a tactical error. While I was rewriting the "Variables & let" page, I expanded my PR to include a bunch of tweaks to other pages that led to the need to work around a `mdbook` bug and using `markdown-link-check` on other pages. This makes #2988 "all about those problems" instead of what I really wanted, which was a discussion about the `let` keyword.

So I am creating a new issue as a request for people to review the "Variables & let" page in my repo at: https://github.com/richb-hanover/prql/blob/new-variables-let/web/book/src/queries/variables.md 

The original post says:

> [the page] seemed incomplete, and I couldn't entirely understand everything that let does. I have taken the liberty of attempting to explain it better. I made the following changes and assertions which should be checked carefully:
> 
> - I changed the title of the page to "Variables & let" in the hopes of making it easier to find the let description.
> - The new page states `let` can assign a scalar, function, an array, or pipeline
> - Are the descriptions on the page correct?
> - Why do we introduce the `into` statement - doesn't `let ...` cover all the cases?
 > - The original page made a couple other assertions. Are they still true/relevant?

Thanks for your comments.

**Comment by aljazerzen** [comment]
Github PRs nicely work with multiple parallel conversations, so we can review everything there. Unless if there is some deeper issue with `let` or `into` on the language lever. If you want, you can also split the PR into two (or tell me to do it for you :D)

I get the frustration, though: you make a big effort and a small tweak and the reviewing spotlight falls on the tweak.

**Comment by richb-hanover** [comment]
Thank you for acknowledging my (mild) frustration :-)  I try always to put each issue in its own email/report: not everyone is as diligent at reading carefully as the PRQL team.

**Comment by richb-hanover** [comment]
More questions about `let`: I still don't understand all the nuances of how to define it, so I dwell in the land of magical thinking, where it can do anything that I dream of... :-)  So let me get more concrete:

- @max-sixty used to refer to `let` as an "alias". (We've decided to use the term "assign" now.) But "alias" carries a notion of a literal textual replacement. This makes sense in the case of a scalar: `let pi = 3.14159`; everywhere `pi` shows up, PRQL can replace with the string "3.14159". 
- Is that true for functions? (after some kind of substitution of parameters into "the right place")
- Is that true for arrays? Can arrays have parameters/variables?
- And what about pipelines?
   - Must the pipeline begin with `from ...`?
   - Could the pipeline begin with `from this` and accept whatever was passed from above?
   - Could it be a replaceable/reusable chunk of code (PRQL statements) that combines group, select, window, etc? (I don't have a use case here - I am just asking about possibilities.)
   - Do we have real-world examples of using `let` to assign a pipeline? I see the`top_50` example in the [Book](https://prql-lang.org/book/queries/variables.html). But that is just a didactic example: it could be just as easily be replaced (and would get shorter) by removing the `let` and just using those four lines.
   
More possibilities as I think of them. Thanks.

**Comment by aljazerzen** [comment]
> But "alias" carries a notion of a literal textual replacement.

Don't think about it this way. Imagine that the `x` in `let pi = x` is computed to a value and that value is then used wherever you used `pi`.

> Can arrays have parameters/variables?

I don't know what you mean. A function that evaluates to an array is possible, yes:

```
let x = a -> [a, a, a]
```

> And what about pipelines?

You are asking about pipelines in general here. Let takes any expression and binds it to a name. You can then use that name instead of the whole expression. That's all that `let` does.

> Do we have real-world examples of using let to assign a pipeline?

Sometimes, you might want to use a variable multiple times:
```
let employees = (
  from people
  filter is_employee
)

from e = employees
join managers = employees (e.managed_by == managers.id)
select {name = e.name, managed_by = managers.name}
```

**Comment by not-my-profile** [comment]
(haha sorry for derailing your PR :sweat_smile: ... just a tip for the future: you can mark discussions that are spawned by comments on the changes as resolved which collapses them and thus helps in getting the focus back on what you want to discuss ... which is also why I try to avoid discussing minor details in the main thread since they cannot be collapsed/marked as resolved there)

**Comment by richb-hanover** [comment]
> Imagine that the `x` in `let pi = x` is computed to a value and that value is then used wherever you used pi.
> 
> `let` takes any expression and binds it to a name.

These feel like two important insights. I will chew on them to see how I might update the Variables & let page. Thanks

**Comment by aljazerzen** [comment]
Work off the #2995 PR

**Comment by richb-hanover** [comment]
> Work off the https://github.com/PRQL/prql/pull/2995 PR

I am closing this in favor of #2995 (which is terrific!)
