### ISSUE TITLE
More operator

### ISSUE THREAD

**Issue by aislam-lightbox** [PRQL/prql#3018]
How to use LIKE and IN like SQL
IN SQL we use like for partial match how to use it with PRQL
Also in SQL we use IN to indicate item from a set like select * from account WHERE name in (a,b,c,d) etc  How to use IN with PRQL

**Comment by max-sixty** [comment]
In 0.9.0 (released v soon), we have a regex operator: https://github.com/PRQL/prql/blob/3f0c1c47d22a5a67f99a441dec496a35ab420797/web/book/src/language-features/regex.md

Feel free to reopen with follow-up questions!

**Comment by eitsupi** [comment]
FYI, there is an open issue here about `IN`. #747
