### ISSUE TITLE
Why is `name` in `FuncCall` of type `Box<Expr>` instead of `Ident`?

### ISSUE THREAD

**Issue by not-my-profile** [PRQL/prql#3025]
https://github.com/PRQL/prql/blob/44457ebe48919147790080199cbb52f5d4f46022/crates/prql_ast/src/expr.rs#L84-L85

I would have expected the type to be `Ident` and indeed that was the type before it for some reason (?) was changed in bc3e42809f87b56d3f529fb0cd8730fbf8368d2e to `Box<Expr>`.

**Comment by aljazerzen** [comment]
Because these are all valid PRQL:

```
(from) tables
```

```
from table_a
(join table_b side:left) (==some_id)
```

**Comment by aljazerzen** [comment]
Name might not be the best field descriptor. `func` would be better, but that's quite overloaded.
