### ISSUE TITLE
CI flukes in test-taskfile and markdown-link-check

### ISSUE THREAD

**Issue by not-my-profile** [PRQL/prql#3029]
https://github.com/PRQL/prql/actions/runs/5629636548/job/15260215599

test-taskfile for some reason failed with:

> Error:  Couldn't resolve parser "go-template".

And the markdown link checker incorrectly reports a live link as dead:

```
ERROR: 1 dead links found!
[✖] https://www.cs.ox.ac.uk/people/jeremy.gibbons/publications/spigot.pdf → Status: 0
```

**Comment by max-sixty** [comment]
I purged my `~/.cache/pre-commit` and now get the `go-template` error. So we should try and fix.

We'd got this error in pre-commit updates — e.g. here's today's: https://results.pre-commit.ci/run/github/449091292/1690223003.KYzpsRxVQxyjqIASMzsR5g

But I think it's possibly not related to the update; instead successful results are relying on a stale cache.

**Comment by max-sixty** [comment]
For the dead link — that's a bit annoying — possibly we can exclude it?

(thanks for flagging both of these @not-my-profile !)

**Comment by max-sixty** [comment]
I "fixed" the first, but by ignoring it, ref https://github.com/PRQL/prql/issues/3078
