### ISSUE TITLE
Move to prql org

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#303]
As discussed on discord, now that we've outgrown my personal namespace, let's move to a `prql` org. I have the org set up: https://github.com/prql/

It would be great to have a simple logo so that it's not the GitHub default. I'm no graphic designer. I may ask a friend to help. I'm thinking something very simple like a "P", maybe with some notion of a pipeline (in the vertical line of the `P`??), or just the text `PRQL`. If anyone has some inner design talent, feel free to post ideas here or on Discord!

**Comment by qharlie** [comment]
Can we move PyPrql under /prql/ as well ? 

Thought I saw someone mention a fancy Pipe as the logo ?

**Comment by max-sixty** [comment]
> Can we move PyPrql under /prql/ as well ?

As you wish; PyPrql would be welcome, but there's no requirement to move everything PRQL-related; e.g. @aljazerzen has his VSCode extension (though shall we link to it from the Readme @aljazerzen ?).

If we do, we should make clear you're the maintainer and the level of support people can expect, etc.

> Thought I saw someone mention a fancy Pipe as the logo ?

I joked about https://en.wikipedia.org/wiki/The_Treachery_of_Images on Discord! I worry the smoking pipe would be too abstract / punny for newcomers? (Also maybe not the clean modern theme? But it would be amusing...)

**Comment by aljazerzen** [comment]
We should link it from readme, yes. And it part of PRQL tooling, which means it should be under PRQL org.

**Comment by max-sixty** [comment]
Done!
