### ISSUE TITLE
ordering guarantees in sqlite

### ISSUE THREAD

**Issue by YuxiLing** [PRQL/prql#3040]
### What happened?

prql version: 0.8.1

According to prql language book, most of the transforms should persist ordering. However, I found in some cases that generated sql ignores the situation that SQLite does not persist ordering through sub-query blocks.

In the following example, the order does not hold after the `filter` clause. In the SQL output, `order by c1` should be in front of `limit 30` to let SQLite guarantee the ordering.

### PRQL input

```elm
prql target:sql.sqlite
from tb1
sort [c1]
filter (c2 <= 10)
take  30
sort [-c3]
select [new_col = c4*c5]
```

### SQL output

```SQL
WITH table_7 AS (
  SELECT
    c3,
    c4,
    c5,
    c2,
    c1
  FROM
    tb1
  ORDER BY
    c1
),
table_5 AS (
  SELECT
    c3,
    c4,
    c5,
    c2
  FROM
    table_7 AS table_6
),
table_3 AS (
  SELECT
    c4 * c5 AS new_col,
    c3
  FROM
    table_5 AS table_4
  WHERE
    c2 <= 10
  LIMIT
    30
), table_2 AS (
  SELECT
    new_col,
    c3
  FROM
    table_3 AS table_0
  ORDER BY
    c3 DESC
)
SELECT
  new_col
FROM
  table_2 AS table_1

-- Generated by PRQL compiler version:0.8.1 (https://prql-lang.org)
```

### Expected SQL output

```SQL
WITH table_7 AS (
  SELECT
    c3,
    c4,
    c5,
    c2,
    c1
  FROM
    tb1
),
table_5 AS (
  SELECT
    c3,
    c4,
    c5,
    c2
  FROM
    table_7 AS table_6
),
table_3 AS (
  SELECT
    c4 * c5 AS new_col,
    c3
  FROM
    table_5 AS table_4
  WHERE
    c2 <= 10
  ORDER BY
    c1
  LIMIT
    30
), table_2 AS (
  SELECT
    new_col,
    c3
  FROM
    table_3 AS table_0
  ORDER BY
    c1,
    c3 DESC
)
SELECT
  new_col
FROM
  table_2 AS table_1

-- Generated by PRQL compiler version:0.8.1 (https://prql-lang.org)
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

### Anything else?

I hope these will be useful. Thank you.

**Comment by max-sixty** [comment]
That's a long result! Is there any smaller query that demonstrates this, or is the full query required?

Yes — thank you for these @YuxiLing !

**Comment by YuxiLing** [comment]
From my testing, yes. It requires prql code to be complicated as in this structure to get such sub-query blocks in the SQL code. 

Meanwhile, I checked this issue in the latest PRQL (0.9.0), and it has been fixed.

**Comment by max-sixty** [comment]
Thanks @YuxiLing !

Please continue to post reports; these were useful.
