### ISSUE TITLE
The order after multiple `sort` clauses

### ISSUE THREAD

**Issue by YuxiLing** [PRQL/prql#3042]
### What happened?

prql version: 0.8.1

Comments: sql does not persist the order after `derive` clause. 

In the following example, `sort -c1` should be transformed to `order by` clause together with `sort c3`.

### PRQL input

```elm
from tb1
sort [-c1]
derive [new_col = c1+c2]
sort [c3]
take  20
```

### SQL output

```SQL
SELECT
  *,
  c1 + c2 AS new_col
FROM
  tb1
ORDER BY
  c3
LIMIT
  20
```

### Expected SQL output

```SQL
SELECT
  *,
  c1 + c2 AS new_col
FROM
  tb1
ORDER BY
  c1 DESC,
  c3
LIMIT
  20
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
I'm not sure I understand — surely the result will be sorted by `c3`, given that's the final `sort` transform?

**Comment by not-my-profile** [comment]
Yes, transforms in PRQL have the semantics of being applied one after another. So that the initial sort doesn't show up in the generated SQL is correct since that transform doesn't actually have any effect since it's overridden by the final sort (and for derive the order doesn't matter).
