### ISSUE TITLE
Are we OK to version all crates together?

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#3047]
### What's up?

From https://github.com/PRQL/prql/pull/3000#discussion_r1269859218

Currently all crates release the version we specify when we release. I'd propose having them all inherit from the main workspace version. We've had success doing that for all crates so far, so I think we'd need some compelling reasons to deviate from that...

**Comment by not-my-profile** [comment]
As I said in that thread I dislike the practice of needless version bumps but I see that you have already bumped them all in #3046.

**Comment by max-sixty** [comment]
> As I said in that thread I dislike the practice of needless version bumps but I see that you have already bumped them all in #3046.

Yes, they bump automatically with our release script (though because they're not published, it would be possible to reverse that)

**Comment by not-my-profile** [comment]
You cannot release a crate with dependencies on unpublished crates (crates.io doesn't let you). ... I just set `publish = false` in `prql_ast` and `prql_parser` to prevent accidental publishes until they're deemed ready ...

**Comment by max-sixty** [comment]
Ah good point, so the release is going to fail. I should have thought of that... I'll fix now

**Comment by not-my-profile** [comment]
Yes ... so there's no reversing that ... which is what I meant by deciding to release now with the current release script you've answered your own question.

**Comment by max-sixty** [comment]
Yes agree. I do think we should release, and shouldn't wait in order to revisit this discussion. I hope that comes across as a reasonable tradeoff...

**Comment by not-my-profile** [comment]
There hasn't been a release in two months, so I don't really understand the sudden rush. I don't mind you making executive decisions, I am just off put by you filing such an issue about the opinion of others only to make the decision by yourself 40mins later.

**Comment by max-sixty** [comment]
Ok, for context I had been commiting on Discord to release for a few days! (Though it shouldn't be necessary to be on Discord to have project context; possibly I should have been updating the release issue too.)

And FWIW I opened the issue because I saw they'd been bumped; I hadn't realized we needed to release these at the time preventing reverting; hence the 0.9.0 release failing.

I hope that's reasonable. Very much appreciate you expressing & conceptualizing any perceived annoyance.

**Comment by eitsupi** [comment]
Sorry to be away from this project for a while, but I don't understand why you merged #3000 before releasing 0.9.0.

It was mentioned weeks ago that 0.9.0 was releasable (https://github.com/PRQL/prql/issues/2689#issuecomment-1628713521).

**Comment by max-sixty** [comment]
Sounds like there's general disquiet — sorry.

I hadn't released because I wanted to work on the changelog, but hadn't found the time. I generally don't think we should block things unless really necessary.

In retrospect I should have released earlier. Do folks agree? Are there other things we should have done differently?

**Comment by eitsupi** [comment]
> I hadn't released because I wanted to work on the changelog, but hadn't found the time. I generally don't think we should block things unless really necessary.

I agree, but the release had been blocked for the past few weeks or months.
To me it is natural that the 0.9.0 release takes precedence over the merge of #3000 (which of course was not on the milestone).

My point is probably the same as @not-my-profile.
The timing of the release and the choice of PRs to include in the release seems unreasonable to me.

---

By the way I think it is worth to use the same version at least until reaching 1.0.0 to reduce administration hassle.

**Comment by max-sixty** [comment]
> To me it is natural that the 0.9.0 release takes precedence over the merge of #3000 (which of course was not on the milestone).
> 
> My point is probably the same as @not-my-profile. The timing of the release and the choice of PRs to include in the release seems unreasonable to me.

OK, agree in retrospect. I think the biggest changes come out of this:
- I will be more attentive — I was away for a couple of weeks and then moving house, but I should have recognized the tradeoffs between a release and #3000
- Now we have more contributors (great!), we should be even more hesitant to do anything that would block a release. It's not always possible to obey this principle, and some alternatives (massive PRs / long-lived branches with a different base of code) are worse, but we should try.

FWIW, I'm doing things such as the release because I'm trying to fill the holes of things others are less keen on doing. But if anyone else wants to do things like this, please go ahead — I'm not protective over them.

Is that a reasonable retrospective on the mistakes here? What else should we be doing differently?

**Comment by max-sixty** [comment]
> By the way I think it is worth to use the same version at least until reaching 1.0.0 to reduce administration hassle.

WDYM?

**Comment by aljazerzen** [comment]
> > By the way I think it is worth to use the same version at least until reaching 1.0.0 to reduce administration hassle.
> 
> WDYM?

Probably that while we are in the stage of rapid development, it's easier to keep all versions of crates, cli and the language in sync. And bump crate versions even if nothing was changed.

--- 

> I'm doing things such as the release because I'm trying to fill the holes of things others are less keen on doing

Maybe we could lift this work off the spiritual leader of the project :D Having a dedicated release manager for each version would probably benefit the release cycle.

**Comment by max-sixty** [comment]
> Probably that while we are in the stage of rapid development, it's easier to keep all versions of crates, cli and the language in sync. And bump crate versions even if nothing was changed.

Ah great, agree.
