### ISSUE TITLE
prql-compiler 0.9.0 is not released on crates.io

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#3051]
https://github.com/PRQL/prql/issues/3047#issuecomment-1649164903

**Comment by max-sixty** [comment]
Yes, we need to do a 0.9.1. I commented on Discord. I'll do it tomorrow (heading to sleep now)

**Comment by eitsupi** [comment]
Perhaps a release dry run should be done with a nightly build to prevent such accidents.

**Comment by max-sixty** [comment]
Is there something that would have picked this up? That would be great if there were.

**Comment by eitsupi** [comment]
> Is there something that would have picked this up? That would be great if there were.

The Cargo book says:

> It is recommended that you first run cargo publish --dry-run (or [cargo package](https://doc.rust-lang.org/cargo/commands/cargo-package.html) which is equivalent) to ensure there aren’t any warnings or errors before publishing. This will perform the first three steps listed above.
>
> $ cargo publish --dry-run

https://doc.rust-lang.org/cargo/reference/publishing.html

**Comment by max-sixty** [comment]
FYI resolving more issues in https://github.com/PRQL/prql/pull/3065

`cargo release --dry-run` & `cargo publish -p prql-compiler` & `cargo publish -p prql-ast` all pass (or fail for an expected reason, such as `prql-ast` not being published)

**Comment by max-sixty** [comment]
Closing.

Quite a mess today, I'm sorry to all those who it stressed out. If folks have thoughts about what went wrong / what we could have done better, feel free to add here. I've taken a first pass at https://github.com/PRQL/prql/issues/3047#issuecomment-1650259896:


>   - I will be more attentive — I was away for a couple of weeks and then moving house, but I should have recognized the tradeoffs between a release and [refactor: extract `prql_ast` and `prql_parser` crates #3000](https://github.com/PRQL/prql/pull/3000)
> 
>   - Now we have more contributors (great!), we should be even more hesitant to do anything that would block a release. It's not always possible to obey this principle, and some alternatives (massive PRs / long-lived branches with a different base of code) are worse, but we should try.

And from @aljazerzen :

> Maybe we could lift this work off the spiritual leader of the project :D Having a dedicated release manager for each version would probably benefit the release cycle.

I'm ofc happy to share this...

**Comment by eitsupi** [comment]
Thank you for doing the release work and associated miscellaneous tasks.

I am confused about the failed release in 0.9.1 as well. Why was 0.9.1 needed?

**Comment by max-sixty** [comment]
0.9.1 failed because those crates were missing descriptions: https://github.com/PRQL/prql/actions/runs/5660154608/job/15335261686

https://github.com/PRQL/prql/pull/3065 fixed this, and reverted some other changes that I'd missed
