### ISSUE TITLE
Link to the Prefect integration on the homepage is broken

### ISSUE THREAD

**Issue by snth** [PRQL/prql#3074]
### What happened?

The link to the Prefect integration on the main page is broken:
![image](https://github.com/PRQL/prql/assets/652285/1623121b-b428-4d8a-bca9-b4fddff2cef7)

### PRQL input

```elm
Broken link: https://prql-lang.org/book/integrations/prefect.html
```

### SQL output

```SQL
Correct link: https://prql-lang.org/book/project/integrations/prefect.html
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
#3075
