### ISSUE TITLE
Unify GHA linux cache

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#3096]
### What's up?

Currently `prqlc` is built on every PR with `-musl`: https://github.com/PRQL/prql/actions/runs/5663989436/job/15346734099?pr=3093#step:3:42

But the linux GHA cache is build with `-gnu`: https://github.com/PRQL/prql/actions/runs/5663989436/job/15346734529?pr=3093#step:7:4

So the prqlc cache misses every time.

Is it possible for us to use the same one for both?

(Tagging @eitsupi because they seem to know this area, hope that's OK)

**Comment by eitsupi** [comment]
Isn't the problem that we are setting `save-if: false`?

https://github.com/PRQL/prql/blob/975ffa505dcc1c0f1ddb94a876c201b156d7dd10/.github/actions/build-prqlc/action.yaml#L22-L27

**Comment by eitsupi** [comment]
As an aside, I don't know what the `prefix-key` does for us.
If I understand correctly, the cache is currently only updated from the main branch, so there is no problem if this does not exist.

**Comment by max-sixty** [comment]
> Isn't the problem that we are setting `save-if: false`?

We only have one cache per OS, because we're out of cache space.

If we enabled saving from the `prqlc` job, we'd need a different `shared-key` from the `test-rust` job — or we'd get a race condition the OSs where they're the same — and we'd overflow our cache space.

**Comment by eitsupi** [comment]
> If we enabled saving from the `prqlc` job, we'd need a different `shared-key` from the `test-rust` job — or we'd get a race condition the OSs where they're the same — and we'd overflow our cache space.

In other words, if we only enable the cache for `inputs.target == 'rust-x86_64-unknown-linux-musl'`, which is not tested, the problem would be solved.

**Comment by max-sixty** [comment]
> As an aside, I don't know what the `prefix-key` does for us.

The cache isn't perfect at detecting what is / isn't required, and so after a while it can accrue some files which we don't use. We were hitting 3GB caches at one point.

Cycling a cache key occasionally starts afresh, solving this problem

**Comment by eitsupi** [comment]
> The cache isn't perfect at detecting what is / isn't required, and so after a while it can accrue some files which we don't use. We were hitting 3GB caches at one point.

Oh, I see. Thanks.

**Comment by max-sixty** [comment]
> In other words, if we only enable the cache for `inputs.target == 'rust-x86_64-unknown-linux-musl'`, which is not tested, the problem would be solved.

Yes. Though we are very short on cache space... ideally we would unify them.

But if we can't do that, we can try adding that and seeing if we overflow on a single build...

**Comment by aljazerzen** [comment]
Things like this and duckdblib not being cached may be avoided if we used nix a the "framework for building stuff". There are [libraries](https://github.com/nix-community/naersk) that make Rust+Nix combination quite easy and additionally, the whole build+test pipeline could be tested locally.

(I don't have much say here, since I'm not in devops much, just an idea)

**Comment by max-sixty** [comment]
[me trying to learn about musl vs gnu](https://chat.openai.com/share/13d8f3d7-ef2d-4e12-ad9e-7ae2926a0c30)

**Comment by aljazerzen** [comment]
That is quite informative and (as far as I know) correct.

**Comment by max-sixty** [comment]
Is there a big benefit to using musl? Or is it just best practice?

**Comment by eitsupi** [comment]
I learned of musl's existence because binaries built with gnu, which is easy to build, did not work in my test environment. In other words, if you build with a gnu target, it is not portable. (It requires additional package installation to make it work)

**Comment by max-sixty** [comment]
Closed by unifying the caches by OS & target
