### ISSUE TITLE
Support for date operations, e.g. datepart/extract

### ISSUE THREAD

**Issue by ibestvina** [PRQL/prql#3109]
Does PRQL support date/time operations such as datepart or extract, and what is currently the best way of achieving something like:

```sql
SELECT DATEPART(week, [date]) AS WeekNumber,
       AVG([sales]) AS AverageWeeklySales
FROM sales
GROUP BY DATEPART(week, [date])
ORDER BY WeekNumber
```

**Comment by aljazerzen** [comment]
Currently, this is not yet implemented. 

Tracking in #366. We should really get around to this.

As a workaround, you can use s-strings:

```elm
from sales
derive WeekNumber = s"DATEPART({week}, [date])"
group WeekNumber (
  aggregate {AverageWeeklySales = average sales}
)
sort WeekNumber
```
