### ISSUE TITLE
Evaluate Profile-Guided Optimization (PGO)

### ISSUE THREAD

**Issue by zamazan4ik** [PRQL/prql#3116]
Hi!

Recently I checked Profile-Guided Optimization (PGO) improvements on multiple projects. The results are [here](https://github.com/zamazan4ik/awesome-pgo/).

Since PGO showed measurable improvements in compiler-like loads (Rustc, Clang, Clangd, clang-format, GCC, etc.), I think it could be useful to check PGO on prql too.

We need to perform PGO benchmarks on prql compiler. And if it shows improvements - add a note about possible improvements in prql performance with PGO.

For the Rust projects I suggest starting with [cargo-pgo](https://github.com/Kobzol/cargo-pgo).

**Comment by max-sixty** [comment]
I'm open to it — but runtime performance is more than adequate at the moment — so I would vote to not weigh it highly if it means adding complexity to any of the build steps...

**Comment by max-sixty** [comment]
Marking this as postponed. If someone wants to champion it, then open to exploring it.
