### ISSUE TITLE
Support old mysql engine

### ISSUE THREAD

**Issue by inferrna** [PRQL/prql#3121]
Hi. This example generates code incompatible with mysql older than 8.0 because of ROW_NUMBER()

```bash
echo "from employees| group role (sort join_date | take 1)" | prqlc compile -t sql.mysql
```
<details>
  <summary>Resulting query</summary>

```sql
WITH table_0 AS (
  SELECT
    *,
    ROW_NUMBER() OVER (
      PARTITION BY role
      ORDER BY
        join_date
    ) AS _expr_0
  FROM
    employees
)
SELECT
  *
FROM
  table_0
WHERE
  _expr_0 <= 1

```
</details>
Mysql below 8.0 is supposed to use user defined variables for tasks like this. Similar example here: https://www.sqlines.com/mysql/how-to/get_top_n_each_group.

So it would be nice to have target like sql.mysql_old.

**Comment by max-sixty** [comment]
If someone wanted to champion this, we'd accept it. But to offer full transparency — I think it's quite unlikely we priortize a legacy dialect from the perspective of the project...

**Comment by eitsupi** [comment]
Thanks for reporting that.

While working on translating the operators I think I saw a few that don't work in MySQL 5.X.
Do you think it would be worthwhile to support MySQL 5.X?

**Comment by inferrna** [comment]
I just realized that mysql 5.7 ends in 3 months (31 Oct 2023). So we instead migrate to 8.x, thank you.

**Comment by eitsupi** [comment]
Thank for your info!
I will close this for now.
