### ISSUE TITLE
Lack of a page of "relation literal" on the book

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#3123]
Something like:

```elm
let a = from [
      {a = 1, b = 10},
      {a = 2, b = 20},
      {a = 3, b = 30},
      {a = 4, b = 40},
      {a = 5, b = 50},
    ]
 
from a
```

**Comment by aljazerzen** [comment]
This is described the tutorial: https://github.com/PRQL/prql/pull/3052/files#diff-06c6ed121123e6a7381f65cb361dc13e27939d66161a50dcd6b15befbaef4f13

Because it is a logical consequence of arrays and tuples, I didn't feel the need to include it in the reference.

**Comment by eitsupi** [comment]
Oh, I see. Thanks.

I think there used to be a `from_text` page, so I was hoping this page would be similar to that.
