### ISSUE TITLE
Lack of multiple conditions example on book

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#3128]
### What happened?

prql-compiler 0.8.1 allows:

```elm
from a
join b [==col1, ==col2]
```

But prql-compiler 0.9.2 doesn't allow now.

```
Error: 
   ╭─[:2:15]
   │
 2 │ join b (==col1, ==col2)
   │               ┬  
   │               ╰── unexpected , while parsing function call
───╯
```

### PRQL input

```elm
from a
join b (==col1, ==col2)
```

### SQL output

```SQL
NA
```

### Expected SQL output

```SQL
SELECT
  a.*,
  b.*
FROM
  a
  JOIN b ON a.col1 = b.col1
  AND a.col2 = b.col2
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by aljazerzen** [comment]
This is intended behavior: you have to use `&&`.

**Comment by eitsupi** [comment]
> This is intended behavior: you have to use `&&`.

Oh, sorry. I had forgotten that such a thing had been mentioned in an earlier discussion.
As there is currently nothing in the documentation that does joins with multiple conditions, so we should add something.
