### ISSUE TITLE
count column_name compiles to count(*)

### ISSUE THREAD

**Issue by kukimik** [PRQL/prql#3139]
### What's up?

`count colum_name` compiles to `COUNT(*)`.

<details><summary> Here's an example <a href="https://prql-lang.org/book/reference/syntax/pipes.html#inner-transforms">from the docs</a>.</summary>

```
from employees
group {title, country} (
  aggregate {
    average salary,
    ct = count salary,
  }
)
```

compiles to

```sql
SELECT
  title,
  country,
  AVG(salary),
  COUNT(*) AS ct
FROM
  employees
GROUP BY
  title,
  country
```

</details>

This may be surprising to people coming from SQL (at least it was surprising to me). In SQL `COUNT(column_name)` is not equivalent to `COUNT(*)`. The first one counts the rows whose `column_name` field is not null, the second one counts all rows. Is always compiling to `COUNT(*)` a conscious design decision? If so, how is it justified? And what is the purpose of the `column_name` argument if it is always compiled to `*`? Wouldn't it make more sense to get rid of it?

**Comment by max-sixty** [comment]
I _think_ this is a mistake which crept in to 0.9.0 after the refactoring — @aljazerzen is that your understanding?

**Comment by kukimik** [comment]
This comment (introduced in https://github.com/PRQL/prql/commit/83b966e420a2e07827b864d4bd93a05a36124e63):

https://github.com/PRQL/prql/blob/864c5cd6652e8389445a0f6ab48a462492d1725b/crates/prql-compiler/src/semantic/std.prql#L160

indicates that this may be expected behaviour. Or maybe I misunderstand the comment.

**Comment by aljazerzen** [comment]
You did understand that correctly, we removed the "count only non-null values" behavior of `count` function. I believe I included this in the changelog as a breaking change.

The rationale here is that we want to prepare ground for more orthogonal approach, where `count` returns length of an array and `count (column_name | filter this != null)` can be used to count only non-null values.

**Comment by max-sixty** [comment]
> The rationale here is that we want to prepare ground for more orthogonal approach, where `count` returns length of an array and `count (column_name | filter this != null)` can be used to count only non-null values.

Sorry, ofc we did discuss this. I don't think I'd internalized we'd do it in this order. But overall I do find the proposal a great improvement.

**Comment by kukimik** [comment]
Thanks for clarification. I'm not sure how arrays work (docs are a stub), but I think this answers my question.
