### ISSUE TITLE
How can I run `pre-commit.ci` before pushing to my repo?

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#3149]
### What's up?

`pre-commit.ci` makes a bunch of (useful) changes after I push to my repo. This dirties up the commit history.

How can I run it prior to pushing? Is there a `task run...` that will do this? Thanks.

**Comment by max-sixty** [comment]
(4) [here](https://pre-commit.com/)!

**Comment by richb-hanover** [comment]
To flesh out this answer for the Dev Container: use `pre-commit run --all-files` To set this up:

- I installed `pre-commit` within the Dev Container with `pip install pre-commit`
- (Optional) I updated pip with `python -m pip install --upgrade pip`
- I then ran `pre-commit run --all-files` to check the files prior to committing them.
