### ISSUE TITLE
no way to select non-trivial constants without a table

### ISSUE THREAD

**Issue by vthriller** [PRQL/prql#3169]
### What's up?

To prevent explosion of aggressively inlined expressions one might want to rewrite some `let` expressions as CTEs, e.g. to go from

```
let ma = case {
	s"version()" ~= 'mingw32|64-bit|x86_64|ppc64|ia64|amd64' => 8,
	true => 4,
}
let bs = s"current_setting('block_size')::numeric"
```

to

```
join (select {
	ma = case {
		s"version()" ~= 'mingw32|64-bit|x86_64|ppc64|ia64|amd64' => 8,
		true => 4,
	},
	bs = s"current_setting('block_size')::numeric",
}) (true)
```

which, AFAICS, is not currently possible without some `from __FIXME_DUMMY_TABLE`.

**Comment by max-sixty** [comment]
Yes, I think this is https://github.com/PRQL/prql/issues/1772, is that right?

**Comment by vthriller** [comment]
No, I'm not talking about `let`.

Anyway, I just found there is actually a way to achieve what I wanted, it's `from s"..."`:

```
join (from s"select 
	case
		when version() ~ 'mingw32|64-bit|x86_64|ppc64|ia64|amd64' then 8
		else 4
	end as ma,
	current_setting('block_size')::numeric as bs
") (true)
```

which, I think, is fine for rare occasions like crunching internal DB statistics.

(Funny thing is, I managed to skim over `from s""` feature multiple times while reading the docs and only discovered it by accident via "s-strings representing a table must start with `SELECT `" error while I was tinkering in the playground.)

Feel free to label as documentation issue (that would be a nice candidate for some sort of "PRQL by example") or close it outright with the resolution of "reporter doesn't know how to read our docs" (-:

**Comment by max-sixty** [comment]
> Feel free to label as documentation issue (that would be a nice candidate for some sort of "PRQL by example") or close it outright with the resolution of "reporter doesn't know how to read our docs" (-:

😂 

No I think are a few problems:
- There are times we indeed generate unclear SQL (#3170 has good examples)
- Docs could indeed be more explicit
- But even better than improved docs on s-strings would be avoiding the s-strings! Our vision for those are as an escape hatch, not as a good way to write PRQL. (though at the moment they're completely essential)
- ~I think functions might help here, to the extent you want to break up the PRQL (but doesn't help with the SQL) — to what extent is that an issue for you? Or is this only an issue with incomprehensible SQL?~ Edit: actually not that helpful

For example:

```elm
let ma = tbl -> (
  tbl
  derive x = case {
    s"version()" ~= "mingw32|64-bit|x86_64|ppc64|ia64|amd64" => 8,
    true => 4,
  }
)

from y
ma
```

```sql
SELECT
  *,
  CASE
    WHEN REGEXP(
      version(),
      'mingw32|64-bit|x86_64|ppc64|ia64|amd64'
    ) THEN 8
    ELSE 4
  END AS x
FROM
  y

-- Generated by PRQL compiler version:0.9.2 (https://prql-lang.org)
```

**Comment by vthriller** [comment]
> I think functions might help here, to the extent you want to break up the PRQL (but doesn't help with the SQL) — to what extent is that an issue for you? Or is this only an issue with incomprehensible SQL?

Well, the original issue is actually #3170, and what #3169 is about is actually a stop-gap measure to prevent constant table-agnostic expressions from being inlined, so that `ma` remains `ma` in generated code and does not expand to monstrous `case` expression.

Back to your example:
- it still requires some table to be selected from,
- it doesn't achieve the original goal of preventing inlining.

That is, if I expand that example with, say,

```
derive a = pages * x
derive b = tuples % x
select a+b
```

I still get

```sql
SELECT
  pages * CASE
    WHEN REGEXP(
      version(),
      'mingw32|64-bit|x86_64|ppc64|ia64|amd64'
    ) THEN 8
    ELSE 4
  END + tuples % CASE
    WHEN REGEXP(
      version(),
      'mingw32|64-bit|x86_64|ppc64|ia64|amd64'
    ) THEN 8
    ELSE 4
  END
FROM
  y

-- Generated by PRQL compiler version:0.9.2 (https://prql-lang.org)
```

which should be fine in this toy example, but would definitely blow up further down the pipeline.

**Comment by max-sixty** [comment]
Yes OK, that's a good case. The functions don't really help here, because this is about the SQL that's generated.

The regex example above is a good case for something that should be in a CTE.

I do think this is a difficult problem — what are the rules for whether something should be put into a CTE? That it's complex? That it's repeated?

We could imagine generating lots of possible queries and then selecting one for the lowest value of some complexity metric. But that's an exponentially difficult problem. Instead, there might be some heuristics — e.g. assign a score for each expression and put it in a CTE if the total complexity rises beyond a certain level?

(The thing I don't think we should do is offer an interface to directly control CTE creation — then the interface becomes too coupled with SQL itself...)

**Comment by vthriller** [comment]
> what are the rules for whether something should be put into a CTE? That it's complex? That it's repeated?

Both sound okay, I think. Thresholds for expression complexity might be a bit tricky, as a) one can think of many ways to measure that (# of operators? # of produced lexemes? `strlen()`?), b) DB engines will have different tolerance levels. Number of indirect inclusions might be easier to implement, and it also might be effective enough at first (80/20 rule and all that).

**Comment by vthriller** [comment]
Also, if no one could remember another reason to have table-free selects, we might disregard this issue and continue discussion about inlining in #3170. I personally would be fine with leaving s-strings for querying DB internals.

**Comment by max-sixty** [comment]
> Also, if no one could remember another reason to have table-free selects, we might disregard this issue and continue discussion about inlining in #3170. I personally would be fine with leaving s-strings for querying DB internals.

Yeah, my current (weakly-ish held) view is that we should not focus on an interface which guarantees where the statement will end up — whether it's a select or not. Instead we should:
- always get the result correct
- try and produce legible SQL

So we're more like a C compiler into assembly, than a SQL macro engine (like dbt's front end).

Does that answer this question, and we should indeed move to #3170? Or am I still missing something?

**Comment by vthriller** [comment]
Yeah, I have nothing to follow up with here. Closing.
