### ISSUE TITLE
Improve release workflow to prevent release error

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#3179]
Releases 0.9.0 and 0.9.1 failed to publish prql-compiler to crates.io. (#3051)

To prevent this, it is necessary to test whether it is possible to publish by executing a command like `cargo release` in advance.

```sh
$ cargo release
error: tag `0.9.2` already exists (for `prql-compiler-macros`)
error: prql-ast 0.9.2 is already published
error: prql-parser 0.9.2 is already published
error: prql-compiler 0.9.2 is already published
error: prql-compiler-macros 0.9.2 is already published
error: prqlc 0.9.2 is already published
warning: updating prql-compiler-macros to 0.9.2 despite no changes made since tag 0.9.2
warning: updating prql-java to 0.9.2 despite no changes made since tag 0.9.2
  Publishing prql-ast
    Updating crates.io index
   Packaging prql-ast v0.9.2 (/workspaces/prql/crates/prql-ast)
    Packaged 10 files, 17.1KiB (5.1KiB compressed)
   Uploading prql-ast v0.9.2 (/workspaces/prql/crates/prql-ast)
warning: aborting upload due to dry run
  Publishing prql-parser
    Updating crates.io index
   Packaging prql-parser v0.9.2 (/workspaces/prql/crates/prql-parser)
    Packaged 9 files, 101.9KiB (16.4KiB compressed)
   Uploading prql-parser v0.9.2 (/workspaces/prql/crates/prql-parser)
warning: aborting upload due to dry run
  Publishing prql-compiler
    Updating crates.io index
   Packaging prql-compiler v0.9.2 (/workspaces/prql/crates/prql-compiler)
    Packaged 157 files, 1.1MiB (298.4KiB compressed)
   Uploading prql-compiler v0.9.2 (/workspaces/prql/crates/prql-compiler)
warning: aborting upload due to dry run
  Publishing prql-compiler-macros
    Updating crates.io index
   Packaging prql-compiler-macros v0.9.2 (/workspaces/prql/crates/prql-compiler-macros)
    Packaged 3 files, 2.5KiB (1.3KiB compressed)
   Uploading prql-compiler-macros v0.9.2 (/workspaces/prql/crates/prql-compiler-macros)
warning: aborting upload due to dry run
  Publishing prqlc
    Updating crates.io index
   Packaging prqlc v0.9.2 (/workspaces/prql/crates/prqlc)
warning: package `hermit-abi v0.3.1` in Cargo.lock is yanked in registry `crates-io`, consider updating to a version that is not yanked
    Packaged 15 files, 157.0KiB (27.7KiB compressed)
   Uploading prqlc v0.9.2 (/workspaces/prql/crates/prqlc)
warning: aborting upload due to dry run
     Pushing Pushing 0.9.2, compile-files-v0.9.2, main, misc-v0.9.2, prql-ast-v0.9.2, prql-compiler-v0.9.2, prql-parser-v0.9.2, prql-v0.9.2, prqlc-v0.9.2 to origin
error: dry-run failed, resolve the above errors and try again.
```

This check will fail if the same version has already been published on crates.io.

Therefore, the local version must be upgraded before the test is run.
Our current workflow is to version up just before release, but is it worth versioning up right after release?
Or would it be better to configure GitHub Actions to only run tests if the version of crates.io and the local version differ?

https://github.com/PRQL/prql/blob/1f9e8c59e5889f31a605b870ea5b1e8fb3323135/web/book/src/project/contributing/development.md?plain=1#L383-L435

**Comment by max-sixty** [comment]
Yes, WDYT about this suggestion? https://github.com/PRQL/prql/issues/2957#issuecomment-1627707689

**Comment by eitsupi** [comment]
> Yes, WDYT about this suggestion? [#2957 (comment)](https://github.com/PRQL/prql/issues/2957#issuecomment-1627707689)

I like it but I don't know if something like `0.9.3-alpha` will work, given that we need to select a version number that is allowed by package registries (crates.io and PyPI and...?).

**Comment by eitsupi** [comment]
It seems that the latest version on crates.io can get with this command.

```sh
$ curl -sL https://crates.io/api/v1/crates/prql-compiler/versions | jq -r '.versions[].num' | sort -V | tail -n 1
0.9.2
```

**Comment by max-sixty** [comment]
Good point. It seems actually quite difficult to have something that works with crates.io, PyPI & npm (source: [overly long conversation with GPT-4](https://chat.openai.com/share/f6b8f15c-1cd8-4c76-96f3-fe6c9b925361))

So maybe we bump to 0.9.3 immediately after releasing 0.9.2?

**Comment by eitsupi** [comment]
> So maybe we bump to 0.9.3 immediately after releasing 0.9.2?

I think it is easy and reasonably effective. I believe duckdb does that and deploys development versions to the web shell all the time.
