### ISSUE TITLE
Dead links to https://docs.rs/prql-compiler/latest/prql_compiler/ast/ in code comments

### ISSUE THREAD

**Issue by kukimik** [PRQL/prql#3186]
### What's up?

https://docs.rs/prql-compiler/latest/prql_compiler/ast/ is a dead link, yet it appears in comments in several places:

https://github.com/PRQL/prql/blob/c1edb812c11149529796cef3f68ee9a80ed227f3/bindings/prql-lib/libprql_lib.hpp#L102
https://github.com/PRQL/prql/blob/c1edb812c11149529796cef3f68ee9a80ed227f3/bindings/prql-lib/libprql_lib.hpp#L131
https://github.com/PRQL/prql/blob/c1edb812c11149529796cef3f68ee9a80ed227f3/bindings/prql-lib/libprql_lib.h#L134
https://github.com/PRQL/prql/blob/c1edb812c11149529796cef3f68ee9a80ed227f3/bindings/prql-lib/libprql_lib.h#L167
https://github.com/PRQL/prql/blob/c1edb812c11149529796cef3f68ee9a80ed227f3/bindings/prql-dotnet/PrqlCompiler/PrqlCompiler.cs#L65
https://github.com/PRQL/prql/blob/c1edb812c11149529796cef3f68ee9a80ed227f3/bindings/prql-dotnet/PrqlCompiler/PrqlCompiler.cs#L109
https://github.com/PRQL/prql/blob/c1edb812c11149529796cef3f68ee9a80ed227f3/bindings/prql-lib/src/lib.rs#L46
https://github.com/PRQL/prql/blob/c1edb812c11149529796cef3f68ee9a80ed227f3/bindings/prql-lib/src/lib.rs#L92

**Comment by max-sixty** [comment]
Thanks a lot for finding those @kukimik . Fixed in #3189
