### ISSUE TITLE
Rename "chinook" section in playground

### ISSUE THREAD

**Issue by not-my-profile** [PRQL/prql#3201]
The sidebar in the playground currently has the queries for the sample tables under the "chinook" heading.

Users might be confused what a "chinook" is ... I certainly was. "sample tables" or something like that would probably be more clear.

The key would apparently have to be changed in this object:

https://github.com/PRQL/prql/blob/97cdc93b317d19712fba7ae0414d4eeb8b50c4a6/web/playground/src/app/App.js#L27-L32

**Comment by postmeback** [comment]
Can i work in this issue ??

**Comment by max-sixty** [comment]
Yes & yes, thanks!
