### ISSUE TITLE
Can the `prqlc` prompt only show when waiting?

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#3228]
### What's up?

We have a prompt which shows when running `prqlc compile`, to avoid appearing to hang while waiting for an input — "Enter PRQL, then press ctrl-d to compile:`" 

I think that's great, I quite dislike the confusion in CLIs where it's unclear if they're thinking or waiting. IIRC, doing this is in a bunch of "CLI best practices" guides

But it also shows `Enter PRQL, then press ctrl-d to compile:` when something is piped in:

```sh
$ echo "from artists" | prqlc compile -
Enter PRQL, then press ctrl-d to compile:

SELECT
  *
FROM
  artists

-- Generated by PRQL compiler version:0.9.2 (https://prql-lang.org)
```

Weirdly I can't remember that happening previously; do others?

Is there some way we can only show when it's waiting, and not when piping text in?

**Comment by eitsupi** [comment]
I downloaded prqlc from https://github.com/PRQL/prql/actions/runs/5333165066 (nightly build from d5d5362722985593db50bb67c00c7594217702be), but that did not show up.
I believe this change was made somewhere between 0.8 and 0.9.

**Comment by eitsupi** [comment]
I went back through the history of cli.rs and tried each prqlc attached to the PR in turn and found that this occurred in #2885.

Maybe due to this change?
https://github.com/PRQL/prql/pull/2885/files#diff-5042ecb23fbc2e8750e6452e008e9e96007bc06be4dff012653aedeaede02865L411

**Comment by max-sixty** [comment]
Great find @eitsupi ! Thanks for looking through the history.

---

The weird part of this is that it seems to be doing exactly the same thing as we were: https://github.com/aj-bagwell/clio/blob/v0.3.3/src/path.rs#L275

(the only part I can see that's different is the `input.path() == Path::new("-") && `, but that's surely not the thing?!)

I can try reverting that and see if it fixes it
