### ISSUE TITLE
PRQL equivalent of `ilike`

### ISSUE THREAD

**Issue by samuelcolvin** [PRQL/prql#3238]
### What's up?

Hi, pqrl looks great. Thank you.

How would I go about implement the equivalent of SQL`ilike` or `like` operators?

In particular I want simple string contains, e.g. `table.foobar ilike '%foo%'`.

I've looked through the docs and searched the code, but can't find an obvious solution. Obviously I can use a regex, but that will be much less performant than a simple "string contains" query.

**Comment by max-sixty** [comment]
Thanks for the issue.

> Obviously I can use a regex, but that will be much less performant than a simple "string contains" query.

Is this necessarily the case? I don't have a good prior here, but I hadn't thought that regex searching for `foo` is necessarily worse than `like "%foo"`?

We had https://github.com/PRQL/prql/issues/1123, but closed it in preference of the regex implementation

**Comment by FinnRG** [comment]
@max-sixty The database cannot utilize text indexes (i.e. GIN indexes for Postgres) when using a regex.

**Comment by max-sixty** [comment]
Ah, thanks.

Maybe we compile `derive x =~ "foo"` to `LIKE "%foo%"` — i.e. if it's possible to use `LIKE`, then we do that, otherwise we use Regex?

**Comment by samuelcolvin** [comment]
@max-sixty makes sense.

What I think I would most like is something similar to
* `'foo' in x` or `x.contains('foo')`
* `x.startsWith('foo')`
* `x.endsWith('foo')`

For me these would be the most intuitive ways to describe 99% of `like` usage. But I'm not sure if it fixes with the design philosophy of PRQL?

**Comment by eitsupi** [comment]
> What I think I would most like is something similar to
> 
>     * `'foo' in x` or `x.contains('foo')`
> 
>     * `x.startsWith('foo')`
> 
>     * `x.endsWith('foo')`
> 
> 
> For me these would be the most intuitive ways to describe 99% of `like` usage. But I'm not sure if it fixes with the design philosophy of PRQL?

I like this idea.
`like` function (I think it would be a function if we implement `like` because operators should be symbols) could be difficult to translate to non-SQL backends, but starts with, etc. can be implemented with regular expressions in other backends.

**Comment by max-sixty** [comment]
My vision was that we could do all of this with `~=`:

| Request | Proposal | SQL Equivalent |
|---|---|---|
| `'foo' in x` or `x.contains('foo')` | `x ~= "foo"` | `x LIKE '%foo%'` |
| `x.startsWith('foo')` | `x ~= "^foo"` | `x LIKE 'foo%'` |
| `x.endsWith('foo')` | `x ~= "foo$"` | `x LIKE '%foo'` |


Those could compile to variants of `x LIKE %foo%` — it's trivial to convert the regexes into the `LIKE` where it's possible (I'm not even sure why DBs don't do this themselves tbh...)

The only downside is that some very basic regex is needed — `^` & `$`.

What do folks think?

**Comment by samuelcolvin** [comment]
I personally think that for casual users `contains`/`in`, `startswith` and `endswith` would be massively easier to read and understand.

`~=` looks to me like "not equal to" (e.g. in MATLAB and lua) or "approximately", which is not your intended meaning.

But any option would be great.

**Comment by vanillajonathan** [comment]
I also proposed methods in discussion #1767.

I think `x.contains("foo")`,`x.startsWith("foo")`, and `x.endsWith("foo")` would be nice.

**Comment by richb-hanover** [comment]
**Partial Solution:** See https://github.com/PRQL/prql/issues/1123
