### ISSUE TITLE
Special function to return PRQL version

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#3260]
Integrations such as the prql dialect on ClickHouse (which does not display post-compilation SQL) do not easily know the version of the PRQL language that can be used.
I wonder if it might be worth implementing a special function (?) that returns the PRQL compiler version as a string to know the PRQL version in such cases.

Something like:

```elm
from prql_version
```

Compiles to

```sql
SELECT '0.9.4'
```

This is also useful:

```elm
from foo
select bar = prql_version
```

Compiles to

```sql
SELECT
  '0.9.4' AS bar
FROM
  foo
```

**Comment by max-sixty** [comment]
Yes — maybe a `prql` namespace, so like `prql.version`?

**Comment by eitsupi** [comment]
> Yes — maybe a `prql` namespace, so like `prql.version`?

I like this.
It makes sense to reserve the `prql` namespace.

**Comment by vanillajonathan** [comment]
Now imagine if `prql.version` was a struct or a object, so you could do `prql.version.major` and `prql.version.minor`.

**Comment by hulxv** [comment]
I want to take this issue. How can I start from the codebase?

**Comment by max-sixty** [comment]
> I want to take this issue. How can I start from the codebase?

Great.

We can model this on `std.floor`. Here's an example of its use: https://github.com/PRQL/prql/blob/0d342efd4482580244f702565c97cc779d692c42/crates/prql-compiler/src/semantic/eval/mod.rs#L474

Here's where it's defined: https://github.com/PRQL/prql/blob/0d342efd4482580244f702565c97cc779d692c42/crates/prql-compiler/src/semantic/eval/mod.rs#L157-L167

And here's where we can get the version from: https://github.com/PRQL/prql/blob/9c6ea2a2fa3eea2597b8596c4231f46036a30f4b/crates/prql-compiler/src/lib.rs#L106-L108

Does that make sense? Feel free to ask any questions!

**Comment by vanillajonathan** [comment]
But could it be a struct on `prql` though so you could do `prql.version.major` and `prql.version.minor`?

**Comment by max-sixty** [comment]
> But could it be a struct on `prql` though so you could do `prql.version.major` and `prql.version.minor`?

Maybe later, let's keep it simple at first

**Comment by hulxv** [comment]
Thanks, @max-sixty  for help. but I have another question, please.

> Yes — maybe a `prql` namespace, so like `prql.version`?

How can I create a new namespace? should I do something like this in [eval body](https://github.com/PRQL/prql/blob/0d342efd4482580244f702565c97cc779d692c42/crates/prql-compiler/src/semantic/eval/mod.rs#L136-L286) or there's another way?

```rust
 "std.prql.version" => { 
     // func body
 } 
```

**Comment by max-sixty** [comment]
I think we can just use `"prql.version" => {...`, no need for the `std.`

(We don't really have namespaces here implemented yet, so we're just matching on the string, but when we do it'll fit in quite well)

**Comment by hulxv** [comment]
Will I need to create something like [std_module](https://github.com/PRQL/prql/blob/0d342efd4482580244f702565c97cc779d692c42/crates/prql-compiler/src/semantic/eval/mod.rs#L388-L405) and change [lookup function](https://github.com/PRQL/prql/blob/0d342efd4482580244f702565c97cc779d692c42/crates/prql-compiler/src/semantic/eval/mod.rs#L97-L110)? or add new function to `std_module` directly?

**Comment by max-sixty** [comment]
> Will I need to create something like [std_module](https://github.com/PRQL/prql/blob/0d342efd4482580244f702565c97cc779d692c42/crates/prql-compiler/src/semantic/eval/mod.rs#L388-L405) and change [lookup function](https://github.com/PRQL/prql/blob/0d342efd4482580244f702565c97cc779d692c42/crates/prql-compiler/src/semantic/eval/mod.rs#L97-L110)?

Good spot! You're correct — that's necessary too. I think that should be sufficient.

(I would create a new one `prql`, rather than use the `std.` codepath for that too...)

**Comment by hulxv** [comment]
I don't want to be annoying but, Can I contact you to ask some questions? Is Discord a good way?

**Comment by max-sixty** [comment]
For sure! Discord is good — I'm less active there than GitHub, but others are on, and I'll make sure I'm on later today.

**Comment by hulxv** [comment]
@max-sixty I think this issue should be closed
