### ISSUE TITLE
Cutting time from CI

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#3290]
### What's up?

We're getting non-trivial CI queues. I'm trying to ensure CI is fast, since I worry that once queues start getting long, they don't recover — folks do fewer bigger PRs, care less about instant feedback, we feel less pressure to keep CI times short, we get longer queues — somewhat as described in https://matklad.github.io/2021/09/04/fast-rust-builds.html.

We also have an annoying effect in our pipeline around merging lots of PRs quickly; for more details:

<details>

- For a PR to merge the `check-ok-to-merge` job needs to run. It waits for most jobs within that PR's pipeline before running.
- When there's a queue, we want to merge things as soon as possible, because merging new code causes the old CI pipeline to be replaced by the new one, saving the wasted work of running tests on non-current code
- Because the `check-ok-to-merge` job waiting, the job is then queued _behind_ tests from later PRs, which can run immediately
- So CI waits for later PRs to finish their pipelines before running `check-ok-to-merge` on a previous PR and so before merging that PR
- As a result, we often can't merge quicker than the time it takes to run a full `test-all` pipeline, which is ~15 minutes atm, even we're otherwise unconstrained.

</details>

Here's a snapshot of where `test-all` spends its time: https://github.com/PRQL/prql/actions/runs/5798841411/usage

### Some ideas

- [x] Don't run bindings' tests on multiple platforms in `test-all`, at least if there are no changes. We can run them on nightly.
  - This would cut a lot — ~2/3 python jobs~, 1/2 java jobs, 1/2 elixir jobs, ~2/3 js jobs~ (edit with the ones done)
- [ ] Don't run `test-release-dry-run` in `test-all` — move to nightly. Bugs here are very rare (though very annoying when they do happen, so it's good we have a test here). 
  - We could also unify a "dry-run" (which is really a "quick-run") and running when not on a tag, which is really a dry-run. (this would also obviate `check-published`...)
- [x] Don't run `test-all` twice on some PRs — because `test-all` can be triggered in two ways, it can sometimes run twice.
- [x] Add back caching for `test-js`; it could probably share a cache with `build-web`
- ~[ ] Don't run `build-prqlc` on a standard PR. By reducing `test-all`, we can also make adding a `pr-test-all` label more palatable in order to generate a `prqlc` binary.~ Decided not to do this

**Comment by eitsupi** [comment]
>  Don't run test-release-dry-run in test-all — move to nightly. Bugs here are very rare (though very annoying when they do happen, so it's good we have a test here).

If we do this, I think it will break the release unless we have something like a feature freeze period of at least a few days before release and make sure to let the nightly builds pass.

**Comment by eitsupi** [comment]
>  Don't run build-prqlc on a standard PR. By reducing test-all, we can also make adding a pr-test-all label more palatable in order to generate a prqlc binary.

I strongly disagree. I believe there were several bugs that I would not have found the cause of without this.

**Comment by max-sixty** [comment]
> If we do this, I think it will break the release unless we have something like a feature freeze period of at least a few days before release and make sure to let the nightly builds pass.

We can always label a PR `pr-nightly`, which then runs the nightly workflow, to confirm the release process passes before releasing? We could have a rule to do this on the release notes, for example?

**Comment by max-sixty** [comment]
> > Don't run build-prqlc on a standard PR. By reducing test-all, we can also make adding a pr-test-all label more palatable in order to generate a prqlc binary.
> 
> I strongly disagree. I believe there were several bugs that I would not have found the cause of without this.

TBC, I very much agree that building `prqlc` is great — I agree it's caught lots of bugs, from both you & others.

My question is whether it has to be built by default on almost every PR. What would be the downside of having it only build on merges and `pr-test-all` labels? 

Is it that people wouldn't bother to add the label and then not test with `prqlc` as often? (Not saying this is true or not, just trying to understand each of our points of view)

**Comment by eitsupi** [comment]
In push triggers, can we stop running so many jobs regardless of the files that have changed?
I believe that currently even a typo fix triggers all tests.

> We can always label a PR `pr-nightly`, which then runs the nightly workflow, to confirm the release process passes before releasing? We could have a rule to do this on the release notes, for example?

I don't know if it is a good thing to expect humans to remember that.
Would it make sense to run nightly jobs during the pre-release phase since the current workflow anticipates creating pre-releases prior to release?

> Is it that people wouldn't bother to add the label and then not test with `prqlc` as often? (Not saying this is true or not, just trying to understand each of our points of view)

Yes, I believe it is misdirected to assume that people will label them.

**Comment by max-sixty** [comment]
> Yes, I believe it is misdirected to assume that people will label them.

OK, yes, fair. Let's leave it as-is, then.

I can look more at https://github.com/PRQL/prql/issues/3145 re speeding up the `prqlc` compilation at some point instead

**Comment by max-sixty** [comment]
> In push triggers, can we stop running so many jobs regardless of the files that have changed?
> I believe that currently even a typo fix triggers all tests.

Yes! I've already cut this back a bit — and https://github.com/PRQL/prql/pull/3291 does this much more — now we only run `ubuntu` tests on most bindings when we merge to main unless there's a binding-specific change.

I'll extend that to the other bindings, maybe even the rust ones.

Here's a snapshot of where the resources go: https://github.com/PRQL/prql/actions/runs/5798841411/usage. Apart from the items above, the `duckdb` compile times is the sole cause of rust jobs taking 10-15 min rather than 3 min, but we can only wait on upstream for that, now we've removed it from our PR jobs.

**Comment by max-sixty** [comment]
This is mostly done! And added some more things. This is spread out between #3246, #3291, #3303, #3304, #3308, #3320 & #3317!

The only thing remaining is consolidating the release check to run on nightly (which would include a `pr-nightly` label, so we can test before we release). I'm happy to do it, but don't want to step on @eitsupi 's toes — let me know your preferences, @eitsupi (and OK if you don't think we should...)

**Comment by eitsupi** [comment]
Awesome, thanks for working on this!

> The only thing remaining is consolidating the release check to run on nightly (which would include a `pr-nightly` label, so we can test before we release). I

I am sorry, but I do not understand what you are trying to tell me. Is it not included here?

https://github.com/PRQL/prql/blob/ea63af2f18b039cc026a1d6afccc72d9fd75a20d/.github/workflows/nightly.yaml#L185-L189

**Comment by max-sixty** [comment]
Sorry, I had meant that'd we could _consolidate_ it into nightly — i.e. remove this file — https://github.com/PRQL/prql/blob/49f8bd9e12b43eeb286b6cf993ca8889896ebf75/.github/workflows/test-all.yaml, where it's the last remaining job.

i.e. this bullet:

- [ ] Don't run `test-release-dry-run` in `test-all` — move to nightly. Bugs here are very rare (though very annoying when they do happen, so it's good we have a test here). 
  - We could also unify a "dry-run" (which is really a "quick-run") and running when not on a tag, which is really a dry-run. (this would also obviate `check-published`...)

**Comment by max-sixty** [comment]
FYI we now run all of `nightly` on any `Cargo.lock` change — including the full `nightly-release` tests. So that means that we can't release without running that test.

Here's an example: https://github.com/PRQL/prql/actions/runs/5860910536

(and FYI we exclude a couple of expensive jobs, such as `test-taskfile` from this)
