### ISSUE TITLE
Community — ideas?

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#33]
Would folks use a Slack / Discord / etc?

Both to aid contributions — e.g. folks who are keen to contribute but would need some help from others on getting up to speed on writing rust code for the parser — and as a community space for how to more generally make SQL less painful.

**Comment by qharlie** [comment]
Yes I was hoping for real-time chat.  IRC, Gitter, Discord , and lastly Slack are my votes.

**Comment by iafisher** [comment]
I use Discord already. Seems like a popular choice for open-source projects these days.

**Comment by max-sixty** [comment]
I just set up a discord; let's see how this goes: https://discord.gg/57C9u5bm

**Comment by max-sixty** [comment]
Discord is going! I'll close this but feel free to suggest other ideas
