### ISSUE TITLE
Nesting variables

### ISSUE THREAD

**Issue by syko** [PRQL/prql#3316]
### What's up?

The way we generate our PRQL it would help a lot if we could use `let` inside another `let`.

So far it has been a minor inconvenience but today I had to resort to using `from` with a 70-line s-string to get around it.

Would've been much easier with PRQL :)

**Comment by max-sixty** [comment]
Yes this would be good. If you have a small example that demonstrates the benefits, by all means drop it in. 

I would have thought it's _possible_ to flatten it, even if it becomes less manageable? Or does having an inner scope offer new functionality?

Sorry to hear about the 70-line s-string — not ideal...

**Comment by richb-hanover** [comment]
@syko Curious minds want to know... Would you give an excerpt of your 70-line s-string? Thanks

**Comment by syko** [comment]
I guess normally you should be able to flatten it. Although if the inner variables were scoped to the code block of the outer variable definition that would be an additional benefit.

In my case, however, I was declaring some PRQL in a YAML file. That PRQL then gets assigned to a PRQL variable dynamically at runtime. This means that the PRQL in the YAML cannot use variables itself and thus it needs to be aware of the "environment" where it will be run. Of course, it also needs to be aware of that to avoid name conflicts but that's exactly what nested scopes could solve ;)

Specifically, I needed to do some data cleanup and deduplication before joining tables so the s-string was something like
```sql
from s"""
  select * from (
    WITH table_a AS (
      ...
    ),
    table_b AS (
      ...
    )
    SELECT *
    FROM table_a
    JOIN table_b ON (...)
  )
"""
# ... and PRQL can take it from there
```

**Comment by aljazerzen** [comment]
What you want are modules:

```
let some_var = (...)

module my_yaml_1 {
   let table_a = (...)
   let table_b = (...)
   
   # this expressions will be accessible as my_yaml_1.main
   from table_a
   join table_b (...)
}

from my_yaml_1.main
```

Note that this syntax is currently purposefully disabled as we thought it did not bring much to the table.

**Comment by syko** [comment]
Interesting. That would definitely work for my use case.

At some point I might come asking to nest modules though... 🤣

**Comment by aljazerzen** [comment]
> At some point I might come asking to nest modules though... rofl

That's what modules are designed to do!

```elm
module my_yaml_1 {
   module section_1 {
      let table_a = (...)
      let table_b = (...)
   }
  
   module section_2 {
      ...
   }

   from section_1.table_a
   join section_1.table_b (...)
}

from my_yaml_1.main
```

**Comment by max-sixty** [comment]
FWIW we thought that having _inline_ modules wasn't that helpful, and following [@matklad's advice](https://matklad.github.io/2021/11/27/notes-on-module-system.html), had planned to only have modules defined with separate files.

I could imagine a couple of ways of handling this, though:
- Use inline modules
- Allow for a module-like scope, without having a full module; e.g.

```elm
let x = (
  let y = (
    from foo
    derive bar = 5
  )

  from baz
  join y (==id)
)

from x  # or from x.main
```

**Comment by tjdammann** [comment]
+1 on adding support for nested modules and/or variables — the project I'm working on has a bunch of connected data on which I'm performing queries that require a lot of nested joins. We are currently generating PRQL at query time based on dynamic input, so it's not ideal to have to write modules to files in order to use them.

The current workaround is to prefix variable names with the nesting path  — e.g., if querying a users table with relations `users -> purchases -> products`, we end up having variable names like:
```
let users_purchases_products = ( ... )
let users_purchases = ( ... )
let users = ( ... )
```
We're doing it this way in order to avoid naming collisions, but would be much nicer to be able to nest variables and/or use inline modules to avoid this.

**Comment by syko** [comment]
I was finally able to look into the new modules more and they look nice. Something like this would definitely work for us, except for the idea of separate files. Our prql is also dynamically generated at runtime so there's no file structure to speak of in the context of prql (the fact that we even have some in yaml files can be considered a hack).

**Comment by max-sixty** [comment]
Thanks @syko 

Would the inner scope work, as in [comment above](https://github.com/PRQL/prql/issues/3316#issuecomment-1679372163)? The main difference would be that the inner scope can only return a single item, whereas a module could be more like a library.

---

If that wouldn't work, possibly we revisit the decision of not having inline modules. I know I've been the biggest proponent of following the \@matklad blog post, but that's arguably bearing a lot of weight now...

**Comment by syko** [comment]
Yeah the inner scope matches exactly what I originally had in mind 👍

**Comment by max-sixty** [comment]
OK great; if folks agree then we can slate this for implementation. (Though this would be a part of the codebase I don't know well, so we'd probably need direction from @aljazerzen ...)

**Comment by aljazerzen** [comment]
I think one could just remove this and it would work: https://github.com/PRQL/prql/blob/main/crates/prql-compiler/src/semantic/resolver/mod.rs#L114C27-L120

**Comment by max-sixty** [comment]
> I think one could just remove this and it would work: https://github.com/PRQL/prql/blob/main/crates/prql-compiler/src/semantic/resolver/mod.rs#L114C27-L120

I somehow missed this, sorry. 

Thanks a lot for doing it!
