### ISSUE TITLE
No such image: for AMD64 ghcr.io/prql/prql-devcontainer-base:latest

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#3367]
### What happened?

I wanted to rebuild my M2 Dev Container from scratch, and encountered this error message after deleting all containers, images, and volumes:

```
docker inspect --type image ghcr.io/prql/prql-devcontainer-base:latest
[]
Error response from daemon: No such image: ghcr.io/prql/prql-devcontainer-base:latest
```

It works fine on my Intel Macbook.

What other information could I collect? Thanks.

### PRQL input

```elm
N/A
```

### SQL output

```SQL
N/A
```

### Expected SQL output

```SQL
N/A
```

### MVCE confirmation

- [X] Minimal example
- [ ] New issue

**Comment by richb-hanover** [comment]
Also:

```
 docker run -it --pull=always --platform=linux/arm64 ghcr.io/prql/prql-devcontainer-base bash -c "which mdbook-admonish; mdbook-admonish --version"
latest: Pulling from prql/prql-devcontainer-base
docker: no matching manifest for linux/arm64 in the manifest list entries.
See 'docker run --help'.
```
**Update:** My need for the ARM version is not urgent - I am developing on the Intel version currently.

**Comment by max-sixty** [comment]
Thanks @richb-hanover .

Possibly now they're built separately, they're not both pushed to `latest`. Or possibly a recent build broke on one of them. I'm retrying the build from #3370 to check

**Comment by eitsupi** [comment]
@max-sixty I'm on the road right now, so I'll state briefly that I think you've broken the workflow.
Please look into buildx's multi-platform builds.

This line doesn't make sense.
This is because only the tag pushed later will be valid.

https://github.com/PRQL/prql/blob/c8797b77776db7400b95fd32e988210d5a53f881/.github/workflows/build-devcontainer.yaml#L15

workflow dispatch does not solve this problem.

**Comment by max-sixty** [comment]
> @max-sixty I'm on the road right now, so I'll state briefly that I think you've broken the workflow.
> Please look into buildx's multi-platform builds.

Great, thanks. That's somewhat what I thought might be happening ("Possibly now they're built separately, they're not both pushed to `latest`").

The weird part of that is that `arm64` is the version that would push _last_, but is the one not available.

But let me open a PR, I still guess that's it

**Comment by richb-hanover** [comment]
Solved. Works for Intel/amd64 as well. (see below) Thanks!

NB: The Intel build still does not incorporate an `mdbook-admonish` build in the base container. The workaround is `cargo install mdbook-admonish` afterwards

**ARM build**
```
richb@Mac-mini2 ~ %  docker run -it --pull=always --platform=linux/arm64 ghcr.io/prql/prql-devcontainer-base bash -c "which mdbook-admonish; mdbook-admonish --version"
latest: Pulling from prql/prql-devcontainer-base
49185a1a3bc3: Pull complete
c0f6f6b31000: Pull complete
385ee361272e: Pull complete
69a603957da8: Pull complete
76b97b4ed230: Pull complete
631246c1d82b: Pull complete
13495e513001: Pull complete
0d2f70f8bcc5: Pull complete
814ee9171bff: Pull complete
cc805a669abc: Pull complete
d6a71fa2d5b9: Pull complete
3045dad80acb: Pull complete
5685d7099980: Pull complete
99c603ca58ed: Pull complete
43f0fae9e4ac: Pull complete
cb472932d6ed: Pull complete
Digest: sha256:d31be7daa8d4f3742c8af0ef4add980736647eac615675fa1bc644e1cf008e24
Status: Downloaded newer image for ghcr.io/prql/prql-devcontainer-base:latest
/usr/local/cargo/bin/mdbook-admonish
mdbook-admonish 1.10.2
```
**Intel build**
```
?130 ~ % docker run -it --pull=always --platform=linux/amd64 ghcr.io/prql/prql-devcontainer-base bash -c "which mdbook-admonish; mdbook-admonish --version"
latest: Pulling from prql/prql-devcontainer-base
9a9e034800a1: Already exists
fd91c1fad56d: Already exists
9dd6a2c0cfa3: Already exists
83d4a6da525a: Already exists
191b9033cd14: Already exists
b048703fa5ef: Already exists
288d69d0ffa6: Already exists
fff8ac7ee023: Already exists
aa24b9950ff9: Already exists
a8017ae9fa75: Already exists
ceef440f2eb6: Already exists
6aed9c223d0d: Already exists
c3798c786dcb: Already exists
b66fee9d847f: Already exists
c6234f85f56f: Already exists
21e8ef17e7b3: Already exists
Digest: sha256:d31be7daa8d4f3742c8af0ef4add980736647eac615675fa1bc644e1cf008e24
Status: Downloaded newer image for ghcr.io/prql/prql-devcontainer-base:latest
/usr/local/cargo/bin/mdbook-admonish
mdbook-admonish: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by mdbook-admonish)
mdbook-admonish: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by mdbook-admonish)
mdbook-admonish: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by mdbook-admonish)
```

**Comment by eitsupi** [comment]
> The weird part of that is that `arm64` is the version that would push _last_, but is the one not available.

You can use the `docker buildx imagetools inspect` command to find out what is included in the manifest.
