### ISSUE TITLE
Release workflow does not seem to be working as expected when creating a release

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#3382]
~~I have created a release on 18b9cba60e70ee740e506c8868d2d351cc8846e6, but nothing appears to have been published.~~
~~I probably should have checked first on my fork to make sure the workflow was working correctly (I think I checked on the changes I made to my release workflow, but didn't keep track of the other changes).~~

~~I removed the release and tag as it seemed to run as a dry run.~~

~~@max-sixty Any thoughts?~~

Sorry, I did not understand the difference between creating a release as a pre-release and then making changes to the release versus creating it as a release from the beginning.
The workflow seems to work correctly only in the former case.

49 is the latter and 50 is the former in this picture.

![image](https://github.com/PRQL/prql/assets/50911393/033ec9a1-7cd8-4276-9fa1-b9dbb93f4ce5)

**Comment by max-sixty** [comment]
Looking!

**Comment by max-sixty** [comment]
Thanks for having done this!

I see this as working more-or-less correctly now, is that your understanding?

i.e. the release workflow is here: https://github.com/PRQL/prql/actions/runs/5957270684, and everything ran correctly apart from a couple of jobs we can look into. It published to cargo correctly: https://github.com/PRQL/prql/actions/runs/5957270684/job/16160036478.



> Sorry, I did not understand the difference between creating a release as a pre-release and then making changes to the release versus creating it as a release from the beginning.
> The workflow seems to work correctly only in the former case.

Sorry for not understanding / not having written better notes... WDYM "creating a release as a pre-release and then making changes to the release"? I've historically gone to "Draft a new release", filled out this form, but _not_ tagged the "Set as a pre-release".

<img width="1114" alt="image" src="https://github.com/PRQL/prql/assets/5635139/3675907c-d685-4b82-925d-29a4dbe745ef">

**Comment by eitsupi** [comment]
> Sorry for not understanding / not having written better notes... WDYM "creating a release as a pre-release and then making changes to the release"? I've historically gone to "Draft a new release", filled out this form, but _not_ tagged the "Set as a pre-release".

Yes, perhaps the documentation needs to be updated.

---

BTW I find that I can't run the following command (it hangs when I do). Am I forgetting some prerequisite?

https://github.com/PRQL/prql/blob/2997d57c0a4c76646fc42562ef099522d005e6a7/web/book/src/project/contributing/development.md?plain=1#L414-L417

Edit: I did this on Codespaces and it worked. Perhaps it simply takes longer?

**Comment by max-sixty** [comment]
> > Sorry for not understanding / not having written better notes... WDYM "creating a release as a pre-release and then making changes to the release"? I've historically gone to "Draft a new release", filled out this form, but _not_ tagged the "Set as a pre-release".
> 
> Yes, perhaps the documentation needs to be updated.

Which is the bit that's confusing in the docs?

To the extent it's important — what did you mean by "creating a release as a pre-release and then making changes to the release"?

---

> BTW I find that I can't run the following command (it hangs when I do).

Interesting, it's quite quick on mine. Does the first part work? I think the only requirement is for `cargo-release` to be installed. Maybe try updating that? I'm guessing if it's not installed you'd see an error...

**Comment by eitsupi** [comment]
> Which is the bit that's confusing in the docs?
> 
> To the extent it's important — what did you mean by "creating a release as a pre-release and then making changes to the release"?

Oh sorry, I did not understand that you did not understand this.
So if we select `Set as the latest release` to create the release, the workflow will not execute as intended.
We should select `Set as a pre-release`, and change to `Set as the latest release` later.

> Interesting, it's quite quick on mine.

I think it looked as if it hung because it was compiling in the background because there was no local cache.

**Comment by max-sixty** [comment]
> We should select `Set as a pre-release`, and change to `Set as the latest release` later.

Though I've never done this! :)

Are you sure it's not that the `Set as a pre-release` step doesn't do what's intended, but then `Set as the latest release` is the one that works?

**Comment by eitsupi** [comment]
> Are you sure it's not that the `Set as a pre-release` step doesn't do what's intended, but then `Set as the latest release` is the one that works?

If I remember correctly, I initially created the latest release, but then deleted the release when I realized that the GitHub Actions were not working correctly (https://github.com/PRQL/prql/actions/runs/5957121375). I then created the release again as a pre-release and then switched to the latest release and I think the workflow worked correctly (https://github.com/PRQL/prql/actions/runs/5957270684/attempts/1).

**Comment by max-sixty** [comment]
> then deleted the release when I realized that the GitHub Actions were not working correctly (https://github.com/PRQL/prql/actions/runs/5957121375).

OK — this was running as a dry run. I'm not sure what happened. I do know that historically I have not done a pre-release, and it has worked fine. Maybe we try again for 0.9.5 and see what happens...

**Comment by eitsupi** [comment]
If I understand correctly, it looks like `github.ref_type != 'tag'` when the release was created directly.

I am not sure what `github.ref_type` pointing to.......

**Comment by max-sixty** [comment]
> I am not sure what `github.ref_type` pointing to.......

This is described as either a tag or a branch — is there any way it could be a branch?

I may look at trying to make this value explicit — it's difficult to debug when it's read in each individual job...

**Comment by max-sixty** [comment]
https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=published#release has the different release types. 

We're using "released" which means "A release was published, or a pre-release was changed to a release.", which sounds correct...
