### ISSUE TITLE
`aggregate` without list produces incorrect result

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#339]
Currently

```elm
from x
aggregate average value
```

produces 

```sql
SELECT
FROM
  x
```

Possibly we should produce the same as were it `aggregate [average value]`? If we don't we should at least raise an error.

**Comment by aljazerzen** [comment]
That a bug.

Note that when calling a function (or a transform in this case) you cannot call other functions. Your query is equivalent to:

```
from x
aggregate (average) (value)
```

Compiler should throw an error, because you passed two arguments to `aggregate`, which expects only one.

**Comment by max-sixty** [comment]
> Compiler should throw an error, because you passed two arguments to `aggregate`, which expects only one.

Yes, agree. Thanks a lot for the PR!
