### ISSUE TITLE
What triggers a Dev Container rebuild?

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#3441]
### What's up?

I am cloning this question from #3427, since it looks like a separate issue...

> [In #3427](https://github.com/PRQL/prql/issues/3427#issuecomment-1696626434) @eitsupi  asked, "What does "I start the Dev Container" mean?"

When I speak of "starting the Dev Container" I mean launching/opening VS Code on my macOS machine. Whenever I pull from main, I am offered the opportunity to rebuild because .devcontainer (or some such) has changed. 

I always figure, "Sure. The Dev Container knows better than I do." That executes the postCreateCommand and seems to flush out the mdbook-admonish package, so I need to use `cargo` to reinstall.

I ran an experiment in [this video.](https://youtu.be/iqtC6P5BFjg) I started the Dev Container, and it offered to rebuild. I said OK, and went through the same malarkey as previously reported. 

I then quit, and restarted VS Code at 6:19 in the video. It (again) offered to rebuild, but I clicked Ignore. Running `task run-book` did not give the "GLIBC_x not found" message and the mdbook-notes were present without rebuilding the Dev Container or installing mdbook-admonish.

I then quit and restarted VS Code (at 7:45) It DID NOT offer to rebuild, but started right up. `task run-book` worked as expected without the 'GLIBC' warning and showing the mdbook-notes properly.

So... Several questions (mostly displaying my ignorance about how Dev Containers work):

- After I pull from main, does the .devcontainer stuff always change and require rebuilding?
- Why did the Dev Container offer to rebuild the _second_ time at 6:19, since it had just rebuilt the container?
- If I Ignore the rebuild request, is it likely that it'll "stay ignored"?
- If I continue to ignore, how will I know that it is time to rebuild because something important has changed?

**Comment by eitsupi** [comment]
I don't think that is a problem specific to this repository, so could you ask the question here?
https://github.com/microsoft/vscode-remote-release

I am not the author of VS Code Dev Containers so I have no knowledge of the detection logic and do not have an answer.

**Comment by eitsupi** [comment]
I think I answered a similar question somewhere before (edit: this issue #2906), and I don't think it is necessary to rebuild a container until something breaks.

I always ignore the toast of VS Code and rebuild containers whenever I want.
During the rebuild I just go for a cup of coffee.

**Comment by richb-hanover** [comment]
> I think I answered a similar question somewhere before (edit: this issue #2906), and I don't think it is necessary to rebuild a container until something breaks.
> 
> I always ignore the toast of VS Code and rebuild containers whenever I want. During the rebuild I just go for a cup of coffee.

@eitsupi - You are correct - you answered this in #2906. (I didn't know enough then to understand your meaning at the time.) I am closing this. Thanks.

PS And I really appreciate the knowledgeable PRQL team!

**Comment by max-sixty** [comment]
(@eitsupi possibly this is shown by VS Code because a new image was pushed — supports the perspective that there is some downside pushing very often...)
