### ISSUE TITLE
Numerical notation

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#3453]
### What's up?

Supported could be added for numerical notation in binary, hex and octal. It would be useless!

```elm
from pets
filter id == 0b11111111 # 255
```

```elm
from pets
filter id == 0o377 # 255
```

```elm
from pets
filter id == 0xff # 255
```

**Comment by max-sixty** [comment]
Yes, this would be a reasonable first issue. Not the top priority of the project, but would be fine to add. Start with `lexer.rs`...

> It would be useless!

Not sure what this means! Maybe you meant "useful"? :)

**Comment by vanillajonathan** [comment]
> Not sure what this means! Maybe you meant "useful"? :)

I jokingly meant that it would be "less useful", and hence a low priority issue. I consider it more of a "cool" feature than something truly useful.

**Comment by vanillajonathan** [comment]
This was added in PRQL 0.10.0.
https://github.com/PRQL/prql/blob/main/CHANGELOG.md#0100--2023-10-26

With #3661, #3654 and #3672.
