### ISSUE TITLE
Procedual Languange extension for Postgres

### ISSUE THREAD

**Issue by kaspermarstal** [PRQL/prql#3455]
### What's up?

Hi, I am writing a pl/prsql extension for postgres that allows the user to write functions with prql. Are there any design considerations that you (PRQL authors) would like me to take into account?

**Comment by max-sixty** [comment]
That would be great, we'd be excited to see this.

I don't think I have any pressing priorities in mind (though I'm also not _that_ familiar with the process so others should weigh in, as ever)

We had some discussion on this in https://github.com/PRQL/prql/issues/725 IIUC, but @kaspermarstal you're welcome to use this issue if you prefer.

**Comment by kaspermarstal** [comment]
Ah great. I read through the issue and my own thoughts align well with the discussion. I'll use #725 for consistency. 

Love the positive sentiment! Thanks!

**Comment by max-sixty** [comment]
Thanks @kaspermarstal . Keen to know if you make progress, let us know anything we can do!

**Comment by snth** [comment]
Thanks @kaspermarstal . That will be awesome. I'm looking forward to seeing this!
