### ISSUE TITLE
Derive and Group combo produces wasm unreachable error with prql-js@0.9.x

### ISSUE THREAD

**Issue by syko** [PRQL/prql#3460]
### What happened?

I was trying to upgrade from `0.8.1` to `0.9.4` and ran into a new error.

It seems the following conditions are needed for this to happen:
- Target: `sql.postgres` (works fine with `sql.generic` or `sql.mysql`)
- Derive a new field
- Group by derived field
- Use `take` in the `group` body (aggregating seems to work)

Happens on both `@0.9.0` and `@0.9.4`.
Node version `v18.14.1`
I see the playground even throws an error if the target declaration is present.

### PRQL input

```elm
prql target:sql.postgres

from [{a=1}, {a=2}]
derive {
  b = 1,
}
group b (
  take 1
)
```

### SQL output

```SQL
No sql, this instead:

error: Uncaught RuntimeError: unreachable
    at <anonymous> (wasm://wasm/00f087fe:1:3131561)
    at <anonymous> (wasm://wasm/00f087fe:1:3257088)
    at <anonymous> (wasm://wasm/00f087fe:1:3245743)
    at <anonymous> (wasm://wasm/00f087fe:1:147662)
    at <anonymous> (wasm://wasm/00f087fe:1:1766112)
    at <anonymous> (wasm://wasm/00f087fe:1:2922438)
    at <anonymous> (wasm://wasm/00f087fe:1:3126985)
...
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by eitsupi** [comment]
Thanks for reporting!
This maybe the same issue of #3111

**Comment by max-sixty** [comment]
Thanks for the report, sorry this isn't fixed.

I do think this is likely #3111, would you agree @syko ?

I'll comment there to see if we can get closer to a resolution

**Comment by syko** [comment]
Yeah it looking at the latest example there it seems like it's the same issue. I'll go ahead and close this.
