### ISSUE TITLE
`case` should use `[]` instead of `{}`

### ISSUE THREAD

**Issue by aljazerzen** [PRQL/prql#3462]
### What's up?

Currently, this is syntax for case:

```prql
from employees
derive distance = case {
  city == "Calgary" => 0,
  city == "Edmonton" => 300,
}
```

In the last dev call, @snth made a point that `case` syntax should be more similar to arrays than tuples, since the elements of the case block:
- must have the same type,
- are not named.

This is the proposed syntax:

```prql
from employees
derive distance = case [
  city == "Calgary" => 0,
  city == "Edmonton" => 300,
]
```

**Comment by snth** [comment]
Thanks @aljazerzen . Very much agree with this.

**Comment by vanillajonathan** [comment]
Someone might want to match Calgary **OR** Edmonton.
Someone might want to range match income between 1000 and 2000.

**Comment by snth** [comment]
@vanillajonathan sure, the type here just refers to the type of the result which has to be uniform (but could be a "sum"/union type).

There are no restrictions on the case expressions:

```elm
from employees
derive result = case [
  city == "Calgary" || city == "Edmonton" => "Canada",
  (income | in 1000..2000) => "poor",
]
```

**Comment by max-sixty** [comment]
(if it's no extra work — and I don't think it's more than a couple of lines which already exist, in the parser — we could support `{}` for a while too. Though we don't really have a notion of deprecation warnings, which means we wouldn't have a great story for removing it)

**Comment by snth** [comment]
I am generally supportive of a deprecation strategy but given our current manpower I think we might want to keep "moving fast and breaking things" while we still can.

**Comment by max-sixty** [comment]
Yes, agree on reflection
