### ISSUE TITLE
wrong expression precedence

### ISSUE THREAD

**Issue by echou** [PRQL/prql#3469]
### What happened?

wrong "/" and "*" expression precedence。

### PRQL input

```elm
from foo
select a / (b * 0.7)
```

### SQL output

```SQL
SELECT
  (a / b * 0.7)
FROM
  foo
```

### Expected SQL output

```SQL
SELECT
  (a / (b * 0.7))
FROM
  foo
```

### MVCE confirmation

- [ ] Minimal example
- [ ] New issue

**Comment by eitsupi** [comment]
Thanks for reporting this!
