### ISSUE TITLE
Module System Redux

### ISSUE THREAD

**Issue by snth** [PRQL/prql#3474]
### What's up?

Hi,

As mentioned on the last dev-call, I have some ideas for the module system that I would like to discuss. The discussion in #3316 also illustrates that there may be a broader need for this.

## tl;dr

PRQL, and hence the prqlc compiler, is different from languages like Rust, Go, Zig, C, C++, ... in that while compiled, it compiles to SQL rather than some bytecode.

  - PRQL often need to operate within environments without a file system, e.g. in DuckDB, ClickHouse, Python, R, DBeaver, ...
  - prqlc usually doesn't have to compile large systems or applications (like systems languages like Rust, Zig, C, or C++ might have to), but rather just single analytical queries. This implies that execution speed and parallelizability are unlikely to be as big of a concern as for those systems languages.
  - Therefore different tradeoffs for the module system are likely to be appropriate.

---
Disclaimer: This is a first draft and I may edit this later.

## Background

Triggered by a recent [HackerNews post](https://news.ycombinator.com/item?id=37265097) on [Why htmx Does Not Have a Build Step](https://htmx.org/essays/no-build-step/) I reflected on this again. (Disclaimer: I'm a big fan of htmx and have found their thinking and approach great and very clear headed in what I've seen.) The top comment from the HN thread also resonated with me:

> I liked Julia Evans' take on this: [https://jvns.ca/blog/2023/02/16/writing-javascript-without-a...](https://jvns.ca/blog/2023/02/16/writing-javascript-without-a-build-system/)
>""" My goal is that if I have a site that I made 3 or 5 years ago, I’d like to be able to, in 20 minutes:
>
> - get the source from github on a new computer
>
> - make some changes
>
> - put it on the internet """
> 
> Front-end build scripts make sense for projects that are constantly developed by a team that is actively ready to incrementally  fix any problems that come up.
> 
> For sites that only get maintained every year or so (and I have plenty of those myself) my experience is that they often cause more problems than they solve.
> 
> I also found that I started really enjoying JavaScript development again once I gave myself permission to ignore the npm/webpack/etc script world entirely and just write regular code that runs in browsers!

Lastly there was also a link to the SQLite approach of the [SQLite Amalgamation](https://www.sqlite.org/amalgamation.html). I think the SQLite scenario is actually quite similar to PRQL in that SQLite needs to operate embedded in whatever host system it runs on. Similarly PRQL code needs to be able to stand on its own and compile to SQL through whatever binding we've provided (JS, Python, R, Elixir, DBeaver) without necessarily having access to a file system.

## Proposal

My proposal therefore is that:

  - PRQL code should be deployable as a "single file", or more accurately as a "single document", which can easily be embedded or pasted into whatever host environment.
  - When working on a file system, we can still encourage the good practice of separating modules into separate files by making files equivalent to a `module { ... }` declaration (I'll hopefully make this clearer with an example below).

## Example

Using the examples from the [Modules documentation](https://prql-lang.org/book/reference/spec/modules.html#example)
```
# _project.prql

module employees
```

```
# employees.prql

let employees = (...)

let salaries = (...)

let departments = (...)
```

Running `prqlc` on this, would internally first amalgamate this into:
```elm
module employees {

    let employees = (...)

    let salaries = (...)

    let departments = (...)
}
```
and then compile that in turn into the final SQL output.

The intermediate, amalgamated PRQL document should be produceable with a compiler flag since you might want/need to paste that into an execution environment like DBeaver.

**Comment by snth** [comment]
I also really dislike the use of the `module` keyword for when using/importing a module and think that should stay reserved for module definitions. For importing a module, I strongly feel a verb should be used like `import` or `use`. I don't have a strong preference between those and would suggest going with whatever is most commonly used, which in my experience would be `import`.

**Comment by max-sixty** [comment]
I like this, +1. 

I agree with the point about the goals being different between PRQL and systems languages.

---

One question — what is the role of `module employees` in the root `_project.prql`[^1]? Does that include the file? How does that intersect with your point re:

> I also really dislike the use of the `module` keyword for when using/importing a module

...because the only place I recall seeing this is in your proposal above 😀 (but may well be forgetting something...)

[^1]: nit: `Project.prql`

**Comment by snth** [comment]
> One question — what is the role of module employees in the root _project.prql[1](https://github.com/PRQL/prql/issues/3474#user-content-fn-1-68c4b4790ce9fc0a14f62c8389836a56)? Does that include the file?

Yes, my understanding is that that's the current directive to include the file. I don't know if that's still accurate since I am just going on what's stated in the docs and I'm aware that there's an open issues that the docs on modules are not up to date (ref?).

The current [module docs](https://prql-lang.org/book/reference/spec/modules.html#file-importing) say the following:
> To include PRQL source code from other files, we can use the following syntax:
>
>    `module my_playlists`

This is the part that I'm objecting to in my second comment.

I'm hoping to try out the module functionality this weekend to get a feel for how they actually work in practice.

**Comment by max-sixty** [comment]
Ah, that's out of date, t'was more like a proposal. Check out a working example at https://github.com/prql/prql/blob/ef89bba0ca3f35c5b1cc1aa48cf814fe6ed5d4a4/crates/prqlc/tests/project/Project.prql#L8

**Comment by snth** [comment]
Thanks @max-sixty. Oh, so you just refer to modules by name without needing to import them?

**Comment by aljazerzen** [comment]
Yup, the current published file is actually a proposal that not accepted in its entirety. It should be updated to reflect current behavior.

PS: I'm hiding these comments as they are a sidebar

**Comment by aljazerzen** [comment]
The amalgamation that you talk about is actually (almost) exactly how prqlc works under the hood.

As there are other calls for `module employees { ... }` syntax (#3316), I'm +1 on this proposal.

**Comment by snth** [comment]
I'm also +2 on this as I've started playing around with the modules and think this will be a key step to allow the PRQL ecosystem to grow.

Adding to your #3316 reference, [this comment](https://github.com/PRQL/prql/issues/3316#issuecomment-1704969314) in particular highlights the need to be able to have this in a single file.

---
One thing I'd like to add to the module enhancements is dropping the need to have a main pipeline.

Not sure if I was using them correctly but I kept hitting errors about a lack of main pipeline. When building packages/libraries, you don't really want that so I think that should be removed.

---
Where are we on the `import` keyword (or equivalent)? It would seem to me that one would require something like that.

**Comment by max-sixty** [comment]
> One thing I'd like to add to the module enhancements is dropping the need to have a main pipeline.

Yes, but then what is the compilation target? What does it output?

> Where are we on the `import` keyword (or equivalent)? It would seem to me that one would require something like that.

Currently it's implicit, based on the file structure. Maybe that's too implicit. Though we thought it was worth trying...

**Comment by aljazerzen** [comment]
@snth I've added `prqlc collect` command:

```
➜  prqlc collect prqlc/prqlc/tests/project
module artists {
  let input = read_parquet "artists.parquet"
}

let favorite_artists = [
  {artist_id = 120, last_listen = @2023-05-18},
  {artist_id = 7, last_listen = @2023-05-16},
]

favorite_artists
join side:left artists.input (==artist_id)
```

Before we add docs and the changelog, please check it out and give me some feedback.

**Comment by max-sixty** [comment]
> Before we add docs and the changelog, please check it out and give me some feedback.

It's good! One issue is that we don't allow for the `module` declaration inline. I know I was less keen on this, but maybe in order to ease development, we should? Since at the moment, when I pipe the output of `prqlc collect` into `compile` it raises an error...

**Comment by max-sixty** [comment]
FYI I added to changelog in #3740, but happy to revert if we're not ready yet

**Comment by aljazerzen** [comment]
> we don't allow for the module declaration inline

I thought I removed that... I should have added a test

**Comment by max-sixty** [comment]
> I thought I removed that... I should have added a test

Sorry, I was piping into `prqlc`, not `| cargo run -p prqlc -- compile`, so it was on an old version.

It does work now! `cargo run -p prqlc -- collect prqlc/prqlc/tests/project | cargo run -p prqlc -- compile`

**Comment by aljazerzen** [comment]
Currently, we support:
- single-file PRQL projects with inline module declarations,
- multiple-files PRQL projects with implicit module declarations,
- `prqlc collect` command from converting from multiple files into a single one.

I think this covers all proposals outlined above.

**Comment by max-sixty** [comment]
Yes v nice! I can write some docs now that I think we're more ready to support this?

**Comment by aljazerzen** [comment]
Yes, I don't think modules will change dramatically, so go ahead.

**Comment by vanillajonathan** [comment]
I think @snth raised an interesting issue in comment https://github.com/PRQL/prql/issues/3474#issuecomment-1707364348.

> I also really dislike the use of the `module` keyword for when using/importing a module and think that should stay reserved for module definitions. For importing a module, I strongly feel a verb should be used like `import` or `use`. I don't have a strong preference between those and would suggest going with whatever is most commonly used, which in my experience would be `import`.

**Comment by aljazerzen** [comment]
We don't have the notion of "importing" a module. All modules in the module tree are imported by default and one can access them using qualified identifiers (`my_module.my_submodule.my_var`).

So current state is in line with the comment.
