### ISSUE TITLE
Playground: Keyboard command to comment / un-comment the current selection 

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#3475]
### What's up?

Feature request: I have come to treasure the `Cmd-/` keyboard shortcut (Mac - `Ctl-/` on Windows, Linux) to comment or un-comment the selection in various IDEs. 

This would be an enormously useful facility to add to the Playground too. When I'm horsing around adding/removing statements in PRQL queries, it would be nice to have a single keystroke to include/exclude them.

Thanks!

**Comment by max-sixty** [comment]
I agree, this would be very useful. I'm not sure whether Monaco supports it with a simple option to tell it how to make a comment, or it needs to be implemented manually. (That would be helpful to know even if someone isn't experienced enough to make the change)

**Comment by snth** [comment]
Very much agree. Often wished for this functionality in the playground as well.

**Comment by snth** [comment]
Putting these here in case they help. Feel free to delete the comment if not.

https://github.com/microsoft/monaco-editor/issues/398

https://github.com/microsoft/monaco-editor/issues/102
