### ISSUE TITLE
Lexer allows params that starts and ends with a dot

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#3476]
### What happened?

The lexer allows a param to begin with a `.` character after the `$` and it also allows it to end with a `.` character.

I expected the dot only to be allowed in the middle but not at the start or at the end of the parameter name.

### PRQL input

```elm
from pets | filter name == $.1.
```

### SQL output

```SQL
SELECT
  *
FROM
  pets
WHERE
  name = $.1.
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
Is this a problem, though? I think it's fine to be overly permissive unless it causes a problem...

**Comment by vanillajonathan** [comment]
No, I don't think it is a problem, it was just unexpected. I expected it to be more strict and that a `.` character wouldn't be allowed at the start or at the end.

You may close this issue if you think it is a non-issue.

**Comment by max-sixty** [comment]
Yeah — if this does become a problem feel free to reopen. Or anyone has some particular need to implement it, we'd accept the PR. But otherwise no need to track something being a bit too permissive; I hope that sounds reasonable.

Thanks @vanillajonathan ...

**Comment by vanillajonathan** [comment]
I don't see it becoming a problem, but this could be a good-first-issue for new contributors.

**Comment by vanillajonathan** [comment]
The lexer also allows numbers that end with underscores.

**Comment by max-sixty** [comment]
> I don't see it becoming a problem, but this could be a good-first-issue for new contributors.

Yeah, if anyone wants to take a swing then OK, but I wouldn't add the label — we do want our first issues to be impactful to PRQL as well as the contributor's onboarding
