### ISSUE TITLE
Bump prql-compiler's MSRV to 1.70.0

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#3556]
https://github.com/PRQL/prql/pull/3521#issuecomment-1722412149

Would it make sense to change MSRV from 1.65.0 to 1.70.0 when prql-compiler 0.10.0?

FYI, Debian testing migrations from 1.69 to 1.70 is on the way: https://tracker.debian.org/pkg/rustc

**Comment by max-sixty** [comment]
Yes! 

We don't need to bump the minor version to increase the MSRV (some debate but settled on this standard in the community). So we can always immediately follow Debian.

**Comment by eitsupi** [comment]
> We don't need to bump the minor version to increase the MSRV (some debate but settled on this standard in the community)

Really? This is pretty surprising considering that cargo installs different patch versions without considering MSRV.

**Comment by max-sixty** [comment]
Some discussion and links: https://github.com/rust-lang/api-guidelines/discussions/231#discussioncomment-3849277

**Comment by eitsupi** [comment]
Debian testing is now Rust 1.70.

**Comment by max-sixty** [comment]
#3578

**Comment by eitsupi** [comment]
Closed by #3578
