### ISSUE TITLE
Named options / arguments of functions

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#3581]
### What's up?

I believe that currently function arguments can only be specified positionally, which makes it difficult to use functions with a large number of options.

For example, could we introduce a syntax like shell `func_name --option option_value argument`?

Sorry if this has been discussed before.

**Comment by snth** [comment]
Hi, you can have keyword arguments using the `:`.

For example the following works in the playground:

```elm
let top_albums = n artist:null -> (
  from albums
  filter artist_id>=(artist ?? 0) && artist_id<=(artist ?? 999)
  take n 
)

top_albums 10 artist:1
```
or you can leave out the `artist` argument and just call:

```elm
top_albums 10 
```

It's a bit of a contrived example but best I could come up quickly.

That said, while I've been working on example queries for the talks and writing functions, I have found that the DX around the functions isn't that great - the error messages are often confusing and you can't call keyword arguments positionally. For example the following call doesn't work:

```elm
top_albums 10 1
```

**Comment by max-sixty** [comment]
We also have named parameters though: https://prql-lang.org/book/reference/declarations/functions.html

Though we're definitely less flexible than many languages — parameters can only be one or the other.

But it does make it simpler — python's rules around positional vs named parameters end up being extremely complicated. I'd be keen to see examples where the current constraints make something un-ergonomic.

**Comment by eitsupi** [comment]
Thank you both. I did not understand that.

I think the current implementation that enforces names makes sense. (Although a variable-length argument would be useful to support something like DuckDB's `read_csv` function.)

**Comment by snth** [comment]
> I'd be keen to see examples where the current constraints make something un-ergonomic.

How about a generic `top_n` function? The example below is silly because it's the same as a simple `take` but assume there is some extra filtering or sorting etc... 

EDIT: The following actually does work. (I had a previous version which didn't.)

```elm
let top_n = n:10 rel -> (
  rel
  take n 
)

from albums
top_n n:5
```

I'd argue that having to write `top_n n:5` instead of `top_n 5` is a little unergonomic but it's ok and I can live with it.

**Comment by snth** [comment]
This is good news for me actually. I had been struggling with this and couldn't make it work previously and been meaning to post an issue. Thanks @eitsupi for getting this discussion going. It cleared something up for me.

**Comment by max-sixty** [comment]
Great to hear!

---

And tbc, the function could take a positional param:

```elm
let top_n = n rel -> (
  rel
  take n 
)

from albums
top_n 10
```

(same sql)

**Comment by eitsupi** [comment]
Named arguments seem to be working fine, so closing this issue.
