### ISSUE TITLE
Language parameter for the demo

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#3606]
### What's up?

It would be good if the demo accepted a language parameter which could be set when linking to the demo to set the language.

Example:
https://pygments.org/demo/#lang=python

**Comment by max-sixty** [comment]
I'm sure this is obvious, but what do we mean "linking to the demo"? The playground?

**Comment by vanillajonathan** [comment]
My bad, I opened this in the wrong project. How clumsy of me!

It's intended for us be able to specify `#lang=prql` when linking to the Pygments demo.

**Comment by max-sixty** [comment]
No prob, agree with the idea! 😀
