### ISSUE TITLE
Exclusions in unsupported dialects should be errors?

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#3622]
### What happened?

It is not possible to represent the exclusion of unknown columns in dialects that do not support something like EXCLUDE, but it does not seem to be an error.

### PRQL input

```elm
from tracks
select !{milliseconds,bytes}
```

### SQL output

```SQL
SELECT
  *
FROM
  tracks

-- Generated by PRQL compiler version:0.9.5 (https://prql-lang.org)
```

### Expected SQL output

```SQL
(Should be an error)
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
Definitely agree — I started on this in https://github.com/PRQL/prql/pull/2342, but it's a bit more complicated than I thought, since we use the exclude function for other things... I definitely think this is a bug atm...

**Comment by eitsupi** [comment]
Oh, sorry. I forgot about that. Thanks for working that!

Close it as a duplicate of #2292.
