### ISSUE TITLE
`!` in `select` is compiled to `NOT` in `SELECT`?

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#3623]
### What happened?

When using `!` for excluding a column, if forgetting to add `{}` it is translated to `NOT`.

### PRQL input

```elm
prql target:sql.duckdb

from tracks
select !milliseconds
```

### SQL output

```SQL
SELECT
  NOT milliseconds
FROM
  tracks

-- Generated by PRQL compiler version:0.9.5 (https://prql-lang.org)
```

### Expected SQL output

```SQL
SELECT
  * EXCLUDE (milliseconds)
FROM
  tracks
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
`!` does mean `NOT`! Maybe we should document this better... It is listed in https://prql-lang.org/book/reference/syntax/operators.html, but I don't think we ever actually give its definition...

**Comment by eitsupi** [comment]
My question here is that the results differ with or without `{}`. I feel this is a bug because in other places the presence or absence of `{}` has not affected the result

**Comment by aljazerzen** [comment]
I agree, this is quite unexpected. We could add a special case for this in our semantics, or we could require `select` and `derive` to always have `{}`.

(in any case, this is not a compiler bug)

**Comment by max-sixty** [comment]
> My question here is that the results differ with or without `{}`. I feel this is a bug because in other places the presence or absence of `{}` has not affected the result

Yes that is a good point. Arguably that was a risk when we chose to allow `!` to mean both `NOT` and "exclude".

One thing we _maybe_ could do — though I haven't thought it enough to recommend it — is disallow `select foo * 2` — i.e. any unnamed expression. 

So then `select !foo` would be invalid, while `select x=!foo` would be valid. And `select x={!foo}` still means `NOT`, while `select {!foo}` and `select !foo` both mean "exclude"[^1].

[^1]: or `select !foo` could be invalid, but at least isn't ambiguous

But that also feels like a big change, plausibly to make up for a small mistake.

Another option would be to choose a different symbol for "exclude", but I'm not sure there are good ones... (`^`? `~`??)

**Comment by aljazerzen** [comment]
> One thing we maybe could do — though I haven't thought it enough to recommend it — is disallow select foo * 2 — i.e. any unnamed expression.

No, I really dislike this, since it is a special rule.

> Another option would be to choose a different symbol for "exclude", but I'm not sure there are good ones..

True.

---

What about requiring `{}` for select?

**Comment by max-sixty** [comment]
> No, I really dislike this, since it is a special rule.

Yes fair



> What about requiring `{}` for select?

I do think it's nice to just have `select foo`. But I won't cling too tightly!

And even if we made that change — then isn't there still ambiguity / special-casing? 

~`select {!foo}` could still be interpreted as either `NOT` or "excludes", no?~ edit: actually I think it's fairly clear that `select !{foo}` would be exclusion, `select {!foo}` would be `NOT`.

IIRC, we thought this was OK _because_ we could use the tuple to discriminate between them. Or am I misremembering?

**Comment by aljazerzen** [comment]
That was exactly the reasoning I believe:
- negation of tuples is exclusion,
- negation of non-tuples is boolean negation

**Comment by max-sixty** [comment]
Yes, you're right (I edited above).

In that case, it does seem like `select !foo` is legibly `NOT`, since it's not negating a tuple.

If folks feel strongly about forcing tuples, then I won't cling on. Though we would still be left with lots of places we can't pass tuples (`filter` / `group` ), so I'm currently holding that it doesn't overall make the language more consistent...

**Comment by aljazerzen** [comment]
Yeah, I don't think this is ambiguous, so I don't think we should require `{}` in `select`.

@eitsupi if you agree, we can close this issue.

**Comment by max-sixty** [comment]
I added docs at #3820
