### ISSUE TITLE
Floating point seems to return incorrectly on playground

### ISSUE THREAD

**Issue by jangorecki** [PRQL/prql#3633]
### What happened?

Seems like dots are being removed from numbers when using from array. Not sure what's the way then to generate minimal example that has decimal number in the data.

### PRQL input

```elm
from [
  {col_int=1, col_double=1.5}
]
```

### SQL output

```SQL
col_int	col_double
1	15
```

### Expected SQL output

```SQL
col_int	col_double
1	1.5
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

### Anything else?

reproduced on playground

**Comment by eitsupi** [comment]
Thank you for finding this.
The conversion to SQL seems to be working correctly, so I expect there is a bug somewhere in the JavaScript (arrow or duckdb)

```sql
WITH table_0 AS (
  SELECT
    1 AS col_int,
    1.5 AS col_double
)
SELECT
  col_int,
  col_double
FROM
  table_0

-- Generated by PRQL compiler version:0.9.5 (https://prql-lang.org)
```

**Comment by eitsupi** [comment]
Maybe this? duckdb/duckdb-wasm#1321

**Comment by eitsupi** [comment]
```elm
from [{a = 10.0}]
derive b = 10.0
```

->

```sql
WITH table_0 AS (
  SELECT
    10.0 AS a
)
SELECT
  a,
  10.0 AS b
FROM
  table_0

-- Generated by PRQL compiler version:0.9.5 (https://prql-lang.org)
```

->

<html><body>


a | b
-- | --
100 | 100


</body>
</html>

**Comment by jangorecki** [comment]
@eitsupi thanks for tracking it down. BTW. it seems that I am not able to use `null` inside from:array
```prql
from [
  {time_id=1, value=1},
  {time_id=8, value=null},
]
```
should I fill new issue for that? I already feel like spamming repo with issues :smile:

**Comment by eitsupi** [comment]
> should I fill new issue for that?

I think this is tracked in #2822

**Comment by max-sixty** [comment]
Closing this as an upstream issue

> should I fill new issue for that? I already feel like spamming repo with issues 😄

Yes please! Your issues have been great, please keep them up!
