### ISSUE TITLE
Wrong syntax highlight of numbers on the book?

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#3639]
### What happened?

I was looking at the book deployed from #3634 and noticed that the colors of the numbers were strange.

![image](https://github.com/PRQL/prql/assets/50911393/5f742b3c-7456-40b8-b02a-d172fc3eb525)

in the Playground

![image](https://github.com/PRQL/prql/assets/50911393/db734a08-d632-4ec7-8dc1-cf4916e2edb9)

### PRQL input

```elm
from [
  {time_id=1, value=15},
  {time_id=2, value=11},
  {time_id=3, value=16},
  {time_id=4, value=9},
  {time_id=7, value=20},
  {time_id=8, value=22},
]
```

### SQL output

```SQL
WITH table_0 AS (
  SELECT
    1 AS time_id,
    15 AS value
  UNION
  ALL
  SELECT
    2 AS time_id,
    11 AS value
  UNION
  ALL
  SELECT
    3 AS time_id,
    16 AS value
  UNION
  ALL
  SELECT
    4 AS time_id,
    9 AS value
  UNION
  ALL
  SELECT
    7 AS time_id,
    20 AS value
  UNION
  ALL
  SELECT
    8 AS time_id,
    22 AS value
)
SELECT
  time_id,
  value
FROM
  table_0

-- Generated by PRQL compiler version:0.9.5 (https://prql-lang.org)
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
Good spot, thanks. The regex I'd created with an LLM had an obvious flaw. I've now fixed it in #3640.
