### ISSUE TITLE
glaredb dialect and integration tests

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#3658]
Thanks to @universalmind303, GlareDB seems supporting PRQL like ClickHouse! (GlareDB/glaredb#1895)

**Comment by eitsupi** [comment]
I have looked at adding GlareDB to the integration test and am struggling to get the CSV files to load into the database.

GlareDB does not allow reading of local files on the server side, so CSVs cannot be read directly.
Also, I thought about using <https://github.com/fsouza/fake-gcs-server> as storage but it does not appear to be compatible with the GCS emulator (or MinIO).

Perhaps the easiest connection to storage that can be made today seems to be to register tables on the existing Postgres container as external tables.
https://github.com/PRQL/prql/blob/fb6dd86465304ac9ab53a46adbd05a394649a3f9/crates/prql-compiler/tests/integration/docker-compose.yml#L2-L13

with commands like this:

```sql
CREATE EXTERNAL TABLE albums
    FROM postgres
    OPTIONS (
        host = 'postgres',
        port = '5432',
        user = 'root',
        password = 'root',
        database = 'dummy',
        schema = 'public',
        table = 'albums'
    );
```

If connecting to Postgres, the data must be loaded on Postgres before the external table is created on GlareDB, but I was not sure if that is guaranteed in the current test implementation.

https://github.com/PRQL/prql/blob/fb6dd86465304ac9ab53a46adbd05a394649a3f9/crates/prql-compiler/tests/integration/main.rs#L295-L306

If I understand correctly, G is listed before P here, and Postgres is called after.

**Comment by universalmind303** [comment]
@eitsupi You should be able to easily read local csv files either through `csv_scan`, or referencing the file directly

```sql
select * from 'path/to/some/file.csv';
```


```sql
select * from csv_scan('path/to/some/file.csv');
```

you can also read them from a url `csv_scan('https://path/to/some/file.csv')`

**Comment by eitsupi** [comment]
@universalmind303 Thanks, but I am trying to run it as a server and connect with a Postgres client.

**Comment by eitsupi** [comment]
@universalmind303 I tried reading CSV via http by adding something like the following, but it doesn't work. Perhaps https is allowed but http is not?

```yml
  nginx:
    image: nginx:alpine-slim
    expose:
      - 80
    volumes:
      - ./data/chinook:/usr/share/nginx/html:ro
```

**Comment by scsmithr** [comment]
https://github.com/GlareDB/glaredb/issues/1324 was mostly around disabling the output of `COPY` to local files. Running `select * from '<file>.csv'` should still work when running `glaredb server`.

I checked out your branch and made the following change to the glaredb block in the compose yaml:

```yaml
  glaredb:
    build:
      context: dockerfiles
      dockerfile: glaredb.Dockerfile
    ports:
      - "6543:6543"
    volumes:
      - ./data/chinook:/data/chinook
```

This mounts in the test data dir which glaredb can read from correctly. After running docker compose up, I can connect to it via psql and run the select:

```
% psql postgres://localhost:6543/glaredb
psql (14.9, server 15.1)
WARNING: psql major version 14, server major version 15.
         Some psql features might not work.
Type "help" for help.

glaredb=> select * from '/data/chinook/albums.csv' limit 5;
 album_id |                 title                 | artist_id 
----------+---------------------------------------+-----------
        1 | For Those About To Rock We Salute You |         1
        2 | Balls to the Wall                     |         2
        3 | Restless and Wild                     |         2
        4 | Let There Be Rock                     |         1
        5 | Big Ones                              |         3
(5 rows)
```

The test data can be easily loaded into a table as well:

```
glaredb=> create table albums as select * from '/data/chinook/albums.csv';
CREATE TABLE
glaredb=> select * from albums limit 5;
 album_id |                 title                 | artist_id 
----------+---------------------------------------+-----------
        1 | For Those About To Rock We Salute You |         1
        2 | Balls to the Wall                     |         2
        3 | Restless and Wild                     |         2
        4 | Let There Be Rock                     |         1
        5 | Big Ones                              |         3
(5 rows)
```

And regarding reading over http, glaredb should support that. I'd have a dig in a little bit more why that wouldn't be working with the nginx server.

**Comment by eitsupi** [comment]
@scsmithr Thanks for checking this! I verified that I can read local files. I think I probably did something wrong yesterday.

We're currently following the steps of creating a table and then loading the CSV contents into the table.

1. Create tables with this SQL file. https://github.com/PRQL/prql/blob/fb6dd86465304ac9ab53a46adbd05a394649a3f9/crates/prql-compiler/tests/integration/data/chinook/schema.sql

2. Load the data from CSV files like this:
  https://github.com/PRQL/prql/blob/fb6dd86465304ac9ab53a46adbd05a394649a3f9/crates/prql-compiler/tests/integration/main.rs#L203-L211

Is there currently a way to read a CSV file and write to an existing table? Something like the below doesn't seem to work.

```psql
glaredb=> copy (select * from '/tmp/chinook/albums.csv') to albums;
COPY
glaredb=> select * from albums;
 album_id | title | artist_id 
----------+-------+-----------
(0 rows)
```

Thank you for your cooperation in this.

**Comment by scsmithr** [comment]
That copy to statement should actually be erroring since we don't yet support it. Just opened https://github.com/GlareDB/glaredb/issues/1917.

However, we can use `insert into <table> select * from '<file>'` as an alternative.

For example for invoices:

```
glaredb=> CREATE TABLE invoices (
    invoice_id INTEGER,
    customer_id INTEGER,
    invoice_date TIMESTAMP,
    billing_address VARCHAR(255),
    billing_city VARCHAR(255),
    billing_state VARCHAR(255),
    billing_country VARCHAR(255),
    billing_postal_code VARCHAR(255),
    total REAL
);
CREATE TABLE

glaredb=> insert into invoices select * from '/data/chinook/invoices.csv';
INSERT 0 412

glaredb=> select * from invoices limit 5;
 invoice_id | customer_id |    invoice_date     |     billing_address     | billing_city | billing_state | billing_country | billing_postal_code | total 
------------+-------------+---------------------+-------------------------+--------------+---------------+-----------------+---------------------+-------
          1 |           2 | 2009-01-01 00:00:00 | Theodor-Heuss-Straße 34 | Stuttgart    |               | Germany         | 70174               |  1.98
          2 |           4 | 2009-01-02 00:00:00 | Ullevålsveien 14        | Oslo         |               | Norway          | 0171                |  3.96
          3 |           8 | 2009-01-03 00:00:00 | Grétrystraat 63         | Brussels     |               | Belgium         | 1000                |  5.94
          4 |          14 | 2009-01-06 00:00:00 | 8210 111 ST NW          | Edmonton     | AB            | Canada          | T6G 2C7             |  8.91
          5 |          23 | 2009-01-11 00:00:00 | 69 Salem Street         | Boston       | MA            | USA             | 2113                | 13.86
(5 rows)
```

**Comment by eitsupi** [comment]
@scsmithr Thanks for your quick response, that works fine!

I tried this on f5fade5fc781992398f1f312bd0c603e52fea920

```sh
$ pushd crates/prql-compiler/tests/integration/
$ docker compose up -d postgres glaredb
[+] Running 9/9
 ✔ postgres 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                      14.9s 
   ✔ 96526aa774ef Pull complete                                                              1.0s 
   ✔ 1c7e9d0e60f3 Pull complete                                                              0.7s 
   ✔ 9538d5302eee Pull complete                                                              0.7s 
   ✔ ddefdf18815a Pull complete                                                              5.6s 
   ✔ 483d47e7b846 Pull complete                                                              1.6s 
   ✔ 4f69e6f6f92e Pull complete                                                              1.8s 
   ✔ 6ad5f543b2cb Pull complete                                                              2.3s 
   ✔ 3f41102d5734 Pull complete                                                              2.5s 
[+] Building 4.3s (8/8) FINISHED                                                   docker:default
 => [glaredb internal] load .dockerignore                                                    0.1s
 => => transferring context: 2B                                                              0.0s
 => [glaredb internal] load build definition from glaredb.Dockerfile                         0.0s
 => => transferring dockerfile: 419B                                                         0.0s
 => [glaredb] resolve image config for docker.io/docker/dockerfile:1.4                       1.7s
 => CACHED [glaredb] docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a8  0.0s
 => [glaredb internal] load metadata for docker.io/library/buildpack-deps:stable             1.8s
 => [glaredb 1/2] FROM docker.io/library/buildpack-deps:stable@sha256:584ae312404463556590d  0.0s
 => CACHED [glaredb 2/2] RUN <<EOF (cd /usr/local/bin...)                                    0.0s
 => [glaredb] exporting to image                                                             0.0s
 => => exporting layers                                                                      0.0s
 => => writing image sha256:b6c2e4efa24a2c2a155ad68fed2a899b7db4fc93b418cdeea7261e2098fe82b  0.0s
 => => naming to docker.io/library/integration-glaredb                                       0.0s
[+] Running 3/3
 ✔ Network integration_default       Created                                                 0.1s 
 ✔ Container integration-postgres-1  Started                                                 0.2s 
 ✔ Container integration-glaredb-1   Started                                                 0.2s 

$ docker compose exec postgres bash
# psql "host=glaredb user=glaredb dbname=glaredb port=6543"
psql (16.0, server 15.1)
Type "help" for help.

glaredb=> CREATE TABLE invoices (
glaredb(>     invoice_id INTEGER,
glaredb(>     customer_id INTEGER,
glaredb(>     invoice_date TIMESTAMP,
glaredb(>     billing_address VARCHAR(255),
glaredb(>     billing_city VARCHAR(255),
glaredb(>     billing_state VARCHAR(255),
glaredb(>     billing_country VARCHAR(255),
glaredb(>     billing_postal_code VARCHAR(255),
glaredb(>     total REAL
glaredb(> );
CREATE TABLE
glaredb=> insert into invoices select * from '/tmp/chinook/invoices.csv';
INSERT 0 412
glaredb=> select * from invoices limit 5;
 invoice_id | customer_id |    invoice_date     |     billing_address     | billing_city | billing_state | billing_country | billing_postal_code | total 
------------+-------------+---------------------+-------------------------+--------------+---------------+-----------------+---------------------+-------
          1 |           2 | 2009-01-01 00:00:00 | Theodor-Heuss-Straße 34 | Stuttgart    |               | Germany         | 70174               |  1.98
          2 |           4 | 2009-01-02 00:00:00 | Ullevålsveien 14        | Oslo         |               | Norway          | 0171                |  3.96
          3 |           8 | 2009-01-03 00:00:00 | Grétrystraat 63         | Brussels     |               | Belgium         | 1000                |  5.94
          4 |          14 | 2009-01-06 00:00:00 | 8210 111 ST NW          | Edmonton     | AB            | Canada          | T6G 2C7             |  8.91
          5 |          23 | 2009-01-11 00:00:00 | 69 Salem Street         | Boston       | MA            | USA             | 2113                | 13.86
(5 rows)
```

**Comment by eitsupi** [comment]
#3669 has been merged and the `sql.glaredb` target can now be specified🎉

prqlc Binaries can be download from the latest CI result <https://github.com/PRQL/prql/actions/runs/6515707351>

```sh
$ prqlc list-targets
sql.any
sql.ansi
sql.bigquery
sql.clickhouse
sql.duckdb
sql.generic
sql.glaredb
sql.mssql
sql.mysql
sql.postgres
sql.sqlite
sql.snowflake
```

But so far it seems that rust-postgres is not getting the results it gets from executing the query correctly, so all integration tests are skipped. (https://github.com/PRQL/prql/pull/3669#issuecomment-1762545507)

**Comment by scsmithr** [comment]
I can take a look at the test failures today.

**Comment by scsmithr** [comment]
I've adapted the prql integration tests to our framework that we use in glaredb so that we can get quicker feedback on changes we'd need to make. Everything is in this file: https://github.com/GlareDB/glaredb/blob/main/testdata/sqllogictests/prql.slt. Tests that don't work yet have been commented out and have been noted in this issue: https://github.com/GlareDB/glaredb/issues/1918

We get different outputs for the `group_all` test compared to the snapshot (e.g. `7.920000076293945` vs `7.920000000000001`), but it's probably related to using f32/f64.

As for the panic you saw in your pr, seems like it's just an encoding issue on our end with f32 vs f64 when going over the postgres protocol. Once this is fixed, we can open up a pr for enabling integration tests in this repo.

**Comment by eitsupi** [comment]
Great, thanks!

**Comment by eitsupi** [comment]
Thanks to the new release of GlareDB (0.6.0), the integration tests for GlareDB have been enabled on #3749.

However, the following query appears to continue to fail due to compatibility issues with rust-postgres.

https://github.com/PRQL/prql/blob/648b8fa7005345ff1d106ebcb4f8174e4b5cd31e/prqlc/prql-compiler/tests/integration/queries/switch.prql#L2-L9

The log shows that strings such as `no composer` and `unknown composer` have disappeared.

```log
---- test_rdbms stdout ----
Snapshots in allow-duplicates block do not match.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Differences in Block ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: prqlc/prql-compiler/tests/integration/snapshots/integration__results@switch.prql.snap
Snapshot: results@switch.prql
Source: prqlc/prql-compiler/tests/integration/main.rs:130
Input file: prqlc/prql-compiler/tests/integration/queries/switch.prql
────────────────────────────────────────────────────────────────────────────────
-previous assertion
+current assertion
────────────┬───────────────────────────────────────────────────────────────────
    0     0 │ Samuel Rosa
    1       │-no composer
    2       │-no composer
    3       │-no composer
          1 │+
          2 │+
          3 │+
    4     4 │ L. Muggerud
    5       │-no composer
          5 │+
    6     6 │ L. Muggerud
    7       │-unknown composer
          7 │+
    8     8 │ Gilberto Gil
    9     9 │ Chico Science
────────────┴───────────────────────────────────────────────────────────────────
thread 'test_rdbms' panicked at 'snapshot assertion for 'results@switch.prql' failed in line 130. Result does not match previous snapshot in allow-duplicates block.', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.34.0/src/runtime.rs:590:13
```

<https://github.com/PRQL/prql/actions/runs/6662744370/job/18107575044?pr=3749#step:13:99>

**Comment by scsmithr** [comment]
I'll try to take a poke at this soon. This particular query needed to be commented out when we were running it in our tests (https://github.com/glaredb/glaredb/blob/494b79a1c5648b3b23169522fb3fb803e20e1f60/testdata/sqllogictests/prql.slt#L832-L842), but we might've been on an older prql here.
