### ISSUE TITLE
How to structure different dialects

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#367]
Continuing from https://github.com/prql/prql/pull/347

What's the best approach here? I'd propose we have a Trait in `translator.rs` which is implemented by each dialect — any thoughts?

**Comment by max-sixty** [comment]
I had a quick go at including a `struct` in the definition of a `Query`, but got some rust type errors around object safety which I didn't take the time to figure out. Here's where I paused (but is maybe not even helpful to start from) https://github.com/prql/prql/compare/dialect

One naive approach would be to keep the Enum we currently have, and then have a lookup to find the respective struct. Then the appropriate functions in `translator.rs` could part of a Trait which structs would implement. That seems worse than implementing them on the object which is a field of `Query` though.

**Comment by max-sixty** [comment]
This also applies to versions. 

Are there approaches that won't lead to nD x nV implementations, where nD is the number of dialects and nV is the number of versions? Are there other libraries that do this well? 

The rust language manages editions — I haven't looked into the mechanics, but the basics are [here](https://github.com/rust-lang/rust/blob/master/compiler/rustc_span/src/edition.rs). And `sqlparser-rs` has a nice [simple way of handling dialects](https://github.com/sqlparser-rs/sqlparser-rs/blob/main/src/dialect/mod.rs)

**Comment by aljazerzen** [comment]
Having `dyn Dialect` in AST will be quite painful because of serialization and de-serialization. 

What about having:
```rust
trait DialectHandler {
   ...
}

enum Dialect { ... }

impl DialectEnum {
  fn handler() -> Box<dyn DialectHandler> {
  }
}
```

so `Dialect` enum can be in AST, and `DialectHandler` trait is used for nice polymorphic behavior?

I'm pushing such commit now, feel free to revert it.

**Comment by max-sixty** [comment]
Closed by https://github.com/prql/prql/pull/398, thanks to @aljazerzen ; I'll open a new issue for versions
