### ISSUE TITLE
Adding a count on a field includes all rows, even those with null values

### ISSUE THREAD

**Issue by tjdammann** [PRQL/prql#3697]
### What's up?

Not sure if this is a bug or expected behavior — I've been working with aggregates recently, and noticed the following from the docs:

```
from employees
aggregate {
  average salary,
  ct = count salary
}
```

Compiles to this in SQL:

```
SELECT
  AVG(salary),
  COUNT(*) AS ct
FROM
  employees
```

In the case where there are null values in the `salary` field, this count ends up counting all the rows rather than only non-null values.

For my use case, I'm doing the following:

- Starting with a `companies` table 
- Left joining in a `users` table on `companies.id = users.company_id`
- Adding a `count` on `users.id`, grouped by `companies.id`

When I look at the results, for companies with no related users, the `count` field is showing up as 1 rather than 0 (as the compiled `COUNT(*)` counts all the rows, including those with null `users.id`).

I wanted to check if this is expected behavior and/or if it would be worth switching to allow counting of specific fields in addition to rows. Seems to me that `ct = count salary` should compile to `COUNT(salary)`, whereas something like `ct = count *` would compile to `COUNT(*)`.

Thanks in advance!

**Comment by max-sixty** [comment]
Thanks for the issue @tjdammann . This does seem to be causing some confusion — am I right in thinking this is the same as https://github.com/PRQL/prql/issues/3620 ?

**Comment by max-sixty** [comment]
Closing as a duplicate, but feedback welcome in #3620
