### ISSUE TITLE
Improving GitHub workflows

### ISSUE THREAD

**Issue by iafisher** [PRQL/prql#37]
It would be nice to add a GitHub workflow to automatically format Rust code using `rustfmt` to ensure that all PRs use consistent formatting.

I found https://github.com/mbrobbel/rustfmt-check - it doesn't appear to be very widely used, but it might get the job done.

**Comment by max-sixty** [comment]
Yes good idea.

I've had lots of success with `pre-commit`, so if there are hooks for `rustfmt` on that, then that could work. It has a nice feature that it'll auto-fix PRs, and can be run locally: https://pre-commit.com/#pre-commitci-example. Here's the config we use in xarray: https://github.com/pydata/xarray/blob/main/.pre-commit-config.yaml

That GHA looks good too — fine to start with that!

**Comment by max-sixty** [comment]
Another thing we could run (maybe every day rather than on PRs) is `cargo audit`

**Comment by max-sixty** [comment]
We have a decent set of checks now, including rustfmt, and I just added pre-commit. If anyone is up for making a contribution here, things we could add:
- [ ] Publish to cargo
- [x] `cargo audit`
- [x] https://github.com/xd009642/tarpaulin for code coverage

Or any others — I'm always up for automating as much as possible.

**Comment by max-sixty** [comment]
https://gist.github.com/PurpleBooth/84b3d7d6669f77d5a53801a258ed269a has some great examples

**Comment by max-sixty** [comment]
https://github.com/max-sixty/prql/pull/289 now runs tests on all platforms on merge (or a specific PR label), and splits the tests up such that they complete in 32s

**Comment by max-sixty** [comment]
These are all done! Closing
