### ISSUE TITLE
Generated SQL contains relation var name clashes

### ISSUE THREAD

**Issue by lovasoa** [PRQL/prql#3713]
### What happened?

No error was emitted, but incorrect sql code was generated

### PRQL input

```elm
from t
join t (==x)
```

### SQL output

```SQL
SELECT
  t.*,
  t.*
FROM
  t
  JOIN t ON t.x = t.x

-- Generated by PRQL compiler version:0.9.5 (https://prql-lang.org)
```

### Expected SQL output

```SQL
-- Maybe something like:
SELECT
  t.*,
  _t_alias.*
FROM
  t
  JOIN t AS _t_alias ON t.x = _t_alias.x
-- but that wouldn't be very useful since one could not use _t_alias in the rest of the query
```

otherwise, prql could simple throw an error

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
Does giving it an alias solve this?

```elm
from t
join t2=t (==x)
```

```sql
SELECT
  t.*,
  t2.*
FROM
  t
  JOIN t AS t2 ON t.x = t2.x

-- Generated by PRQL compiler version:0.9.5 (https://prql-lang.org)
```

**Comment by lovasoa** [comment]
yes, the bug occurs only when not setting an alias

**Comment by max-sixty** [comment]
I'm not sure it's necessarily a bug though — in SQL we'd need to set an alias for it to be useful — isn't it the same here?

**Comment by aljazerzen** [comment]
Yea, it a bug - the compiler should generate valid SQL, except in cases where it is lacking schema information.

**Comment by aljazerzen** [comment]
Also, great minimal repro @lovasoa

**Comment by lovasoa** [comment]
Thinking about it, what would make the most sense is to alias the original table, not the one being joined

```sql
-- Maybe something like:
SELECT
  t.*,
  _t_alias.*
FROM
  t AS _t_alias
  JOIN t ON t.x = _t_alias.x
```

and in the prql, we would have

```prql
from t
# "t" in all intermediate steps here refers to the original t 
join t (==x)
# starting here, "t" references the right side of the join
```
