### ISSUE TITLE
Date, time & duration literals

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#373]
In SQL, creating date objects is a mixture of:
- A string `'2020-01-01'`
- `DATE(2016, 12, 25)` — BQ
- `make_date(year int, month int, day int)` — Postgres

The strings are dynamically typed so they can be implicitly converted when, for example, they're compared to another date (some quick experimenting suggests this also happens when compared to other strings that might be a date!).

Some better options:
- Malloy uses `@2020-01-01`
- We could extend our use of number & string combinations from https://github.com/prql/prql/pull/369 (`5days`) to dates and use `d2020-01-01` or `D2020-01-01`. We can also apply this to timestamps / times / etc with different letters.
- Very open to other ideas

Any thoughts?

**Comment by rbpatt2019** [comment]
I'd lean towards something like d2020-01-01, though I'm not necessarily completely sold on it. Reason being, we also have s-strings, where the leading letter means "dump raw SQL". Though, having just typed that, it might a good reason to use the leading d - it's consistent with other specs.

**Comment by max-sixty** [comment]
Thanks for the response @rbpatt2019 !

On one specific thing:

> Reason being, we also have s-strings, where the leading letter means "dump raw SQL".

Yeah, I do think we should use s-strings as an escape hatch, rather than a recommended approach — basically with the principle that if s-strings keep showing up somewhere, then we should implement that thing in PRQL...

**Comment by mtoy-googly-moogly** [comment]
Yeah the `@` in Malloy was a bit of an experiment addressing this same issue. Literal times are all `@YYYY-MM-DD` or `@YYYY-MM-DD HR:MN:SC`

It still is an experiment that I am not 100% ready to judge. I really love the way expressions with these literals look in queries, the `@` carries the poetic suggesting "at this time" as I read it, but I do not love that I am essentially creating a bias towards one particular date format.

Something which wrapped date-string, but still tagged it as a date, would be better maybe .. but I do still LOVE the way dates and timestamps look in Malloy.

**Comment by max-sixty** [comment]
Yes I do like that approach a lot.

Though is there ambiguity in some cases?

e.g. is it possible to represent a timestamp from a date, like `TIMESTAMP("2008-12-25")`? (Or maybe it's fine and people will just write `@2008-12-25 00` for the timestamp?)

Or datetimes?

**Comment by mtoy-googly-moogly** [comment]
In Malloy we know the types of entities in expressions and `@YYYY-MM-DD` is something which might become a date or a timestamp depending on the context it is used. We generate `TIMESTAMP('YYYY-MM-DD')` when needed.  Or try to :)

**Comment by mtoy-googly-moogly** [comment]
But timezones and datetimes is a can of worms we have not opened up yet. About to.

**Comment by max-sixty** [comment]
Sometimes it's fine to leave it implicit, but I was leaning towards the letter prefixes because I had thought it sometimes needs to be explicit — e.g. if we insert `@2008-12-25` into a new column, do we get a date or a timestamp?

Using letters give us access to a larger number of types, at the cost of it being less simple and less elegant for the main case. Maybe if the main case is broad enough, that's sufficient and people can use s-strings as an escape hatch when needed.

For context, rust does something a bit similar with https://doc.rust-lang.org/rust-by-example/primitives/literals.html

**Comment by aljazerzen** [comment]
This discussion has spread out here: #377 and on discord,  to which I cannot link, so I'll summarize:

There are two options for date literal notation:

1. `d"2022-12-31"` for dates and `t"2022-12-31"` for timestamps, similar to s and f strings
2. `@2022-12-31`, concise, but has problems with expressing datetime vs timestamp.

One option is to add `_ts` suffix to indicate timestamps, just as Rust does with number literals. Another is to use casts: 
```
as timestamp @2022-12-31T16:54
```

Regarding the date format, I think should only allow a restricted subset of [ISO 8601](https://en.m.wikipedia.org/wiki/ISO_8601):

- `@20221231` is forbidden - it must contain full punctuation (`-` and `:`),
- `@2022-12-31` is a date
- `@2022-12` or `@2022` are forbidden - SQL cannot express month only
- `@16:54:32.123456` is a time
- `@16:54:32`, `@16:54`, `@16` are all allowed, expressing `@16:54:32.000000`, `@16:54:00.000000`, `@16:00:00.000000` respectively.
- `@2022-12-31T16:54:32.123456` is a datetime without timezone (allowed time truncations)
- `@2022-12-31T16:54:32.123456Z` is a datetime in UTC
- `@2022-12-31T16:54+02:00` and `@2022-12-31T16:54+02` are datetimes in UTC+2
- `@2022-12-31T16:54+02_ts` is timestamp in UTC+2
- `@2022-12-31T16:54_ts` is timestamp without timezone
- `@2022-12-31_ts` is forbidden (timestamp must specify time)
- `@16:54_ts` is forbidden (timestamp must specify date)
- `@16:54+02` is forbidden (time is always local, so it cannot have a timezone)
- `@2022-12-31+02` is forbidden (date is always local, so it cannot have a timezone)

It's a long list and most of the parsing / converting can be off-loaded to the database, but I believe that PRQL must have its own rules of what means what, so these literals have same meaning across all dialects.

**Comment by max-sixty** [comment]
I very much agree with basically all of what @aljazerzen writes, thank you for describing. We can also use that for the docs.

Should we default to `timestamp` rather than `datetime`?
I had thought that `timestamp` was more popular; e.g. postgres only has `timestamp` IIUC: https://www.postgresql.org/docs/current/datatype-datetime.html
So the suffix would be `_dt` or `dt` to have a `datetime`. (or if we're not sure about that yet, we can recommend casting).


> It's a long list and most of the parsing / converting can be off-loaded to the database, but I believe that PRQL must have its own rules of what means what, so these literals have same meaning across all dialects.

➕ 👍 

We'll start out fairly weak; passing things through, but we'll have a contract that we can test against and guarantee compatibility.

**Comment by aljazerzen** [comment]
I agree on timestamp being the default and having `_ts` and `_dt` express timestamp and datetime explicitly.

**Comment by max-sixty** [comment]
Do you think we should use `::` if we're using that as an annotation, rather than `_ts`, now?

**Comment by aljazerzen** [comment]
In some languages (such as Rust), type annotation of a literal does not have the same syntax as type annotation of a variable (or parameter or return value):
```rust
1254_i64         // numbers use _
let a: i64 = 15; // variables use : 
```

But in our case, I think it could work - it is inherently the same information we are trying to convey. The question is only if that will be possible to implement without too much hassle. But that we cannot know before doing it.

So my answer is: yes, let's have `@16:54:dt` instead of `@16:54_dt`

**Comment by max-sixty** [comment]
Great!

One minor thing — ref https://github.com/prql/prql/pull/442 — this may supports having `::` rather than `:` for type annotations — being able to parse `@16:54:dt` and `@16:54:01:dt` might not be trivial (I'm sure it's not impossible — but simpler parsing often means better error messages and better interactive feedback when we get there)
