### ISSUE TITLE
Playground not working on production site

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#3747]
### What happened?

Today (26Oct2023), I went to the Playground https://prql-lang.org/playground/ and I see the header across the top, but the bottom panes have white background, with no query or resulting SQL displayed.

Browser console shows this error message:

`Loading failed for the module with source “https://prql-lang.org/assets/index-2c804b4a.js”.`

### PRQL input

```elm
N/A
```

### SQL output

```SQL
N/A
```

### Expected SQL output

```SQL
N/A
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
Thanks! Looking now

**Comment by max-sixty** [comment]
This works now. Thanks a lot for raising @richb-hanover .

Fixed by https://github.com/PRQL/prql/pull/3751
