### ISSUE TITLE
Checklist for Release Process?

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#3766]
### What's up?

Perhaps we could create a checklist to enumerate all the fussy steps of releasing a new version and add it to the [Releasing](https://prql-lang.org/book/project/contributing/development.html#releasing) section of the Book. It might include:

PRQL Repo:
- All the machinery to release a version (I'm not clear on what this entails)
- Whatever's necessary to backport (if required)
- Update CHANGELOG to incorporate all changes
- Create a tag releae
- Update "Current Status" in README

VScode Extension:
- Ensure newest version gets pulled into the repo
- Update the version number in `package.json` to match 

Other repo's:
- I have no idea what is entailed

Thanks!

**Comment by richb-hanover** [comment]
I will also mention that it's good to review that our documentation is up to date with the changes, but don't want that effort to gate these interim releases.

**Comment by max-sixty** [comment]
This is in `development.md`. We could add the VSCode extension release as an item. Though it's a bit easier to wait for dependabot to upgrade `prql-js`. 

(Ideally we could have a tool which automates that release, but not sure it's easy)

**Comment by richb-hanover** [comment]
If the VScode extension should be automagically updated and posted to the Marketplace when dependabot upgrades `prql-js`, then I guess the only item I would add to the existing checklist in `development.md` is something like:

* Review **Current Status** in the README file

**Comment by richb-hanover** [comment]
I'm confused... I changed `development.md` to reflect this change (my branch `patch-2` - see https://github.com/richb-hanover/prql/blob/patch-2/web/book/src/project/contributing/development.md) and thought I issued a PR. 

But the PR doesn't appear in the main PRQL repo. What could have happened? Many thanks

**Comment by max-sixty** [comment]
I never saw a PR! I'm not sure it went in...

**Comment by richb-hanover** [comment]
I'll try again...

**Comment by richb-hanover** [comment]
Let's see how #3777 works out...

**Comment by richb-hanover** [comment]
Closed with #3777
