### ISSUE TITLE
Too long symbol names in Rust

### ISSUE THREAD

**Issue by alexey-milovidov** [PRQL/prql#3768]
### What's up?

https://pastila.nl/?00001deb/dcae5f096cc0c517eae5d58ca7ed3157#T8hKbIl4Q/i5qJs3RaVtog==

**Comment by alexey-milovidov** [comment]
The first symbol name is 85640 bytes.

**Comment by max-sixty** [comment]
Thanks — that is very long...

We'll look at it.

Is this merely an annoyance for ClickHouse, or is more severe than that?

**Comment by alexey-milovidov** [comment]
Only an annoyance, nothing severe.

**Comment by aljazerzen** [comment]
These symbols are from our parser, which provide little to no information when debugging panics in it. It could be stripped, but I'm not sure if there is a way to strip these symbols only from a specific crate / module in Rust.

Or we could strip it all together?

**Comment by riking** [comment]
You can reduce the size of the type by making certain steps a `Box<dyn ...>` instead of the concrete Chumsky type -- everything below the `dyn` is hidden from the type system and therefore the symbol names.
