### ISSUE TITLE
`development.md` page is broken in Book

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#3778]
### What's up?

I wanted to modify the `development.md` page in the Book (https://prql-lang.org/book/project/contributing/development.html) but couldn't make it look correct in the Dev Container.

So I looked at the page on the live Book, and it is broken in the same way. 

The problem seems to be triggered near the `admonish note` that follows **Integration tests**.

I tried a few variations in that area of the document but couldn't find what's wrong. Hopefully, someone who's more versed in Markdown or the admonish processor can fix it. Thanks.

**Comment by max-sixty** [comment]
Thanks, good spot. Fixed in #3785

**Comment by richb-hanover** [comment]
And now I know more about using `admonish note`. No leading spaces - who knew? (Apparently, you do.)
