### ISSUE TITLE
"output.arrow" tab hides error message in Playground

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#3807]
### What happened?

Using a modified version of the query from https://github.com/PRQL/prql/issues/3490#issuecomment-1712962873, SOMETIMES I cannot see the error message in the Playground. (The modification is to paste in the full query, then comment out the second `aggregate` transform, to get the query shown below.)

When it fails, I only see a small strip of red at the bottom of the left pane, containing the word "Error".

But now I cannot make it happen - it shows the full error message as expected. Darn.

### PRQL input

```elm
from inv=invoices
join item=invoice_items (==invoice_id)
join t=tracks (item.track_id==t.track_id)

group {inv.billing_country, t.name} (
  aggregate (c=count t.name)
)

group {billing_country} (
  # aggregate (
  #   sort (-c)
  #   take 1
  # )
)
```

### SQL output

```SQL
N/A
```

### Expected SQL output

```SQL
N/A
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by richb-hanover** [comment]
I have tried changing window sizes, and other silly stuff, but can't make it happen. I'll snag a screen shot if I see it again.

**Comment by max-sixty** [comment]
Haha, OK — yeah I couldn't reproduce either. I believe you it happened! 😄 

Let's reopen when it does!

**Comment by richb-hanover** [comment]
@max-sixty  I was able to trigger this error in the Playground. Here's a screenshot.

<img width="483" alt="image" src="https://github.com/PRQL/prql/assets/1094930/11591292-eed8-4f11-8965-b3e39177b81e">

To reproduce: (Original message had steps swapped...)

1. Paste the query below (ignore the non-sensical SQL)
2. Remove one of the "="  Full error message appears
3. Click "output.arrow" tab. Presto! Only "Error:" appears
4. It seems related to which tab is showing - the other two hide part of the message
```
from invoices

select ! total == 0.99
```

**Comment by eitsupi** [comment]
I can't repro.

![image](https://github.com/PRQL/prql/assets/50911393/074a26d1-f6d3-45b6-bf1b-68d6f8a824b4)
![image](https://github.com/PRQL/prql/assets/50911393/8146986d-9c66-45c4-9c1e-4a55278b5481)

**Comment by richb-hanover** [comment]
My apologies - original instructions swapped steps 2 & 3. You should paste, remove a "=", then observe the error message in the Playground, then click the "output.arrow".

**Comment by max-sixty** [comment]
OK yeah, looks like the size of the error box is taking a lower priority than the size of the query results.

To confirm, this is the bottom of the window, so it does get cut off.

<img width="1271" alt="image" src="https://github.com/PRQL/prql/assets/5635139/1be7320d-41f8-4e65-98e3-4c6553619e19">

PRs welcome to prioritize the error box size! (I don't know web that well, but I imagine it's a very tractable problem...?)

**Comment by richb-hanover** [comment]
I'm looking at this now... Other test cases: 

* To force a "Binder error", change `transaction_fee` to `xtransaction_fee`
* To force a "Catalog error", use this query:
   ```
   let A = (
   from invoices
   )
   from s"select * from A using sample reservoir(10 rows) repeatable(0)"
   ```

**Comment by max-sixty** [comment]
> To force a "Catalog error", use this query:

That's because the table `A` doesn't exist in the DB. The SQL pane works though...

> To force a "Binder error", change `transaction_fee` to `xtransaction_fee`

What's the rest of the query? Sorry if I'm missing something obvious...

**Comment by richb-hanover** [comment]
Sorry I wasn't clear. I'm simply leaving these notes for myself as a way to create different kinds of error messages. I'm using these to debug the reason that the tabs cause different portions of the error message to be visible.

**Comment by richb-hanover** [comment]
I believe PR #3838 fixes this
