### ISSUE TITLE
Rename "output.sql", "output.arrow", etc. tabs in Playground

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#3822]
### What's up?

Two thoughts about the Playground:

1. I recommend we rename the four tabs of the Playground to something like this. Any better choices? If not, I'll create a PR.

   * Compiled SQL
   * Query Results
   * PL yaml
   * RQ yaml

2. The first two tabs are useful for newcomers. The last two are inscrutable (to me, at least). I assume they were enormously valuable in early development days for checking the generated code. Are they still useful? Do they justify taking up screen space in the Playground?

Thanks as always

**Comment by aljazerzen** [comment]
I agree, this would make more sense. Current design tries to mimic vscode editor tabs, but this is probably not obvious to all.

The last two tabs are still useful - I occasionally use them to quickly debug something on the main branch.

**Comment by max-sixty** [comment]
Agree re renaming — care to take a swing at a PR @richb-hanover ?

(I find the other tabs useful at times too, I would prefer to retain...)

**Comment by richb-hanover** [comment]
OK. I will raise a PR to update the names in the tabs in the next week or so.

You've confirmed all four tabs have value: I will leave them all. Thanks

**Comment by richb-hanover** [comment]
I believe PR #3838 fixes this
