### ISSUE TITLE
a-(b+c) becomes a-b+c

### ISSUE THREAD

**Issue by echou** [PRQL/prql#3835]
### What happened?

wrong operator precedence

### PRQL input

```elm
from foo
select a - (b + c)
```

### SQL output

```SQL
SELECT
  a - b + c
FROM
  foo
```

### Expected SQL output

```SQL
SELECT
  a - (b + c)
FROM
  foo
```

### MVCE confirmation

- [x] Minimal example
- [x] New issue

**Comment by max-sixty** [comment]
I'm not sure how this happened. I'm looking into it now. I thought I fixed a bunch of complicated precedence problems — seems like I missed a very simple one?!
