### ISSUE TITLE
Building Snap fails on the release pipeline

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#3836]
### What's up?

The `build-and-publish-snap` job fails on the release pipeline.

https://github.com/PRQL/prql/actions/runs/6863024094/job/18661935807#logs

I don't know why.

By the way @max-sixty can you look when you're logged in on the Snapcraft website if it is possible to set some metadata such as the license and add some links the PRQL website and GitHub?

**Comment by max-sixty** [comment]
Good spot — it looks like the snap is being built in a context with an older version of rust. Do you know what that is? Can we install a newer version of rust in that context?

Our general tests are built in a plain GHA image, and update automatically. So maybe that's in a docker container?

**Comment by max-sixty** [comment]
> By the way @max-sixty can you look when you're logged in on the Snapcraft website if it is possible to set some metadata such as the license and add some links the PRQL website and GitHub?

I added the website (though it won't let me add two websites, so I'm not sure I can add the GH)

But if I add the license, it will stop using the metadata we supply programmatically. Could we instead update our snap definition?

<img width="695" alt="image" src="https://github.com/PRQL/prql/assets/5635139/39b9dd3d-df58-41d0-be66-1e46d64e33b8">

**Comment by vanillajonathan** [comment]
> Good spot — it looks like the snap is being built in a context with an older version of rust. Do you know what that is? Can we install a newer version of rust in that context?
> 
> Our general tests are built in a plain GHA image, and update automatically. So maybe that's in a docker container?

I think Snapcraft doesn't use Docker, I think it uses a container manager called LXD which manages LXC containers which is a Linux technology for containers, and unlike Docker the containers are always Ubuntu.

I found:
https://github.com/qarmin/szyszka/blob/master/snap/snapcraft.yaml

Which ran into the same problem and solved it by having declaring in the Snapcraft YAML file to use Rustup to install the latest version of Rust.

> But if I add the license, it will stop using the metadata we supply programmatically. Could we instead update our snap definition?

Our Snapcraft YAML file:
https://github.com/PRQL/prql/blob/main/prqlc/packages/snap/snapcraft.yaml
Declares the license and other metadata, but I don't know why it doesn't get picked up on the Snapcraft website.

**Comment by max-sixty** [comment]
> I don't know why it doesn't get picked up on the Snapcraft website.

I don't think it's successfully published for a while — let's reassess after the next successful publish?
