### ISSUE TITLE
Use `prqlc` in Dev Container?

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#3858]
### What's up?

Using a recent Dev Container, I was surprised that I could not use `prqlc` from the CLI.

```
vscode ➜ /workspaces/prql (main) $ echo "" | prqlc compiler
bash: prqlc: command not found
```

I imagine something needs to be added to the `postCreateCommand` hook, but don't know what.

**Comment by max-sixty** [comment]
Given it's a dev container, I would probably use the one from the current code, which can be called with `cargo run -p prqlc -- compile`.

If we install `prqlc`, we'll have the version that existing when we built the dev container, which could be confusing. Though folks can always `cargo install` the current version themselves from the local path if they want the shorter `prqlc`.

Does that make sense?

**Comment by richb-hanover** [comment]
Yes - that's a good solution. TL;DR... Use:

`echo "from foo" | cargo run -p prqlc -- compile`

The first time, it compiles a bunch of files, but re-running the command works right off. Thanks

**Comment by richb-hanover** [comment]
... and just so I don't have to re-create the command again, here's a here-doc as an input to prqlc...

```
cat <<'EOF' |  cargo run -p prqlc -- compile 
from inv=invoices
join item=invoice_items (==invoice_id)

group { inv.billing_city } (

  group { item.name } (
    aggregate {
      ct1 = count inv.name,
    }
  )
)
EOF
```
