### ISSUE TITLE
Errors in Playground colorization with date-like strings

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#3910]
### What happened?

The Playground doesn't colorize the date-like strings properly. `"2015-01-01"` (without an "@") looks odd. Here's an image:

<img width="478" alt="image" src="https://github.com/PRQL/prql/assets/1094930/aa7d992b-963f-4b34-ba06-54307a205955">

### PRQL input

```elm
from reservations        

# coloration is wrong; resulting date is OK
filter (                 
  staydate2 >= "2015-01-01" && staydate2<="2015-12-31"
)
```

### SQL output

As expected...

```SQL
SELECT
  *
FROM
  reservations
WHERE
  staydate2 >= '2015-01-01'
  AND staydate2 <= '2015-12-31'

-- Generated by PRQL compiler version:0.10.1 (https://prql-lang.org)

```

### Expected SQL output

```SQL
N/A
```

### MVCE confirmation

- [ ] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
Thanks @richb-hanover 

Open to changing the monarch grammar. Also open to #3598 and switching out for the Lezer one...

**Comment by richb-hanover** [comment]
This can go on the back burner.  It's a problem with the appearance, not code generation, so can wait 'til there's a bigger push to work on the Playground.

**Comment by max-sixty** [comment]
OK thanks! In general, totally fine to open these sorts of issues though!
