### ISSUE TITLE
How to use `loop`? Examples desired...

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#3926]
### What's up?

PRQL has a `loop` construct, but I really don't understand how to use it "in real life". 

The examples in the [Book](https://prql-lang.org/book/reference/stdlib/transforms/loop.html) and the [Blog](https://prql-lang.org/posts/2023-03-14-pi-day/) aren't really instructive: they seem "too clever by half", and don't give any guidance for a real-world application that uses data from a table.

I'm willing to write something up, either in the Book or as a blog post, but I need someone to show how `loop` might be used with real tables. (As a side benefit, I expect I'll also learn a bit about how SQL's RECURSIVE works as well.) Many thanks.

**Comment by kgutwin** [comment]
I've used `WITH RECURSIVE` in SQLite a couple of times in my recent project; I haven't yet tried to translate them into PRQL, but I can explain how two "real world" use cases work from the SQL angle at least...

The first example is very simple and is just like the example in the book.

```sql
WITH RECURSIVE generate_series (value) AS (
    SELECT 0
    UNION ALL
    SELECT value + 1 FROM generate_series
    WHERE value + 1 <= 210
)

INSERT INTO collections (name, description, created_on)
SELECT
    value AS name,
    lower(hex(randomblob(random() % 256 + 128))) AS description,
    datetime('now') AS created_on
FROM generate_series
LIMIT 210;
```

This generates 210 collections, with their "names" just the value from the series (0, 1, 2, ...) and random hex characters as a description. It was used to preload a database for a set of unit tests for our application. Note that the `LIMIT 210` and `WHERE value + 1 <= 210` statements are redundant (either one will stop the recursive series).

The second example is more clever. In this case, we have a database table of "items" defined like this:

```sql
CREATE TABLE items (
    id TEXT NOT NULL,
    type TEXT NOT NULL,  -- 'file', 'folder', ...
    name TEXT NOT NULL,
    folder_id TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (folder_id) REFERENCES items(id)
);
```

You can see that an item can be in a 'folder' by setting its `folder_id` to the `id` of another folder item. When the `folder_id` is NULL, that indicates the item is in the "root" folder.

We can then make a view that shows items by their path using `WITH RECURSIVE`:

```sql
CREATE VIEW items_by_path (
    id,
    type,
    name,
    folder_id,
    path
) AS
WITH RECURSIVE path_of (id, path) AS (
    SELECT 
        id,
        name
    FROM items WHERE folder_id IS NULL
    UNION ALL
    SELECT 
        items.id,
        path_of.path || '/' || items.name
    FROM items
    INNER JOIN path_of ON items.folder_id = path_of.id
)
SELECT
    items.id,
    items.type,
    items.name,
    items.folder_id,
    path_of.path
FROM items
INNER JOIN path_of ON path_of.id = items.id;
```

The `WITH RECURSIVE` works very simply - you return an item's `id` and `name` directly from the `items` table when the item's `folder_id` is NULL; then, you union that set of results with everything else from the `items` table, using an `INNER JOIN` to prepend the path to the item's name. The only trick is that the INNER JOIN is on the `path_of` relation, which is where the recursion comes in. You could imagine that if you did this without `WITH RECURSIVE`, it would work (replacing `path_of` in the `INNER JOIN` with `items`) but only one level deep; the `WITH RECURSIVE` allows it to work to an arbitrary depth.

What the above looks like in SQLite:

```
sqlite> insert into items (id, type, name, folder_id) values ('a', 'folder', 'first', null);
sqlite> insert into items (id, type, name, folder_id) values ('b', 'folder', 'second', 'a');
sqlite> insert into items (id, type, name, folder_id) values ('c', 'folder', 'third', 'b');
sqlite> select * from items_by_path;
+----+--------+--------+-----------+--------------------+
| id |  type  |  name  | folder_id |        path        |
+----+--------+--------+-----------+--------------------+
| a  | folder | first  |           | first              |
| b  | folder | second | a         | first/second       |
| c  | folder | third  | b         | first/second/third |
+----+--------+--------+-----------+--------------------+
```

**Comment by richb-hanover** [comment]
Yup. I'm going to have to teach myself how `WITH RECURSIVE` works :-) 

These examples are terrific. I plan to go away and chew on them, see how to express them in PRQL, and then write something up. Probably not 'til after the holidays... 

PS I'm open to additional examples. Thanks again!

**Comment by snth** [comment]
@richb-hanover I have some more examples here: [prql-dataconf-2023-10-25.ipynb](https://colab.research.google.com/drive/16vs62Qmx4yLtXrVW1_Qs7vYsplG4xDU6?usp=sharing
)

I don't know if they are really instructive but they're probably more useful. I did plan to expound these in more detail, but alas, there has been no time. Shoot me a question if you are unclear on any of these.

**Comment by richb-hanover** [comment]
Oh wow! More examples! These are all great. These are clearly not "contrived". Thanks!

**Comment by max-sixty** [comment]
Thanks @snth !
