### ISSUE TITLE
Name of the type for UTF-8 encoded strings of textual data

### ISSUE THREAD

**Issue by aljazerzen** [PRQL/prql#3981]
Title says it all (while trying to be impartial). Followup for discussion in #3913. It looks like this topic is practically already decided, but I'm documenting the reasoning here anyway.

---

Current state:
- `type text`
- `let from_text = func ...`
- `module text { let lower = func ... }`

There is a proposal that all three items be renamed from `text` to `string`.

Survey of other languages, courtesy of @vanillajonathan:

> It seems like most languages prefer `string` or `String` over `str` and `String` or `text`.
> 
> - C# uses `string.Format`
> - D uses `std.string.isNumeric("123")`
> - Elixir uses `String.first("elixir")`
> - F# uses `String.length "Hello"`
> - Go uses `strings.ToLower("Hello")`
> - Java uses `String.format`
> - JavaScript uses `String.fromCharCode(65)`
> - Kotlin uses `String.format("Hello")`
> - Lua uses `string.lower("Hello")`
> - PowerShell uses `[string]::Format("Hello")`
> - Python uses `str.format`
> - Ruby uses `String::try_convert('Hello')`
> - Rust uses `String::from("Hello, world!");`
> - Scala uses `String.format("Hello")`
> - VB.NET uses `String.Format`

Argument against is that PRQL is not meant for computer-science people only, and because term "string" is not a generally known term we should stick something more descriptive. That is `text` (current state).

---

An alternative is also just `str`, which suffers from same problems. It is also shorter which is not universally accepted as good.

**Comment by max-sixty** [comment]
I'm +1 on `text` for the reasons above!

**Comment by aljazerzen** [comment]
`text` it is.

**Comment by PrettyWood** [comment]
We may need to differentiate the types and modules `text` and `date` in the highlighting.
Don't know if they need to have a different name per se (It would be easier for sure)

**Comment by aljazerzen** [comment]
Differentiate between type `text` and module `text` (and similar for `date`)? I think that they don't need to have a different name right now, and it can stay this way. For naive highlighting that does just lexing and no parsing we can just assume they are types in both cases.

Highlighting does not have to be 100% accurate.

**Comment by snth** [comment]
This as already been adopted but for the record, I'm +1 on `text` as well.
