### ISSUE TITLE
Top with group on Postgres

### ISSUE THREAD

**Issue by PrettyWood** [PRQL/prql#3986]
### What happened?

We have a query builder in my company https://github.com/ToucanToco/weaverbird/, which is a click button interface that generates some config in our DSL that is then translated into Mongo, Pandas, many SQL dialects
We are rewriting our whole data pipeline in Rust and I wanted to use PRQL instead of generating many CTEs

I generated the code for the `top` step. The generated PRQL query works fine in the playground (without a dialect!) but our integration tests fail. And I force the dialect to Postgres in the playground, the query is indeed totally different

(In the MRE I want to keep the top 2 beers of each kind)

### PRQL input

```elm
prql target:sql.postgres

from_text """
price_per_l,alcohol_degree,name,cost,beer_kind,volume_ml,brewing_date,nullable_name
0.1599999964237213,13.5,Superstrong beer,2.890000104904175,Triple,330,2022-01-01,
0.05400000140070915,4.877377033233643,Ninkasi Ploploplop,2.890000104904175,India Pale Ale,330,2022-01-02,Ninkasi Ploploplop
0.004999999888241291,0.5699344873428345,Brewdog Nanny State Alcoholvrij,2.2899999618530273,Sans alcool,330,2022-01-03,Brewdog Nanny State Alcoholvrij
0.0560000017285347,6.994105339050293,Ardwen Blonde,2.0899999141693115,Best-sellers,330,2022-01-04,Ardwen Blonde
0.07000000029802322,8.930644989013672,Cuvée des Trolls,1.5499999523162842,Blonde,250,2022-01-05,
0.004999999888241291,1.2437106370925903,Weihenstephan Hefe Weizen Alcoholarm,1.590000033378601,Blanche & Weizen,500,2022-01-06,Weihenstephan Hefe Weizen Alcoholarm
0.04500000178813934,4.717409610748291,Bellfield Lawless Village IPA,2.490000009536743,India Pale Ale,330,2022-01-07,Bellfield Lawless Village IPA
0.08399999886751175,12.974271774291992,Pauwel Kwak,1.690000057220459,Belge blonde forte & Golden Ale,330,2022-01-08,Pauwel Kwak
0.06499999761581421,7.74746561050415,Brasserie De Sutter Brin de Folie,2.190000057220459,Blonde,330,2022-01-09,
0.05999999865889549,8.749608993530273,Brugse Zot blonde,1.7899999618530273,Blonde,330,2022-01-10,Brugse Zot blonde
"""
select {`beer_kind`,`price_per_l`}
group {`beer_kind`} (
  sort {+`price_per_l`}
  take 2
)
```

### SQL output

```SQL
SELECT
  DISTINCT ON (beer_kind) beer_kind,
  price_per_l
FROM
  table_0
ORDER BY
  beer_kind,
  price_per_l
```

### Expected SQL output

```SQL
table_1 AS (
  SELECT
    beer_kind,
    price_per_l,
    ROW_NUMBER() OVER (
      PARTITION BY beer_kind
      ORDER BY
        price_per_l
    ) AS _expr_0
  FROM
    table_0
)
SELECT
  beer_kind,
  price_per_l
FROM
  table_1
WHERE
  _expr_0 <= 2
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

### Anything else?

Loving PRQL. Thanks for your help and sorry if I didn't create the right query for our usecase 🙏

**Comment by max-sixty** [comment]
Thanks @PrettyWood !

Am I correct in thinking that we _do_ want `DISTINCT ON` in postgres, but there's a bug in ignoring the `take 2` transform?

**Comment by PrettyWood** [comment]
I guess so

**Comment by aljazerzen** [comment]
No, we don't want `DISTINCT ON` since that will pick only the first item in each GROUP BY partition.

The correct behavior would be to pick first two items in each partition. In SQL, this is only achievable by using `ROW_NUMBER()` and `WHERE`.

This is the problem here: https://github.com/prql/PRQL/blob/main/prqlc/prql-compiler/src/sql/srq/preprocess.rs#L172-L177
- we are checking if we should `take_only_first`,
- we correctly apply this condition to `DISTINCT`,
- we don't apply this condition to `DISTINCT ON`  <-- this is the bug

**Comment by aljazerzen** [comment]
Oh, I didn't notice, you've opened a PR already.

**Comment by max-sixty** [comment]
> Oh, I didn't notice, you've opened a PR already.

Yeah and also realized my suggestion was wrong 😄
