### ISSUE TITLE
`std.prql` module

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#3996]
Perhaps we can now move `std.prql_version` to `std.prql.version`?

https://github.com/PRQL/prql/blob/b19bd8077b9035d5bd88c9cfeddd56f6f4ab6c86/web/book/src/project/target.md?plain=1#L98-L107

(This is a breaking change, so we may need to deprecate the `prql_version` first and remove it later.)

I also imagine that it would be useful to have a function to get the current target, or to get some information as a relation.

**Comment by max-sixty** [comment]
+1 from me

(and +1 to the concept of deprecations, though we would have to build that, and I would vote to not wait on it before making breaking changes as long as we're confident it's a good change)

**Comment by eitsupi** [comment]
I tried to implement this, but `prql` is a reserved word and cannot be used as a module name?

Edit: we can use `` `prql` `` instead of `prql` as the module name.
