### ISSUE TITLE
Clickhouse DATETIME conversion invalid format

### ISSUE THREAD

**Issue by ukclivecox** [PRQL/prql#4048]
### What happened?

Clickhouse can not convert ISO format using the TIMESTAMP operator.

### PRQL input

```elm
prql target:sql.clickhouse
from foo | filter (time_listed | in ..@2023-03-01T00:00:00Z)
```

### SQL output

```SQL
SELECT
  *
FROM
  foo
WHERE
  time_listed <= TIMESTAMP '2023-03-01T00:00:00Z'
```

### Expected SQL output

```SQL
SELECT
  *
FROM
  foo
WHERE
  time_listed <= TIMESTAMP '2023-03-01T00:00:00'
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

### Anything else?

SELECT parseDateTime32BestEffort('2023-03-01T00:00:00Z')

```
┌─parseDateTime32BestEffort('2023-03-01T00:00:00Z')─┐
│                               2023-03-01 00:00:00 │
└───────────────────────────────────────────────────┘
```

SELECT toDateTime('2023-03-01T00:00:00Z')

```
Received exception from server (version 23.10.4):
Code: 6. DB::Exception: Received from localhost:19000. DB::Exception: Cannot parse string '2023-03-01T00:00:00Z' as DateTime: syntax error at position 19 (parsed just '2023-03-01T00:00:00'): While processing toDateTime('2023-03-01T00:00:00Z'). (CANNOT_PARSE_TEXT)
```

SELECT toDateTime('2023-03-01T00:00:00')

```
┌─toDateTime('2023-03-01T00:00:00')─┐
│               2023-03-01 00:00:00 │
└───────────────────────────────────┘
```

**Comment by max-sixty** [comment]
I don't think that stripping the timezone would be good — `'2023-03-01T00:00:00Z'` has a different meaning to `'2023-03-01T00:00:00'`.

A really complete approach would be to preemptively know that ClickHouse didn't support timezones, and raise an error. Getting to that level of support across language features & dialects would be nice, but require lots of investment.

So for the moment, is it reasonable to just use `..@2023-03-01T00:00:00)` in the PRQL query? That then passes on the `'2023-03-01T00:00:00'` value and the query should work.

**Comment by ukclivecox** [comment]
Yes, I can work around this. Just created this issue as an FYI for discussion for a full solution.

**Comment by max-sixty** [comment]
OK great.

Let's leave it open for a bit to see if others have thoughts.

My initial inclination is that this level of detail in the compiler is probably some distance away, unless a contributor has a specific interest in clickhouse datetimes. So we could mark as postponed.

**Comment by max-sixty** [comment]
Marking as postponed. Thanks for the suggestion @ukclivecox.
