### ISSUE TITLE
Cannot use it with a vite project

### ISSUE THREAD

**Issue by maelp** [PRQL/prql#4148]
### What happened?

When using the "bundler" way of including the lib in my typescript / vite project I have the following error

<img width="847" alt="image" src="https://github.com/PRQL/prql/assets/15458/568a8804-2990-4c79-925a-75aecd0da6f9">

### PRQL input

```elm
none
```

### SQL output

```SQL
none
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by vanillajonathan** [comment]
You need to install the [`vite-plugin-wasm`](https://www.npmjs.com/package/vite-plugin-wasm) npm package as a dev dependency.

    npm install vite-plugin-wasm --save-dev

Edit your `vite.config.js` file to add `wasm` as a plugin. See the code for the Playground, we use Vite.

https://github.com/PRQL/prql/tree/main/web/playground

**Comment by maelp** [comment]
interesting, I thought this was no longer necessary (eg I don't need it to use duckdb-wasm), can you tell me more about it?

(after installing the plugin, I can confirm it now works)

**Comment by maelp** [comment]
(for instance I can use duckdb-wasm or opencascade-js without using vite-plugin-wasm, in what case is this plugin needed?)

**Comment by vanillajonathan** [comment]
I don't know, maybe @aljazerzen knows.
