### ISSUE TITLE
`group` not working as intended with `take`

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#421]
Possibly we need to implement #420 given our plan of how to implement this query? Though in the meantime, should this raise an error rather than ignoring `group`?

```elm
from employees
group role (
  sort join_date  # taken from above
  take 1
)
```

```sql
SELECT
  employees.*
FROM
  employees
ORDER BY
  join_date
LIMIT
  1
```

**Comment by aljazerzen** [comment]
I believe this now throws an error:

```
from employees
group role (
  sort join_date  # taken from above
  take 1
)
```

```
Error: transform `Take` is not allowed within group context
```

It's also missing the span and pretty formatting, but eventually this should compile to DISTINCT anyway.

**Comment by max-sixty** [comment]
OK cool — FYI it doesn't throw an error on main, but maybe on the proposed PR

**Comment by aljazerzen** [comment]
True that, I merged "window functions PR" so now it should.

**Comment by max-sixty** [comment]
Wonderful, confirmed: 
<img width="634" alt="image" src="https://user-images.githubusercontent.com/5635139/166006119-3377c8d2-e38e-48f5-aed4-a926ed6742d2.png">

**Comment by max-sixty** [comment]
We now have `DISTINCT` working!

We don't have it working in groups though, so we should probably raise an error: 

```elm
from employees
group role (
  sort join_date  # taken from above
  take 1
)
```

```sql
SELECT
  DISTINCT employees.*
FROM
  employees
```

**Comment by aljazerzen** [comment]
This is not easy to do with our current compiler setup. Will instead try to hurry up with making this work.

But I've added this error message:
```
from employees
group aaa (
  take 1..2
)
Error:
   ╭─[-:3:3]
   │
 3 │   take 1..2
   ·   ────┬────
   ·       ╰────── `take` within `group` currently only supports argument `1`
   ·
   · Help: For now, you can derive a row number within a group and do a filter on that.
───╯
```
