### ISSUE TITLE
`task build-all` fails in Dev Container

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#4210]
### What happened?

Using PRQL c953a385c on macOS 14.2.1 on M2 silicon (Docker 4.27.1), I was able to run the three web tasks (run-playground, run-book, run-website) successfully in the Dev Container. I then decided to try `task build-all` and got a compilation error.

I then removed all containers, images, and volumes and re-ran. Docker rebuilt everything, the three web tasks work fine, and the `task build-all` still fails with the following messages (this is only the tail of the file - everything left in the console of the Dev Container) See the messages at: https://pastebin.com/UFVyJUGL

Note: an interesting change: the `prql/target` folder in the OS frequently gets large (it had been up to 9.8 GBytes). I also `rm -rf target` (from the OS). After the re-build the `target` folder had been recreated, but has exactly zero bytes.

What other diagnostic information could I provide? Thanks.

### PRQL input

```elm
N/A
```

### SQL output

```SQL
N/A
```

### Expected SQL output

```SQL
N/A
```

### MVCE confirmation

- [ ] Minimal example
- [ ] New issue

**Comment by max-sixty** [comment]
Is it a disk space issue? How much space is Docker allocated?

**Comment by richb-hanover** [comment]
Here's what I see:

- In the past, I have had trouble when my host OS free disk got low. 
- But... the host OS disk now has 78GBytes free of the 256GByte capacity
- Docker Desktop Settings -> Resources showed 96 GBytes. I bumped it up to 120GBytes, with the same error messages.
- Docker Desktop Settings now shows 51GB available of 117 GBytes.

Another interesting change, ALL the Docker volumes (devcontainer-cargo-cache..., devcontainer-cargo-target..., vscode) have zero bytes. And as noted previously, `prql/target` on the host disk also has zero bytes

**Comment by eitsupi** [comment]
Something may be wrong with the file system permissions.
It may be cured by completely uninstalling Docker and deleting all existing folders and starting over.

So what I am saying is that this is most likely a Docker issue and you are more likely to get an accurate answer if you ask the question in the Docker community rather than here.
I use Docker to a certain extent, so I can give some advice, but it is not accurate.

**Comment by max-sixty** [comment]
FYI I did try pulling the latest image and running `task build-all` — it does work on my end...

**Comment by richb-hanover** [comment]
Thanks for your thoughts here. I was able to make the project build on my M2 box by removing all containers, images, and volumes, then removing the Build Cache. (I use the Disk Usage extension to make it visible.) I had to use `task build-all` multiple times until all the errors were bypassed. The Dev Container works fine now.

@max-sixty. I suppose it could be disk-space related. What is a good way to determine the utilization?

@eitsupi I am glad you considered a permissions problem, but I don't think it's likely. I only use this M2 Mac for building PRQL, and have not changed anything there (beyond updating Docker and updating the PRQL repo) since last year.

One last thing (I know, I'm perseverating on this): 

- All three Docker volumes on the M2 Mac are empty; `prql/target` is empty on the host OS. I am used to seeing that folder get to 2-5 GBytes.
- On my Intel Macbook, the Docker volumes have a sensible amount of data (according to the Docker Desktop), and `prql/target` has about 2.3GBytes (expected). However, none of the files have been updated in that folder since 17 Nov 2023. 

It's almost as if those files (Docker volumes, `prql/target`) are being stored "somewhere else"... Is this even possible? (If it seems OK, please feel free to say, "Rich, it's OK..." and we can close this :-) Thanks.

**Comment by max-sixty** [comment]
> I had to use `task build-all` multiple times until all the errors were bypassed.

That is curious...




> * On my Intel Macbook, the Docker volumes have a sensible amount of data (according to the Docker Desktop), and `prql/target` has about 2.3GBytes (expected). However, none of the files have been updated in that folder since 17 Nov 2023.
> 
> 
> It's almost as if those files (Docker volumes, `prql/target`) are being stored "somewhere else"... Is this even possible? (If it seems OK, please feel free to say, "Rich, it's OK..." and we can close this :-) Thanks.

I have large docker volumes:

```
$ docker system df

TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          11        7         15.36GB   10.34GB (67%)
Containers      7         1         1.766GB   74B (0%)
Local Volumes   19        7         80.95GB   18.32GB (22%)
Build Cache     64        0         120.1kB   120.1kB
```

And a big `target`:

```
# From inside the container
$ cd target
$ du -sh .
54G     .
```

...which makes sense. Looks like much of the target can be `cargo clean`-ed, so I don't think that much space is necessary.

Are you seeing something different?

> @max-sixty. I suppose it could be disk-space related. What is a good way to determine the utilization?

Not an expert, but if the `docker system df` command is giving more space than docker is allocated, then that's concerning. I have found that docker will run out of space, and compilers can give really confusing error messages.

**Comment by richb-hanover** [comment]
Curiouser and curiouser... There's some covert storage somewhere... (That is to say that the files ordinarily written to _target_ are not showing up on the directory in the host OS...)

On the host OS:

```
richb@Mac-mini2 prql % touch richb.txt       <-- create a unique temporary file

richb@Mac-mini2 prql % ll
total 560
drwxr-xr-x  38 richb  staff    1216 Feb 12 15:30 .
drwxr-xrwx   6 richb  staff     192 Jan 20 13:03 ..
-rw-r--r--@  1 richb  staff   10244 Feb 12 15:25 .DS_Store
drwxr-xr-x   3 richb  staff      96 Aug  1  2023 .cargo
drwxr-xr-x   8 richb  staff     256 Feb 10 21:03 .config
drwxr-xr-x   5 richb  staff     160 Feb 10 21:03 .devcontainer
drwxr-xr-x  16 richb  staff     512 Feb 12 07:50 .git
-rw-r--r--   1 richb  staff     640 Aug  1  2023 .gitattributes
drwxr-xr-x  11 richb  staff     352 Feb 10 21:03 .github
-rw-r--r--   1 richb  staff     585 Jan 30 19:35 .gitignore
-rw-r--r--   1 richb  staff     535 Aug  1  2023 .markdownlint-cli2.yaml
-rw-r--r--   1 richb  staff    1587 Jan 30 19:35 .mega-linter.yaml
-rw-r--r--   1 richb  staff    3217 Feb  6 19:10 .pre-commit-config.yaml
-rw-r--r--   1 richb  staff     354 Oct 18 21:45 .prettierignore
-rw-r--r--   1 richb  staff     183 Aug  1  2023 .prettierrc.yaml
-rw-r--r--   1 richb  staff      62 Aug  1  2023 .sqlfluff
drwxr-xr-x   4 richb  staff     128 Aug  1  2023 .task
drwxr-xr-x   3 richb  staff      96 Aug  1  2023 .vscode
-rw-r--r--   1 richb  staff   53396 Feb 11 07:18 CHANGELOG.md
-rw-r--r--   1 richb  staff  118686 Feb 11 07:18 Cargo.lock
-rw-r--r--   1 richb  staff    1266 Feb 11 07:18 Cargo.toml
-rw-r--r--   1 richb  staff   10273 Aug  1  2023 LICENSE
-rw-r--r--   1 richb  staff    7964 Feb  7 21:49 README.md
-rw-r--r--   1 richb  staff   16120 Feb 10 21:03 Taskfile.yml
-rw-r--r--   1 richb  staff     530 Jan 30 19:35 _typos.toml
-rw-r--r--   1 richb  staff    1947 Jan 30 19:35 bacon.toml
drwxr-xr-x  10 richb  staff     320 Aug  1  2023 bindings
drwxr-xr-x   7 richb  staff     224 Oct 18 21:45 crates
-rw-r--r--   1 richb  staff    7046 Oct 16 21:36 flake.lock
-rw-r--r--   1 richb  staff    2108 Feb  6 19:10 flake.nix
drwxr-xr-x   7 richb  staff     224 Jan 30 19:35 grammars
drwxr-xr-x   9 richb  staff     288 Feb  7 21:49 lutra
drwxr-xr-x   3 richb  staff      96 Oct 18 21:45 packages
drwxr-xr-x  13 richb  staff     416 Feb 10 21:03 prqlc
-rw-r--r--   1 richb  staff       0 Feb 12 15:30 richb.txt          <-- note richb.txt
-rw-r--r--   1 richb  staff     285 Dec 28 19:21 rust-toolchain.toml
drwxr-xr-x   2 richb  staff      64 Feb 10 21:26 target
drwxr-xr-x   8 richb  staff     256 Oct 22 08:43 web

richb@Mac-mini2 prql % cd target
richb@Mac-mini2 target % du -sh .
  0B	.

richb@Mac-mini2 prql % ll target
total 0
drwxr-xr-x   2 richb  staff    64 Feb 10 21:26 .
drwxr-xr-x  38 richb  staff  1216 Feb 12 15:30 ..

richb@Mac-mini2 prql % docker system df
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          2         1         3.326GB   2.685GB (80%)
Containers      1         1         1.49GB    0B (0%)
Local Volumes   3         3         51.85GB   0B (0%)
Build Cache     29        0         124.1kB   124.1kB


```

Within the Dev Container: _richb.txt_ is present

```
/workspaces/prql (main) $ ll
total 240K
-rw-r--r--  1 vscode vscode 2.0K Jan 31 00:35 bacon.toml
drwxr-xr-x 10 vscode vscode  320 Aug  2  2023 bindings
-rw-r--r--  1 vscode vscode 116K Feb 11 12:18 Cargo.lock
-rw-r--r--  1 vscode vscode 1.3K Feb 11 12:18 Cargo.toml
-rw-r--r--  1 vscode vscode  53K Feb 11 12:18 CHANGELOG.md
drwxr-xr-x  7 vscode vscode  224 Oct 19 01:45 crates
-rw-r--r--  1 vscode vscode 6.9K Oct 17 01:36 flake.lock
-rw-r--r--  1 vscode vscode 2.1K Feb  7 00:10 flake.nix
drwxr-xr-x  7 vscode vscode  224 Jan 31 00:35 grammars
-rw-r--r--  1 vscode vscode  11K Aug  2  2023 LICENSE
drwxr-xr-x  9 vscode vscode  288 Feb  8 02:49 lutra
drwxr-xr-x  3 vscode vscode   96 Oct 19 01:45 packages
drwxr-xr-x 13 vscode vscode  416 Feb 11 02:03 prqlc
-rw-r--r--  1 vscode vscode 7.8K Feb  8 02:49 README.md
-rw-r--r--  1 vscode vscode    0 Feb 12 20:30 richb.txt                 <-- note richb.txt
-rw-r--r--  1 vscode vscode  285 Dec 29 00:21 rust-toolchain.toml
drwxr-xr-x  7 vscode root   4.0K Feb 12 13:15 target
-rw-r--r--  1 vscode vscode  16K Feb 11 02:03 Taskfile.yml
-rw-r--r--  1 vscode vscode  530 Jan 31 00:35 _typos.toml
drwxr-xr-x  8 vscode vscode  256 Oct 22 12:43 web

vscode ➜ /workspaces/prql (main) $ ll target
total 20K
drwxr-xr-x   7 vscode vscode 4.0K Feb 12 14:09 debug
drwxr-xr-x 169 vscode vscode 4.0K Feb 12 13:14 doc
drwxr-xr-x   7 vscode vscode 4.0K Feb 12 13:15 release
drwxr-xr-x   2 vscode vscode 4.0K Feb 12 12:54 tmp
drwxr-xr-x   5 vscode vscode 4.0K Feb 12 13:15 wasm32-unknown-unknown
vscode ➜ /workspaces/prql (main) $ 

vscode ➜ /workspaces/prql (main) $ du -sh .
48G   
```

**Comment by max-sixty** [comment]
https://github.com/PRQL/prql/blob/591c2a58c25f7fe4aa096d6c029ba4901b48d54b/.devcontainer/devcontainer.json#L37

The `target` is mapped to a volume!

**Comment by richb-hanover** [comment]
Ahah! the commit message from 17 Nov 2023 for #3817 says: "devops: Use internal volume for target in devcontainer (https://github.com/PRQL/prql/pull/3817)" 

If I understand correctly, the `target` files are now internal to Docker, and are no longer written to the host OS. That ~~jives~~ jibes with my observation that none of the files on my Intel Macbook had been modified after that date...

So... moving `target` into Docker appears to make it difficult for my installation to `task build-all`. But I never need to do that (I just do it for cussedness...) I wouldn't be affected because I make all my changes in the playground, website, and book. I would be OK leaving it as-is. Thanks.

**Comment by max-sixty** [comment]
OK great!
