### ISSUE TITLE
Replace `anyhow::Result` with our own `prqlc::Result` alias

### ISSUE THREAD

**Issue by aljazerzen** [PRQL/prql#4220]
We use `anyhow::Result` for return type of most function calls within prqlc, even though it 99% of cases, it it can only return error of type `prqlc::Error`.

I suggest we do the following:

```
type prqlc::Result<T> = Result<T, prqlc::Error>
```
... and use that instead of `anyhow::Result`.

It is probably good to be more explicit about what the error is.

**Comment by max-sixty** [comment]
Yes, makes sense to me!
