### ISSUE TITLE
make PRQL usable from observable/framework

### ISSUE THREAD

**Issue by srenatus** [PRQL/prql#4273]
### What's up?

The current setup of the JS bindings won't allow for using them from https://observablehq.com/framework/. I've tried many things (😅) and finally came across [this page](https://observablehq.com/@huw/prql), which explains the conundrum [here](https://observablehq.com/@huw/prql#cell-26):

> [...] PRQL publishes 3 entrypoints to npm—bundler, node, and web—but unfortunately the web entrypoint is actually compiled with the no-modules flag, which sets the wasm_bindgen variable globally rather than exporting anything from the package. None of these entrypoints work in Observable using any methods.

The page goes on explaining a workaround, which works, but it would be so nice if you could just say
```js
import init, { compile } from "npm:prql-js";
await init()
// ... etc ...
```
instead of manually building prql and putting the files into the repository.

(ℹ️ The linked page predates Observable Framework, but the reconstruction of the problem is still valid.)

The gist is that all it would take would be to switch the `web` target to `web` instead of `no-modules`. I'd be happy to push a PR, but I don't know about the impact of replacing `no-modules`. To play extra nice with JS CDNs (like jsdelivr, esm.sh, unpkg.com), we'd need to keep the package.json as-is, I think. That _could_ break existing usage? 🤔 

Related https://github.com/PRQL/prql/issues/1836

**Comment by max-sixty** [comment]
Thanks @srenatus.

Is anyone familiar with whether we can build the `web` without `no-modules` without downsides?

We could make yet another target of `no-modules` and have `web` use the `web` target? (Would take a PR for this, would start here: https://github.com/PRQL/prql/blob/dbd9c9153ef5b2696dbabd0922fafabc5b8fdde9/prqlc/bindings/js/package.json#L33)

**Comment by srenatus** [comment]
> Is anyone familiar with whether we can build the web without no-modules without downsides?

I've found this explanation quite helpful: https://rustwasm.github.io/wasm-bindgen/examples/without-a-bundler.html -- it shows the "web" target and the "no-modules" target. It lists some downsides regarding the use of `no-modules`.

But the thing I'm uncertain about is the current usage of the JS bindings. Clearly you've got a playground, and we wouldn't want to break that. (So, either keep compatibility somehow, or adapt the code.)

> We could make yet another target of no-modules and have web use the web target?

I'm afraid that wouldn't be enough -- to have the JS CDNs pick up the right thing, it would also need to be the thing that's references in `package.json`: https://github.com/PRQL/prql/blob/8bf0230819332972a8234222a4c80263296fc969/prqlc/bindings/js/package.json#L2

Happy to help!

**Comment by max-sixty** [comment]
> Clearly you've got a playground, and we wouldn't want to break that. (So, either keep compatibility somehow, or adapt the code.)

FWIW it looks like the playground uses the bundler target:

https://github.com/PRQL/prql/blob/87ecb1ef9e70647dc5ced31bff63253cbfae6ead/web/playground/src/workbench/Workbench.jsx#L3

---



> I've found this explanation quite helpful: https://rustwasm.github.io/wasm-bindgen/examples/without-a-bundler.html -- it shows the "web" target and the "no-modules" target. It lists some downsides regarding the use of `no-modules`.

Nice. A bit of a puzzle on whether there's a disadvantage of the `web` target...

---

If downstream users need to change their code slightly to consume it, I think that's fine. If we're breaking things that can't be fixed with a small change in code, then that's less fine. Unless there are objections, I would be quite open to a PR that switches this to the newer & overall better `web` target, and then very worst case we can revert it.

**Comment by srenatus** [comment]
Cool. I'll get a PR going tomorrow or later this week 🐾

**Comment by max-sixty** [comment]
Awesome, thanks!
