### ISSUE TITLE
The `let main =` example in the book doesn't work

### ISSUE THREAD

**Issue by broneill** [PRQL/prql#4275]
### What happened?

In the [variables](https://prql-lang.org/book/reference/declarations/variables.html) page of the PRQL book, it states that `from x` is equivalent to `let main = x`.  When I try the example in the playground, it doesn't work unless I use `let main = from x`.

I think this is just a documentation issue and not a bug in PRQL itself.

### PRQL input

```elm
let main = albums
```

### SQL output

```SQL
Error: 
   ╭─[:1:12]
   │
 1 │ let main = albums
   │            ───┬──  
   │               ╰──── Unknown name `albums`
───╯
```

### Expected SQL output

```SQL
SELECT
  *
FROM
  albums
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
Good spot, thanks @broneill . I can confirm on my end. Unfortunately this is one of the very few places in the book that isn't tested!

@aljazerzen you have more of a vision for this than me; should we remove these docs? Happy to if you agree.

**Comment by broneill** [comment]
Personally, I'd like it to remain in the docs, but fixed. I like knowing that there's a special main function that's defined automatically. Maybe that's an implementation detail only?

**Comment by aljazerzen** [comment]
Yeah, that's a typo, i'll push a fix
