### ISSUE TITLE
0.11.4 didn't publish

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#4282]
### What's up?

I failed to backport the version change to `web`, so `0.11.4` didn't correctly publish.

We did solve the issue of publishing `prqlc` artifacts. So unless it's specifically helpful I won't do a `0.11.5`. Instead we'll do a `0.12` with some planning for the `db.` change.

If it is specifically helpful to do a `0.11.5`, let me know and I can do that.

**Comment by broneill** [comment]
I also noticed that the dates in the changelog are wrong for versions 0.11.2 and up. The year should be 2024.

**Comment by max-sixty** [comment]
> I also noticed that the dates in the changelog are wrong for versions 0.11.2 and up. The year should be 2024.

D'oh! Thanks for spotting. Fixed in #4284
