### ISSUE TITLE
Store & share queries from live editor

### ISSUE THREAD

**Issue by swuecho** [PRQL/prql#430]
like the rust playground

**Comment by max-sixty** [comment]
This would be great, thanks for the suggestion @swuecho .

Does it require a backend server for this? Currently it's a static site, which is nice and simple. I'd be up for making this work; it would probably need another layer of complexity though.

Potentially an intermediate option would be to store the last query locally.

**Comment by swuecho** [comment]
Yes. I checked rustplayground. A backend server is indeed required to post gist.

use LocalStorage keep the query history (last 10) will be great too.  MB size storage space is enough to store all the query history.

https://stackoverflow.com/questions/2989284/what-is-the-max-size-of-localstorage-values

**Comment by max-sixty** [comment]
OK great, thanks for looking.

We'd be fine to host a server; it's more work to write.

I think the local history might be a much easier place to start. 

There are lots of things to do in JS, given our current contributors are more rust & python focused, so if that's something you'd be up for contributing towards, that would be very valuable.

**Comment by aljazerzen** [comment]
Closed with https://github.com/prql/prql-webapp
