### ISSUE TITLE
Multiple `select` transform is wonky

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#4316]
### What happened?

I got an error.
```
Error: 
   ╭─[:4:8]
   │
 4 │ select bar
   │        ─┬─  
   │         ╰─── Unknown name `bar`
───╯
```

### PRQL input

```elm
from invoices
select foo
select bar
```

### SQL output

```SQL
-- None
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
That's because there's no `bar` left after the `select foo` — only `foo` is available!

**Comment by vanillajonathan** [comment]
Maybe it can be more helpful and suggest `select { foo, bar }`?

**Comment by max-sixty** [comment]
I think we could say what's available; i.e. ```Unknown name `bar`; available columns: `foo` ```. Feel free to add that in `bad_error_messages.rs`...
