### ISSUE TITLE
Join not compiled

### ISSUE THREAD

**Issue by xueyumusic** [PRQL/prql#4336]
### What happened?

I build main branch on my laptop, and try to run join query. But both left join or self equality join not worked. 

```
from employees
join positions (==emp_no)

Error:
   ╭─[:2:6]
   │
 2 │ join positions (==emp_no)
   │      ────┬────
   │          ╰────── Unknown name `positions`
───╯
```

### PRQL input

```elm
from employees
join side:left positions (employees.id==positions.employee_id)
```

### SQL output

```SQL
Error:
   ╭─[:2:16]
   │
 2 │ join side:left positions (employees.id==positions.employee_id)
   │                ────┬────
   │                    ╰────── Unknown name `positions`
───╯
```

### MVCE confirmation

- [ ] Minimal example
- [ ] New issue

**Comment by max-sixty** [comment]
Hi @xueyumusic , we are working on changing the resolver. 

One change on the main branch is to enforce a `db.` prefix in `db.table`.

Can you check that works for you?

**Comment by xueyumusic** [comment]
> Hi @xueyumusic , we are working on changing the resolver.
> 
> One change on the main branch is to enforce a `db.` prefix in `db.table`.
> 
> Can you check that works for you?

Hi, @max-sixty. Yes it worked when adding db prefix. Thanks!

**Comment by max-sixty** [comment]
Cheers @xueyumusic . FYI we have decided to move those changes to a new branch and continue experimenting with a new resolver there: https://github.com/PRQL/prql/issues/4338.

So please expect the original approach to work in the next release, sorry for the churn...
