### ISSUE TITLE
CROSS JOIN or multi from condition in postgres

### ISSUE THREAD

**Issue by warriorGod** [PRQL/prql#4341]
# syntax for cross join

It might be just me, but I cant find a way to write this in prql. I know its basic, but I can't find the example anywhere. I also could not see any test cases with prql -> sql checks where I could search for my use case - I only found https://github.com/PRQL/prql/tree/main/prqlc/prqlc/tests/integration/queries

The use case is simple - put query params in a table and reuse that when building your data up through multiple steps. Example below is similar.

```
with firstnames as (
  select 'First' as first
),

lastnames as (
  select 'Last' as last
)

select * from firstnames, lastnames
-- OR
select * from firstnames CROSS JOIN lastnames;
```

So its basically a join without a condition ... can it be done in prql?

**Comment by aljazerzen** [comment]
You can use join, with condition `true`:

```
from firstnames
join lastnames true
```

**Comment by warriorGod** [comment]
Thanks! Missed that.

**Comment by vanillajonathan** [comment]
If this isn't obvious then maybe it should be documented somewhere?

**Comment by aljazerzen** [comment]
Yes, it should. Probably as an example in docs of `std.join`.
