### ISSUE TITLE
Notation for specifying sort direction

### ISSUE THREAD

**Issue by snth** [PRQL/prql#436]
I find that having separate `order:asc` terms breaks the visual flow when reading sort expressions. For example, in the example below at first glance it appears as if one is sorting by four columns and it is difficult to pick out the column names.

```elm
sort age order:desc, name order:asc
```

I would explore what alternatives there might be (bearing in mind that I'm speaking from the perspective of a user and I have no knowledge how possible or not it is to implement these in the parser).

To me the simplest, and closest to SQL, would be to dispense with the `order` token and just affix the direction to the column name like so

```elm
sort age:desc, name:asc
```

However in the quest for simplicity and terseness I've also considered whether one could overload some symbols/operators. The ones that naturally come to my mind are `<`, `>`, `+`, and `-`. So

```elm
sort age>, name<
```
or
```elm
sort age-, name+
```

Of these, I prefer the latter. I also think it makes logical sense in that one can think of this as always sorting ascending and just sometimes we don't sort the values but rather the negatives of the values which naturally gives the descending order.

One unaddressed issue is the placement of the NULL values which I haven't found a neat suggestion for yet.

**Comment by max-sixty** [comment]
Thanks for adding the issue @snth .

Adding https://github.com/prql/prql/pull/351 as a previous discussion.

I would vote for `-age` or `>age` or `age-` meaning "reduce age as you move through the column", i.e. descending.

**Comment by snth** [comment]
Thanks for the link. Sorry that I missed that previous discussion. I guess I was only looking at open ones.

As per your suggestion and @aljazerzen 's proposal from the #351 thread, the following is probably the nicest and most logical:

```elm
sort [age, -first_name, last_name]
```

For numerical columns like `age`, `-age` makes complete sense. For things like `-first_name` it's a bit of a stretch but still quite sensible and quick and easy to parse visually.

**Comment by snth** [comment]
I also agree with the comment in that thread that we should probably stick with `NULLS LAST` until we find a way to support specifying the alternatives.

**Comment by aljazerzen** [comment]
I believe there is not much more to discuss here. 

For anyone who wants to contribute: my current implementation can be reused no changes to AST required. One would only have to correct how sort transform is constructed in `semantic::transforms` and then fix all unit tests.

There may be problems with parsing the unary operator - but maybe not.

**Comment by max-sixty** [comment]
OK great if we have consensus!

**Comment by max-sixty** [comment]
This is a bit harder than I thought — there's it breaks rules around the [expr defn](https://github.com/prql/prql/blob/main/prql-compiler/src/prql.pest#L69-L72). 

Edit: let me try and find a decent approach here

**Comment by max-sixty** [comment]
Initial quick finding (even before we get to the sort issue):
- In `derive x = -5` we want to parse `-5` as an expr, so allow for leading `+` / `-`
- In `derive gross_salary = salary + payroll_tax` we want to parse `salary + payroll_tax` as an expr, not a function call of `salary` and `+payroll_tax`. So not allow for leading `+` / `-`

**Comment by max-sixty** [comment]
https://github.com/prql/prql/pull/461 contributes towards this.

Possibly `derive x = (-5)` or `sort (-foo)` — with parentheses — is a reasonable tradeoff

**Comment by max-sixty** [comment]
> Possibly `derive x = (-5)` or `sort (-foo)` — with parentheses — is a reasonable tradeoff

Yeah let's do this. This is also what Ocaml does

**Comment by aljazerzen** [comment]
I've stumbled across this problem when doing expression parsing, but decided to ignore it :D

The tradeoff is not so bad, I agree with the proposal.

**Comment by max-sixty** [comment]
Closed by https://github.com/prql/prql/pull/465
