### ISSUE TITLE
Struct syntax

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#438]
For creating "structs" / "objects" / "composite types" — e.g. [snowflake objects](https://docs.snowflake.com/en/sql-reference/data-types-semistructured.html#characteristics-of-an-object), [postgres composite types](https://www.postgresql.org/docs/current/rowtypes.html), [bigquery structs](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#struct_type), what do people think of syntax?

We could use brackets for this:

```elm
from employees
derive name: {first_name, last_name}
derive name_concise: {first: first_name, last: last_name}
```

Possibly structs aren't created that much and we don't want to expend brackets on them. In which case we could just use `as` and do something different for `struct` rather than other types (currently [it just casts](https://github.com/prql/prql/blob/49fc1ca04c7aab82824c846c5b2be85f2022edf7/prql-compiler/src/sql/stdlib.prql#L28):

```elm
from employees
derive name: ([first_name, last_name] | as struct)
derive name_concise: ([first: first_name, last: last_name] | as struct)
```

Or very open to other ideas

**Comment by vanillajonathan** [comment]
I've seen modules mentioned and the struct syntax you mention looks inline. Would that syntax work for importing/exporting structs from modules?

Or would you need something like:
```rust
struct PersonName {
    first_name,
    last_name,
}
```

**Comment by max-sixty** [comment]
At the moment there's no importing from modules... This discussion is about how to create Struct values, such as `name_concise: {first: first_name, last: last_name}`.

**Comment by aljazerzen** [comment]
Stale, discussed as a part of the type system

**Comment by vanillajonathan** [comment]
The `struct` keyword could be before instead of after with `as`.
```elm
from employees
derive name: struct {first_name, last_name}
derive name_concise: struct {first: first_name, last: last_name}
```
