### ISSUE TITLE
unexpected error on non-prql file

### ISSUE THREAD

**Issue by m-span** [PRQL/prql#4423]
### What happened?

When attempting to parse an external file that is not named with extension *.prql, the compiler gives an confusing error message:

```
cargo run --bin prqlc -- compile ~/prqltest.txt
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
     Running `target/debug/prqlc compile /[...]/prqltest.txt`
[E0002] Error: Cannot find the root module within the following files:

↳ Hint: add a file that starts with uppercase letter to the root directory
```

(contents of prqltest.txt file don't seem to matter or affect error)

### PRQL input

```elm
n/a
```

### SQL output

```SQL
n/a
```

### Expected SQL output

```SQL
n/a
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

### Anything else?

I suggest either of the following:

- It accepts the file that its given and attempts to scan contents as prql
- It denies the file and gives an error message requesting a different extension

**Comment by max-sixty** [comment]
Thanks @KaeporaGaebora !

Fixed by https://github.com/PRQL/prql/pull/4424. 

Agree we could possibly allow these files; I left a TODO in the code
