### ISSUE TITLE
[Docker] the 'cargo' binary ... is not applicable to the '1.77.2-aarch64-unknown-linux-gnu' toolchain

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#4459]
### What happened?

I wanted to build the newest commit e82c88f4 on my M2 macMini (running macOS 14.4.1) in DOCKER. I pulled the version, then tried to run `task build-all` and got the following error:

```bash
vscode ➜ /workspaces/prql (main) $ task build-all
task: [build-all] cargo build --all-targets --all-features
error: the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the '1.77.2-aarch64-unknown-linux-gnu' toolchain
task: Failed to run task "build-all": exit status 1
vscode ➜ /workspaces/prql (main) $ 
```

I first noticed this when I ran `task web:run-playground` in Docker on the same M2 machine...

### PRQL input

```elm
N/A
```

### SQL output

```SQL
N/A
```

### Expected SQL output

```SQL
N/A
```

### MVCE confirmation

- [X] Minimal example
- [ ] New issue

**Comment by max-sixty** [comment]
Could you try rebuilding the container? I can't reproduce this. The toolchain version did change, so possibly there's a conflict with what `cargo` is pointing to (feel free to investigate that ofc, ideally we wouldn't need to rebuild the container each time the toolchain changes...)

**Comment by richb-hanover** [comment]
That did the trick. I used Docker Desktop to remove all containers, volumes, images, then reopened VSCode and it rebuilt the container, then I could use `web:run-playground`, `web:run-book`, and `web:run-website` as expected.

NB: To keep it fresh in my mind, `task build-all` still fails (#4210) because I don't have enough free disk space. This is fine - I don't ever need to `build-all`, just the tasks above

**Comment by max-sixty** [comment]
OK great.

If this happens again, would be interesting whether the VS Code command "Dev Containers: Rebuild and Reopen in Container" fixes it, which is less drastic than wiping everything.
