### ISSUE TITLE
Incorrect Postgres interval syntax

### ISSUE THREAD

**Issue by MaksimMisin** [PRQL/prql#4486]
### What happened?

PRQL compiles incorrect interval expression for Postgres' SQL dialect. Specifically, the quotes should surround the whole interval expression, not just the number.

### PRQL input

```elm
from [
    {created=@2024-01-01},
]
derive {
    deadline = created + 2weeks
}
```

### SQL output

```SQL
WITH table_0 AS (
  SELECT
    DATE '2024-01-01' AS created
)
SELECT
  created,
  created + INTERVAL '2' WEEK AS deadline
FROM
  table_0
```

### Expected SQL output

```SQL
WITH table_0 AS (
  SELECT
    DATE '2024-01-01' AS created
)
SELECT
  created,
  created + INTERVAL '2 WEEK' AS deadline
FROM
  table_0
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

### Anything else?

Current syntax actually works for a bunch of typical intervals such as day, hour, year, but fails for the likes of week, milisecond, decade. 
When quotes are surrounding the whole expression, everything works fine.

**Comment by max-sixty** [comment]
Thanks @MaksimMisin 

(@m-span this is an example of a small SQL gen issue. Those will persist through any changes to the resolver. While this isn't exactly a foundational issue, it would be a nice intro to that end of the compiler...)

**Comment by m-span** [comment]
After a little exploring, I found the relevant lines of code

`sql/gen_expr.rs::395-399`:
```rust
            let value = if ctx.dialect.requires_quotes_intervals() {
                Box::new(sql_ast::Expr::Value(Value::SingleQuotedString(vau.n.to_string())))
            } else {
                Box::new(translate_literal(Literal::Integer(vau.n), ctx)?)
            };
```

It appears that this exception to use quotes on the value 2 in `'2' WEEK` is only done for `postgres` and `glaredb`.

Interestingly enough, while I do see that Postgres documentation states that it requires special quoting as described by the OP, I can't find anywhere in the GlareDb documentation where it requires the value to be quoted by itself. Certainly no other databases require this, to my knowledge. The documentation is quite sparse on this topic @max-sixty Is this actually the desired behavior for GlareDb? If so, should it also be adjusted to meet the postgres spec?

This is a weird spec, to fail on `WEEK` but not `DAY`

**Comment by max-sixty** [comment]
Nice find!

I think GlareDB will follow the Postgres spec. 

(We disabled their tests recently since there were some inconsistencies in a new version — I think we shouldn't prioritize GlareDB highly relative to Postgres...)

**Comment by eitsupi** [comment]
Since GlareDB (i.e., DataFusion behind it) copies Postgres syntax, it simply copied Postgres' when implementing the GlareDB dialect. In other words it was not set up to match GlareDB, it was there originally.
