### ISSUE TITLE
DevContainer doesn't contain `pre-commit`

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#4548]
### What's up?

I used Docker Desktop to delete all PRQL containers, volumes, and images, then restarted the DevContainer.

When I used `task test-lint` I got an error to the effect that `pre-commit` is not available.

I used `pip install pre-commit` and all was well: I could run `task test-lint` without problems.

How could we get `pre-commit` installed into the base PRQL DevContainer? Thanks.

**Comment by eitsupi** [comment]
See https://github.com/PRQL/prql/issues/3709#issuecomment-1774100184

To support macOS, it seems impossible.

**Comment by max-sixty** [comment]
@richb-hanover if anything has changed since we hit the error and installing pre-commit in `postCreateCommand` works, we can re-enable it...

**Comment by max-sixty** [comment]
Marking as postponed — it's a problem but there's not much we can do at the moment
