### ISSUE TITLE
Node.js 16 is deprecated - use Node.js 20

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#4549]
### What's up?

In the Github Actions, say https://github.com/PRQL/prql/actions/runs/9410193834, there are a whole flock of messages noting that Node 16 is deprecated, and to use Node 20.

I know that a while back we made the leap from Node 12 to Node 16, but I have no memory of what we had to tweak...

**Comment by max-sixty** [comment]
This is on the underlying actions, so there's nothing for us to do...

Though we're using your rust action! So updating that will get rid of most of them!

**Comment by richb-hanover** [comment]
@max-sixty Ahah! It's coming back to me... I just updated the [`cargo` repo](https://github.com/richb-hanover/cargo) but it's not "taking" - recent builds still throw the "Node 16" error messages. 

Does anyone remember how to get the GitHub Actions to recognize when there's a change in an upstream action? Thanks.

**Comment by richb-hanover** [comment]
And this repo - https://github.com/clechasseur/rs-cargo - seems to have taken the project over. Any reason not to make a wholesale switch to it?

**Comment by max-sixty** [comment]
Yes we can switch!

**Comment by richb-hanover** [comment]
OK. I'll test it out on my repo and see if anything catches fire.
