### ISSUE TITLE
Syntax highlighting for web

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#456]
At the moment we have syntax highlighting for:
- VSCode, thanks to @aljazerzen 's https://github.com/prql/prql-code
- Language reference, in https://github.com/prql/prql/blob/main/reference/highlight-prql.js

We don't have it for web, which would be nice given it's probably the place that people will initially try out the language for themselves. From a cursory search, it looks like this is done with Monarch; here are their docs: https://microsoft.github.io/monaco-editor/monarch.html. 

I couldn't find a way of doing this once for all these formats. Now that PRQL is more settled, it's unlikely we're going to have to redo things, and PRQL is simple enough that the definitions aren't complicated.

**Comment by aljazerzen** [comment]
That's true, we will have to have (at least) 3 syntax definitions:
- TextMate for vscode 
- highlight-js
- monarch for monaco-editor (web)

But their way of defining all scopes and such is very similar. Also as you said, there will not be much changes so I agree that we can go ahead and do them each separately.

But it would be nice for them to reference each other (or one of them) so they can be compared easily.

**Comment by aljazerzen** [comment]
Closed with https://github.com/prql/prql-webapp
