### ISSUE TITLE
Snap auth seems to have expired

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#4562]
### What's up?

@vanillajonathan are you familiar with this at all?

https://github.com/PRQL/prql/actions/runs/9432185880/job/25981634759

**Comment by vanillajonathan** [comment]
Yeah it seems the Snap credentials have expired.

    2024-06-08T23:20:29.3331710Z Exported credentials are no longer valid for the Snap Store.
    2024-06-08T23:20:29.3375339Z Recommended resolution: Run export-login and update SNAPCRAFT_STORE_CREDENTIALS.
    2024-06-08T23:20:29.3377078Z For more information, check out: https://snapcraft.io/docs/snapcraft-authentication

https://snapcraft.io/docs/snapcraft-authentication

I think you have to run:

    snapcraft export-login <credentials-filename>

and update the `SNAPCRAFT_STORE_CREDENTIALS` secret in the GitHub repository settings used by `.github/workflows/release.yaml`.

**Comment by max-sixty** [comment]
OK great, thanks a lot. I did this; let's see whether it works!

**Comment by max-sixty** [comment]
It worked, thanks! https://github.com/PRQL/prql/actions/runs/9432813673/job/25983050930

**Comment by max-sixty** [comment]
Though FYI the versions might not be flowing through?

<img width="653" alt="image" src="https://github.com/PRQL/prql/assets/5635139/adf2377c-f231-4c5c-a332-d71f04a26b5f">

**Comment by vanillajonathan** [comment]
Yes, and also other metadata such as website, issues, contact, and license are not flowing through either despite being declared in the `snapcraft.yaml` file. I don't know why.
