### ISSUE TITLE
Script for updating version numbers?

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#4566]
### What's up?

Looking at the ton of work in #4564 to update a version number in the PRQL project makes me ache for some kind of global "PRQL_VERSION__NUMBER" that would take care of all this fussy hand-work. But that's not likely to be possible.

I wonder if a script might be able to do this... The script would have to be somewhat clever, because we wouldn't want to change a non-PRQL version number in the file. 

As a start, here's a list of the kinds of substitutions that were made, and the files they applied to.

Might this be worthwhile? Any other thoughts on this subject (before I fall into this rabbit hole)? Thanks.

**Still manually Edited (or automatically regenerated)**
- CHANGELOG.md
- prqlc/bindings/js/package-lock.json
- web/playground/package-lock.json

**s/"0.12.1"/"0.12.2"/g**
- Cargo.toml 
- lutra/lutra/Cargo.toml
- prqlc/bindings/elixir/native/prql/Cargo.toml
- prqlc/bindings/js/package.json
- prqlc/prql-compiler-macros/Cargo.toml
- prqlc/prql-compiler/Cargo.toml
- prqlc/prqlc-parser/Cargo.toml
- prqlc/prqlc/Cargo.toml
- web/book/src/project/target.md
- web/playground/package.json

**s/'0.12.1'/'0.12.2'/g**
- prqlc/prqlc/tests/integration/sql.rs
- web/book/tests/documentation/snapshots/documentation__book__project__target__version__1.snap

**'Generated with \[prqlc](https:\//prql-lang.org/) 0.12.1.'**
- prqlc/prqlc/src/cli/docs_generator.rs

**Comment by max-sixty** [comment]
We have this! Check out https://github.com/PRQL/prql/blob/ff492a5a98dff52c429a39607eaa185111fdbead/web/book/src/project/contributing/development.md#L489 !

**Comment by richb-hanover** [comment]
WHEW! Another rabbit hole avoided :-) Thanks
