### ISSUE TITLE
Filter with a list returns an incorrect result

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#469]
```elm
from employees
filter [age > 25, age < 40]
```

```elm
SELECT
  employees.*
FROM
  employees
WHERE
  age > 25 age < 40
```

(in this case we can use `in` & `..` but the principle holds)

---

I don't see much downside in disallowing lists and joining them with `and`, even though it's very easy to do two `filter`s:

```elm
from employees
filter age > 25
filter age < 40
```

**Comment by aljazerzen** [comment]
To be honest, lists here don't make much sense.

In my opinion ...
```elm
from employees
filter age > 25 and age < 40
```
... or ...
```elm
from employees
filter age > 25
filter age < 40
```
... is much more readable than ...
```elm
from employees
filter [age > 25, age < 40]
```

So I agree on disallowing lists.

**Comment by ajfriend** [comment]
FWIW, I'd vote for the "list AND" syntax, as I raised in #788 :)
