### ISSUE TITLE
Can't put `#` in an alias name - it's treated as a comment

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#4725]
### What happened?

I want to create a pair of column headings - one with a count, and one with a percentage, (e.g., `LotTooSmall#` and `LotTooSmall%`)

I can use "\`" to make the alias \`LotTooSmall%\`, but the "#" in  \`LotTooSmall#\` is treated as a comment character.

### PRQL input

```elm
Works: `LotTooSmall%` = <some expression>

Doesn't Work: `LotTooSmall#` = <some expression> 
    because the remainder of the line after the "#" is treated as a comment
```

### SQL output

```SQL
N/A
```

### Expected SQL output

```SQL
N/A
```

### MVCE confirmation

- [x] Minimal example
- [x] New issue

**Comment by max-sixty** [comment]
Can we add a complete PRQL example?

Here's a case that does work:

```elm
from artists
derive `foo#` = 5
```

```sql
SELECT
  *,
  5 AS "foo#"
FROM
  artists

-- Generated by PRQL compiler version:0.12.2 (https://prql-lang.org)
```

**Comment by richb-hanover** [comment]
Ahah! It's a bug in the VSCode extension's syntax highlighting. @max-sixty's example above works properly (generates the desired SQL) in VSCode, but the syntax highlight turns everything after the "#" grey, fooling me into thinking that the alias name wasn't respecting the "#" character.

I will close this issue and move it over to the VSCode Extension repo. Thanks
