### ISSUE TITLE
NULL-COALESCING Operator

### ISSUE THREAD

**Issue by snth** [PRQL/prql#475]
Handling `NULL` values is a very common operation in SQL queries. Different SQL dialects have different functions for handling these, see for example https://www.w3schools.com/sql/sql_isnull.asp. The `COALESCE` function appears to be the most widely supported but is rather verbose to type and takes up a lot of space when reading queries. IMHO infix operator expressions are also easier to read but opinions on this may vary.

According to Wikipedia `??` seems to be the most common choice for this operator: https://en.wikipedia.org/wiki/Null_coalescing_operator

For example this is supported in [C#](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator), [Dart](https://dart.dev/codelabs/dart-cheatsheet#null-aware-operators) and [Javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator).

This would allow one to write expressions like 
```sql
ABS(COALESCE(a.amount, 0) - COALESCE(b.amount, 0)) AS difference
```
as
```elm
derive difference = (a.amount ?? 0) - (b.amount ?? 0) | abs
```
in PRQL.

I therefore propose implementing this operator in PRQL and have it transpile to the `COALESCE` function.

Related [discussion on Discord](https://discord.com/channels/936728116712316989/945832228011798528/973306057701093496).

**Comment by aljazerzen** [comment]
I fully agree on this - in Typescript and Angular this saves so much pain. It can be one of tiny features that make PRQL pleasant to interact with.

**Comment by snth** [comment]
@aljazerzen What do you think about the precedence level for this?

In the other language examples it seems to have quite low precedence. I guess in those languages that makes sense because it's one of those operators that only evaluates the RHS if the LHS is null.

My feeling is that for PRQL one is likely to mostly apply it to table column values so having a high order of precedence would avoid having many parentheses as in my example above.

Would be good to have some more examples to look at.

**Comment by aljazerzen** [comment]
In [typescript](https://www.tektutorialshub.com/typescript/operator-precedence-in-typescript/), it has precedence between trenary opearator (`cond ? a : b `) and logical operators.

As you said that is quite low and would not be suitable in our use-case. 

Your example indicates that it should be higher than addition, so I would say it should be above multiplication:

```pest
// in increasing order of precedence
expr = !{ expr_compare ~ (operator_logical ~ expr_compare)* }
expr_compare = _{ expr_add ~ (operator_compare ~ expr_add)? }
expr_add = _{ expr_mul ~ (operator_add ~ expr_mul)* }
expr_mul = _{ expr_null ~ (operator_mul ~ expr_null)* }
expr_null = _{ term ~ ("??" ~ term)? }

term = ...
```
