### ISSUE TITLE
Reformatting an alias omits quoting

### ISSUE THREAD

**Issue by kgutwin** [PRQL/prql#4812]
### What happened?

Aliases are (apparently) supported to be backtick-quoted in the PRQL grammar. However, those quotes are lost when using `prqlc fmt`, causing syntax errors.

### PRQL input

```elm
from customers
select {`customer name` = last_name}
```

### SQL output

```SQL
SELECT
  last_name AS "customer name"  -- works as intended...
FROM
  customers

-- Generated by PRQL compiler version:0.13.0-25-g53f747c1 (https://prql-lang.org)

-=-=-=-=-=-=-=
# Actual output of `prqlc fmt`:

from customers
select {customer name = last_name}
```

### Expected SQL output

```SQL
# Expected output of `prqlc fmt`

from customers
select {`customer name` = last_name}
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by max-sixty** [comment]
Thanks, good spot. I think I can fix this without waiting for all of `prqlc fmt`...

**Comment by kgutwin** [comment]
I also noticed that the following doesn't format as expected:

```
from `foo.bar`
select { baz }
```

formats to:

```
from foo.bar
select { baz }
```
