### ISSUE TITLE
DevContainer: Need to run `git config ... --add safe.directory` one time

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#4817]
### What happened?

I retrieved b35bd41 (6Aug2024) and rebuilt the container. When I ran `task web:run-website`, I got the error:

```
ERROR Failed to read Git log: fatal: detected dubious ownership in repository at '/workspaces/prql'
To add an exception for this directory, call:

        git config --global --add safe.directory /workspaces/prql
```

This seems to happen each time I rebuild the container (not each time I work on the website). Could this command be worked into the Dev Container? Thanks.

### PRQL input

```elm
N/A
```

### SQL output

```SQL
N/A
```

### Expected SQL output

```SQL
N/A
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

### Anything else?

This error was mentioned in https://github.com/PRQL/prql/issues/3709 - is this related? Thanks as always

**Comment by max-sixty** [comment]
I don't recall exactly why we needed multiple owners but remember it was for a reasonable reason...

Do you want to add that command to the Dockerfile and see whether that helps?

**Comment by richb-hanover** [comment]
I'm a little uncertain about how to edit the Dev Container...

I see that _.devcontainer/_ contains the Dockerfile. But that's astonishingly short and concise.

I also see the _devcontainer.json_ file that has a whole bunch of stuff: features/customizations/postCreateCommand...

Where would a command go to add that `git config...` command? Many thanks.

**Comment by max-sixty** [comment]
Sorry for the slow reply — just got back from vacation. I was thinking it would go in the Dockerfile...

**Comment by richb-hanover** [comment]
OK. I'll poke at it. Thanks

**Comment by richb-hanover** [comment]
It appears that the `git config...` command must be executed by the `postCreateCommand` section of the _.devcontainer/devcontainer.json_ file
