### ISSUE TITLE
Odd version number in Windows Dev Container

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#4837]
### What's up?

While testing various dev containers, I rebuilt PRQL on Windows. Using `task web:run-playground`, the playground worked as expected, except that the version number in the comment at the bottom was not 0.13.1 as expected. 

Is this a concern? What other info could I provide? Thanks.

```
SELECT
  id
FROM
  invoices

-- Generated by PRQL compiler version:0.13.0-38-g62c7cc3c (https://prql-lang.org)
```

**Comment by richb-hanover** [comment]
Update: 

* On my macOS Playground/Dev Container, the version string in the comment is the expected 0.13.1
* The Windows Playground shows the commit hash for the main branch (62c7cc3c) that compiled it

**Comment by kgutwin** [comment]
I believe this is expected from #4804, correct?

See also #4546 which gives a little more detail.

**Comment by max-sixty** [comment]
Yes this is a new feature!

**Comment by richb-hanover** [comment]
Great! Closing.
