### ISSUE TITLE
First cut at Quick Start guide

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#4990]
### What's up?

I have a couple friends who were curious about analyzing data that we have collected (about property tax and land values in our town). They had been using spreadsheets, but the analysis gets unwieldy...

I really like the combination of **qStudio** and **PRQL** for making queries on a SQL database. So I wrote a few "quick start" guides that my friends could use to get up to speed. 

It's at: [qStudio-PRQL Quick Start](https://github.com/richb-hanover/qStudio-PRQL_Quick_Start) If you have comments or suggestions, raise an Issue to that repo. Enjoy!

**Comment by max-sixty** [comment]
This is really cool! Thank you @richb-hanover !

Can we link to it somewhere? I think we have a qStudio page in the docs?

**Comment by richb-hanover** [comment]
PR has been accepted - qStudio page has been updated at: https://prql-lang.org/book/project/integrations/qstudio.html
