### ISSUE TITLE
Removing implicitly named identifiers

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#5]
Some [good feedback from ajkjk](https://news.ycombinator.com/item?id=30063842):

> "sort sum_gross_cost # Uses the auto-generated column name." ... seems like a huge landmine. Languages really should not have any implicit way of constructing identifiers (among other reasons it is not easily greppable).

> You might consider using a syntax like `sum:gross_cost` which can function as a sort parameter and an aggregation, but is actually recognizable as an object instead of having an implicit transformation going on in the background. Like this:

```elm
filter gross_cost > 0
aggregate by:[title, country] [
  sum:gross_cost,
]
sort sum:gross_cost
```

I think this is right — while I think it's helpful to implicitly generate column names, to use them as identifiers I think should require being explicit.

A few possible approaches:

- The proposal above, which uses `sum:gross_cost`. I had planned for `:` to be used for passing values to named arguments in functions — see the `func`  example in the readme. I'm not precious about that syntax, but it should be unambiguous.
- Mandate that the column in `sort` should be assigned a name, like:

  ```elm
  filter gross_cost > 0
  aggregate by:[title, country] [
    sum salary,
    let sum_gross_cost = sum gross_cost,
  ]
  sort sum_gross_cost
  ```

  One downside of this is the incongruence between `sum salary` and `let sum_gross_cost = sum gross_cost` in the `aggregate` list. But we need some way to assign names in general, so we'll have to handle that regardless.

- Allow for expressions in the `sort`, like:

  ```elm
  filter gross_cost > 0
  aggregate by:[title, country] [
    sum salary
    sum gross_cost,
  ]
  sort (sum gross_cost)
  ```

  The issue here is that the columns we're aggregating by are implicit, based on the last `aggregate` expression, which isn't great.

Atm I'd lean towards "Mandate that the column in `sort` should be assigned a name" but as ever open to feedback

**Comment by rchowell** [comment]
The syntax `sum:gross_cost` may look nice for the common aggregation functions sum, min, max, avg, count. But you will need to consider if the aggregation function takes more than one argument.

For example, what becomes of `percentile(gross_cost, 99), percentile(gross_cost, 99.9)`?

This would be fine because the transpiler or planner would recognize it's the same field
```
filter gross_cost > 0
aggregate by:[title, country] [
  sum salary
  sum gross_cost,
]
sort (sum gross_cost)
```

It's not necessary to require `sort` on an identifier rather than an arbitrary expression. What would be nice is exploring syntax for aliasing

```
// A
filter gross_cost > 0
aggregate by:[title, country] [
  sum salary
  sum_gross_cost := sum gross_cost,
]
sort (sum gross_cost)

// B
filter gross_cost > 0
aggregate by:[title, country] [
  sum salary
  sum gross_cost as sum_gross_cost
]
sort (sum gross_cost)

// C
filter gross_cost > 0
aggregate by:[title, country] [
  sum salary
  sum gross_cost -> sum_gross_cost
]
sort (sum gross_cost)
```

**Comment by ajakaja** [comment]
Thanks for the proactivity of converting HN comments into issues!

A follow-up thought: there's probably no reason to use different syntax than SQL if it's not necessary -- the point is to improve on its issues, not just be different for difference's sake. So, I think the cleanest solution is probably to use `as sum_gross_cost`  for aliasing. The colon expressions in my HN comment seem unnecessary, and you could imagine much more complicated computations than `sum` which would be prohibitive to convert into a clean identifier anyway. Better to just stick with aliasing probably.

**Comment by dataspun** [comment]
+1 @ajakaja the ANSI SQL standard AS for aliasing column and table names is clean and widely used.  Even better, making AS _required_ in PRQL would prevent [rampant](https://stackoverflow.com/questions/1503295/t-sql-aliasing-using-versus-as) code smell.

**Comment by max-sixty** [comment]
Would `as` work as a _leading_ keyword though? I think that's somewhat binding. Would it be like:

```elm
filter gross_cost > 0
aggregate by:[title, country] [
  sum salary,
  as sum_gross_cost = sum gross_cost,   # (or `:=` / `<-` or wever)
]
sort sum_gross_cost
```

**Comment by SilverEzhik** [comment]
Is there any specific reason for it to be a leading keyword, rather than keeping the order in as it is in SQL?

Also, to throw one more idea in (my personal preference is still `as`), how about a JSON-like syntax: 

```elm
filter gross_cost > 0
aggregate by [title, country] {
  sum salary,
  sum_gross_cost: sum gross_cost,
}
sort sum_gross_cost
```
