### ISSUE TITLE
How to generate fibonacci sequence in pure prql?

### ISSUE THREAD

**Issue by futu2** [PRQL/prql#5003]
### What's up?

I found some solution [here](https://stackoverflow.com/questions/21746100/how-to-generate-fibonacci-series), but all require big s-string.
My code fails to achieve this.
```prql
let fibo =  (
    from n=fibo
    join n1=fibo (n.n + 1 == n1.n)
    join n2=fibo (n.n + 2 == n2.n)
    select {
        n = n.n,
        res = case [
            n == 0 => 0,
            n == 1 => 1,
            n == 2 => 2,
            true => n1.res + n2.res
        ]
    }
)
from fibo
```
which compiles to
```sql
WITH table_0 AS (
  SELECT
    n.n,
    CASE
      WHEN n.n = 0 THEN 0
      WHEN n.n = 1 THEN 1
      WHEN n.n = 2 THEN 2
      ELSE n1.res + n2.res
    END AS res
  FROM
    fibo AS n
    JOIN fibo AS n1 ON n.n + 1 = n1.n
    JOIN fibo AS n2 ON n.n + 2 = n2.n
)
SELECT
  n,
  res
FROM
  table_0 AS fibo
```
the following is sql training kata from codewar

>
>I love Fibonacci numbers in general, but I must admit I love some more than others.
>
>I would like for you to write me a function that, when given a number n (n >= 1 ), returns the nth >number in the Fibonacci Sequence.
>
>For example:
>
>   nthFibo(4) == 2
>
>Because 2 is the 4th number in the Fibonacci Sequence.
>
>For reference, the first two numbers in the Fibonacci sequence are 0 and 1, and each subsequent >number is the sum of the previous two.
```sql
--# write your SQL statement here: 
-- you are given a table 'fibo' with column 'n'.
-- return a table with:
--   this column and your result in a column named 'res'
--   ordered ascending by 'n'
--   distinct results (remove duplicates)
```

**Comment by snth** [comment]
Hi @futu2 ,

Sorry, I didn't notice this issue until now.

You can use the following:

```elm
let n = 10

from [{i=2, fib=1, fib_prev=1}]
loop (
  filter i<n
  select {i+1, fib+fib_prev, fib}
  )
filter i==n    # comment out this line if you want the first n Fibonacci numbers
select fib
```

I'll see if I can add similar version to the docs.

**Comment by snth** [comment]
Updated to fit your spec:

--# write your SQL statement here: 
-- you are given a table 'fibo' with column 'n'.
-- return a table with:
--   this column and your result in a column named 'res'
--   ordered ascending by 'n'
--   distinct results (remove duplicates)

If I'm understanding it correctly then this should do it:

```elm
from fibo=[{n=11}]
select {i=2, fib=1, fib_prev=0, n}
loop (
  filter i<n
  select {i+1, fib+fib_prev, fib, n}
  )
select {n=i, res=fib}
```

**Comment by futu2** [comment]
Thanks.  It just works. I hasn't found loop section in std lib doc before.
