### ISSUE TITLE
Deduplicate npm packages

### ISSUE THREAD

**Issue by aljazerzen** [PRQL/prql#612]
Ideally, we would not have [3 npm packages](https://www.npmjs.com/package/@prql-org/prql-node) but a [single one](https://www.npmjs.com/package/prql-js).

I did a little research, and currently it is possible, but not easy.

This is very similar issue: https://github.com/spruceid/didkit/issues/208

One way to do it would mean creating two builds and merge results together, described [here](https://github.com/rustwasm/wasm-bindgen/issues/1627#issuecomment-505973461) and [here](https://github.com/rustwasm/wasm-bindgen/pull/326#issuecomment-415991338).

Another (easier) way would be to wait for this to merge: https://github.com/rustwasm/wasm-pack/issues/313 https://github.com/rustwasm/wasm-pack/issues/469

**Comment by max-sixty** [comment]
I think this was done, by @charlie-sanders , is that correct?

**Comment by qharlie** [comment]
Yes this is done , closing it.
