### ISSUE TITLE
Add a "card" testimonial in the "what people are saying" section?

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#628]
Is it possible for us to add a "card" among the tweets section, with something someone said, but hasn't tweeted? In particular, my acquaintance Jeremiah Lowin, founder of Prefect, generously offered a testimonial:

> It starts with FROM, it fixes trailing commas, and it's called PRQL?? If this is a dream, don't wake me up.

Would be great to have this there along with his name and role, if the formatting will work.

**Comment by roG0d** [comment]
Done! https://github.com/prql/prql/pull/635
Some preview of the new quoteblock, as always open to changes! 😁

![Captura de pantalla_2022-06-21_23-59-36](https://user-images.githubusercontent.com/32329949/174906949-9bf61865-e757-4cfd-b82a-05f1a0872b5d.png)
