### ISSUE TITLE
Move playground within the website

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#632]
As discussed on Discord:

It would be less of a jump, and so fewer people giving up exploring the language, if `Playground` could share a header and formatting with the rest of the site.

I don't think it can't be build purely with Hugo given it requires wasm & JS, but it could be copied into a path as part of a build step (as we do in the [build](https://github.com/prql/prql/blob/main/.github/workflows/publish.yaml#L50-L58)).

It would require adjusting the Playground's CSS to be more similar to the site's.

This was originally inspired by @alonso's [Rulex](https://rulex-rs.github.io/). Though it looks like they've recently regressed a bit and it's not exactly the same header.

**Comment by mklopets** [comment]
The easiest way would be just to use an `iframe` here. Ideally, this would have a `maximize` button, though (which is why I didn't immediately open a PR)

![2022-12-03 17 58 46](https://user-images.githubusercontent.com/3150328/205450010-3d866165-b5a2-4532-a403-97dd21b4f36a.gif)

**Comment by mklopets** [comment]
FWIW: I think this same issue also applies to the "book"!

**Comment by mklopets** [comment]
Opened a PR to move both 🤷
