### ISSUE TITLE
Nicer looking FAQ

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#670]
Does anyone have ideas for making the FAQ look better? Can we add a template for a clickable FAQ to our current theme, or would it conflict? 

Currently it's not that elegant: https://prql-lang.org/faq/ — both not clickable, and very wide...

**Comment by spenserblack** [comment]
It's a bit simple, but I think a ToC to jump to and from items could help. E.g.
```markdown
## ToC

- [**Cool story Hansel, but what can I actually do with PRQL now?**](#cool-story-hansel-but-what-can-i-actually-do-with-prql-nowtoc)
- [**Something here reminds me of another project, did you take the idea from them?**](#something-here-reminds-me-of-another-project-did-you-take-the-idea-from-themtoc)

## [Cool story Hansel, but what can I actually do with PRQL now?](#toc)

...

## [Something here reminds me of another project, did you take the idea from them?](#toc)
```
Only issue is that this will put the linked sections at the *top* of the page, which currently means underneath the fixed-position header.

**Comment by max-sixty** [comment]
That would be great! Can we create that in Hugo automatically?

It's possible we need to write our own template, but maybe we can leverage those already out there...

**Comment by spenserblack** [comment]
I'm not familiar with Hugo, but I definitely agree that an auto-generated table of contents would be ideal. Just based on familiarity with similar tools, maybe each FAQ could be represented with a data format that points to FAQ contents, somewhat like this?
```yaml
faqs:
  - title: "Cool story..."
    contents: partials/faqs/cool-story.md
```
```markdown
<!-- partials/faqa/cool-story.md -->
We're still early...
```
Again, I'm not familiar with Hugo at the moment, so I may be *way* off the mark with this :slightly_smiling_face:

**Comment by max-sixty** [comment]
Yes! That's exactly how hugo works actually — here's our front page: https://github.com/prql/prql/blob/main/website/content/_index.md?plain=1

**Comment by max-sixty** [comment]
This was done by #1217, thanks @mklopets !
