### ISSUE TITLE
0.2 release plan

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#673]
Tomorrow morning around 9am PST:
- HackerNews
- Reddit
- Lobste.rs — though I don't have an account here — does anyone else?
- Twitter, with our current 4 followers
- Issue 1 in this repo (which maybe we transition away from? I've been bad at keeping it updated. But maybe people aren't on Twitter?)

CC @prql

**Comment by aljazerzen** [comment]
I'd say keep the issue #1 - it would be a best bet to reach me. 

It shouldn't get too much updates, only the major releases anyway.
