### ISSUE TITLE
Video / gif

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#675]
Do we want some sort of video / gif of typing in the playground? I think that could be very engaging, both for the GH Readme, and particularly on platforms like Reddit which allow for embedding a video without another step.

I don't think there's enough context to do a full voiceover video, but could be persuaded if people think there is.

**Comment by mklopets** [comment]
I'd love a side-by-side of one engineer writing a given query in PRQL, and one doing it in vanilla SQL, with the first one beating the 2nd by a long shot (and without stumbling on errors).

**Comment by max-sixty** [comment]
Tagging @aljazerzen re the video...

**Comment by aljazerzen** [comment]
I made a [video](https://www.youtube.com/watch?v=IOXqklGlPdg), which I just made public. We can link to it from the website somewhere under "getting started".

But for the showcase, something faster would be better. Like [asciinema](https://asciinema.org/a/427156).

**Comment by aljazerzen** [comment]
... and I did [the showcase](https://www.youtube.com/watch?v=IQRRsfavEic) too.

**Comment by snth** [comment]
Thank you @aljazerzen

**Comment by max-sixty** [comment]
Thank you! These are both excellent!
