### ISSUE TITLE
brew install requires auth

### ISSUE THREAD

**Issue by gregwebs** [PRQL/prql#688]
brew install prql/prq/prql-compiler
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated Homebrew from edea67f8b to 38e1af857.

...

==> Tapping prql/prq
Cloning into '/opt/homebrew/Library/Taps/prql/homebrew-prq'...
Username for 'https://github.com':
Password for 'https://github.com':
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/prql/homebrew-prq/'
Error: Failure while executing; `git clone https://github.com/prql/homebrew-prq /opt/homebrew/Library/Taps/prql/homebrew-prq --origin=origin --template=` exited with 128.

**Comment by max-sixty** [comment]
I think that might just be a missing `l`

```diff
-brew install prql/prq/prql-compiler
+brew install prql/prql/prql-compiler
```

Let us know any issues though!

**Comment by gregwebs** [comment]
That install command is copied from https://prql-lang.org/

**Comment by max-sixty** [comment]
Oh gosh, sorry @gregwebs ! Fixed by https://github.com/prql/prql/pull/707
