### ISSUE TITLE
Syntax error in generated expression using sqlite

### ISSUE THREAD

**Issue by beaugunderson** [PRQL/prql#695]
I saw some syntax in a [comment on Hacker News](https://news.ycombinator.com/item?id=31898582) and decided to try it out against an existing sqlite database.

I used `pyprql` 0.5.3 as the method of connection with a `sqlite://database.db` connection string.

Here's the output:

```
PRQL:	from results
group finalPosition (
  sort [-finishTime]
  take 1
)

SQL:
	WITH table_0 AS (
  SELECT
    results.*,
    ROW NUMBER() OVER (
      PARTITION BY finalPosition
      ORDER BY
        finishTime DESC
    ) AS _rn
  FROM
    results
)
SELECT
  table_0.*
FROM
  table_0
WHERE
  _rn <= 1

Results:
Exception when handling the input: (sqlite3.OperationalError) near "(": syntax error
```

**Comment by max-sixty** [comment]
I think fixed by https://github.com/prql/prql/pull/698. Thanks a lot for the issue @beaugunderson 

(We need better tests against real DBs, which is very much on our roadmap)

**Comment by beaugunderson** [comment]
I can verify that now executes! It is very slow on my 25m row database but I'm fairly sure I can fix that via indexing. :)
