### ISSUE TITLE
Explain which back ends this works with somewhere obvious

### ISSUE THREAD

**Issue by gisborne** [PRQL/prql#703]
I’ve spent maybe 15 minutes on the website, trying to determine which SQL backends this works with.

It’s not in the FAQ, not that I can see on any page on the website.

Seems like information that should be prominent.

**Comment by max-sixty** [comment]
Thanks a lot for the question @gisborne — let us know if that answer makes sense

**Comment by gisborne** [comment]
It does. I feel like this is one of the first things someone would want to know, though, so I'd have it on the home page.

**Comment by max-sixty** [comment]
Yes, agree. We do have "By compiling to SQL, PRQL is instantly compatible with most databases, and existing tools or programming languages that manage SQL." in the first section — but maybe it's within too much text, or it's not clearly expressed? WDYT?
