### ISSUE TITLE
Consolidating some of the copy

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#706]
Reading through the comments on HN / Reddit — I think we have so much stuff out there between the website home page / the FAQ / the book / the examples on the website / the examples in the book / the repo, that it might be difficult to quickly see the important material when initially browsing. 

Let's think about consolidating some pages (but not sure what! They are all our favorite children!)

**Comment by aljazerzen** [comment]
Still relevant, but not actionable.
