### ISSUE TITLE
Refresh prql-js

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#708]
From @skybrain: https://news.ycombinator.com/item?id=31900876

- Refresh Readme — fine to remove examples and redirect to one of our many other sources I think
- I'm less familiar with this — any ideas for how to do this well? Does this touch what you were looking at last week @charlie-sanders ?
  > It has a typescript definition file, but it looks like it's autogenerated and a bit clunky. You get back a CompileResult and have to call free() explicitly, it seems? That doesn't seem very idiomatic for JavaScript.

**Comment by qharlie** [comment]
Should be fixed with 0.2.2 release
