### ISSUE TITLE
Move AST into a separate crate

### ISSUE THREAD

**Issue by AlisCode** [PRQL/prql#709]
Hey there, after reading a bit of the source code and trying to fiddle around with it, I realized the AST is not publicly exposed, meaning no one can create a tool that outputs a valid PRQL AST. I think there are definitely use cases though. Off the top of my mind, writing an `sqlx`-like/`diesel`-like library that leverages PRQL would require writing an AST somewhere in the process.

I see two potential solutions : 

* Just changing the `ast` mod to public visibility, which is fine for prototyping I guess
* Exposing the AST into a separate crate, say `prql-ast` 

I personnally find the second approach to be better because whatever brick of software would end up creating an AST would likely not need to depend on the whole prql-compiler infrastructure, but just require the AST definition itself. I guess that's just an opinion and I'd like to discuss it :)

**Comment by aljazerzen** [comment]
I agree, a separate crate would be better, but can we stick to a public ast module for now? It's easier to develop the compiler if its all the same crate.

This issue can remain open until we publish a separate crate (I hope with 0.3, otherwise 0.4) and the issue I linked can track the public ast mod.

**Comment by aljazerzen** [comment]
Update: if some crate needs prql AST, it will very likely also need at least parser or the SQL backend. So there is little point in splitting the two at the moment.
