### ISSUE TITLE
Quoted identifiers

### ISSUE THREAD

**Issue by Baoqi** [PRQL/prql#717]
Currently, it seems we can only use limited characters/numbers as the column names. Much like identifiers in programming languages.  

But we may encounter tables with various strange names, some may contains  `(), .` ,  some may use non-English characters, like `列名1`. 

So, can we also support some escape support for those special names.

I come up with 2 ways, first is support some escape functionality like MySQL syntax. 

```
from employees
derive [
    ## this is for input 
    abc = `special column(1)` * 2
]
derive [
   ### this is for output, although,
   # I actually want to rename column, 
   # instead of adding a new column
   `special column output(2)` = abc
]
```

But this may require a lot of changes, like inside f-strings, alias, etc.  And make the prql hard to read.

Another way may introduce some hints, only occur around input and output. like:

```
from employees
input_hints [
    ## this is for input 
    input_column1 = "special column(1)"
]
derive[
    abc = input_column1 * 2
]
output_hints [
   abc = "special column output(2)"
]
```

This will be translate to:

```
select *, "special column(1)" * 2 as "special column output(2)"
from employees
```

How do you think about this,  thanks a lot.

**Comment by aljazerzen** [comment]
I prefer the first approach (the back-ticks) much more than the second one. And I also think this is very necessary! Thanks for bringing the issue to light.

On a similar note, we have to decide about casing for variable names in PRQL. SQL is infamously case-insensitive, but PRQL's function names are already case sensitive. So I would suggest to also treat PRQL's variables as case sensitive. This would mean that all SQL column names that contain non-lowercase ASCII letters must be quoted (with appropriate quotes, depending on the dialect).

**Comment by max-sixty** [comment]
Very much agree!

I'm not against backticks per se, but one downside is that it makes copying examples into markdown more difficult.

While I think s-strings should be escape hatches more than things we use permanently, s-strings will work today, and  https://github.com/prql/prql/issues/721 would account for any more complicated names.

**Comment by max-sixty** [comment]
(mistakenly closed, `cmd+shift+enter` is not my friend)

**Comment by max-sixty** [comment]
A more pressing case is `project-name.DATASET_NAME.TABLE` in BigQuery. `from` can't take an s-string; it must take an ident, so there is no escape hatch to a quite common problem.

(We fixed using backticks a few days ago, but the `-` in the name isn't allowed)

**Comment by max-sixty** [comment]
Fixed by https://github.com/prql/prql/pull/744. Thanks a lot for the issue @Baoqi
