### ISSUE TITLE
JOIN to itself

### ISSUE THREAD

**Issue by severak** [PRQL/prql#719]
Hi, I am trying to translate this query (one of my most complex) to PRQL:

```
SELECT a.name, a.avatar_url, COALESCE(g.name, a.name) AS slug_name, g.name AS group_name, g.avatar_url AS group_avatar_url, p.*
FROM (
SELECT blog_id, MAX(datetime) as maxdt, id as post_id
FROM posts
GROUP BY blog_id
ORDER BY maxdt DESC
) AS lsu
INNER JOIN posts p ON lsu.post_id=p.id
INNER JOIN blogs a ON p.author_id=a.id
LEFT OUTER JOIN blogs g ON p.blog_id=g.id AND p.author_id!=p.blog_id
LIMIT 30
```

(idea is that I want last `post` from each `blog` with optional another instance of `blog` as group - [my schema](https://bitbucket.org/severak/kyselo/src/dev/doc/schema.sql) is a bit crappy)

Is there even possibility to do JOIN on itself or you need to express this  in another way?

This is what I came up with, but it does not work:

```
from posts
group [blog_id] (
aggregate [id, maxdt=max datetime]
)
join side:left p=posts [id=id]
```

**Comment by max-sixty** [comment]
Thanks for the question @severak 

IIUC, we can do this with a `table` expression:

```elm
table latest_posts = (
  from posts
  group id (
    aggregate [maxdt = max datetime]
  )
)

from posts
join side:left latest_posts [id]
```

Note that PRQL will also find the "max item": https://prql-lang.org/book/transforms/group.html

```elm
from employees
group role (
  sort join_date
  take 1
)
```

though the generated SQL isn't beautiful (but in most DBs is more performant than the self-join, and robust to ties):

```sql
WITH table_0 AS (
  SELECT
    employees.*,
    ROW_NUMBER() OVER (
      PARTITION BY role
      ORDER BY
        join_date
    ) AS _rn
  FROM
    employees
)
SELECT
  table_0.*
FROM
  table_0
WHERE
  _rn <= 1
```

Does that answer your question?

**Comment by severak** [comment]
It looks like what I was looking for. Not direct translation but PRQL version looks very readable.

However I am unable to test it (for now) because `WITH` clause is only for newer versions of SQLite.

Anyway - thanks for answer.

**Comment by max-sixty** [comment]
Great. I'll close this for now, but please feel free to open another for other questions.
