### ISSUE TITLE
VSCode live transpilation

### ISSUE THREAD

**Issue by qharlie** [PRQL/prql#720]
An idea from Anubis https://discord.com/channels/936728116712316989/945832046121607208/991387922001559564 

> Would love to see the VSCode extension have a live transpile and have the code connect to a live DB session for auto complete. Also, would love to se file.prql be a thing that opens up automatically in VSCode.

Maybe we can ship the WASM prql-compiler with the plugin.

**Comment by max-sixty** [comment]
This would be great, and let us gradually start building out the LSP.

(btw @charlie-sanders I'm going to try and paste things in from Discord, so it's all here & more searchable, as well as linking. Thanks a lot for kicking off the issue)

**Comment by max-sixty** [comment]
Closed by @jiripospisil!
