### ISSUE TITLE
Raw s-string

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#721]
As discussed on [discord](https://discord.com/channels/936728116712316989/991384476313714749).

Crystal uses variables like `{?foo}`; which would be good to pass through.

Two options I can see:
- Work this into the parser, like we did for dbt. `{?foo}` is passed through to SQL just as `{{ foo }}` is.
- Allow for a "raw s-string", like `sr"{?foo}"`. This doesn't special-case the parser so much, though is a bit less visually appealing for Crystal users.
  - The issue with `s"{?foo}" is that s-strings interpret code between `{ }` as a PRQL expression.

Edit: As per @mattdharmon's suggestion, let's go with the raw s-string

**Comment by mattdharmon** [comment]
I think raw s-string might be a good idea since there are things like SISS packages that need to be called from time to time that a vendor has made.

**Comment by max-sixty** [comment]
@mattdharmon are there any docs on these `{?foo}` variables? I'd like to use them as a test case and couldn't immediately find a description of them online.

**Comment by max-sixty** [comment]
Proposal here: https://github.com/prql/prql/pull/752#issuecomment-1187625092

@mattdharmon — would this cover your use case? It would mean the crystal variable would be `"{?foo}"` in postgres, or surrounded by backticks in MySql. So if a Crystal layer is replacing those with variables, it needs to do so inside the quotes.
