### ISSUE TITLE
Provide antlr4 grammar file?

### ISSUE THREAD

**Issue by melin** [PRQL/prql#728]
If there is an antlr4 grammar file, use spark to implement, support distributed compute

**Comment by aljazerzen** [comment]
Only grammar we have currently is written in [PEST](https://pest.rs/): https://github.com/prql/prql/blob/main/prql-compiler/src/prql.pest

There was an intereset to also provide EBNF sytnax file (https://github.com/prql/prql/issues/285).

Until language is stabilized and 1.0.0 is released I would avoid having to maintain 3 different grammar definitions. But feel free to experiment.

What do you mean with "use spark to implement, support distributed compute"?

**Comment by doki23** [comment]
He means that he wants to use prql in apache spark.

**Comment by melin** [comment]
> He means that he wants to use prql in apache spark.
yes，spark support custom syntax using antlr4

**Comment by doki23** [comment]
I think we just need binding rust api to java like what prql-python have done.

**Comment by aljazerzen** [comment]
Exactly. Just a antlr4 grammar file would provide only the parsing of the language, but would not know what to do with PRQL functions, variables and groups. 

To run on spark, the easiest way would probably be to compile to spark's SQL dialect using some java wrapper around prql-compiler. I'm not sure if this is even possible in java and have no knowledge of the Spark ecosystem and archtitecture, so take this advice with a grain of salt.

**Comment by doki23** [comment]
I'm researching this. If I try it successfully, I'm going to contribute a prql-java module.

**Comment by doki23** [comment]
I've create a [beta repo](https://github.com/doki23/prql-java) and test it successfully. But it still need some improvements because it has to set `java.library.path` env var for user's jvm process.

**Comment by max-sixty** [comment]
That looks great @doki23 ! 

I admittedly don't use Java much and so can't be helpful on the code, but you're welcome to either keep it as a separate repo or start a new path `prql-java` in this repo.
