### ISSUE TITLE
Improve prql-compiler crate public API

### ISSUE THREAD

**Issue by aljazerzen** [PRQL/prql#731]
As a response to #709 and a few other questions, here is a todo list for improving public API of the compiler crate:

- offer `prql!("from employees filter country == {}", "USA")` macro that compiles the query at compile-time
- make the whole `ast` module public
- offer non-formatted errors

**Comment by max-sixty** [comment]
Thanks for adding these

Very much agree on the latter two. If anyone is up for a contribution, these would be great, and I'm happy to help guide you (and I hope it's OK to say @aljazerzen likely is too!)

> offer `prql!("from employees filter country == {}", "USA")` macro that compiles the query at compile-time

Do we need a macro for this though? Could we just have `compile(format!("from employees filter country == {}", "USA"))`?

**Comment by aljazerzen** [comment]
Yeah, `compile(format!(...))` would work. 

But I think that they want to have PRQL transpiled at **compile time**, so it can be used with [this](https://github.com/launchbadge/sqlx#compile-time-verification). Our `compile` function would transpile at runtime. @xialvjun is that right?

I think this only requires about a 100 lines of code, but it is quite advanced Rust...

**Comment by max-sixty** [comment]
> But I think that they want to have PRQL transpiled at **compile time**, so it can be used with [this](https://github.com/launchbadge/sqlx#compile-time-verification). Our `compile` function would transpile at runtime.

Oh, this could be very cool. Maybe its offline mode could be something like https://github.com/prql/prql/issues/523

**Comment by spenserblack** [comment]
:+1: from me for an ability to compile at compile-time. I think ideally a release distribution of a tool that uses prql should have a pre-compiled SQL query embedded, instead of compiling the prql code at runtime (of course, this can also be achieved by moving prql compilation into a separate build step from the main build step).

I think it's more Rust-like to have a macro, too (the aforementioned `format!`, for example, moves a lot of the logic to compile time instead of runtime).

**Comment by xialvjun** [comment]
> But I think that they want to have PRQL transpiled at **compile time**, so it can be used with [this](https://github.com/launchbadge/sqlx#compile-time-verification). Our `compile` function would transpile at runtime. @xialvjun is that right?

Yes, **compile time verification** and **anonymous struct declaration**. So we can:

```rust
let employees = prqlx.query!(
        "
from employees
filter country == ?
select [first_name, last_name]
        ",
        "USA"
    )
    .fetch_all(&pool) // -> Vec<{ first_name: String, last_name: String }>
    .await?;

// employees[0].first_name
// employees[0].last_name
```

**Comment by max-sixty** [comment]
For a "good first issue", these two would be ideal:

> * make the whole `ast` module public
> * offer non-formatted errors

---

and...

> offer `prql!("from employees filter country == {}", "USA")` macro that compiles the query at compile-time

...is more work if it includes `sqlx`, and if it doesn't then I'm not sure it's much better than 

> `compile(format!(...))`
