### ISSUE TITLE
Move functional tests into a more general location

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#735]
Currently much of `sql/translator.rs` is functional tests testing the whole pipeline; e.g. here's 100 lines of them picked at random: https://github.com/prql/prql/blob/af3b5fb94fb7539307e50ef28cc40b47cfbb03bc/prql-compiler/src/sql/translator.rs#L1462-L1550.

We can:
- move these to a separate file; either in a `tests` path, or into a `test_lib.rs` (or some similar name) file with unit tests designed for these
- change all these `parse(resolve_and_translate({query}))` into just `compile`

**Comment by aljazerzen** [comment]
I agree, these test the whole pipeline, not just the translator.

Maybe we can put them into `test-databases/` so they are executed on at least SQLite and DuckDB?

**Comment by max-sixty** [comment]
I did some of this in https://github.com/prql/prql/pull/875, so I'll close this, but there's more to do here.

> Maybe we can put them into test-databases/ so they are executed on at least SQLite and DuckDB?

I think this could be good, but one factor here is that having them in the `examples` path means they don't compile with `--lib`, and we want a fast write-compile-test cycle for that crate, so probably we don't want to mix it with starting a DB in-process... (Unless my estimate for how long that takes is too high)

We could definitely have them in a common location and then use them in both — I've been thinking of a more cohesive & complete set of tests, e.g. which test each stage of the compiler.
