### ISSUE TITLE
parentheses are lost when inside func 

### ISSUE THREAD

**Issue by Baoqi** [PRQL/prql#745]
Take a prql in https://prql-lang.org/book/queries/functions.html for example:

```
func celsius_of_fahrenheit temp -> (temp - 32) * 3

from cities
derive temp_c = (temp_f | celsius_of_fahrenheit)
```
will translate to:

```
SELECT
  cities.*,
  temp_f - 32 * 3 AS temp_c
FROM
  cities
```

The parentheses are lost, seems more correct result should be:

```
SELECT
  cities.*,
  (temp_f - 32) * 3 AS temp_c
FROM
  cities
```

**Comment by aljazerzen** [comment]
Thank you for reporting. As a by-product of prql parsing, parenthesis are removed, but we haven't implemented the part that checks the precedence and inserts them back in.

This issue is tracked at #609
