### ISSUE TITLE
Didn't understand Playground until window was > 1160px wide

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#750]
I wasn't sure what to do with the [Playground](https://prql-lang.org/playground/) when I first went there. It was only when I made the window wider (the threshold seems to be 1160 px) that I saw the SQL pane on the right. Sure enough, changes on the left updated the right pane. Slick!

My suggestion would be to let the two panes share the space, even if they're as narrow as 100px... Thanks!

**Comment by max-sixty** [comment]
Thanks, that's a helpful observation.

This would be a welcome contribution.

**Comment by richb-hanover** [comment]
Excellent! Thanks!
