### ISSUE TITLE
Publish npm package for Node

### ISSUE THREAD

**Issue by mklopets** [PRQL/prql#766]
An npm package for prql-js that's usable on the backend would be fantastic. There's probably even a way to get both the `bundler` and `nodejs` builds published under one package.

For now, I threw a `wasm-pack build --target nodejs` build up at https://www.npmjs.com/package/prql-node, but it would be great if this was properly maintained/updated.

PS: awesome work on this.

**Comment by qharlie** [comment]
Heya, yes I need to merge https://github.com/prql/prql/pull/732 which will bundle all 3 as one package , but glad you got it working !
