### ISSUE TITLE
Add from_json support to compiler

### ISSUE THREAD

**Issue by florent-martineau** [PRQL/prql#775]
We can currently serialize PRQL into JSON, but we cannot deserialize JSON into PRQL.

FYI, code is ready

**Comment by max-sixty** [comment]
Thanks @florent-martineau ! So I understand, WDYM "code is ready"?

**Comment by florent-martineau** [comment]
I meant the code is ready and works locally, I just haven't made the PR yet. Same thing for #776.

I was saying code is ready to avoid having people waste their time on it, since I have already made a first version.

**Comment by max-sixty** [comment]
Oh amazing! Thanks @florent-martineau
