### ISSUE TITLE
Link to bindings is broken

### ISSUE THREAD

**Issue by MFAshby** [PRQL/prql#818]
Hi! 

I was hoping to try out prql in a toy app, and I was excited to see in the FAQ that there are bindings for Rust. 

However the link is broken. Page: https://prql-lang.org/faq/ link for Bindings points to: https://prql-lang.org/content/_index.md#Bindings, which is a 404.

**Comment by max-sixty** [comment]
Thanks @MFAshby ! Closed by #821
