### ISSUE TITLE
Fix Quoting issue for BigQuery

### ISSUE THREAD

**Issue by blackary** [PRQL/prql#852]
Though #838 may have resolved issues with other dialects, it hasn't fixed the BigQuery case

```
prql dialect:bigquery
from db.schema.table
```

Now yields the result with no quotes at all

```sql
SELECT
  db.schema.table.*
FROM
  db.schema.table
```

But, this is invalid. In BigQuery, it actually needs to have `s around the full name in the select and from.

```sql
SELECT
  `db.schema.table`.*
FROM
  `db.schema.table`
```

**Comment by max-sixty** [comment]
As long as the identifiers are valid, BQ didn't seem to require backticks.

Do you have a specific case where it raises and error?

Thank you

**Comment by blackary** [comment]
Here's a fully-functioning example:

```
prql dialect:bigquery
from `bigquery-public-data.pypi.file_downloads`
filter timestamp > '2024-08-01'
```

-> 

```sql
SELECT
  `bigquery-public-data`.pypi.file_downloads.*
FROM
  `bigquery-public-data`.pypi.file_downloads
WHERE
  timestamp > '2024-08-01'
```

Note that it puts backticks around `biquery-public-data` because of the hyphens, and I get the error 

```
Unrecognized name: `bigquery-public-data` at [2:3]
```

I get the same error if the db name doesn't have hyphens in it.

If I change it so that there are backticks around the whole db.schema.table, it works (though, given the date, returns no results)

```sql
SELECT
  `bigquery-public-data.pypi.file_downloads`.*
FROM
  `bigquery-public-data.pypi.file_downloads`
WHERE
  timestamp > '2024-08-01'
```

**Comment by max-sixty** [comment]
Ah, sorry about that @blackary , mea culpa.

IIUC, the initial example _would_ be OK — i.e., without the hyphen, it would be fine without the backticks. But if any part of the table expression has an invalid character, the whole identifier needs backticks. Lmk if that's inconsistent with how you're thinking about it.

Ironically I originally tested this with BQ, so the very first approach worked like this. But it's incompatible with Postgres (#822), which requires each part to be quoted separately.

So we'll have to split the implementation up further between dialects, I'll prioritize this and get to it later this week.

**Comment by blackary** [comment]
Sorry, @max-sixty, that wasn't the best example, due to the hyphenated project name -- I used that one because it's using a public dataset. Here's something closer to the real example I'm working with:

```
prql dialect:bigquery
from company.apps.users
```

```sql
SELECT
  company.apps.users.*
FROM
  company.apps.users
  ```
  
  Even with no hyphens, BigQuery still complains about the select part
  
 ```
  Unrecognized name: company at [2:3]
```

If I put backticks around both, it works fine


```sql
SELECT
  `company.apps.users`.*
FROM
  `company.apps.users`
  ```
  
  Thanks for being so responsive! I'm excited to try prql, but am not able to currently due to this issue.

**Comment by max-sixty** [comment]
I see — so it seems that:

- We might not need backticks in the `FROM` clause (it seems to work without them, even with hyphens)
- We always need them in the `SELECT` clause where there's a dataset / two periods; e.g. this fails:

  ```sql
  SELECT broadstreet_adi.area_deprivation_index_by_census_block_group.* 
  FROM bigquery-public-data.broadstreet_adi.area_deprivation_index_by_census_block_group LIMIT 1000
  ```

  but this succeeds

  ```sql
  SELECT area_deprivation_index_by_census_block_group.* 
  FROM bigquery-public-data.broadstreet_adi.area_deprivation_index_by_census_block_group LIMIT 1000
  ```

So I _think_ a rule is both fairly simple and complete is: "Any ident containing >2 periods should be quoted". We can write a BQ-specific implementation without too much trouble, I think. It over-quotes idents in the `FROM` clause, but that's OK.

An alternative is to quote every identifier, which would definitely be complete. But then it makes the SQL more "machine-generated" and less friendly — in this case less welcoming to newcomers, and in other cases more difficult to debug.

Are there any gaps you can perceive in that rule @blackary?

> Thanks for being so responsive! I'm excited to try prql, but am not able to currently due to this issue.

Thanks for your feedback and patience — I would have hoped the patience would be expended on more conceptual issues, but inevitably it's these small differences between dialects which are the difficult cases 🙏

**Comment by blackary** [comment]
@max-sixty I think that rule would cover all the cases. If I was hand-writing the SQL, I would do your second example (just using the table name in the select, without schema or db), but I figure that might add other issues with potential name collisions.

Also, regarding over-quoting, it seems that if you quote the SELECT case, you must also quote the FROM. 

e.g. this fails

```sql
SELECT
  `company.apps.users`.*
FROM
  company.apps.users
```

But this works

```sql
SELECT
  `company.apps.users`.*
FROM
  `company.apps.users`
```

Thanks for being willing to work on the fiddly dialect edge-cases.

**Comment by max-sixty** [comment]
https://github.com/prql/prql/pull/858 almost gets us there, but then I just spotted another case!

```elm
prql dialect:bigquery
from pj.ds.tbl
```

works well:

```sql
SELECT
  `pj.ds.tbl`.*
FROM
  `pj.ds.tbl`
```

...but because idents are currently required to be fully enclosed by backticks, the code that dbt generates doesn't work:

```elm
prql dialect:bigquery
from `pj`.`ds`.`tbl`
```

```sql
SELECT
  `pj``.``ds``.``tbl`.*
FROM
  `pj``.``ds``.``tbl`  # invalid
```

This is mostly a problem for dbt; it's rare that someone really requires this when manually writing it out. Currently the parser (i.e. the very first stage) doesn't understand ident "parts". I'll see whether I can try and inch towards a solution without building any complexity there for the moment.

**Comment by max-sixty** [comment]
FYI I looked at whether we could get rid of the BQ specialization after `0.3.0`. I don't think that's possible, since we use full identifiers in the `SELECT`, and from above:

> We always need them in the `SELECT` clause where there's a dataset / two periods

So leaving the BQ specialization in for the moment. Possibly in the future we can remove the dataset etc from the `SELECT` statement

**Comment by jezao** [comment]
this is the generated query:

/* {"app": "dbt", "dbt_version": "1.7.11", "profile_name": "analytics", "target_name": "dev", "node_id": "model.analytics.combined_requests"} */


  create or replace view `foleon-production`.`analytics`.`combined_requests`
  OPTIONS()
  as 


WITH requests AS (
    SELECT
        timestamp,
        CAST(timestamp AS STRING) AS original_time,
        httpRequest.requestMethod AS method,
        REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]hostname=([^&]*)') AS hostname,
        REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]hostname_original=([^&]*)') AS hostname_original,
        foleon-production.`analytics`.`requests`.decodeUrl(REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]ua=([^&]*)')) AS ua,
        REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]page_id=([^&]*)') AS page_id,
        REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]session_id=([^&]*)') AS session_id,
        SAFE_CAST(REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]foleon_page_id=([^&]*)') AS INT64) AS foleon_page_id,
        REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]foleon_page_cid=([^&]*)') AS foleon_page_cid,
        SAFE_CAST(REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]foleon_doc_id=([^&]*)') AS INT64) AS foleon_doc_id,
        REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]foleon_doc_cid=([^&]*)') AS foleon_doc_cid,
        REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]type=([^&]*)') AS type,
        REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]event=([^&]*)') AS event,
        foleon-production.`analytics`.`requests`.decodeUrl(REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]metadata=([^&]*)')) AS METADATA,
        REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]sri=([^&]*)') AS sri,
        foleon-production.`analytics`.`requests`.decodeUrl(REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]path=([^&]*)')) AS path,
        SAFE_CAST(REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]viewport_width=([^&]*)') AS INT64) AS viewport_width,
        SAFE_CAST(REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]viewport_height=([^&]*)') AS INT64) AS viewport_height,
        REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]language=([^&]*)') AS LANGUAGE,
        SAFE_CAST(REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]screen_width=([^&]*)') AS INT64) AS screen_width,
        SAFE_CAST(REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]screen_height=([^&]*)') AS INT64) AS screen_height,
        foleon-production.`analytics`.`requests`.decodeUrl(REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]timezone=([^&]*)')) AS timezone,
        SAFE_CAST(REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]unique=([^&]*)') AS BOOL) AS unique,
        REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]id=([^&]*)') AS id,
        foleon-production.`analytics`.`requests`.decodeUrl(REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]referrer=([^&]*)')) AS referrer,
        REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]original_id=([^&]*)') AS original_id,
        SAFE_CAST(REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]duration=([^&]*)') AS INT64) AS duration,
        SAFE_CAST(REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]scrolled=([^&]*)') AS INT64) AS scrolled,
        SAFE_CAST(REGEXP_EXTRACT(httpRequest.requestUrl, r'[?&]time=([^&]*)') AS INT64) AS time
    FROM
        foleon-production.`analytics`.`requests`
),

old_pageviews AS (
    SELECT
        TIMESTAMP(pageview.startedAtIso) AS timestamp,
        pageview.startedAtIso AS original_time,
        'GET' AS method,
        '' AS hostname,
        '' AS hostname_original,
        pageview.userAgent AS ua,
        session.id AS page_id,
        pageview.sessionId AS session_id,
        page.id AS foleon_page_id,
        '' AS foleon_page_cid,
        edition.id AS foleon_doc_id,
        '' AS foleon_doc_cid,
        'pageview' AS type,
        NULL AS event,
        NULL AS METADATA,
        '' AS sri,
        CONCAT('/',title.identifier,'/',edition.identifier,'/',page.identifier) AS path,
        360 AS viewport_width,
        640 AS viewport_height,
        '' AS LANGUAGE,
        360 AS screen_width,
        640 AS screen_height,
        '' AS timezone,
        FALSE AS unique,
        '' AS id,
        '' AS referrer,
        '' AS original_id,
        NULL AS duration,
        NULL AS scrolled,
        NULL AS time
    FROM
        foleon-production.`analytics`.`old_pageviews` AS pageview
    JOIN
        foleon-production.`analytics`.`old_sessions` AS session ON session.id = pageview.sessionId
    JOIN
        foleon-production.`becky`.`edition` AS edition ON edition.id = session.publicationId
    JOIN
        foleon-production.`becky`.`page` AS page ON page.id = session.entryPageId
    JOIN
        foleon-production.`becky`.`title` AS title ON title.id = edition.title_id
    WHERE
        pageview.startedAt IS NOT NULL
),

combined AS (
    SELECT * FROM requests
    UNION ALL
    SELECT * FROM old_pageviews
)

SELECT * FROM combined;

----

this is the bigquery error:
Invalid project ID 'production.analytics'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
