### ISSUE TITLE
Update brew references to Homebrew Core

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#866]
`prql-compiler` is now in homebrew-core thanks to @ankane.

*(edited below)*
- We can change docs to point there. 
- We should probably deprecate our existing formula, generously contributed by @roG0d 
- We can set up a workflow to bump the version in core when we release

Apparently there is an action to automatically bump it: https://github.com/dawidd6/action-homebrew-bump-formula; this might be as simple as https://github.com/dandavison/delta/blob/b3cc0f8cae943ec87a4e7b300af431cecda80b68/.github/workflows/cd.yml#L86-L95.

We have a [great workflow atm](https://github.com/prql/prql/blob/0.2.3/.github/workflows/release.yaml#L8-L25) (thanks @roG0d !), so it would be sad to see that go. Possibly we could put it in a repo, it seems high quality and general enough that others may want to use it.

**Comment by max-sixty** [comment]
Since we moved from `prql-compiler` to `prqlc`, we can slightly change the above steps:

- Change the official upstream brew formula at https://formulae.brew.sh/formula/prql-compiler from `prql-compiler` to `prqlc`. This requires a PR into homebrew
- Set up a workflow to bump the version in the official upstream when we release, using https://github.com/dawidd6/action-homebrew-bump-formula. (PR into this repo)
- Change our docs to point to the official upstream
- ~Deprecate our existing formula~ done

**Comment by eitsupi** [comment]
Closed by #2614
