### ISSUE TITLE
CTE names are incorrectly quoted in Postgres

### ISSUE THREAD

**Issue by mklopets** [PRQL/prql#881]
given the prql query:

```
prql dialect:postgres

table X = (
  from x_orig
  filter price < 100
)

from X
```

on `v0.2.2`, we get:
```sql
WITH X AS (
  SELECT
    x_orig.*
  FROM
    x_orig
  WHERE
    price < 100
)
SELECT
  X.*
FROM
  X
```

vs on `v0.2.3` or newer, we get additional quoting at the end:
```diff
SELECT
-  X.*
+  "X".*
FROM
-  X
+  "X"
```

With those additional quotes, Postgres complains with:
```
Query 1 ERROR: ERROR:  relation "X" does not exist
```

I couldn't quickly find any reference to why this is, but there are two options – tested & both seem to work:
a) remove **both** sets of quotes (select + from)
b) add quotes to the CTE's name definition:
```diff
-WITH X AS (
+WITH "X" AS (
```

**Comment by max-sixty** [comment]
Thanks @mklopets . 

Quotes are added here because there are upper case letters in the name. So hopefully that's a reasonable workaround.

I'll look at why they're not added into `WITH`, definitely a bug. It's likely related to BigQuery requiring different handling of idents that are tables vs columns...

**Comment by mklopets** [comment]
Got it. For context on casing, we've got some prql tables that use PascalCasing to differentiate them from snake_cased DB tables (we can definitely change that)

**Comment by max-sixty** [comment]
This is a bug and I will fix it, so not on you tbc :)

But if you want a workaround, IIUC Postgres is case insensitive outside of quotes: https://stackoverflow.com/questions/21796446/postgres-case-sensitivity, so `pascalcasing` should work atm.

**Comment by max-sixty** [comment]
Done — thanks as ever for the issue @mklopets
