### ISSUE TITLE
S-strings with literal curly braces

### ISSUE THREAD

**Issue by blackary** [PRQL/prql#885]
I'm struggling to figure out how to put regex in an s-string without it trying to populate the contents of curly braces:

```
from employees
derive [
  long_enough = s"regexp_contains(title, '([a-z0-9]*-){2,}')"
]
```

yields

```
Error: during parsing
   ╭─[:3:57]
   │
 3 │   long_enough = s"regexp_contains(title, '([a-z0-9]*-){2,}')"
   ·                                                         ┬  
   ·                                                         ╰── expected operator_mul, operator_add, operator_compare, operator_logical, operator_coalesce, or interval_kind
───╯
```

If I remove the comma after the 2, it doesn't raise an error, but drops the curly braces

```
SELECT
  employees.*,
  regexp_contains(title, '([a-z0-9]*-)2') AS long_enough
FROM
  employees
  ```

**Comment by max-sixty** [comment]
I was thinking of using `{{` — https://github.com/prql/prql/pull/752 — would that work? I hadn't heard back on the related issue for a different case, but that approach seems sufficient for this case?

**Comment by blackary** [comment]
@max-sixty Yes, I think that would work well.

**Comment by blackary** [comment]
If 

```
from employees
derive [
  long_enough = s"regexp_contains(title, '([a-z0-9]*-){{2,}}')"
]
```

would become

```
SELECT
  employees.*,
  regexp_contains(title, '([a-z0-9]*-){2,}') AS long_enough
FROM
  employees
```

then that would be a great solution

**Comment by max-sixty** [comment]
Perfect, now in the book! https://github.com/prql/prql/pull/752/files#diff-4ac8d3b0b4a8253a8ee24b0629f7d9f2c6d1f1796e55a14ae54d787242aaf8f1R42

**Comment by max-sixty** [comment]
Done! Lmk if you need a release; I think we're currently tracking about weekly, but if you need something sooner it's easy for me to hit the buttons.

**Comment by blackary** [comment]
Thanks! I have a fair amount of regex like that, so it's a bit of a blocker for many of potential use-cases, but I'm happy to wait till whenever it's convenient for you to release.

**Comment by max-sixty** [comment]
Cool — it's easier & easier to do releases now, so I just did another. Thanks a lot for the flow of issues; please keep them coming / let us know if there's any current issues that are blocking you atm.
