### ISSUE TITLE
Support for SQL style comments

### ISSUE THREAD

**Issue by qharlie** [PRQL/prql#935]
Just to make it one step easier to transition from SQL.

**Comment by aljazerzen** [comment]
For future reference, discussion from Discord:

> Charlie_Sando
>  — 
> 23/08/2022
> Any objections to supporting SQL style comments -- ?
> 
> 
> max-sixty
>  — 
> 23/08/2022
> Fine with me! BigQuery does both and it works OK. I don't think there's ever a need for -- generally.
> 
> Though worth posting an issue and ensuring there aren't any good dissents
> 
> 
> aljazerzen
>  — 
> 24/08/2022
> I dont have practical objections, but i do have a principal one: i dont think its needed. The beauty of a new language is that its easy to learn because there is not much to learn.
> 
> This is also the "One way of doing each thing" principle
> 
> 
> Charlie_Sando
>  — 
> 24/08/2022
> Agree on the 'one way principal', but I think comments fall outside that territory, since most languages have more than one way to comment things ( usually  multiline/single line though ).
> 
> The main reason I want it is for tooling, editors that expect SQL can reasonably highlight PRQL ,  and supporting SQL style comments would take that one step further 
> 
> 
> aljazerzen
>  — 
> 25/08/2022
> I see. That would be useful, but would also strongly encourage its usage. Even without highlighting, people coming from sql would gravitate toward this style of comments.
> So I'd either have only # comment or only -- - there is no point in having both, if only one would get used
> 
> 
> max-sixty
>  — 
> 25/08/2022
> Yes agree re the "one ways of doing things"
> 
> @Charlie_Sando could we instead change the shortcut in Rill to add # rather than --?
> 
> 
> Charlie_Sando
>  — 
> 26/08/2022
> yeah we can 👍 .  It will likely be an upstream edit this is probably a depedency
