### ISSUE TITLE
Cast string value to number using PRQL

### ISSUE THREAD

**Issue by MaxOrelus** [PRQL/prql#949]
Is there a simple way to cast a string to a number using prql? I've looked through the documentation, but nothing stands out indicating that a way to do such a thing?

**Comment by max-sixty** [comment]
Thanks for the issue @MaxOrelus (and sorry it's been a few days to reply, a few of us are away)

We should document this better so I'll leave this open.

PRQL has an `as` function, which can be used like:

```
gross_salary = (salary + payroll_tax | as int)
```

Does that suffice?

**Comment by BenHewins** [comment]
This doesn't seem to work as expected (at least in the playground)
This input:
```
from employees
derive [
  gross_salary = (salary + payroll_tax | as int)
]
```
Gives this output
```
SELECT
  employees.*,
  CAST(int AS salary + payroll_tax) AS gross_salary
FROM
  employees
```

I think that the definition [here](https://github.com/prql/prql/blob/0e037a3894f2b443135d3584bfd4796d83521388/prql-compiler/src/semantic/stdlib.prql#L37) is probably not the most ergonomic way around, and changing it to
```
func as<scalar> type column ->  s"CAST({column} AS {type})"
```
would give less surprising results, assuming using the pipe operator is the recommended way to use it. No idea if that's viable though!

**Comment by max-sixty** [comment]
Gosh, that's a basic error, sorry about about that @BenHewins . I'll fix that right now.

**Comment by max-sixty** [comment]
Fixed and added a small test & doc. Let me know if you want a release for this. Thanks for pointing it out.
