### ISSUE TITLE
Join on tables with different column names

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#954]
I am having fun playing with PRQL. I am working through the cte0.prql example, adapting it to my existing data.

I have two tables AA and BB, which have columns named AA_Book, AA_Page, BB_Book, BB_Page. (For historical reasons, the tables have the table name with the column name.)

In SQL, I do the join like this `... on AA_Book = BB_Book AND AA_Page = BB_Page ...`

What's the "right way" to join these tables in PRQL? Thanks.

**Comment by richb-hanover** [comment]
Ahah! Answered my own question:

```
...
join used_sales [AA_book == BB_book, AA_page == BB_page]
```

**Comment by max-sixty** [comment]
Great, cheers @richb-hanover . 

Feel free to add ants other questions here.
