### ISSUE TITLE
Discussions not enabled on GitHub repository

### ISSUE THREAD

**Issue by Barney-x1** [PRQL/prql#962]
Hi. I notice that you have previously initiated discussions about PRQL on Hacker News and Reddit (and possibly elsewhere). These seem to have died out and I think it would be a great idea to enable GitHub discussions in the repository. I personally have a couple of questions to ask (as I'm sure do many others) and it would also enable the dev(s?) to ask for feedback on proposals.

**Comment by max-sixty** [comment]
Hi @Barney-x1 — I think it's fine to use Issues for those at the moment. Or do you think Discussions are a better format?

We don't have _that_ much activity between GH Issues & Discord — maybe a few messages a day — so I think @aljazerzen was thinking we should centralize them as much as possible.

(at the object level — feel free to post your questions as issues for now, and we can decide whether to use discussions here)

**Comment by Barney-x1** [comment]
Hi. I didn't know there was a chat facility with Discord.

Personally I'd much rather use a proper threaded forum for development. I know Discord has a feature to create a thread, but 90% of stuff which might answer a "how do I...?" question ends up "lost" in chat. 

Searchability/browsability is so much better in a traditional forum. Google hits will take you to a page of chatter with your hit who-knows-where and surrounded by posts irrelevant to what you're interested in. That's if it can be found at all - I find that the post referenced by the search engine is usually nowhere to be found on the page any more, having long ago scrolled off into oblivion. 

There's a good reason why forums rather than chat rooms have been used for collaborative software development for 30+ years, and I think that "because it's trendy/modern" is a poor reason to use a chat app instead.

But that's just my 2 cents, and to be fair I haven't actually used Discord(!).

I'll post my current questions as issues for now.

**Comment by max-sixty** [comment]
Yeah, I'm very partial to your perspective on the tradeoffs there. We do try and move anything that's longer-term into GH Issues.

Thanks — please feel free to liberally post questions; all gratefully received
