### ISSUE TITLE
Can't build `playground` locally

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#969]
I forked the prql repo to my own account, then cloned it to my machine (macOS 10.15.7). I then tried to build the playground so I could try it locally. I got an error (`sh: wasm-pack: command not found`), so I added `"wasm-pack": "^0.10.3"` to the devDependencies in the `package.json` file.

I then tried the following. I saw a couple warnings about deprecations, but I don't know what to do about the `cargo metadata` file. What other troubleshooting information could I provide? Many thanks.

```
√ playground % node --version
v16.14.0
√ playground % npm --version
8.3.1
√ playground % npm install
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

> prql-playground@0.1.0 preinstall
> cd ../prql-js && npm run build-bundler


> prql-js@0.2.6 build-bundler
> wasm-pack build --target bundler --release --out-dir dist/bundler

Error: Error during execution of `cargo metadata`: error: failed to parse lock file at: /Users/richb/github/prql/Cargo.lock

To learn more, run the command again with --verbose.

npm ERR! code 1
npm ERR! path /Users/richb/github/prql/playground
npm ERR! command failed
npm ERR! command sh -c cd ../prql-js && npm run build-bundler

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richb/.npm/_logs/2022-09-14T17_44_20_052Z-debug-0.log
?1 playground %
```

**Comment by richb-hanover** [comment]
Hmmm... I did more troubleshooting. I removed the Cargo.lock file from the main directory, and got farther. But I suspect that I need to build a bunch more stuff before the playground will build.

Is there an installation guide that builds a working system? (Or a Dockerfile that handles all this?) Many thanks.

**Comment by max-sixty** [comment]
Hi @richb-hanover, thanks for the issue.

Maybe this should be more prominent — in https://github.com/prql/prql/blob/main/CONTRIBUTING.md I wrote about the `Taskfile.yml`, which sets up the whole environment and we test on every merge.

Does that help? Let me know and I'm happy to help debug.

**Comment by richb-hanover** [comment]
Ahah! Yes - I would have found it if there were a short section on the main README.md, probably immediately below **Current Status** like this:

```
### Installation

Instructions for building prql are in the [Contributing page](https://github.com/prql/prql/blob/main/CONTRIBUTING.md) page
```

(Yes, I did see that link in the "Get Involved" section, but I'm shy, and I don't know whether I really wanted to get involved - I only wanted to horse around :-)

**Comment by max-sixty** [comment]
Ha! You're involved already :)

Thanks, let me take a pass at that

**Comment by richb-hanover** [comment]
And I'm discovering that I have cargo and rustup from 2016 (or so) - let me update and get back to you

**Comment by max-sixty** [comment]
Great — and tbc, you should be able to *use* the Playground at https://prql-lang.org/playground/ without installing it — you only need to install to make changes / horse around :)

**Comment by richb-hanover** [comment]
Oh yes - I have been thinking of a good way to misuse the PRQL compiler, but it may not work, so I'll keep it under wraps 'til I have something to show. (My mentor at my first job always said, "You don't really understand something until you can think of three ways to misuse it..")

**Comment by richb-hanover** [comment]
It's still too subtle. Most CONTRIBUTING.md files are full of feel-good stuff, codes of conduct, contacting the authors, finding the forum, etc. They're critically important to lay out the ethos of a project. But I (almost) never look there first time through a project.

Split everything about the development environment into its own DEVELOPMENT.md file. You've got great stuff there - make it more prominent.

**Comment by richb-hanover** [comment]
And in the playground/README.md, you could also link to the DEVELOPMENT.md file before discussing about the `npm install; npm start` command.

That also would have tipped me off to the larger "get everything installed" page.

**Comment by richb-hanover** [comment]
And now back to the business at hand. After installing modern cargo/rust/etc. (using `brew`), I was able to get the `cargo test` to do something that looked useful. I saw a couple warnings during the process:

```
...
   Compiling mdbook-preprocessor-boilerplate v0.1.1
   Compiling prql-compiler v0.2.6 (/Users/richb/github/prql/prql-compiler)
warning: use of deprecated function `itertools::zip`: Use [std::iter::zip](https://doc.rust-lang.org/std/iter/fn.zip.html) instead
 --> prql-compiler/src/sql/materializer.rs:9:16
  |
9 | use itertools::zip;
  |                ^^^
  |
  = note: `#[warn(deprecated)]` on by default

warning: use of deprecated function `itertools::zip`: Use [std::iter::zip](https://doc.rust-lang.org/std/iter/fn.zip.html) instead
   --> prql-compiler/src/sql/materializer.rs:225:34
    |
225 |         for ((param, _), arg) in zip(func_dec.positional_params.iter(), func_call.args.iter()) {
    |                                  ^^^

warning: `prql-compiler` (lib) generated 2 warnings
   Compiling prql-js v0.2.6 (/Users/richb/github/prql/prql-js)
   Compiling prql-macros v0.2.6 (/Users/richb/github/prql/prql-macros)
   Compiling prql-java v0.2.6 (/Users/richb/github/prql/prql-java)
...
```

**Comment by max-sixty** [comment]
Very good ideas above re the docs — I will add the reference in! Let me think about splitting the files up too. Thanks

Hmmm, weirdly I don't get those, and tests would fail with them. Have you by any chance run `cargo update` such that you're on `itertools=0.10.4`? Resetting back to `main` should fix them, and we'll fix it when we upgrade.

**Comment by richb-hanover** [comment]
Thanks for the thoughts on the rust tool chain. Right now, it's a shambles on my machine, and I need to get it back to ground zero. (You don't need to think about this - I'll wrassle with it - Google is my friend.)

But this is another reason for you to consider creating a Dockerfile for the project. [I have become more and more attracted](https://randomneuronsfiring.com/more-fun-with-docker-tooling/) to using Docker to encapsulate my development tooling into a single Docker container - all the Rust/Node/npm/etc version hassles go away.

**Comment by max-sixty** [comment]
Yeah, I guess we could even have a Dockerfile which installs `task` and runs `task setup-dev`. Personally I'm not a great fan of using Docker in development if it's possible to run natively, but maybe I'm being overly conservative, or I'm overestimating how easy the `task` approach is. 

If others see this and have a view, please feel free to comment.

**Comment by richb-hanover** [comment]
Good news: I was able to scourge my MacBook of the ancient, crufty cargo/rust/whatever. Google *is* my friend. Just now I ran `cargo install` from the main directory (got a couple warnings) then `cd playground; npm install;npm start` and the magic all happened - the Playground opened in my web browser. (I just want to say, this is actually *very* cool!)

But... I don't dwell in this world. I'm sorta up to speed on Node/npm, a tiny bit with Python, but none of the toolchains associated with go, rust, and certainly not C or C++. Even though I use `brew` most of the time on my MacBook, that didn't work for rust - I had to use the install script from the website. And I have to keep track my version of Node - different projects demand different versions... I have been in this business long enough to realize that there will always be version incompatibilities between different projects. Project A requires version 123 of that library, but Project B drives a bug there, and requires an incompatible version...

I guess I'm saying that there's a certain magic in building a Docker container (it's remarkably straightforward) that welds all the relevant build tool versions into a single text file that can be easily distributed to everyone who's working on the project. 

Something to consider, in case you're running short of things to think about :-) Thanks!

**Comment by max-sixty** [comment]
Yes I v much agree — there is that elegance with Docker! I'm definitely open to it.

Thanks for the suggestions above — they've already led to some improvements. Let me know if you make any progress / have any questions about the compiler!
